//! The driver's side of the table structure per variant: capabilities,
//! the table designer, create templates and the DDL / INSERT scripts.

use crate::Variant;
use dbine_driver::ddl::{self, AutoIncrement, SqlFlavor};
use dbine_driver::sql::{qualified_name, quote_ident, Quote};
use dbine_driver::{kinds, Capabilities, CreateTemplate, DdlParts, DesignerSpec, Field, FieldKind, RowChange, TableSchema};
use serde_json::Value;

fn flavor(v: Variant) -> SqlFlavor {
    match v {
        Variant::Redshift => SqlFlavor { auto_increment: AutoIncrement::Identity, ..SqlFlavor::ansi() },
        // No identity columns, no COMMENT ON.
        Variant::CrateDb => SqlFlavor { auto_increment: AutoIncrement::None, comment_on: false, ..SqlFlavor::ansi() },
        Variant::RisingWave | Variant::Materialize => SqlFlavor { auto_increment: AutoIncrement::None, ..SqlFlavor::ansi() },
        _ => SqlFlavor::ansi(),
    }
}

/// The script that applies schema changes ("Comparar esquemas").
pub fn sync_script(v: Variant, changes: &[dbine_driver::TableChange]) -> dbine_driver::Result<dbine_driver::SyncScript> {
    use dbine_driver::alter::{AlterStyle, ColumnAlter};
    let column = match v {
        // Only varchar lengths change, and without USING.
        Variant::Redshift => ColumnAlter::Standard { set_data_type: false, using_cast: false },
        Variant::H2 => ColumnAlter::Standard { set_data_type: true, using_cast: false },
        // Columns can't change type.
        Variant::CrateDb | Variant::RisingWave | Variant::Materialize => ColumnAlter::None,
        _ => ColumnAlter::Standard { set_data_type: false, using_cast: true },
    };
    let f = flavor(v);
    let cd = |t: &TableSchema, c: &dbine_driver::ColumnDef| column_def(v, &f, t, c);
    let dd = |t: &TableSchema, p: DdlParts| Ok(table_ddl(v, t, p));
    let mut script = dbine_driver::alter::sync_script(&AlterStyle::from_flavor(&f, column, &cd, &dd), changes)?;
    crate::compare::fix_drops(v, &mut script.statements, changes);
    if v == Variant::CrateDb {
        crate::compare::crate_sync(&mut script, changes);
    }
    if v.streaming() {
        // A script of several statements runs as a transaction there, and
        // CREATE INDEX can't: one statement per chunk.
        script.statements = script
            .statements
            .iter()
            .flat_map(|s| s.split(";\n").map(|p| format!("{};", p.trim().trim_end_matches(';'))).collect::<Vec<_>>())
            .filter(|s| s != ";")
            .collect();
    }
    Ok(script)
}

/// [`dbine_driver::ColumnDef::options`] key: an identity column's
/// generation and sequence options when they aren't the defaults (read by
/// `database_schema`), as PostgreSQL writes them after `GENERATED`:
/// `ALWAYS` / `BY DEFAULT`, then `(START WITH 100 INCREMENT BY 5 …)`.
/// Same key as SQL Server's `IDENTITY(seed,increment)`.
pub(crate) const IDENTITY_OPTION: &str = "identity";

const BY_DEFAULT_IDENTITY: &str = " GENERATED BY DEFAULT AS IDENTITY";

/// Variants whose identity columns take ALWAYS and sequence options. Not
/// openGauss (serials), CockroachDB (its own identity reading) nor the
/// ones without identity columns.
fn identity_options(v: Variant) -> bool {
    flavor(v).auto_increment == AutoIncrement::GeneratedIdentity && !matches!(v, Variant::OpenGauss | Variant::Cockroach)
}

/// The identity option's value as ` GENERATED … AS IDENTITY (…)`, rebuilt
/// from the recognized words only; `None` if it isn't one.
fn identity_clause(value: &str) -> Option<String> {
    let spaced = value.replace(['(', ')', ','], " ").to_ascii_uppercase();
    let words: Vec<&str> = spaced.split_whitespace().collect();
    let mut i = 0;
    let how = match words.first().copied()? {
        "ALWAYS" => "ALWAYS",
        "BY" if words.get(1) == Some(&"DEFAULT") => {
            i = 1;
            "BY DEFAULT"
        }
        _ => return None,
    };
    i += 1;
    let num = |w: Option<&&str>| -> Option<String> {
        let w = *w?;
        let digits = w.strip_prefix('-').unwrap_or(w);
        (!digits.is_empty() && digits.chars().all(|c| c.is_ascii_digit())).then(|| w.to_string())
    };
    let mut opts: Vec<String> = Vec::new();
    while i < words.len() {
        let (text, used) = match words[i] {
            "START" | "INCREMENT" => {
                let (kw, filler) = if words[i] == "START" { ("START WITH", "WITH") } else { ("INCREMENT BY", "BY") };
                let skip = usize::from(words.get(i + 1) == Some(&filler));
                (format!("{kw} {}", num(words.get(i + 1 + skip))?), 2 + skip)
            }
            w @ ("MINVALUE" | "MAXVALUE" | "CACHE") => (format!("{w} {}", num(words.get(i + 1))?), 2),
            "CYCLE" => ("CYCLE".to_string(), 1),
            "NO" => match words.get(i + 1).copied()? {
                w @ ("CYCLE" | "MINVALUE" | "MAXVALUE") => (format!("NO {w}"), 2),
                _ => return None,
            },
            _ => return None,
        };
        opts.push(text);
        i += used;
    }
    let tail = if opts.is_empty() { String::new() } else { format!(" ({})", opts.join(" ")) };
    Some(format!(" GENERATED {how} AS IDENTITY{tail}"))
}

/// A column as CREATE TABLE / ADD COLUMN writes it, with its identity's
/// ALWAYS and sequence options ([`IDENTITY_OPTION`]).
fn column_def(v: Variant, f: &SqlFlavor, t: &TableSchema, c: &dbine_driver::ColumnDef) -> String {
    let line = ddl::column_def(f, t, c);
    if !c.auto_increment || !identity_options(v) {
        return line;
    }
    match c.options.get(IDENTITY_OPTION).and_then(|o| identity_clause(o)) {
        Some(clause) => line.replacen(BY_DEFAULT_IDENTITY, &clause, 1),
        None => line,
    }
}

/// The identity option for a column read from the catalog (`attidentity`
/// `a` / `d` and its sequence's `pg_sequence` row), `None` when everything
/// is the default (`BY DEFAULT`, start at the first value, step 1, the
/// type's range, cache 1, no cycle).
#[allow(clippy::too_many_arguments)]
pub(crate) fn identity_option(always: bool, type_name: &str, start: i128, increment: i128, min: i128, max: i128, cache: i128, cycle: bool) -> Option<String> {
    let (type_min, type_max): (i128, i128) = match type_name {
        "smallint" => (i16::MIN.into(), i16::MAX.into()),
        "integer" => (i32::MIN.into(), i32::MAX.into()),
        _ => (i64::MIN.into(), i64::MAX.into()),
    };
    let (default_min, default_max) = if increment > 0 { (1, type_max) } else { (type_min, -1) };
    let default_start = if increment > 0 { min } else { max };
    let mut opts: Vec<String> = Vec::new();
    if start != default_start {
        opts.push(format!("START WITH {start}"));
    }
    if increment != 1 {
        opts.push(format!("INCREMENT BY {increment}"));
    }
    if min != default_min {
        opts.push(format!("MINVALUE {min}"));
    }
    if max != default_max {
        opts.push(format!("MAXVALUE {max}"));
    }
    if cache != 1 {
        opts.push(format!("CACHE {cache}"));
    }
    if cycle {
        opts.push("CYCLE".into());
    }
    if !always && opts.is_empty() {
        return None;
    }
    let how = if always { "ALWAYS" } else { "BY DEFAULT" };
    Some(if opts.is_empty() { how.to_string() } else { format!("{how} ({})", opts.join(" ")) })
}

pub fn capabilities(v: Variant) -> Capabilities {
    let supported = crate::blocking::supported(v);
    Capabilities { blocking: supported, kill_session: supported, ..engine_capabilities(v) }
}

fn engine_capabilities(v: Variant) -> Capabilities {
    let all = Capabilities { create_database: true, drop_database: true, foreign_keys: true, monitor: true, ..Default::default() };
    match v {
        // A virtual layer: its databases and views are managed in Denodo.
        Variant::Denodo => Capabilities { monitor: true, ..Capabilities::default() },
        // One database per connection (a file), created on connect.
        Variant::H2 => Capabilities { create_database: false, drop_database: false, ..all },
        // One cluster-wide namespace of schemas; no foreign keys.
        Variant::CrateDb => Capabilities { create_database: false, drop_database: false, foreign_keys: false, monitor: true, ..Default::default() },
        // Greenplum (and its forks) parse FOREIGN KEY but don't keep it;
        // the streaming engines have no foreign keys at all.
        _ if v.mpp() || v.streaming() => Capabilities { foreign_keys: false, ..all },
        _ => all,
    }
}

const PG_TYPES: &[&str] = &[
    "integer",
    "bigint",
    "smallint",
    "numeric(18,2)",
    "real",
    "double precision",
    "boolean",
    "text",
    "varchar(50)",
    "varchar(255)",
    "char(10)",
    "date",
    "time",
    "timestamp",
    "timestamptz",
    "interval",
    "uuid",
    "jsonb",
    "json",
    "bytea",
    "inet",
    "text[]",
    "integer[]",
];

const COCKROACH_TYPES: &[&str] = &[
    "INT8",
    "INT4",
    "INT2",
    "DECIMAL(18,2)",
    "FLOAT8",
    "FLOAT4",
    "BOOL",
    "STRING",
    "VARCHAR(50)",
    "VARCHAR(255)",
    "DATE",
    "TIME",
    "TIMESTAMP",
    "TIMESTAMPTZ",
    "INTERVAL",
    "UUID",
    "JSONB",
    "BYTES",
    "INET",
    "STRING[]",
];

/// RisingWave takes `varchar` without a length.
const RISINGWAVE_TYPES: &[&str] = &[
    "integer",
    "bigint",
    "smallint",
    "numeric",
    "real",
    "double precision",
    "boolean",
    "varchar",
    "date",
    "time",
    "timestamp",
    "timestamptz",
    "interval",
    "jsonb",
    "bytea",
    "varchar[]",
    "integer[]",
];

const MATERIALIZE_TYPES: &[&str] = &[
    "integer",
    "bigint",
    "smallint",
    "numeric(18,2)",
    "real",
    "double precision",
    "boolean",
    "text",
    "varchar(255)",
    "date",
    "time",
    "timestamp",
    "timestamptz",
    "interval",
    "uuid",
    "jsonb",
    "bytea",
    "text[]",
];

const H2_TYPES: &[&str] = &[
    "INTEGER",
    "BIGINT",
    "SMALLINT",
    "NUMERIC(18,2)",
    "REAL",
    "DOUBLE PRECISION",
    "BOOLEAN",
    "VARCHAR(50)",
    "VARCHAR(255)",
    "CHARACTER(10)",
    "CHARACTER LARGE OBJECT",
    "DATE",
    "TIME",
    "TIMESTAMP",
    "TIMESTAMP WITH TIME ZONE",
    "UUID",
    "JSON",
    "VARBINARY(255)",
    "INTEGER ARRAY",
];

const CRATE_TYPES: &[&str] = &[
    "INTEGER",
    "BIGINT",
    "SMALLINT",
    "NUMERIC(18,2)",
    "REAL",
    "DOUBLE PRECISION",
    "BOOLEAN",
    "TEXT",
    "VARCHAR(255)",
    "TIMESTAMP WITH TIME ZONE",
    "TIMESTAMP WITHOUT TIME ZONE",
    "IP",
    "OBJECT",
    "ARRAY(TEXT)",
    "GEO_POINT",
    "GEO_SHAPE",
    "FLOAT_VECTOR(3)",
];

const REDSHIFT_TYPES: &[&str] = &[
    "INTEGER",
    "BIGINT",
    "SMALLINT",
    "DECIMAL(18,2)",
    "REAL",
    "DOUBLE PRECISION",
    "BOOLEAN",
    "VARCHAR(256)",
    "VARCHAR(MAX)",
    "CHAR(10)",
    "DATE",
    "TIME",
    "TIMESTAMP",
    "TIMESTAMPTZ",
    "SUPER",
    "VARBYTE(256)",
    "GEOMETRY",
];

pub fn designer(v: Variant) -> Option<DesignerSpec> {
    let mut d = DesignerSpec {
        schemas: true,
        comments: true,
        ..DesignerSpec::sql_table(match v {
            Variant::Cockroach => COCKROACH_TYPES.to_vec(),
            Variant::Redshift => REDSHIFT_TYPES.to_vec(),
            Variant::RisingWave => RISINGWAVE_TYPES.to_vec(),
            Variant::Materialize => MATERIALIZE_TYPES.to_vec(),
            Variant::CrateDb => CRATE_TYPES.to_vec(),
            Variant::H2 => H2_TYPES.to_vec(),
            _ => PG_TYPES.to_vec(),
        })
    };
    match v {
        Variant::Denodo => return None,
        Variant::Redshift => {
            // No indexes: distribution and sort keys instead.
            d.indexes = false;
            d.table_options = vec![
                Field::new(
                    "diststyle",
                    "Distribución (DISTSTYLE)",
                    FieldKind::Select(vec![("", "(automática)"), ("AUTO", "AUTO"), ("EVEN", "EVEN"), ("KEY", "KEY"), ("ALL", "ALL")]),
                ),
                Field::new("distkey", "Columna de distribución (DISTKEY)", FieldKind::Text).help("Con DISTSTYLE KEY."),
                Field::new("sortkey", "Columnas de orden (SORTKEY)", FieldKind::Text).placeholder("col1, col2"),
            ];
        }
        _ if v.mpp() => {
            d.foreign_keys = false;
            d.table_options = vec![Field::new("distributed_by", "Distribuir por (DISTRIBUTED BY)", FieldKind::Text)
                .placeholder("col1, col2")
                .help("Vacío: por la clave primaria o la primera columna. RANDOMLY para reparto al azar.")];
        }
        Variant::Timescale => {
            d.table_options = vec![Field::new("hypertable_time_column", "Hypertable: columna de tiempo", FieldKind::Text)
                .help("Si se indica, la tabla se convierte en hypertable (create_hypertable).")];
        }
        // Tables with a primary key but no identity columns, secondary
        // indexes, comments nor foreign keys; sharded instead.
        Variant::CrateDb => {
            d.auto_increment = false;
            d.indexes = false;
            d.comments = false;
            d.foreign_keys = false;
            d.table_options = vec![
                Field::new("shards", "Shards (CLUSTERED INTO)", FieldKind::Number).help("Vacío: los que elija CrateDB."),
                Field::new("clustered_by", "Columna de ruteo (CLUSTERED BY)", FieldKind::Text).help("Vacío: la clave primaria."),
                Field::new("number_of_replicas", "Réplicas (number_of_replicas)", FieldKind::Text).placeholder("0-1"),
            ];
        }
        Variant::RisingWave => {
            d.auto_increment = false;
            d.foreign_keys = false;
            d.table_options = vec![Field::new("append_only", "Solo inserciones (APPEND ONLY)", FieldKind::Bool)
                .help("Tablas sin clave primaria que solo reciben INSERT.")];
        }
        // Tables without constraints but NOT NULL; indexes are arrangements.
        Variant::Materialize => {
            d.primary_key = false;
            d.auto_increment = false;
            d.foreign_keys = false;
        }
        _ => {}
    }
    Some(d)
}

fn cols_list(s: &str) -> String {
    s.split(',').map(str::trim).filter(|c| !c.is_empty()).map(|c| quote_ident(Quote::Double, c)).collect::<Vec<_>>().join(", ")
}

fn opt<'a>(t: &'a TableSchema, k: &str) -> Option<&'a str> {
    t.options.get(k).map(|s| s.trim()).filter(|s| !s.is_empty())
}

/// `USING …` for a non-default access method this variant can take: any
/// the server reported (gin, gist, brin, hash, bloom, hnsw…) but the
/// default one.
fn using(v: Variant, kind: Option<&str>) -> Option<String> {
    // Cockroach's own names (a snapshot read before they were normalized,
    // or one going to another engine): `prefix` is btree, `inverted` GIN.
    let k = crate::compare::crdb_index_method(kind?).to_ascii_lowercase();
    match v {
        Variant::Cockroach => (k == "gin").then(|| "GIN".to_string()),
        // A single kind of index (an arrangement / a state table).
        Variant::RisingWave | Variant::Materialize | Variant::CrateDb | Variant::H2 => None,
        // Yugabyte's default is lsm; btree is PostgreSQL's.
        _ if k.is_empty() || matches!(k.as_str(), "btree" | "lsm") || k == crate::compare::EXCLUDE.to_ascii_lowercase() => None,
        _ => Some(k.to_ascii_uppercase()),
    }
}

pub fn table_ddl(v: Variant, t: &TableSchema, parts: DdlParts) -> String {
    let f = flavor(v);
    let name = qualified_name(Quote::Double, t.schema.as_deref().filter(|s| !s.is_empty()), &t.name);
    let mut out: Vec<String> = Vec::new();
    if parts.drop || parts.create {
        let mut s = ddl::table_ddl(&f, t, DdlParts { drop: parts.drop, if_exists: parts.if_exists, create: parts.create, ..Default::default() });
        if parts.create && identity_options(v) {
            // Identity columns with ALWAYS or sequence options (the generic
            // builder writes a plain `GENERATED BY DEFAULT AS IDENTITY`).
            for c in t.columns.iter().filter(|c| c.auto_increment) {
                let (plain, full) = (ddl::column_def(&f, t, c), column_def(v, &f, t, c));
                if plain != full {
                    s = s.replacen(&format!("\n    {plain}"), &format!("\n    {full}"), 1);
                }
            }
        }
        if parts.create {
            // Table options go right after the closing parenthesis.
            let mut tail = String::new();
            match v {
                Variant::Redshift => {
                    if let Some(d) = opt(t, "diststyle") {
                        tail.push_str(&format!(" DISTSTYLE {d}"));
                    }
                    if let Some(k) = opt(t, "distkey") {
                        tail.push_str(&format!(" DISTKEY ({})", cols_list(k)));
                    }
                    if let Some(k) = opt(t, "sortkey") {
                        tail.push_str(&format!(" SORTKEY ({})", cols_list(k)));
                    }
                }
                _ if v.mpp() => match opt(t, "distributed_by") {
                    Some(r) if r.eq_ignore_ascii_case("randomly") => tail.push_str(" DISTRIBUTED RANDOMLY"),
                    Some(k) => tail.push_str(&format!(" DISTRIBUTED BY ({})", cols_list(k))),
                    None => {}
                },
                Variant::CrateDb => {
                    if let Some(k) = opt(t, "clustered_by") {
                        tail.push_str(&format!(" CLUSTERED BY ({})", cols_list(k)));
                    }
                    if let Some(n) = opt(t, "shards") {
                        if !tail.is_empty() {
                            tail.push_str(&format!(" INTO {n} SHARDS"));
                        } else {
                            tail.push_str(&format!(" CLUSTERED INTO {n} SHARDS"));
                        }
                    }
                    if let Some(r) = opt(t, "number_of_replicas") {
                        tail.push_str(&format!(" WITH (number_of_replicas = {})", ddl::sql_literal(&f, &Value::String(r.to_string()))));
                    }
                }
                Variant::RisingWave if opt(t, "append_only") == Some("true") => tail.push_str(" APPEND ONLY"),
                _ => {}
            }
            if !tail.is_empty() {
                s = s.replacen("\n);", &format!("\n){tail};"), 1);
            }
            if v == Variant::OpenGauss {
                s = serial_columns(&s);
            }
            // CrateDB's indexes live in CREATE TABLE only.
            if v == Variant::CrateDb {
                s = crate::compare::crate_create_indexes(&s, &t.indexes);
            }
        }
        out.push(s);
        if parts.create && v == Variant::Timescale {
            if let Some(c) = opt(t, "hypertable_time_column") {
                out.push(format!(
                    "SELECT create_hypertable({}, {}{});",
                    ddl::sql_literal(&f, &Value::String(name.clone())),
                    ddl::sql_literal(&f, &Value::String(c.to_string())),
                    if parts.if_exists { ", if_not_exists => TRUE" } else { "" }
                ));
            }
        }
    }
    if parts.indexes && !matches!(v, Variant::Redshift | Variant::Denodo | Variant::CrateDb) {
        for ix in &t.indexes {
            out.push(crate::compare::index_ddl(v, &name, ix, using(v, ix.kind.as_deref()).as_deref(), parts.if_exists));
        }
    }
    if parts.foreign_keys && capabilities(v).foreign_keys {
        for fk in &t.foreign_keys {
            let one = TableSchema { schema: t.schema.clone(), name: t.name.clone(), foreign_keys: vec![fk.clone()], ..Default::default() };
            let s = ddl::table_ddl(&f, &one, DdlParts { foreign_keys: true, ..Default::default() });
            let named = fk.name.as_deref().is_some_and(|n| !n.is_empty());
            out.push(match v {
                _ if !parts.if_exists || !named => s,
                Variant::Cockroach => s.replacen(" ADD CONSTRAINT ", " ADD CONSTRAINT IF NOT EXISTS ", 1),
                // No IF NOT EXISTS for constraints: a block that tolerates it.
                _ if v.plpgsql() => format!(
                    "DO $$ BEGIN\n    {s}\nEXCEPTION WHEN duplicate_object THEN NULL;\nEND $$;"
                ),
                _ => s,
            });
        }
    }
    out.retain(|s| !s.is_empty());
    out.join("\n")
}

/// openGauss has no identity columns: `integer GENERATED BY DEFAULT AS
/// IDENTITY` becomes `serial` (and bigint / smallint their serials).
fn serial_columns(s: &str) -> String {
    const IDENTITY: &str = " GENERATED BY DEFAULT AS IDENTITY";
    let mut out = s.to_string();
    for (ty, serial) in [
        ("bigint", "bigserial"),
        ("int8", "bigserial"),
        ("integer", "serial"),
        ("int4", "serial"),
        ("int", "serial"),
        ("smallint", "smallserial"),
        ("int2", "smallserial"),
    ] {
        for t in [ty.to_string(), ty.to_uppercase()] {
            out = out.replace(&format!(" {t}{IDENTITY}"), &format!(" {serial}"));
        }
    }
    out.replace(IDENTITY, "")
}

/// INSERTs: Redshift reads backslashes in literals as escapes.
pub fn insert_script(v: Variant, schema: Option<&str>, table: &str, columns: &[String], rows: &[Vec<Value>]) -> String {
    let f = flavor(v);
    if v != Variant::Redshift {
        return ddl::insert_script(&f, schema, table, columns, rows, 100);
    }
    let escaped: Vec<Vec<Value>> = rows
        .iter()
        .map(|r| r.iter().map(|c| match c { Value::String(s) => Value::String(s.replace('\\', "\\\\")), o => o.clone() }).collect())
        .collect();
    ddl::insert_script(&f, schema, table, columns, &escaped, 100)
}

/// `UPDATE … WHERE <key>` per changed row, with the same literals (and
/// Redshift's backslash escaping) as [`insert_script`].
pub fn update_script(v: Variant, schema: Option<&str>, table: &str, changes: &[RowChange]) -> String {
    let f = flavor(v);
    ddl::update_script_with(f.quote, schema, table, changes, &|c| literal(v, &f, c))
}

/// `DELETE … WHERE <key>` per row key, with the same literals as
/// [`update_script`].
pub fn delete_script(v: Variant, schema: Option<&str>, table: &str, keys: &[Vec<(String, Value)>]) -> String {
    let f = flavor(v);
    ddl::delete_script_with(f.quote, schema, table, keys, &|c| literal(v, &f, c))
}

/// A value as a literal of the variant (Redshift reads backslashes as escapes).
fn literal(v: Variant, f: &ddl::SqlFlavor, c: &Value) -> String {
    match c {
        Value::String(s) if v == Variant::Redshift => ddl::sql_literal(f, &Value::String(s.replace('\\', "\\\\"))),
        o => ddl::sql_literal(f, o),
    }
}

pub fn create_templates(v: Variant) -> Vec<CreateTemplate> {
    let t = |kind, label, template: &str| CreateTemplate { kind, label, template: template.to_string() };
    let view = t(kinds::VIEW, "Nueva vista", "CREATE OR REPLACE VIEW \"{schema}\".\"{name}\" AS\nSELECT\n    t.id,\n    t.nombre\nFROM \"{schema}\".\"tabla\" AS t\nWHERE t.activo;\n");
    match v {
        Variant::Denodo => vec![t(
            kinds::VIEW,
            "Nueva vista",
            "CREATE OR REPLACE VIEW {name} AS\nSELECT id, nombre\nFROM vista_base\nWHERE activo = true;\n",
        )],
        Variant::Redshift => vec![
            view,
            t(
                kinds::PROCEDURE,
                "Nuevo procedimiento",
                "CREATE OR REPLACE PROCEDURE \"{schema}\".\"{name}\"(p_id integer)\nAS $$\nBEGIN\n    UPDATE \"{schema}\".\"tabla\" SET activo = false WHERE id = p_id;\nEND;\n$$ LANGUAGE plpgsql;\n",
            ),
            t(
                kinds::FUNCTION,
                "Nueva función",
                "CREATE OR REPLACE FUNCTION \"{schema}\".\"{name}\"(integer)\nRETURNS integer\nSTABLE\nAS $$\n    SELECT $1 * 2\n$$ LANGUAGE sql;\n",
            ),
        ],
        Variant::CrateDb | Variant::H2 => vec![view],
        Variant::Yellowbrick => vec![
            view,
            t(
                kinds::FUNCTION,
                "Nueva función",
                "CREATE OR REPLACE FUNCTION \"{schema}\".\"{name}\"(valor integer)\nRETURNS integer\nLANGUAGE sql\nIMMUTABLE\nAS $$\n    SELECT valor * 2\n$$;\n",
            ),
        ],
        // No CREATE OR REPLACE VIEW.
        Variant::RisingWave => vec![
            t(kinds::VIEW, "Nueva vista", &view.template.replacen("CREATE OR REPLACE VIEW", "CREATE VIEW", 1)),
            t(
                kinds::MATERIALIZED_VIEW,
                "Nueva vista materializada",
                "CREATE MATERIALIZED VIEW \"{schema}\".\"{name}\" AS\nSELECT categoria, count(*) AS cantidad\nFROM \"{schema}\".\"tabla\"\nGROUP BY categoria;\n\n-- Se mantiene sola: cada cambio en la tabla la actualiza.\n",
            ),
            t(
                crate::SOURCE,
                "Nueva fuente",
                "CREATE SOURCE \"{schema}\".\"{name}\" (\n    id integer,\n    nombre varchar,\n    creado timestamptz\n) WITH (\n    connector = 'kafka',\n    topic = 'mi_topico',\n    properties.bootstrap.server = 'localhost:9092',\n    scan.startup.mode = 'earliest'\n) FORMAT PLAIN ENCODE JSON;\n",
            ),
            t(
                crate::SINK,
                "Nuevo sink",
                "CREATE SINK \"{schema}\".\"{name}\" FROM \"{schema}\".\"vista_materializada\"\nWITH (\n    connector = 'kafka',\n    topic = 'mi_topico_salida',\n    properties.bootstrap.server = 'localhost:9092'\n) FORMAT PLAIN ENCODE JSON (force_append_only = 'true');\n",
            ),
        ],
        Variant::Materialize => vec![
            view,
            t(
                kinds::MATERIALIZED_VIEW,
                "Nueva vista materializada",
                "CREATE MATERIALIZED VIEW \"{schema}\".\"{name}\"\nIN CLUSTER quickstart AS\nSELECT categoria, count(*) AS cantidad\nFROM \"{schema}\".\"tabla\"\nGROUP BY categoria;\n\n-- Se mantiene sola: cada cambio en la tabla la actualiza.\n",
            ),
            t(
                crate::SOURCE,
                "Nueva fuente",
                "CREATE SOURCE \"{schema}\".\"{name}\"\nIN CLUSTER quickstart\nFROM LOAD GENERATOR COUNTER (TICK INTERVAL '1s');\n\n-- Kafka: CREATE CONNECTION kafka_conn TO KAFKA (BROKER 'localhost:9092');\n-- CREATE SOURCE ... FROM KAFKA CONNECTION kafka_conn (TOPIC 'mi_topico') FORMAT JSON;\n",
            ),
            t(
                crate::SINK,
                "Nuevo sink",
                "CREATE SINK \"{schema}\".\"{name}\"\nIN CLUSTER quickstart\nFROM \"{schema}\".\"vista_materializada\"\nINTO KAFKA CONNECTION kafka_conn (TOPIC 'mi_topico_salida')\nFORMAT JSON\nENVELOPE DEBEZIUM;\n",
            ),
        ],
        Variant::Cockroach => vec![
            view,
            t(
                kinds::MATERIALIZED_VIEW,
                "Nueva vista materializada",
                "CREATE MATERIALIZED VIEW \"{schema}\".\"{name}\" AS\nSELECT categoria, count(*) AS cantidad\nFROM \"{schema}\".\"tabla\"\nGROUP BY categoria;\n\n-- Para actualizarla: REFRESH MATERIALIZED VIEW \"{schema}\".\"{name}\";\n",
            ),
            t(
                kinds::PROCEDURE,
                "Nuevo procedimiento",
                "CREATE OR REPLACE PROCEDURE \"{schema}\".\"{name}\"(p_id INT8)\nLANGUAGE PLpgSQL\nAS $$\nBEGIN\n    UPDATE \"{schema}\".\"tabla\" SET activo = false WHERE id = p_id;\nEND;\n$$;\n",
            ),
            t(
                kinds::FUNCTION,
                "Nueva función",
                "CREATE OR REPLACE FUNCTION \"{schema}\".\"{name}\"(valor INT8)\nRETURNS INT8\nLANGUAGE SQL\nIMMUTABLE\nAS $$\n    SELECT valor * 2\n$$;\n",
            ),
            t(
                kinds::TRIGGER,
                "Nuevo trigger",
                "CREATE OR REPLACE FUNCTION \"{schema}\".\"{name}_fn\"()\nRETURNS TRIGGER\nLANGUAGE PLpgSQL\nAS $$\nBEGIN\n    NEW.modificado := now();\n    RETURN NEW;\nEND;\n$$;\n\nCREATE TRIGGER \"{name}\"\nBEFORE INSERT OR UPDATE ON \"{schema}\".\"tabla\"\nFOR EACH ROW EXECUTE FUNCTION \"{schema}\".\"{name}_fn\"();\n",
            ),
        ],
        _ => vec![
            view,
            t(
                kinds::MATERIALIZED_VIEW,
                "Nueva vista materializada",
                "CREATE MATERIALIZED VIEW \"{schema}\".\"{name}\" AS\nSELECT categoria, count(*) AS cantidad\nFROM \"{schema}\".\"tabla\"\nGROUP BY categoria\nWITH DATA;\n\n-- Para actualizarla: REFRESH MATERIALIZED VIEW \"{schema}\".\"{name}\";\n",
            ),
            t(
                kinds::PROCEDURE,
                "Nuevo procedimiento",
                "CREATE OR REPLACE PROCEDURE \"{schema}\".\"{name}\"(p_id integer)\nLANGUAGE plpgsql\nAS $$\nBEGIN\n    UPDATE \"{schema}\".\"tabla\" SET activo = false WHERE id = p_id;\n    COMMIT;\nEND;\n$$;\n\n-- CALL \"{schema}\".\"{name}\"(1);\n",
            ),
            t(
                kinds::FUNCTION,
                "Nueva función",
                "CREATE OR REPLACE FUNCTION \"{schema}\".\"{name}\"(valor integer)\nRETURNS integer\nLANGUAGE plpgsql\nIMMUTABLE\nAS $$\nBEGIN\n    RETURN valor * 2;\nEND;\n$$;\n",
            ),
            t(
                kinds::TRIGGER,
                "Nuevo trigger",
                "CREATE OR REPLACE FUNCTION \"{schema}\".\"{name}_fn\"()\nRETURNS trigger\nLANGUAGE plpgsql\nAS $$\nBEGIN\n    NEW.modificado := now();\n    RETURN NEW;\nEND;\n$$;\n\nCREATE TRIGGER \"{name}\"\nBEFORE INSERT OR UPDATE ON \"{schema}\".\"tabla\"\nFOR EACH ROW EXECUTE FUNCTION \"{schema}\".\"{name}_fn\"();\n",
            ),
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use dbine_driver::{ColumnDef, ForeignKeyDef, IndexDef, KeyDef};
    use serde_json::json;

    #[test]
    fn update_script_escapes_quotes_and_redshift_backslashes() {
        let c = RowChange {
            key: vec![("id".into(), json!(7)), ("region".into(), Value::Null)],
            set: vec![("nombre".into(), json!("O'Brien\\x")), ("baja".into(), Value::Null)], ..Default::default()
        };
        assert_eq!(
            update_script(Variant::Postgres, Some("public"), "clientes", std::slice::from_ref(&c)),
            "UPDATE \"public\".\"clientes\" SET \"nombre\" = 'O''Brien\\x', \"baja\" = NULL WHERE \"id\" = 7 AND \"region\" IS NULL;"
        );
        assert_eq!(
            update_script(Variant::Redshift, Some("public"), "clientes", &[c]),
            "UPDATE \"public\".\"clientes\" SET \"nombre\" = 'O''Brien\\\\x', \"baja\" = NULL WHERE \"id\" = 7 AND \"region\" IS NULL;"
        );
    }

    #[test]
    fn delete_script_by_composite_key() {
        let keys = vec![
            vec![("nombre".into(), json!("O'Brien\\x")), ("region".into(), Value::Null)],
            vec![],
        ];
        assert_eq!(
            delete_script(Variant::Postgres, Some("public"), "clientes", &keys),
            "DELETE FROM \"public\".\"clientes\" WHERE \"nombre\" = 'O''Brien\\x' AND \"region\" IS NULL;"
        );
        assert_eq!(
            delete_script(Variant::Redshift, Some("public"), "clientes", &keys),
            "DELETE FROM \"public\".\"clientes\" WHERE \"nombre\" = 'O''Brien\\\\x' AND \"region\" IS NULL;"
        );
    }

    fn sample() -> TableSchema {
        TableSchema {
            kind: "table".into(),
            schema: Some("app".into()),
            name: "pedidos".into(),
            columns: vec![
                ColumnDef { name: "id".into(), data_type: "bigint".into(), nullable: false, auto_increment: true, ..Default::default() },
                ColumnDef { name: "cliente_id".into(), data_type: "integer".into(), comment: Some("Dueño".into()), ..Default::default() },
                ColumnDef { name: "email".into(), data_type: "text".into(), nullable: false, default_value: Some("''::text".into()), ..Default::default() },
            ],
            primary_key: Some(KeyDef { name: Some("pedidos_pkey".into()), columns: vec!["id".into()] }),
            foreign_keys: vec![ForeignKeyDef {
                name: Some("pedidos_cliente_fk".into()),
                columns: vec!["cliente_id".into()],
                ref_schema: Some("app".into()),
                ref_table: "clientes".into(),
                ref_columns: vec!["id".into()],
                on_delete: Some("CASCADE".into()),
                on_update: None,
            }],
            indexes: vec![
                IndexDef { name: "ux_email".into(), columns: vec!["(lower(email))".into()], unique: true, kind: Some("btree".into()), filter: None, ..Default::default() },
                IndexDef { name: "ix_gin".into(), columns: vec!["email".into()], unique: false, kind: Some("gin".into()), filter: Some("(cliente_id IS NOT NULL)".into()), ..Default::default() },
            ],
            comment: Some("Pedidos".into()),
            ..Default::default()
        }
    }

    const ALL: DdlParts = DdlParts { drop: false, if_exists: false, create: true, indexes: true, foreign_keys: true };

    #[test]
    fn postgres_ddl() {
        let s = table_ddl(Variant::Postgres, &sample(), ALL);
        assert!(s.contains("\"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,"), "{s}");
        assert!(s.contains("\"email\" text DEFAULT ''::text NOT NULL,"));
        assert!(s.contains("CONSTRAINT \"pedidos_pkey\" PRIMARY KEY (\"id\")"));
        assert!(s.contains("COMMENT ON TABLE \"app\".\"pedidos\" IS 'Pedidos';"));
        assert!(s.contains("COMMENT ON COLUMN \"app\".\"pedidos\".\"cliente_id\" IS 'Dueño';"));
        assert!(s.contains("CREATE UNIQUE INDEX \"ux_email\" ON \"app\".\"pedidos\" ((lower(email)));"));
        assert!(s.contains("CREATE INDEX \"ix_gin\" ON \"app\".\"pedidos\" USING GIN (\"email\") WHERE (cliente_id IS NOT NULL);"));
        assert!(s.ends_with("ALTER TABLE \"app\".\"pedidos\" ADD CONSTRAINT \"pedidos_cliente_fk\" FOREIGN KEY (\"cliente_id\") REFERENCES \"app\".\"clientes\" (\"id\") ON DELETE CASCADE;"));
    }

    #[test]
    fn identity_options_from_the_catalog() {
        let max = i64::MAX as i128;
        // Defaults stay implicit.
        assert_eq!(identity_option(false, "bigint", 1, 1, 1, max, 1, false), None);
        assert_eq!(identity_option(true, "bigint", 1, 1, 1, max, 1, false).as_deref(), Some("ALWAYS"));
        assert_eq!(
            identity_option(false, "integer", 100, 5, 1, i32::MAX.into(), 1, false).as_deref(),
            Some("BY DEFAULT (START WITH 100 INCREMENT BY 5)")
        );
        assert_eq!(
            identity_option(true, "smallint", 10, 1, 10, 500, 20, true).as_deref(),
            Some("ALWAYS (MINVALUE 10 MAXVALUE 500 CACHE 20 CYCLE)")
        );
        // Descending: starts at -1 by default, the type's minimum.
        assert_eq!(identity_option(false, "integer", -1, -1, i32::MIN.into(), -1, 1, false).as_deref(), Some("BY DEFAULT (INCREMENT BY -1)"));
    }

    #[test]
    fn identity_options_in_the_ddl() {
        let mut t = sample();
        t.columns[0].options.insert(IDENTITY_OPTION.into(), "BY DEFAULT (START WITH 100 INCREMENT BY 5)".into());
        let s = table_ddl(Variant::Postgres, &t, ALL);
        assert!(s.contains("\n    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5) NOT NULL,"), "{s}");
        t.columns[0].options.insert(IDENTITY_OPTION.into(), "ALWAYS (MINVALUE 10 MAXVALUE 500 CACHE 20 CYCLE)".into());
        for v in [Variant::Postgres, Variant::Timescale, Variant::Yugabyte, Variant::AlloyDb] {
            let s = table_ddl(v, &t, ALL);
            assert!(s.contains("\"id\" bigint GENERATED ALWAYS AS IDENTITY (MINVALUE 10 MAXVALUE 500 CACHE 20 CYCLE) NOT NULL,"), "{v:?}: {s}");
        }
        // ADD COLUMN in a sync script too.
        let f = flavor(Variant::Postgres);
        assert_eq!(column_def(Variant::Postgres, &f, &t, &t.columns[0]), "\"id\" bigint GENERATED ALWAYS AS IDENTITY (MINVALUE 10 MAXVALUE 500 CACHE 20 CYCLE) NOT NULL");
        // Variants without these options keep what they wrote.
        assert!(table_ddl(Variant::Cockroach, &t, ALL).contains("\"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,"));
        assert!(table_ddl(Variant::OpenGauss, &t, ALL).contains("\"id\" bigserial NOT NULL,"));
        assert!(table_ddl(Variant::Redshift, &t, ALL).contains("\"id\" bigint IDENTITY(1,1) NOT NULL"));
        // Only the recognized words make it into the DDL.
        for bad in ["ALWAYS; DROP TABLE x", "1000,5", "BY DEFAULT (START WITH 1 OWNED BY x.y)", "ALWAYS (CACHE)"] {
            t.columns[0].options.insert(IDENTITY_OPTION.into(), bad.into());
            assert!(table_ddl(Variant::Postgres, &t, ALL).contains("\"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,"), "{bad}");
        }
        assert_eq!(identity_clause("always (start 3 increment -2 no cycle)").as_deref(), Some(" GENERATED ALWAYS AS IDENTITY (START WITH 3 INCREMENT BY -2 NO CYCLE)"));
    }

    #[test]
    fn if_exists_guards() {
        let s = table_ddl(Variant::Postgres, &sample(), DdlParts { if_exists: true, ..ALL });
        assert!(s.starts_with("CREATE TABLE IF NOT EXISTS \"app\".\"pedidos\""));
        assert!(s.contains("CREATE UNIQUE INDEX IF NOT EXISTS \"ux_email\""));
        assert!(s.contains("DO $$ BEGIN\n    ALTER TABLE"), "{s}");
        let c = table_ddl(Variant::Cockroach, &sample(), DdlParts { if_exists: true, foreign_keys: true, ..Default::default() });
        assert_eq!(c, "ALTER TABLE \"app\".\"pedidos\" ADD CONSTRAINT IF NOT EXISTS \"pedidos_cliente_fk\" FOREIGN KEY (\"cliente_id\") REFERENCES \"app\".\"clientes\" (\"id\") ON DELETE CASCADE;");
        let d = table_ddl(Variant::Postgres, &sample(), DdlParts { drop: true, if_exists: true, ..Default::default() });
        assert_eq!(d, "DROP TABLE IF EXISTS \"app\".\"pedidos\";");
    }

    #[test]
    fn redshift_identity_and_keys_no_indexes() {
        let mut t = sample();
        t.options.insert("diststyle".into(), "KEY".into());
        t.options.insert("distkey".into(), "cliente_id".into());
        t.options.insert("sortkey".into(), "id, cliente_id".into());
        let s = table_ddl(Variant::Redshift, &t, ALL);
        assert!(s.contains("\"id\" bigint IDENTITY(1,1) NOT NULL"));
        assert!(s.contains("\n) DISTSTYLE KEY DISTKEY (\"cliente_id\") SORTKEY (\"id\", \"cliente_id\");"), "{s}");
        assert!(!s.contains("CREATE INDEX") && !s.contains("CREATE UNIQUE"));
        assert!(s.contains("FOREIGN KEY"));
    }

    #[test]
    fn greenplum_distribution_and_timescale_hypertable() {
        let mut t = sample();
        t.options.insert("distributed_by".into(), "id".into());
        let s = table_ddl(Variant::Greenplum, &t, ALL);
        assert!(s.contains("\n) DISTRIBUTED BY (\"id\");"));
        assert!(!s.contains("FOREIGN KEY"));
        let mut t = sample();
        t.options.insert("hypertable_time_column".into(), "creado".into());
        let s = table_ddl(Variant::Timescale, &t, DdlParts { create: true, ..Default::default() });
        assert!(s.contains("SELECT create_hypertable('\"app\".\"pedidos\"', 'creado');"), "{s}");
    }

    #[test]
    fn cockroach_index_methods() {
        let s = table_ddl(Variant::Cockroach, &sample(), DdlParts { indexes: true, ..Default::default() });
        assert!(s.contains("CREATE INDEX \"ix_gin\" ON \"app\".\"pedidos\" USING GIN"));
        let mut t = sample();
        t.indexes[1].kind = Some("prefix".into());
        assert!(!table_ddl(Variant::Cockroach, &t, DdlParts { indexes: true, ..Default::default() }).contains("USING"));
        // Cockroach's raw names (an older snapshot) on Cockroach and on PostgreSQL.
        let ix = DdlParts { indexes: true, ..Default::default() };
        assert!(!table_ddl(Variant::Postgres, &t, ix).contains("USING"));
        t.indexes[1].kind = Some("inverted".into());
        assert!(table_ddl(Variant::Cockroach, &t, ix).contains("\"pedidos\" USING GIN"));
        assert!(table_ddl(Variant::Postgres, &t, ix).contains("\"pedidos\" USING GIN"));
        // The normalized names.
        t.indexes[1].kind = Some("btree".into());
        assert!(!table_ddl(Variant::Cockroach, &t, ix).contains("USING"));
        assert_eq!(using(Variant::Postgres, Some("gin")).as_deref(), Some("GIN"));
        assert_eq!(using(Variant::Postgres, Some("hash")).as_deref(), Some("HASH"));
        assert_eq!(using(Variant::Cockroach, Some("hash")), None);
    }

    #[test]
    fn inserts() {
        let rows = vec![vec![json!(1), json!("a\\b"), json!(true)]];
        let cols = ["a".to_string(), "b".into(), "c".into()];
        assert_eq!(insert_script(Variant::Postgres, Some("s"), "t", &cols, &rows), "INSERT INTO \"s\".\"t\" (\"a\", \"b\", \"c\") VALUES\n  (1, 'a\\b', TRUE);");
        assert!(insert_script(Variant::Redshift, None, "t", &cols, &rows).contains("'a\\\\b'"));
    }

    #[test]
    fn every_declared_kind_has_a_template() {
        for v in Variant::ALL {
            // Sequences, types and synonyms are listed for the schema compare.
            let declared: Vec<&str> =
                v.info().object_kinds.iter().map(|k| k.id).filter(|k| *k != kinds::TABLE && !crate::compare::KINDS.contains(k)).collect();
            let mut have: Vec<&str> = create_templates(v).iter().map(|t| t.kind).collect();
            have.sort();
            let mut want = declared.clone();
            want.sort();
            assert_eq!(have, want, "{v:?}");
        }
    }
}
