//! Against a real server:
//!
//! ```sh
//! docker run -d --name dbine-test-oracle -p 25601:1521 -e ORACLE_PASSWORD=Secret123 \
//!   -e APP_USER=dbine -e APP_USER_PASSWORD=Dbine123 gvenzl/oracle-free:23-slim
//! DBINE_TEST_ORACLE_URL=oracle://dbine:Dbine123@localhost:25601/FREEPDB1 \
//!   cargo test -p dbine-driver-oracle -- --ignored
//! ```

use dbine_driver::{ConnectionConfig, DdlParts, ObjectRef, QueryOutcome, Session};
use serde_json::json;

fn config() -> ConnectionConfig {
    config_from(&std::env::var("DBINE_TEST_ORACLE_URL").expect("DBINE_TEST_ORACLE_URL"))
}

fn config_from(url: &str) -> ConnectionConfig {
    let rest = url.strip_prefix("oracle://").expect("oracle://user:pass@host:port/service");
    let (cred, addr) = rest.split_once('@').unwrap();
    let (user, pass) = cred.split_once(':').unwrap();
    let (hostport, service) = addr.split_once('/').unwrap();
    let (host, port) = hostport.split_once(':').unwrap();
    let mut cfg = ConnectionConfig {
        driver: "oracle".into(),
        host: host.into(),
        port: port.parse().unwrap(),
        username: Some(user.into()),
        password: Some(pass.into()),
        ..Default::default()
    };
    cfg.options.insert("service".into(), service.into());
    cfg
}

async fn session() -> Box<dyn Session> {
    let driver = dbine_driver_oracle::drivers().remove(0);
    driver.connect(&config(), None).await.expect("connect")
}

async fn run(s: &mut Box<dyn Session>, sql: &str) -> QueryOutcome {
    let mut out = QueryOutcome::default();
    if let Err(e) = s.execute(sql, 1000, &mut out).await {
        panic!("{sql}: {e}");
    }
    out
}

fn obj(kind: &str, name: &str) -> ObjectRef {
    ObjectRef { kind: kind.into(), schema: None, name: name.into() }
}

#[tokio::test]
#[ignore]
async fn catalog_values_and_scripts() {
    let mut s = session().await;
    let v = s.server_version().await.unwrap();
    assert!(v.contains("Oracle"), "{v}");

    // Clean slate (errors ignored: objects may not exist).
    for d in ["DROP TABLE dbine_t PURGE", "DROP VIEW dbine_v", "DROP SEQUENCE dbine_seq", "DROP PACKAGE dbine_pkg",
        "DROP PROCEDURE dbine_proc", "DROP FUNCTION dbine_fn", "DROP MATERIALIZED VIEW dbine_mv"]
    {
        let _ = s.execute(d, 10, &mut QueryOutcome::default()).await;
    }

    let script = r#"
CREATE TABLE dbine_t (
  id NUMBER(10) PRIMARY KEY,
  name VARCHAR2(50) DEFAULT 'x' NOT NULL,
  amount NUMBER(12,2),
  big NUMBER,
  ts TIMESTAMP(6),
  d DATE,
  doc CLOB,
  bin RAW(4),
  ident NUMBER GENERATED BY DEFAULT AS IDENTITY
);
CREATE VIEW dbine_v AS SELECT id, name FROM dbine_t;
CREATE MATERIALIZED VIEW dbine_mv AS SELECT id FROM dbine_t;
CREATE SEQUENCE dbine_seq;
CREATE OR REPLACE PROCEDURE dbine_proc(p IN NUMBER) AS
BEGIN
  DBMS_OUTPUT.PUT_LINE('proc ' || p);
END;
/
CREATE OR REPLACE FUNCTION dbine_fn RETURN NUMBER AS BEGIN RETURN 1; END;
/
CREATE OR REPLACE PACKAGE dbine_pkg AS
  PROCEDURE hello;
END;
/
CREATE OR REPLACE PACKAGE BODY dbine_pkg AS
  PROCEDURE hello IS BEGIN DBMS_OUTPUT.PUT_LINE('hello; world'); END;
END;
/
CREATE OR REPLACE TRIGGER dbine_trg BEFORE INSERT ON dbine_t FOR EACH ROW
BEGIN
  :new.name := UPPER(:new.name);
END;
/
INSERT INTO dbine_t (id, name, amount, big, ts, d, doc, bin)
  VALUES (1, 'uno;dos', 1234.5, 123456789012345678901234567890, TIMESTAMP '2024-01-31 13:45:00.123',
          DATE '2024-02-01', 'texto largo', HEXTORAW('DEADBEEF'));
INSERT INTO dbine_t (id, name) VALUES (2, 'b');
exec dbine_proc(7);
BEGIN
  dbine_pkg.hello;
END;
/
"#;
    let out = run(&mut s, script).await;
    assert!(out.messages.contains(&"proc 7".to_string()), "{:?}", out.messages);
    assert!(out.messages.contains(&"hello; world".to_string()), "{:?}", out.messages);
    let affected: Vec<_> = out.results.iter().filter_map(|r| r.rows_affected).collect();
    assert_eq!(affected, vec![1, 1]);

    // Autocommit is on by default: a second session sees the rows.
    let mut other = session().await;
    let o = run(&mut other, "SELECT COUNT(*) FROM dbine_t").await;
    assert_eq!(o.results[0].rows[0][0], json!(2));

    let dbs = s.list_databases().await.unwrap();
    assert!(dbs.contains(&"DBINE".to_string()), "{dbs:?}");
    assert!(!dbs.contains(&"SYS".to_string()), "{dbs:?}");

    let objs = s.list_objects().await.unwrap();
    let has = |k: &str, n: &str| objs.iter().any(|o| o.kind == k && o.name == n);
    assert!(has("table", "DBINE_T"));
    assert!(has("view", "DBINE_V"));
    assert!(has("materialized_view", "DBINE_MV"));
    assert!(!has("table", "DBINE_MV"), "an MV is not listed as a table too");
    assert!(has("sequence", "DBINE_SEQ"));
    assert!(has("procedure", "DBINE_PROC"));
    assert!(has("function", "DBINE_FN"));
    assert!(has("package", "DBINE_PKG"));
    let trg = objs.iter().find(|o| o.kind == "trigger" && o.name == "DBINE_TRG").unwrap();
    assert_eq!(trg.parent.as_deref(), Some("DBINE_T"));
    assert!(!objs.iter().any(|o| o.name.starts_with("ISEQ$$")), "identity sequences are hidden");

    let cols = s.columns(&obj("table", "DBINE_T")).await.unwrap();
    let names: Vec<_> = cols.iter().map(|c| c.name.as_str()).collect();
    assert_eq!(names, ["ID", "NAME", "AMOUNT", "BIG", "TS", "D", "DOC", "BIN", "IDENT"]);
    assert!(cols[0].primary_key && !cols[0].nullable);
    assert_eq!(cols[0].data_type, "NUMBER(10)");
    assert_eq!(cols[1].data_type, "VARCHAR2(50)");
    assert_eq!(cols[1].default_value.as_deref(), Some("'x'"));
    assert_eq!(cols[2].data_type, "NUMBER(12,2)");
    assert!(cols[8].auto_increment);

    let ddl = s.definition(&obj("table", "DBINE_T")).await.unwrap().unwrap();
    assert!(ddl.contains("CREATE TABLE"), "{ddl}");
    let ddl = s.definition(&obj("package", "DBINE_PKG")).await.unwrap().unwrap();
    assert!(ddl.contains("PACKAGE BODY"), "{ddl}");
    let ddl = s.definition(&obj("view", "DBINE_V")).await.unwrap().unwrap();
    assert!(ddl.to_uppercase().contains("VIEW"), "{ddl}");

    let q = s.browse_query(&obj("table", "DBINE_T"), 10);
    assert_eq!(q, "SELECT *\nFROM \"DBINE\".\"DBINE_T\"\nFETCH FIRST 10 ROWS ONLY");
    let out = run(&mut s, &format!("{q}")).await;
    let r = &out.results[0];
    assert_eq!(r.total_rows, 2);
    let row = r.rows.iter().find(|row| row[0] == json!(1)).unwrap();
    assert_eq!(row[1], json!("UNO;DOS"), "trigger upper-cased it");
    assert_eq!(row[2], json!("1234.5"));
    assert_eq!(row[3], json!("123456789012345678901234567890"));
    assert_eq!(row[4], json!("2024-01-31 13:45:00.123"));
    assert_eq!(row[5], json!("2024-02-01 00:00:00"));
    assert_eq!(row[6], json!("texto largo"));
    assert_eq!(row[7], json!("0xDEADBEEF"));

    // Errors stop the script and keep what ran.
    let mut out = QueryOutcome::default();
    let e = s.execute("SELECT 1 FROM dual; SELECT * FROM no_such_table; SELECT 2 FROM dual", 10, &mut out).await;
    assert!(e.unwrap_err().to_string().contains("ORA-00942"));
    assert_eq!(out.results.len(), 1);

    // Session on another schema.
    let driver = dbine_driver_oracle::drivers().remove(0);
    let mut sys = driver.connect(&config(), Some("DBINE")).await.unwrap();
    assert!(sys.list_objects().await.unwrap().iter().any(|o| o.name == "DBINE_T"));

    for d in ["DROP TABLE dbine_t PURGE", "DROP VIEW dbine_v", "DROP SEQUENCE dbine_seq", "DROP PACKAGE dbine_pkg",
        "DROP PROCEDURE dbine_proc", "DROP FUNCTION dbine_fn", "DROP MATERIALIZED VIEW dbine_mv"]
    {
        let _ = s.execute(d, 10, &mut QueryOutcome::default()).await;
    }
}

#[tokio::test]
#[ignore]
async fn bad_password_is_auth_failed() {
    let mut cfg = config();
    cfg.password = Some("wrong".into());
    let driver = dbine_driver_oracle::drivers().remove(0);
    match driver.connect(&cfg, None).await {
        Err(dbine_driver::Error::AuthFailed(m)) => assert!(m.contains("ORA-01017"), "{m}"),
        Err(e) => panic!("expected AuthFailed, got {e:?}"),
        Ok(_) => panic!("connected with a wrong password"),
    }
}

/// Cancelling needs ALTER SYSTEM: runs only when DBINE_TEST_ORACLE_ADMIN_URL
/// (e.g. oracle://system:Secret123@localhost:25601/FREEPDB1) is set.
#[tokio::test]
#[ignore]
async fn interrupter_cancels_a_running_statement() {
    let Ok(url) = std::env::var("DBINE_TEST_ORACLE_ADMIN_URL") else { return };
    std::env::set_var("DBINE_TEST_ORACLE_URL", url);
    let mut s = session().await;
    let stop = s.interrupter().expect("an interrupter");
    let started = std::time::Instant::now();
    tokio::spawn(async move {
        tokio::time::sleep(std::time::Duration::from_secs(2)).await;
        stop();
    });
    let mut out = QueryOutcome::default();
    let e = s.execute("BEGIN DBMS_SESSION.SLEEP(30); END;", 10, &mut out).await.unwrap_err();
    assert!(matches!(e, dbine_driver::Error::Cancelled), "{e:?}");
    assert!(started.elapsed().as_secs() < 15);
    // The session is still usable afterwards.
    let out = run(&mut s, "SELECT 1 FROM dual").await;
    assert_eq!(out.results[0].rows[0][0], json!(1));
}

#[tokio::test]
#[ignore]
async fn compile_errors_come_back_as_messages() {
    let mut s = session().await;
    let out = run(&mut s, "CREATE OR REPLACE PROCEDURE dbine_broken AS BEGIN no_such_thing; END;\n/").await;
    assert!(!out.messages.is_empty(), "a compilation warning");
    let _ = s.execute("DROP PROCEDURE dbine_broken", 10, &mut QueryOutcome::default()).await;
}

/// Estimated plans run nothing; actual ones run the script once and read
/// the executed cursor's figures (with SELECT_CATALOG_ROLE; estimated
/// plans and a message without it).
#[tokio::test]
#[ignore]
async fn plans() {
    let mut s = session().await;
    let _ = s.execute("DROP TABLE dbine_plan PURGE", 10, &mut QueryOutcome::default()).await;
    run(
        &mut s,
        "CREATE TABLE dbine_plan (id NUMBER PRIMARY KEY, g NUMBER);
         INSERT INTO dbine_plan SELECT level, MOD(level, 10) FROM dual CONNECT BY level <= 1000;
         COMMIT",
    )
    .await;
    let count = |out: &QueryOutcome, i: usize| out.results[i].rows[0][0].clone();

    let mut out = QueryOutcome::default();
    s.explain(
        "SELECT /*+ FULL(p) */ g, COUNT(*) FROM dbine_plan p WHERE id < :x GROUP BY g;
         DELETE FROM dbine_plan WHERE id < 100;
         CREATE TABLE dbine_nope (a NUMBER)",
        false,
        10,
        &mut out,
    )
    .await
    .unwrap();
    assert_eq!(out.plans.len(), 2, "{out:?}");
    assert_eq!(out.messages.len(), 1);
    assert!(out.results.is_empty());
    let p = &out.plans[0];
    assert_eq!(p.root.op, "SELECT STATEMENT");
    assert!(p.raw.contains("Plan hash value"), "{}", p.raw);
    fn find<'a>(n: &'a dbine_driver::PlanNode, op: &str) -> Option<&'a dbine_driver::PlanNode> {
        if n.op == op {
            return Some(n);
        }
        n.children.iter().find_map(|c| find(c, op))
    }
    let full = find(&p.root, "TABLE ACCESS").expect("table access");
    assert_eq!(full.detail, "FULL");
    assert!(full.object.as_deref().unwrap().ends_with("DBINE_PLAN"));
    assert!(p.root.total_cost.is_some());
    assert_eq!(out.plans[1].root.op, "DELETE STATEMENT");
    assert_eq!(count(&run(&mut s, "SELECT COUNT(*) FROM dbine_plan").await, 0), json!(1000));
    assert_eq!(count(&run(&mut s, "SELECT COUNT(*) FROM plan_table").await, 0), json!(0));

    let mut out = QueryOutcome::default();
    s.explain(
        "SELECT COUNT(*) FROM dbine_plan WHERE g = 3; DELETE FROM dbine_plan WHERE id <= 100; SELECT COUNT(*) FROM dbine_plan",
        true,
        10,
        &mut out,
    )
    .await
    .unwrap();
    assert_eq!(out.plans.len(), 3);
    assert_eq!(out.results.len(), 3);
    assert_eq!(count(&out, 0), json!(100));
    assert_eq!(count(&out, 2), json!(900));
    let fallback = out.messages.iter().any(|m| m.starts_with("Sin acceso"));
    eprintln!("oracle: fallback = {fallback}; messages {:?}", out.messages);
    if !fallback {
        // The last SELECT ran before without statistics: Oracle may reuse
        // that cursor, and then says so.
        assert!(out.plans[0].actual && out.plans[1].actual, "{:#?}", out.plans);
        assert!(out.plans[2].actual || out.messages.iter().any(|m| m.contains("reutilizó")));
        let scan = find(&out.plans[0].root, "TABLE ACCESS").unwrap();
        assert_eq!(scan.actual_rows, Some(100.0));
        assert!(out.plans[0].raw.contains("A-Rows"), "{}", out.plans[0].raw);
        assert_eq!(out.plans[1].root.op, "DELETE STATEMENT");
    } else {
        assert!(out.plans.iter().all(|p| !p.actual));
    }
    let mut out = QueryOutcome::default();
    assert!(s.explain("SELECT 1 FROM dual; SELECT * FROM dbine_missing", true, 10, &mut out).await.is_err());
    assert_eq!(out.results.len(), 1);
    run(&mut s, "DROP TABLE dbine_plan PURGE").await;
}

/// Schemas as databases, `database_schema` and a DDL round trip into a
/// fresh schema. Creating schemas needs CREATE USER: runs only when
/// DBINE_TEST_ORACLE_ADMIN_URL (e.g. oracle://system:pw@localhost:26015/FREEPDB1) is set.
#[tokio::test]
#[ignore]
async fn schema_ddl_round_trip() {
    let Ok(url) = std::env::var("DBINE_TEST_ORACLE_ADMIN_URL") else { return };
    let cfg = config_from(&url);
    let driver = dbine_driver_oracle::drivers().remove(0);
    assert!(driver.capabilities().create_database && driver.capabilities().foreign_keys);
    let mut admin = driver.connect(&cfg, None).await.unwrap();
    for d in ["DBINE_DDL_SRC", "DBINE_DDL_DST"] {
        let _ = admin.drop_database(d).await;
    }
    admin.create_database("dbine_ddl_src").await.unwrap();
    admin.create_database("dbine_ddl_dst").await.unwrap();
    let e = admin.drop_database("SYSTEM").await.unwrap_err();
    assert!(matches!(e, dbine_driver::Error::Query(_)), "{e:?}");

    let mut src = driver.connect(&cfg, Some("DBINE_DDL_SRC")).await.unwrap();
    run(
        &mut src,
        r#"
CREATE TABLE clientes (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_clientes PRIMARY KEY,
  email VARCHAR2(100 CHAR) NOT NULL,
  nombre VARCHAR2(50) DEFAULT 'anon' NOT NULL,
  activo NUMBER(1) DEFAULT 1,
  alta DATE DEFAULT SYSDATE,
  datos RAW(16),
  CONSTRAINT uq_clientes_email UNIQUE (email)
);
CREATE TABLE pedidos (
  id NUMBER(10) PRIMARY KEY,
  cliente_id NUMBER NOT NULL,
  total NUMBER(10,2),
  creado TIMESTAMP(6),
  notas CLOB,
  CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id) ON DELETE CASCADE
);
CREATE TABLE lineas (
  pedido_id NUMBER(10),
  linea NUMBER(5),
  producto VARCHAR2(40),
  cliente_ref NUMBER,
  CONSTRAINT pk_lineas PRIMARY KEY (pedido_id, linea),
  CONSTRAINT fk_lineas_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos (id),
  CONSTRAINT fk_lineas_cliente FOREIGN KEY (cliente_ref) REFERENCES clientes (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX ux_lineas_producto ON lineas (pedido_id, producto);
CREATE INDEX ix_pedidos_creado ON pedidos (creado DESC);
CREATE INDEX ix_clientes_nombre_up ON clientes (UPPER(nombre));
COMMENT ON TABLE clientes IS 'Clientes del ''sistema''';
COMMENT ON COLUMN clientes.email IS 'Correo';
"#,
    )
    .await;

    let schema = src.database_schema().await.unwrap();
    let names: Vec<_> = schema.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(names, ["CLIENTES", "LINEAS", "PEDIDOS"]);
    let (clientes, lineas, pedidos) = (&schema[0], &schema[1], &schema[2]);
    assert_eq!(clientes.comment.as_deref(), Some("Clientes del 'sistema'"));
    let col = |t: &dbine_driver::TableSchema, n: &str| t.columns.iter().find(|c| c.name == n).unwrap().clone();
    assert!(col(clientes, "ID").auto_increment && col(clientes, "ID").default_value.is_none());
    assert_eq!(col(clientes, "EMAIL").comment.as_deref(), Some("Correo"));
    // CHAR length semantics are part of the type (without them it would be recreated as 100 bytes).
    assert_eq!(col(clientes, "EMAIL").data_type, "VARCHAR2(100 CHAR)");
    assert_eq!(col(clientes, "NOMBRE").default_value.as_deref(), Some("'anon'"));
    assert_eq!(col(clientes, "DATOS").data_type, "RAW(16)");
    assert_eq!(col(pedidos, "TOTAL").data_type, "NUMBER(10,2)");
    assert_eq!(col(pedidos, "CREADO").data_type, "TIMESTAMP(6)");
    assert_eq!(clientes.primary_key.as_ref().unwrap().name.as_deref(), Some("PK_CLIENTES"));
    assert_eq!(pedidos.primary_key.as_ref().unwrap().name, None, "system-named");
    assert_eq!(lineas.primary_key.as_ref().unwrap().columns, ["PEDIDO_ID", "LINEA"]);
    let fk = &pedidos.foreign_keys[0];
    assert_eq!(
        (fk.name.as_deref(), fk.ref_table.as_str(), fk.ref_columns.clone(), fk.on_delete.as_deref()),
        (Some("FK_PEDIDOS_CLIENTE"), "CLIENTES", vec!["ID".to_string()], Some("CASCADE"))
    );
    let rules: Vec<_> = lineas.foreign_keys.iter().map(|f| (f.name.as_deref().unwrap(), f.on_delete.as_deref())).collect();
    assert_eq!(rules, [("FK_LINEAS_CLIENTE", Some("SET NULL")), ("FK_LINEAS_PEDIDO", None)]);
    let ix: Vec<_> = clientes.indexes.iter().map(|i| (i.name.as_str(), i.unique, i.columns.join(","))).collect();
    assert_eq!(ix, [("IX_CLIENTES_NOMBRE_UP", false, "UPPER(\"NOMBRE\")".to_string()), ("UQ_CLIENTES_EMAIL", true, "EMAIL".into())]);
    assert_eq!(lineas.indexes[0].name, "UX_LINEAS_PRODUCTO");
    assert!(lineas.indexes[0].unique);
    assert_eq!(pedidos.indexes[0].columns, ["\"CREADO\" DESC"]);

    // Round trip: every CREATE (after guarded DROPs), then indexes and keys.
    let create = DdlParts { drop: true, if_exists: true, create: true, ..Default::default() };
    let rest = DdlParts { indexes: true, foreign_keys: true, ..Default::default() };
    let mut script: Vec<String> = schema.iter().map(|t| driver.table_ddl(t, create).unwrap()).collect();
    script.extend(schema.iter().map(|t| driver.table_ddl(t, rest).unwrap()));
    let script = script.join("\n");
    let mut dst = driver.connect(&cfg, Some("DBINE_DDL_DST")).await.unwrap();
    run(&mut dst, &script).await;
    assert_eq!(dst.database_schema().await.unwrap(), schema, "{script}");
    // With if_exists, indexes and keys that are already there are skipped.
    let again: Vec<String> =
        schema.iter().map(|t| driver.table_ddl(t, DdlParts { if_exists: true, ..rest }).unwrap()).collect();
    run(&mut dst, &again.join("\n")).await;

    let cols = ["EMAIL".to_string(), "NOMBRE".into(), "ACTIVO".into()];
    let rows = [vec![json!("a@x"), json!("O'Brien"), json!(true)], vec![json!("b@x"), json!("b"), json!(false)]];
    let ins = driver.insert_script(&obj("table", "CLIENTES"), &cols, &rows).unwrap();
    run(&mut dst, &ins).await;
    let out = run(&mut dst, "SELECT SUM(activo), COUNT(*) FROM clientes").await;
    assert_eq!(out.results[0].rows[0], vec![json!(1), json!(2)]);

    let e = dst.drop_database("DBINE_DDL_DST").await.unwrap_err();
    assert!(e.to_string().contains("sesión actual"), "{e}");
    drop((src, dst));
    admin.drop_database("DBINE_DDL_SRC").await.unwrap();
    admin.drop_database("DBINE_DDL_DST").await.unwrap();
    assert!(!admin.list_databases().await.unwrap().contains(&"DBINE_DDL_DST".to_string()));
}

/// The monitor. With a user that can read the V$ views (e.g. SYSTEM) every
/// figure comes back; with a plain user, the notes say what's missing.
#[tokio::test]
#[ignore]
async fn monitor() {
    let driver = dbine_oracle_driver();
    assert!(driver.capabilities().monitor);
    let mut s = driver.connect(&config(), None).await.expect("connect");
    let snap = s.monitor().await.expect("monitor");
    // A second snapshot: the host CPU from V$OSSTAT needs two.
    tokio::time::sleep(std::time::Duration::from_millis(1500)).await;
    let snap2 = s.monitor().await.expect("monitor again");
    for m in &snap2.metrics {
        eprintln!("{:<22} {:<36} {:?} max={:?}{}", m.key, m.label, m.value, m.max, if m.counter { " (counter)" } else { "" });
    }
    for t in &snap2.tables {
        eprintln!("[{}] {} rows; first: {:?}", t.key, t.rows.len(), t.rows.first());
    }
    eprintln!("info: {:?}\nnotes: {:?}", snap2.info, snap2.notes);
    let has = |k: &str| snap2.metrics.iter().any(|m| m.key == k && m.value.is_some());
    if has("connections") {
        for k in ["cpu", "cpu_time", "mem_used", "queries", "transactions", "disk_read", "uptime"] {
            assert!(has(k), "{k}");
        }
        assert!(snap2.tables.iter().any(|t| t.key == "waits" && !t.rows.is_empty()));
    } else {
        assert!(snap.notes.iter().any(|n| n.contains("SELECT_CATALOG_ROLE")), "{:?}", snap.notes);
    }
}

fn dbine_oracle_driver() -> std::sync::Arc<dyn dbine_driver::Driver> {
    dbine_driver_oracle::drivers().into_iter().find(|d| d.info().id == "oracle").unwrap()
}

/// Running a statement that failed to parse again reports the same error
/// (the thin client's statement cache used to turn it into ORA-01003).
#[tokio::test]
#[ignore]
async fn a_failed_statement_fails_the_same_way_twice() {
    let mut s = session().await;
    for _ in 0..3 {
        let mut out = QueryOutcome::default();
        let e = s.execute("SELECT * FROM dbine_no_such_table", 10, &mut out).await.unwrap_err();
        assert!(e.to_string().contains("ORA-00942"), "{e}");
    }
    assert_eq!(run(&mut s, "SELECT 1 FROM dual").await.results.len(), 1);
}

/// The profiler reads V$SESSION: with DBINE_TEST_ORACLE_ADMIN_URL (e.g.
/// SYSTEM) it watches the DBINE_TEST_ORACLE_URL user's schema while that
/// user runs a slow statement and a fast one; without it, the plain user
/// gets an error that names the grant it lacks.
#[tokio::test]
#[ignore]
async fn profiler() {
    let driver = dbine_oracle_driver();
    assert!(driver.supports_profiler());
    let cfg = config();
    let schema = cfg.username.clone().unwrap().to_uppercase();
    let opts = dbine_driver::ProfilerOptions { database: schema.clone(), change_server: true };
    let Ok(admin) = std::env::var("DBINE_TEST_ORACLE_ADMIN_URL") else {
        let mut p = driver.connect(&cfg, None).await.expect("connect");
        match p.profiler_start(&opts).await {
            Err(e) => assert!(e.to_string().contains("SELECT_CATALOG_ROLE"), "{e}"),
            Ok(started) => eprintln!("this user reads V$SESSION: {started:?}"),
        }
        return;
    };
    let mut p = driver.connect(&config_from(&admin), None).await.expect("connect");
    let mut w = driver.connect(&cfg, None).await.expect("connect");
    let started = p.profiler_start(&opts).await.expect("profiler_start");
    eprintln!("{started:?}");
    let marker = format!("dbine_prof_{}", std::process::id());
    let slow = format!("DECLARE {marker}_slow NUMBER; BEGIN DBMS_SESSION.SLEEP(1.2); END;");
    let fast = format!("SELECT 1 AS {marker}_fast FROM dual");
    let work = async {
        tokio::time::sleep(std::time::Duration::from_millis(300)).await;
        run(&mut w, &slow).await;
        tokio::time::sleep(std::time::Duration::from_millis(400)).await;
        run(&mut w, &fast).await;
        tokio::time::sleep(std::time::Duration::from_millis(600)).await;
    };
    let watch = async {
        let mut got = Vec::new();
        let until = std::time::Instant::now() + std::time::Duration::from_secs(5);
        while std::time::Instant::now() < until {
            got.extend(p.profiler_poll().await.expect("profiler_poll"));
            if got.iter().any(|s| s.text.contains(&format!("{marker}_slow"))) && std::time::Instant::now() + std::time::Duration::from_secs(2) > until {
                break;
            }
        }
        got
    };
    let ((), got) = tokio::join!(work, watch);
    p.profiler_stop().await.expect("profiler_stop");
    let mine: Vec<_> = got.iter().filter(|s| s.text.contains(&marker)).collect();
    eprintln!("{mine:#?}");
    let slow_seen: Vec<_> = mine.iter().filter(|s| s.text.contains("_slow")).collect();
    assert_eq!(slow_seen.len(), 1, "the slow statement once");
    let ms = slow_seen[0].duration_ms.unwrap_or(0.0);
    assert!((900.0..5000.0).contains(&ms), "duration {ms}");
    assert_eq!(slow_seen[0].database.as_deref(), Some(schema.as_str()));
    // CPU, buffer gets and direct writes from V$SQLSTATS, in blocks.
    assert_eq!(started.reads_unit.as_deref(), Some("bloques"));
    assert!(slow_seen[0].cpu_ms.is_some() && slow_seen[0].reads.is_some() && slow_seen[0].writes.is_some(), "figures");
    // The fast one is seen only if a look falls between it and DBine's own
    // DBMS_OUTPUT read that follows it: not asserted.
    assert!(mine.iter().filter(|s| s.text.contains("_fast")).count() <= 1);
    assert!(got.iter().all(|s| !s.text.contains("v$session")), "its own statements are left out");
}

/// Schema sync against the server: the generated script turns a table into
/// its new version, and a second comparison finds nothing left to change.
#[tokio::test]
#[ignore]
async fn schema_sync_applies() {
    use dbine_driver::{IndexDef, TableChange};
    let driver = dbine_oracle_driver();
    assert!(driver.supports_schema_sync());
    let mut s = session().await;
    for d in ["DROP TABLE dbine_sync_hijo PURGE", "DROP TABLE dbine_sync_padre PURGE"] {
        let mut out = QueryOutcome::default();
        let _ = s.execute(d, 10, &mut out).await;
    }
    run(
        &mut s,
        r#"
CREATE TABLE dbine_sync_padre (id NUMBER(10) CONSTRAINT pk_sync_padre PRIMARY KEY, codigo NUMBER(10) NOT NULL);
CREATE UNIQUE INDEX ux_sync_padre_codigo ON dbine_sync_padre (codigo);
CREATE TABLE dbine_sync_hijo (
  id NUMBER(10) CONSTRAINT pk_sync_hijo PRIMARY KEY,
  padre_id NUMBER(10),
  nombre VARCHAR2(20) NOT NULL,
  baja DATE,
  CONSTRAINT fk_sync_hijo_padre FOREIGN KEY (padre_id) REFERENCES dbine_sync_padre (id)
);
CREATE INDEX ix_sync_hijo_nombre ON dbine_sync_hijo (nombre);
INSERT INTO dbine_sync_padre VALUES (1, 10);
INSERT INTO dbine_sync_hijo VALUES (1, 1, 'uno', NULL);
"#,
    )
    .await;
    let find = |schema: &[dbine_driver::TableSchema], n: &str| schema.iter().find(|t| t.name == n).unwrap().clone();
    let old = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_HIJO");
    let mut new = old.clone();
    let nombre = new.columns.iter_mut().find(|c| c.name == "NOMBRE").unwrap();
    nombre.data_type = "VARCHAR2(40)".into();
    nombre.nullable = true;
    nombre.default_value = Some("'x'".into());
    new.columns.retain(|c| c.name != "BAJA");
    new.columns.push(dbine_driver::ColumnDef { name: "EMAIL".into(), data_type: "VARCHAR2(100)".into(), nullable: true, ..Default::default() });
    new.indexes = vec![IndexDef { name: "IX_SYNC_HIJO_EMAIL".into(), columns: vec!["EMAIL".into()], unique: false, kind: None, filter: None, ..Default::default() }];
    new.foreign_keys[0].name = Some("FK_SYNC_HIJO_PADRE2".into());
    new.foreign_keys[0].on_delete = Some("CASCADE".into());
    let script = driver.sync_script(&[TableChange::Alter { old, new: new.clone() }]).unwrap();
    eprintln!("{}\n{:?}", script.statements.join("\n"), script.warnings);
    for st in &script.statements {
        run(&mut s, st).await;
    }
    let after = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_HIJO");
    let left = driver.sync_script(&[TableChange::Alter { old: after, new: new.clone() }]).unwrap();
    assert!(left.statements.is_empty(), "{:?}", left.statements);

    // A NOT NULL back, and the index and key dropped; then the tables go.
    let mut last = new.clone();
    last.columns.iter_mut().find(|c| c.name == "NOMBRE").unwrap().nullable = false;
    last.indexes.clear();
    last.foreign_keys.clear();
    let script = driver.sync_script(&[TableChange::Alter { old: new, new: last.clone() }]).unwrap();
    for st in &script.statements {
        run(&mut s, st).await;
    }
    let after = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_HIJO");
    let left = driver.sync_script(&[TableChange::Alter { old: after, new: last.clone() }]).unwrap();
    assert!(left.statements.is_empty(), "{:?}", left.statements);
    let padre = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_PADRE");
    let script = driver.sync_script(&[TableChange::Drop { table: last }, TableChange::Drop { table: padre }]).unwrap();
    for st in &script.statements {
        run(&mut s, st).await;
    }
}
