//! Bulk transfer (see `dbine_driver::transfer`).
//!
//! - Reading: one `SELECT` fetched [`FETCH_ROWS`] rows per round trip (the
//!   first execute keeps the client's small prefetch: a large one breaks the
//!   client's decoding of `JSON` columns), each
//!   value turned into its typed cell: `NUMBER` with scale 0 → integer (or
//!   exact decimal when it doesn't fit 64 bits), other `NUMBER`s → exact
//!   decimal, `BINARY_*` → float, character types and CLOBs → text (whole),
//!   `RAW` / BLOB → bytes (whole; an empty LOB, which the client gives as
//!   NULL, is told apart by a flag in the query), `DATE` / `TIMESTAMP` →
//!   date-time,
//!   `WITH TIME ZONE` → date-time with its offset, `WITH LOCAL TIME ZONE` →
//!   read in UTC (`SYS_EXTRACT_UTC`), intervals → Oracle's own text,
//!   `JSON` → JSON text serialized by the server (`JSON_SERIALIZE`: numbers
//!   exact, members in order). Dates before year 1
//!   are text with a ` BC` suffix (`0044-03-15 12:00:00 BC`), as PostgreSQL
//!   spells them: the cells' formats have no era. Only a `SELECT` runs on
//!   the source.
//! - Loading: array DML. One `INSERT … VALUES (:1, …)` bound with up to
//!   [`ARRAY_ROWS`] rows or [`ARRAY_BYTES`] per execute (one round trip),
//!   bound with the target
//!   column's type (read from the catalog; numbers go as text through
//!   `TO_NUMBER`, with `NLS_NUMERIC_CHARACTERS` set to `.,` for the load and
//!   restored after it, because the client's own number encoding stores
//!   integers ending in `00` as invalid numbers that read back as NULL),
//!   committed every
//!   `commit_rows` / `commit_bytes`. With `table_lock` the insert is
//!   direct-path (`/*+ APPEND_VALUES */`, Oracle's hint for array inserts):
//!   Oracle then requires a commit before the table is touched again in the
//!   same transaction (ORA-12838), so each execute commits (bigger arrays).
//!   Tables with LOB or `JSON` columns load on the conventional path even
//!   with `table_lock`: direct-path array inserts into them fail with
//!   ORA-65501 depending on the order of the rows' sizes.
//!   Values over [`LOB_INLINE`] bytes can't go in a bind (the protocol's
//!   limit), so those rows go one by one through a PL/SQL block that
//!   builds a temporary LOB in 32 KB pieces (also empty CLOBs and BLOBs,
//!   which Oracle keeps apart from NULL only as LOBs).
//! - Oracle stores an empty `VARCHAR2` / `CHAR` / `RAW` as NULL: an empty
//!   text or binary for such a column stops the load (`Unsupported`)
//!   instead of turning into NULL.
//! - Text into `RAW` / BLOB: hex digits (with or without `0x`) when the
//!   source column is binary (or an ObjectId / UUID), its UTF-8 bytes when
//!   it's text; without the source's type, only `0x…` is taken as hex.
//! - Memory: the load pulls the next batch only after the worker has
//!   turned the previous one into bound values, so besides the
//!   orchestrator's window it holds at most [`ARRAY_BYTES`] of pending
//!   rows (and the client's encoding of them while they execute).
//! - A load whose future is dropped (a cancel, or a failed read) stops its
//!   worker: nothing is committed after the drop returns, and what wasn't
//!   committed is rolled back.
//! - Identity columns: `GENERATED BY DEFAULT` accept the given values;
//!   `GENERATED ALWAYS` don't, and the table is never altered here: with
//!   `keep_identity` the load stops and says so (whoever runs the migration
//!   decides whether to `ALTER TABLE … MODIFY … GENERATED BY DEFAULT`).
//!   Without `keep_identity`, identity columns are left out and Oracle
//!   generates them.
//! - Native copy (Oracle to Oracle): the same read and load, except that
//!   `WITH TIME ZONE` values travel with their region (`TZR TZD`, not just
//!   the offset) and `JSON` as Oracle's extended JSON, so extended scalars
//!   (timestamps, binaries, doubles…) keep their types.

use super::{err, join_err, panic_text, poisoned, quote, OracleSession};
use dbine_driver::transfer::{BatchBuilder, BatchSink, BatchSinkRef, BatchSource, Cell, CopySpec, LoadSpec, Progress, ReadSpec, RowBatch, TransferColumn};
use dbine_driver::{Error, Result, Session};
use oracledb::{Connection, DbType, Metadata, OracleNumber, OracleTimestamp, Row, ToDbValue};
use std::sync::atomic::Ordering;
use std::sync::{Arc, Mutex};

/// Rows per fetch round trip.
const FETCH_ROWS: u32 = 1_000;
/// Rows per array execute (conventional path)…
const ARRAY_ROWS: usize = 10_000;
/// …and with `APPEND_VALUES` (each execute commits: bigger arrays).
const DIRECT_ARRAY_ROWS: usize = 50_000;
/// Bytes of bound values per array execute: what the load holds besides
/// the orchestrator's window.
const ARRAY_BYTES: usize = 4 * 1024 * 1024;
/// Largest value that goes in a bind; larger ones go through a temporary LOB.
const LOB_INLINE: usize = 32_767;
/// Bytes per piece written into a temporary LOB (fits a PL/SQL bind).
const LOB_CHUNK: usize = 32_000;
/// Batches queued between the reader and the writer of a native copy.
const NATIVE_BATCHES: usize = 8;
/// A NUMBER's range, below 1e126 and down to 1e-130, as the power of ten
/// of `0.d…` (1e125 is 0.1e126, 1e-130 is 0.1e-129).
const NUMBER_MAX_MAGNITUDE: i64 = 126;
const NUMBER_MIN_MAGNITUDE: i64 = -129;

// ---------------------------------------------------------------- reading

/// How a column is read.
#[derive(Debug, Clone, Copy, PartialEq)]
enum Read {
    /// NUMBER with scale 0: integer when it fits.
    Int,
    Decimal,
    F32,
    F64,
    Bool,
    Date,
    Timestamp,
    /// Already converted to UTC by the query.
    TimestampUtc,
    /// `TO_CHAR` text with the offset.
    TimestampTz,
    /// `TO_CHAR` text with the region (native copy).
    TimestampTzRegion,
    Bytes,
    Text,
    IntervalDs,
    IntervalYm,
    /// `JSON_SERIALIZE` text.
    Json,
    Vector,
}

fn read_kind(m: &Metadata, native: bool) -> Read {
    match m.db_type().name() {
        "DB_TYPE_BINARY_INTEGER" => Read::Int,
        "DB_TYPE_NUMBER" if m.scale() == 0 && m.precision() > 0 => Read::Int,
        "DB_TYPE_NUMBER" => Read::Decimal,
        "DB_TYPE_BINARY_FLOAT" => Read::F32,
        "DB_TYPE_BINARY_DOUBLE" => Read::F64,
        "DB_TYPE_BOOLEAN" => Read::Bool,
        "DB_TYPE_DATE" => Read::Date,
        "DB_TYPE_TIMESTAMP" => Read::Timestamp,
        "DB_TYPE_TIMESTAMP_LTZ" => Read::TimestampUtc,
        "DB_TYPE_TIMESTAMP_TZ" if native => Read::TimestampTzRegion,
        "DB_TYPE_TIMESTAMP_TZ" => Read::TimestampTz,
        "DB_TYPE_RAW" | "DB_TYPE_LONG_RAW" | "DB_TYPE_BLOB" => Read::Bytes,
        "DB_TYPE_INTERVAL_DS" => Read::IntervalDs,
        "DB_TYPE_INTERVAL_YM" => Read::IntervalYm,
        "DB_TYPE_JSON" => Read::Json,
        "DB_TYPE_VECTOR" => Read::Vector,
        _ => Read::Text,
    }
}

/// The select-list item for a column: some types are read through an
/// expression (the column keeps its name).
fn read_expr(m: &Metadata, native: bool) -> String {
    let q = quote(m.name());
    match m.db_type().name() {
        "DB_TYPE_TIMESTAMP_LTZ" => format!("SYS_EXTRACT_UTC(CAST({q} AS TIMESTAMP WITH TIME ZONE)) AS {q}"),
        // As text: the client hands WITH TIME ZONE values over with their UTC
        // clock and the offset (not the local clock), and panics on the ones
        // with a region. `SYYYY`: the sign keeps BC years.
        "DB_TYPE_TIMESTAMP_TZ" if native => format!("TO_CHAR({q}, 'SYYYY-MM-DD HH24:MI:SS.FF9 TZR TZD') AS {q}"),
        "DB_TYPE_TIMESTAMP_TZ" => format!("TO_CHAR({q}, 'SYYYY-MM-DD HH24:MI:SS.FF9TZH:TZM') AS {q}"),
        // Serialized by the server: numbers exact and members in order (the
        // client's decoding keeps objects in a hash map); in a native copy,
        // extended scalars as Oracle's extended JSON.
        "DB_TYPE_JSON" if native => format!("JSON_SERIALIZE({q} RETURNING CLOB EXTENDED) AS {q}"),
        "DB_TYPE_JSON" => format!("JSON_SERIALIZE({q} RETURNING CLOB) AS {q}"),
        "DB_TYPE_XMLTYPE" => format!("XMLSERIALIZE(CONTENT {q} AS CLOB) AS {q}"),
        _ => q,
    }
}

pub(crate) async fn read_batches(s: &mut OracleSession, spec: &ReadSpec, sink: BatchSinkRef) -> Result<u64> {
    read_with(s, spec, sink, false).await
}

async fn read_with(s: &mut OracleSession, spec: &ReadSpec, sink: BatchSinkRef, native: bool) -> Result<u64> {
    let (owner, name) = (s.owner(&spec.table), spec.table.name.clone());
    let table = format!("{}.{}", quote(&owner), quote(&name));
    let cols = match &spec.columns {
        Some(c) if !c.is_empty() => c.iter().map(|c| quote(c)).collect::<Vec<_>>().join(", "),
        _ => "*".to_string(),
    };
    let filter = spec.filter.clone().filter(|f| !f.trim().is_empty());
    let r = s
        .run(move |c| {
            let lobs = lob_columns(c, &owner, &name)?;
            read(c, &table, &cols, &lobs, filter.as_deref(), &sink, native)
        })
        .await;
    if r.is_err() && s.shared.killed.load(Ordering::SeqCst) {
        return Err(Error::Cancelled);
    }
    r
}

/// The table's CLOB, NCLOB and BLOB columns (the client describes them as
/// LONG / LONG RAW, like real LONG columns).
fn lob_columns(c: &Connection, owner: &str, table: &str) -> Result<Vec<String>> {
    let (o, t) = (owner.to_string(), table.to_string());
    let mut out = Vec::new();
    for row in c
        .query(
            "SELECT column_name FROM all_tab_columns WHERE owner = :1 AND table_name = :2 AND data_type IN ('CLOB', 'NCLOB', 'BLOB')",
            &[&o, &t],
        )
        .map_err(err)?
    {
        out.push(row.map_err(err)?.get::<String>(0).map_err(err)?);
    }
    Ok(out)
}

fn read(c: &Connection, table: &str, cols: &str, lobs: &[String], filter: Option<&str>, sink: &BatchSinkRef, native: bool) -> Result<u64> {
    // Described first: the select list depends on the types.
    let meta: Vec<Metadata> = c.query(&format!("SELECT {cols} FROM {table} WHERE 1 = 0"), &[]).map_err(err)?.columns().to_vec();
    let kinds: Vec<Read> = meta.iter().map(|m| read_kind(m, native)).collect();
    let mut select: Vec<String> = meta.iter().map(|m| read_expr(m, native)).collect();
    // The client gives an empty LOB as NULL: a flag per LOB column, after
    // the columns, tells them apart.
    let mut flags: Vec<Option<usize>> = vec![None; meta.len()];
    for (i, m) in meta.iter().enumerate() {
        if lobs.iter().any(|l| l == m.name()) {
            flags[i] = Some(select.len());
            select.push(format!("CASE WHEN {} IS NULL THEN 0 ELSE 1 END", quote(m.name())));
        }
    }
    let mut sql = format!("SELECT {} FROM {table}", select.join(", "));
    if let Some(f) = filter {
        sql.push_str(&format!(" WHERE {f}"));
    }
    let stmt = c
        .statement(&sql)
        .map(|b| b.fetch_array_size(FETCH_ROWS).exclude_from_cache())
        .and_then(|b| b.build())
        .map_err(err)?;
    let cursor = stmt.query(&[]).map_err(err)?;
    let columns: Vec<TransferColumn> =
        meta.iter().map(|m| TransferColumn { name: m.name().to_string(), type_name: m.data_type(), nullable: m.nullable() }).collect();
    let mut sink = sink.lock().map_err(|_| Error::State("destino de lotes".into()))?;
    sink.begin(&columns)?;
    let mut builder = BatchBuilder::new();
    for row in cursor {
        let mut row = row.map_err(err)?;
        let mut cells = Vec::with_capacity(kinds.len());
        for (i, k) in kinds.iter().enumerate() {
            let mut cell = read_cell(&mut row, i, *k).map_err(err)?;
            if let (Cell::Null, Some(f)) = (&cell, flags[i]) {
                if row.get::<Option<i64>>(f).map_err(err)? == Some(1) {
                    cell = if *k == Read::Bytes { Cell::Bytes(Vec::new()) } else { Cell::Text(String::new()) };
                }
            }
            cells.push(cell);
        }
        builder.push(cells, &mut *sink)?;
    }
    builder.flush(&mut *sink)?;
    Ok(builder.rows)
}

fn read_cell(row: &mut Row, i: usize, k: Read) -> std::result::Result<Cell, oracledb::Error> {
    fn opt<T>(v: Option<T>, f: impl FnOnce(T) -> Cell) -> Cell {
        v.map_or(Cell::Null, f)
    }
    Ok(match k {
        Read::Int => opt(row.get::<Option<OracleNumber>>(i)?, |n| {
            let s = n.to_string();
            s.parse::<i64>().map(Cell::Int).unwrap_or(Cell::Decimal(s))
        }),
        Read::Decimal => opt(row.get::<Option<OracleNumber>>(i)?, |n| Cell::Decimal(n.to_string())),
        Read::F32 => opt(row.get::<Option<f32>>(i)?, |v| Cell::Float(v as f64)),
        Read::F64 => opt(row.get::<Option<f64>>(i)?, Cell::Float),
        Read::Bool => opt(row.get::<Option<bool>>(i)?, Cell::Bool),
        Read::Date => opt(row.get::<Option<OracleTimestamp>>(i)?, |t| ts_cell(&t, false, false)),
        Read::Timestamp => opt(row.get::<Option<OracleTimestamp>>(i)?, |t| ts_cell(&t, true, false)),
        Read::TimestampUtc => opt(row.get::<Option<OracleTimestamp>>(i)?, |t| ts_cell(&t, true, true)),
        Read::TimestampTz => opt(row.take::<Option<String>>(i)?, |t| tz_cell(&t)),
        Read::TimestampTzRegion => opt(row.take::<Option<String>>(i)?, |t| Cell::Text(t.trim().to_string())),
        Read::Bytes => opt(row.take::<Option<Vec<u8>>>(i)?, Cell::Bytes),
        Read::Text => opt(row.take::<Option<String>>(i)?, Cell::Text),
        Read::IntervalDs => opt(row.get::<Option<oracledb::OracleIntervalDS>>(i)?, |v| Cell::Text(fmt_interval_ds(&v))),
        Read::IntervalYm => opt(row.get::<Option<oracledb::OracleIntervalYM>>(i)?, |v| Cell::Text(fmt_interval_ym(&v))),
        Read::Json => opt(row.take::<Option<String>>(i)?, Cell::Json),
        Read::Vector => opt(row.get::<Option<oracledb::Vector>>(i)?, |v| Cell::Text(super::vector(&v))),
    })
}

/// A `DATE` / `TIMESTAMP` (`utc`: with `+00:00`): a date-time cell, or
/// text ending in ` BC` before year 1.
fn ts_cell(t: &OracleTimestamp, fraction: bool, utc: bool) -> Cell {
    let mut s = fmt_ts(t, fraction);
    if utc {
        s.push_str("+00:00");
    }
    match (t.year() <= 0, utc) {
        (true, _) => Cell::Text(format!("{s} BC")),
        (false, true) => Cell::DateTimeTz(s),
        (false, false) => Cell::DateTime(s),
    }
}

/// `TO_CHAR(…, 'SYYYY-MM-DD HH24:MI:SS.FF9TZH:TZM')`: the sign is a blank
/// or `-` (BC).
fn tz_cell(s: &str) -> Cell {
    let s = s.trim();
    match s.strip_prefix('-') {
        Some(bc) => Cell::Text(format!("{} BC", trim_fraction(bc))),
        None => Cell::DateTimeTz(trim_fraction(s.trim_start_matches('+'))),
    }
}

/// `YYYY-MM-DD HH:MM:SS[.fffffffff]` (fraction trimmed of trailing zeros;
/// BC years without their sign).
fn fmt_ts(t: &OracleTimestamp, fraction: bool) -> String {
    let mut s = format!(
        "{:04}-{:02}-{:02} {:02}:{:02}:{:02}",
        t.year().unsigned_abs(),
        t.month(),
        t.day(),
        t.hour(),
        t.minute(),
        t.second()
    );
    if fraction && t.nanoseconds() != 0 {
        let f = format!("{:09}", t.nanoseconds());
        s.push('.');
        s.push_str(f.trim_end_matches('0'));
    }
    s
}

/// `YYYY-MM-DD HH:MM:SS.fffffffff±HH:MM` with the fraction's trailing
/// zeros (and a bare point) removed.
fn trim_fraction(s: &str) -> String {
    let Some(dot) = s.find('.') else { return s.to_string() };
    let end = s[dot + 1..].find(|c: char| !c.is_ascii_digit()).map_or(s.len(), |i| dot + 1 + i);
    let frac = s[dot + 1..end].trim_end_matches('0');
    if frac.is_empty() {
        format!("{}{}", &s[..dot], &s[end..])
    } else {
        format!("{}.{frac}{}", &s[..dot], &s[end..])
    }
}

/// Oracle's own form, which `TO_DSINTERVAL` reads back: `+D HH:MM:SS.fffffffff`.
fn fmt_interval_ds(v: &oracledb::OracleIntervalDS) -> String {
    let neg = v.days() < 0 || v.hours() < 0 || v.minutes() < 0 || v.seconds() < 0 || v.nanoseconds() < 0;
    format!(
        "{}{} {:02}:{:02}:{:02}.{:09}",
        if neg { '-' } else { '+' },
        v.days().unsigned_abs(),
        v.hours().unsigned_abs(),
        v.minutes().unsigned_abs(),
        v.seconds().unsigned_abs(),
        v.nanoseconds().unsigned_abs()
    )
}

/// `+Y-M`, as `TO_YMINTERVAL` reads it.
fn fmt_interval_ym(v: &oracledb::OracleIntervalYM) -> String {
    let neg = v.years() < 0 || v.months() < 0;
    format!("{}{}-{}", if neg { '-' } else { '+' }, v.years().unsigned_abs(), v.months().unsigned_abs())
}

// ---------------------------------------------------------------- loading

/// How a value is bound, by the target column's type.
#[derive(Debug, Clone, Copy, PartialEq)]
enum Kind {
    /// Text through `TO_NUMBER` (see the module's docs).
    Number,
    Double,
    Text,
    Raw,
    Timestamp,
    /// Text through `TO_TIMESTAMP_TZ` (keeps the offset or the region; also
    /// for `WITH LOCAL TIME ZONE`).
    TimestampTz,
    IntervalDs,
    IntervalYm,
    Bool,
    /// Textual JSON (the server parses it into a `JSON` column).
    Json,
}

fn kind_of(data_type: &str) -> Kind {
    let t = data_type.to_ascii_uppercase();
    match t.as_str() {
        "NUMBER" | "FLOAT" | "INTEGER" => Kind::Number,
        "BINARY_FLOAT" | "BINARY_DOUBLE" => Kind::Double,
        "RAW" | "LONG RAW" | "BLOB" => Kind::Raw,
        "DATE" => Kind::Timestamp,
        "BOOLEAN" => Kind::Bool,
        "JSON" => Kind::Json,
        _ if t.starts_with("TIMESTAMP") && t.contains("TIME ZONE") => Kind::TimestampTz,
        _ if t.starts_with("TIMESTAMP") => Kind::Timestamp,
        _ if t.starts_with("INTERVAL DAY") => Kind::IntervalDs,
        _ if t.starts_with("INTERVAL YEAR") => Kind::IntervalYm,
        // VARCHAR2, NVARCHAR2, CHAR, NCHAR, CLOB, NCLOB, LONG, XMLTYPE,
        // VECTOR, ROWID…: text the server converts.
        _ => Kind::Text,
    }
}

/// `TO_TIMESTAMP_TZ`'s format: `TZR` takes an offset or a region, `TZD`
/// (optional) the daylight-saving abbreviation that settles an ambiguous
/// hour.
const TZ_FORMAT: &str = "SYYYY-MM-DD HH24:MI:SS.FF9 TZR TZD";

impl Kind {
    /// The bind's type (also the type of its NULLs: every row of an array
    /// execute binds a column with the same type).
    fn db_type(self) -> &'static DbType {
        match self {
            Kind::Double => oracledb::DB_TYPE_BINARY_DOUBLE,
            Kind::Raw => oracledb::DB_TYPE_RAW,
            Kind::Timestamp => oracledb::DB_TYPE_TIMESTAMP,
            Kind::Bool => oracledb::DB_TYPE_BOOLEAN,
            Kind::Number | Kind::Text | Kind::TimestampTz | Kind::IntervalDs | Kind::IntervalYm | Kind::Json => oracledb::DB_TYPE_VARCHAR,
        }
    }

    /// The VALUES item around the bind (`native`: JSON comes as Oracle's
    /// extended JSON).
    fn expr(self, bind: &str, native: bool) -> String {
        match self {
            Kind::Number => format!("TO_NUMBER({bind})"),
            Kind::TimestampTz => format!("TO_TIMESTAMP_TZ({bind}, '{TZ_FORMAT}')"),
            Kind::IntervalDs => format!("TO_DSINTERVAL({bind})"),
            Kind::IntervalYm => format!("TO_YMINTERVAL({bind})"),
            Kind::Json if native => format!("JSON({bind} EXTENDED)"),
            _ => bind.to_string(),
        }
    }
}

/// A bound value.
enum B {
    Null(&'static DbType),
    F(f64),
    S(String),
    R(Vec<u8>),
    T(OracleTimestamp),
    Bool(bool),
}

impl B {
    fn as_dyn(&self) -> &dyn ToDbValue {
        match self {
            B::Null(t) => t,
            B::F(f) => f,
            B::S(s) => s,
            B::R(r) => r,
            B::T(t) => t,
            B::Bool(b) => b,
        }
    }

    fn size(&self) -> usize {
        16 + match self {
            B::S(s) => s.len(),
            B::R(r) => r.len(),
            _ => 0,
        }
    }

    /// Goes through a temporary LOB: too large for a bind, or an empty LOB
    /// (an empty bind would be NULL).
    fn is_big(&self, lob: bool) -> bool {
        match self {
            B::S(s) => s.len() > LOB_INLINE || lob && s.is_empty(),
            B::R(r) => r.len() > LOB_INLINE || lob && r.is_empty(),
            _ => false,
        }
    }
}

/// How text becomes bytes for a `RAW` / BLOB column, by the source
/// column's type.
#[derive(Debug, Clone, Copy, PartialEq)]
enum RawText {
    /// Binary, ObjectId, UUID…: hex digits (`0x` optional).
    Hex,
    /// Text: its UTF-8 bytes.
    Utf8,
    /// Unknown: `0x…` hex, anything else its UTF-8 bytes.
    Unknown,
}

fn raw_text(source_type: &str) -> RawText {
    let t = source_type.to_ascii_lowercase();
    if t.trim().is_empty() {
        return RawText::Unknown;
    }
    const BINARY: [&str; 9] = ["binary", "blob", "bytea", "raw", "bytes", "image", "objectid", "bindata", "uuid"];
    if BINARY.iter().any(|b| t.contains(b)) {
        RawText::Hex
    } else {
        RawText::Utf8
    }
}

/// A target column being loaded.
#[derive(Debug, Clone)]
struct Col {
    name: String,
    kind: Kind,
    /// Its position in the batches' rows.
    index: usize,
    /// CLOB, NCLOB or BLOB.
    lob: bool,
    raw_text: RawText,
}

#[derive(Debug, Clone)]
struct Plan {
    table: String,
    /// The session's `NLS_NUMERIC_CHARACTERS` before the load.
    nls: Option<String>,
    cols: Vec<Col>,
    direct: bool,
    /// A native copy (see the module's docs).
    native: bool,
    commit_rows: u64,
    commit_bytes: u64,
}

impl Plan {
    fn insert_sql(&self) -> String {
        let names: Vec<String> = self.cols.iter().map(|c| quote(&c.name)).collect();
        let values: Vec<String> = self.cols.iter().enumerate().map(|(i, c)| c.kind.expr(&format!(":{}", i + 1), self.native)).collect();
        let hint = if self.direct { "/*+ APPEND_VALUES */ " } else { "" };
        format!("INSERT {hint}INTO {} ({}) VALUES ({})", self.table, names.join(", "), values.join(", "))
    }

    fn array_rows(&self) -> usize {
        let cap = if self.direct { DIRECT_ARRAY_ROWS } else { ARRAY_ROWS };
        cap.min(self.commit_rows.max(1) as usize)
    }
}

/// The target's columns and identities, checked against the load.
/// `source_types`: the source columns' types, in the batches' order
/// (empty when unknown).
fn plan(c: &Connection, owner: &str, table: &str, spec: &LoadSpec, source_types: &[String], native: bool) -> Result<Plan> {
    let (o, t) = (owner.to_string(), table.to_string());
    let mut types = std::collections::HashMap::new();
    for row in c
        .query("SELECT column_name, data_type FROM all_tab_columns WHERE owner = :1 AND table_name = :2", &[&o, &t])
        .map_err(err)?
    {
        let row = row.map_err(err)?;
        let (name, ty): (String, Option<String>) = (row.get(0).map_err(err)?, row.get(1).map_err(err)?);
        types.insert(name, ty.unwrap_or_default());
    }
    if types.is_empty() {
        return Err(Error::Query(format!("No existe la tabla {owner}.{table} o no se tiene acceso.")));
    }
    let mut identity = std::collections::HashMap::new();
    for row in c
        .query("SELECT column_name, generation_type FROM all_tab_identity_cols WHERE owner = :1 AND table_name = :2", &[&o, &t])
        .map_err(err)?
    {
        let row = row.map_err(err)?;
        let (name, gen): (String, Option<String>) = (row.get(0).map_err(err)?, row.get(1).map_err(err)?);
        identity.insert(name, gen.unwrap_or_default());
    }
    let mut cols = Vec::new();
    let mut lobs = false;
    for (index, name) in spec.columns.iter().enumerate() {
        let Some(ty) = types.get(name) else {
            return Err(Error::Query(format!("La tabla {owner}.{table} no tiene la columna {name}.")));
        };
        if let Some(gen) = identity.get(name) {
            if !spec.keep_identity {
                continue; // Oracle generates it.
            }
            if gen.eq_ignore_ascii_case("ALWAYS") {
                return Err(Error::Unsupported(format!(
                    "La columna {name} de {owner}.{table} es GENERATED ALWAYS AS IDENTITY y no acepta valores. \
                     Para conservarlos hay que pasarla antes a GENERATED BY DEFAULT \
                     (ALTER TABLE … MODIFY ({name} GENERATED BY DEFAULT AS IDENTITY)), o copiar sin conservar la identidad."
                )));
            }
        }
        let upper = ty.to_ascii_uppercase();
        lobs |= matches!(upper.as_str(), "CLOB" | "NCLOB" | "BLOB" | "JSON" | "XMLTYPE" | "LONG" | "LONG RAW");
        cols.push(Col {
            name: name.clone(),
            kind: kind_of(ty),
            index,
            lob: matches!(upper.as_str(), "CLOB" | "NCLOB" | "BLOB"),
            raw_text: source_types.get(index).map_or(RawText::Unknown, |t| raw_text(t)),
        });
    }
    if cols.is_empty() {
        return Err(Error::Query("No hay columnas para cargar.".into()));
    }
    let nls: Option<String> = c
        .query_row("SELECT value FROM nls_session_parameters WHERE parameter = 'NLS_NUMERIC_CHARACTERS'", &[])
        .and_then(|r| r.get(0))
        .map_err(err)?;
    if nls.as_deref() != Some(".,") {
        c.execute("ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,'", &[]).map_err(err)?;
    }
    Ok(Plan {
        table: format!("{}.{}", quote(owner), quote(table)),
        nls: nls.filter(|v| v != ".,"),
        cols,
        direct: spec.table_lock && !lobs,
        native,
        commit_rows: spec.commit_rows.max(1),
        commit_bytes: spec.commit_bytes.max(1),
    })
}

/// Whether the load's future is still alive. The worker commits only
/// while holding the lock and seeing it open, and the future's drop takes
/// the lock to close it: once the drop returns, nothing more commits.
#[derive(Default)]
struct Gate(Mutex<bool>);

impl Gate {
    fn closed(&self) -> bool {
        self.0.lock().map_or(true, |g| *g)
    }
}

/// Closes the gate when the load's future ends, however it ends.
struct CloseOnDrop(Arc<Gate>);

impl Drop for CloseOnDrop {
    fn drop(&mut self) {
        // Waits for a commit in progress (one round trip) to finish.
        let mut g = self.0 .0.lock().unwrap_or_else(|p| p.into_inner());
        *g = true;
    }
}

pub(crate) async fn bulk_load(
    s: &mut OracleSession,
    spec: &LoadSpec,
    columns: &[TransferColumn],
    source: &mut dyn BatchSource,
    progress: Progress<'_>,
) -> Result<u64> {
    load_with(s, spec, columns, source, progress, false).await
}

async fn load_with(
    s: &mut OracleSession,
    spec: &LoadSpec,
    columns: &[TransferColumn],
    source: &mut dyn BatchSource,
    progress: Progress<'_>,
    native: bool,
) -> Result<u64> {
    let (owner, table, spec2) = (s.owner(&spec.table), spec.table.name.clone(), spec.clone());
    let source_types: Vec<String> = columns.iter().map(|c| c.type_name.clone()).collect();
    // Through `run`: reconnects first if the interrupter killed the session.
    let plan = s.run(move |c| plan(c, &owner, &table, &spec2, &source_types, native)).await?;

    let gate = Arc::new(Gate::default());
    let _close = CloseOnDrop(gate.clone());
    // `None` marks the end; a channel closed without it is a cancel. One
    // batch at a time, and the next one is pulled only when the worker has
    // taken the previous one into its bound values (`taken`): until then
    // the batch keeps its room in the orchestrator's window.
    let (tx, mut rx) = tokio::sync::mpsc::channel::<Option<Vec<Vec<Cell>>>>(1);
    let (taken_tx, mut taken) = tokio::sync::mpsc::unbounded_channel::<()>();
    let (ptx, prx) = std::sync::mpsc::channel::<u64>();
    let shared = s.shared.clone();
    let worker_gate = gate.clone();
    let worker = tokio::task::spawn_blocking(move || {
        let conn = shared.conn.lock().map_err(|_| poisoned())?;
        let mut first = true;
        let next = || {
            if !std::mem::take(&mut first) {
                let _ = taken_tx.send(());
            }
            if worker_gate.closed() {
                return Err(Error::Cancelled);
            }
            match rx.blocking_recv() {
                Some(Some(rows)) if !worker_gate.closed() => Ok(Some(rows)),
                Some(None) => Ok(None),
                _ => Err(Error::Cancelled),
            }
        };
        // A panic here must not leave the connection's lock poisoned nor
        // the transaction open.
        let r = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| load(&conn, &plan, next, &ptx, &worker_gate)))
            .unwrap_or_else(|p| Err(Error::State(format!("la carga en Oracle falló inesperadamente: {}", panic_text(&*p)))));
        if r.is_err() {
            let _ = conn.rollback();
        }
        if let Some(v) = &plan.nls {
            let _ = conn.execute(&format!("ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '{}'", v.replace('\'', "''")), &[]);
        }
        r
    });
    while let Some(batch) = source.next().await {
        if tx.send(Some(batch.rows)).await.is_err() || taken.recv().await.is_none() {
            break; // The worker stopped: its error comes below.
        }
        while let Ok(n) = prx.try_recv() {
            progress(n);
        }
    }
    let _ = tx.send(None).await;
    drop(tx);
    let r = worker.await.map_err(join_err)?;
    while let Ok(n) = prx.try_recv() {
        progress(n);
    }
    if r.is_err() && s.shared.killed.load(Ordering::SeqCst) {
        return Err(Error::Cancelled);
    }
    r
}

/// Load what `next` gives until it ends; committed totals go to `committed`.
fn load(
    c: &Connection,
    plan: &Plan,
    mut next: impl FnMut() -> Result<Option<Vec<Vec<Cell>>>>,
    committed: &std::sync::mpsc::Sender<u64>,
    gate: &Gate,
) -> Result<u64> {
    let sql = plan.insert_sql();
    let mut stmt = c.statement(&sql).and_then(|b| b.build()).map_err(err)?;
    let array_rows = plan.array_rows();
    let mut pending: Vec<Vec<B>> = Vec::with_capacity(array_rows.min(ARRAY_ROWS));
    let mut pending_bytes = 0usize;
    let (mut since_rows, mut since_bytes, mut total) = (0u64, 0u64, 0u64);

    let commit = |since_rows: &mut u64, since_bytes: &mut u64, total: u64| -> Result<()> {
        // Held through the commit: the load's future can't be dropped
        // halfway through it.
        let closed = gate.0.lock().map_err(|_| poisoned())?;
        if *closed {
            return Err(Error::Cancelled);
        }
        c.commit().map_err(err)?;
        drop(closed);
        *since_rows = 0;
        *since_bytes = 0;
        let _ = committed.send(total);
        Ok(())
    };
    let execute = |stmt: &mut oracledb::Statement, pending: &mut Vec<Vec<B>>| -> Result<u64> {
        if gate.closed() {
            return Err(Error::Cancelled);
        }
        execute(stmt, pending)
    };

    while let Some(rows) = next()? {
        for mut row in rows {
            let mut bound = Vec::with_capacity(plan.cols.len());
            for col in &plan.cols {
                // Taken, not copied: the batch's memory becomes the binds'.
                let cell = row.get_mut(col.index).map_or(Cell::Null, |c| std::mem::replace(c, Cell::Null));
                bound.push(bind(cell, col, plan.native)?);
            }
            let bytes: usize = bound.iter().map(B::size).sum();
            if bound.iter().zip(&plan.cols).any(|(b, col)| b.is_big(col.lob)) {
                // Direct-path rows must be committed before a conventional
                // insert into the same table (ORA-12838).
                if plan.direct && !pending.is_empty() {
                    total += execute(&mut stmt, &mut pending)?;
                    pending_bytes = 0;
                    commit(&mut since_rows, &mut since_bytes, total)?;
                }
                insert_big(c, plan, bound)?;
                total += 1;
                since_rows += 1;
                since_bytes += bytes as u64;
                if plan.direct || since_rows >= plan.commit_rows || since_bytes >= plan.commit_bytes {
                    commit(&mut since_rows, &mut since_bytes, total)?;
                }
                continue;
            }
            pending.push(bound);
            pending_bytes += bytes;
            let window_full = since_rows + pending.len() as u64 >= plan.commit_rows || since_bytes + pending_bytes as u64 >= plan.commit_bytes;
            if pending.len() >= array_rows || pending_bytes >= ARRAY_BYTES || window_full {
                let n = execute(&mut stmt, &mut pending)?;
                total += n;
                since_rows += n;
                since_bytes += pending_bytes as u64;
                pending_bytes = 0;
                if plan.direct || since_rows >= plan.commit_rows || since_bytes >= plan.commit_bytes {
                    commit(&mut since_rows, &mut since_bytes, total)?;
                }
            }
        }
    }
    if !pending.is_empty() {
        let n = execute(&mut stmt, &mut pending)?;
        total += n;
        since_rows += n;
    }
    if since_rows > 0 || total == 0 {
        commit(&mut since_rows, &mut since_bytes, total)?;
    }
    Ok(total)
}

/// One array execute of the pending rows (emptied); the rows inserted.
fn execute(stmt: &mut oracledb::Statement, pending: &mut Vec<Vec<B>>) -> Result<u64> {
    let n = pending.len() as u64;
    {
        let rows: Vec<Vec<&dyn ToDbValue>> = pending.iter().map(|r| r.iter().map(B::as_dyn).collect()).collect();
        let slices: Vec<&[&dyn ToDbValue]> = rows.iter().map(Vec::as_slice).collect();
        stmt.execute_batch(slices.as_slice().into()).map_err(err)?;
    }
    pending.clear();
    Ok(n)
}

/// A row with a value too large for a bind (or an empty LOB): a PL/SQL
/// block builds each such value in a temporary LOB, 32 KB at a time, then
/// inserts the row.
fn insert_big(c: &Connection, plan: &Plan, row: Vec<B>) -> Result<()> {
    let mut decl = String::from("v VARCHAR2(32767); r RAW(32767); ");
    let mut body = String::new();
    let mut values = Vec::new();
    let mut params: Vec<B> = Vec::new();
    let mut free = String::new();
    for (i, (b, col)) in row.into_iter().zip(&plan.cols).enumerate() {
        if !b.is_big(col.lob) {
            params.push(b);
            values.push(col.kind.expr(&format!(":p{}", params.len()), plan.native));
            continue;
        }
        let l = format!("l{i}");
        match b {
            B::S(s) => {
                decl.push_str(&format!("{l} CLOB; "));
                body.push_str(&format!("DBMS_LOB.CREATETEMPORARY({l}, TRUE); "));
                for piece in utf8_pieces(&s, LOB_CHUNK) {
                    params.push(B::S(piece.to_string()));
                    // LENGTH2: a CLOB counts UTF-16 code units, so a
                    // character outside the BMP is 2 (LENGTH says 1).
                    body.push_str(&format!("v := :p{}; DBMS_LOB.WRITEAPPEND({l}, LENGTH2(v), v); ", params.len()));
                }
            }
            B::R(bytes) => {
                decl.push_str(&format!("{l} BLOB; "));
                body.push_str(&format!("DBMS_LOB.CREATETEMPORARY({l}, TRUE); "));
                for piece in bytes.chunks(LOB_CHUNK) {
                    params.push(B::R(piece.to_vec()));
                    body.push_str(&format!("r := :p{}; DBMS_LOB.WRITEAPPEND({l}, UTL_RAW.LENGTH(r), r); ", params.len()));
                }
            }
            _ => unreachable!("only text and bytes are big"),
        }
        values.push(col.kind.expr(&l, plan.native));
        free.push_str(&format!("DBMS_LOB.FREETEMPORARY({l}); "));
    }
    let names: Vec<String> = plan.cols.iter().map(|c| quote(&c.name)).collect();
    let block = format!(
        "DECLARE {decl}BEGIN {body}INSERT INTO {} ({}) VALUES ({}); {free}END;",
        plan.table,
        names.join(", "),
        values.join(", ")
    );
    // By name: the pieces' binds come before the INSERT's in the text.
    let names: Vec<String> = (1..=params.len()).map(|i| format!("P{i}")).collect();
    let named: Vec<(&str, &dyn ToDbValue)> = names.iter().map(String::as_str).zip(params.iter().map(B::as_dyn)).collect();
    let mut stmt = c.statement(&block).map(|b| b.exclude_from_cache()).and_then(|b| b.build()).map_err(err)?;
    stmt.execute_named(&named).map_err(err)?;
    Ok(())
}

/// `s` in pieces of at most `max` bytes, cut on character boundaries.
fn utf8_pieces(s: &str, max: usize) -> Vec<&str> {
    let mut out = Vec::new();
    let mut rest = s;
    while !rest.is_empty() {
        let mut end = rest.len().min(max);
        while !rest.is_char_boundary(end) {
            end -= 1;
        }
        out.push(&rest[..end]);
        rest = &rest[end..];
    }
    out
}

/// What a cell is, for an error message.
fn describe(cell: &Cell) -> String {
    match cell {
        Cell::Bytes(b) => format!("{} bytes", b.len()),
        Cell::Text(s) | Cell::Json(s) | Cell::Decimal(s) if s.len() > 60 => format!("un texto de {} caracteres", s.chars().count()),
        other => format!("{other:?}"),
    }
}

fn bad(cell: &Cell, col: &Col) -> Error {
    Error::Query(format!("Columna {}: no se puede convertir {} al tipo de la columna ({:?}).", col.name, describe(cell), col.kind))
}

/// A cell bound for its target column (taken: its text or bytes move into
/// the bind).
fn bind(cell: Cell, col: &Col, native: bool) -> Result<B> {
    if matches!(cell, Cell::Null) {
        return Ok(B::Null(col.kind.db_type()));
    }
    let b = match col.kind {
        Kind::Number => {
            let text = match &cell {
                Cell::Int(i) => Some(i.to_string()),
                Cell::UInt(u) => Some(u.to_string()),
                Cell::Bool(b) => Some((*b as u8).to_string()),
                Cell::Float(f) if f.is_finite() => plain_decimal(&format!("{f:e}")),
                Cell::Decimal(s) | Cell::Text(s) => plain_decimal(s.trim()),
                _ => None,
            };
            B::S(text.ok_or_else(|| bad(&cell, col))?)
        }
        Kind::Double => {
            let v = match &cell {
                Cell::Float(f) => Some(*f),
                Cell::Int(i) => Some(*i as f64),
                Cell::UInt(u) => Some(*u as f64),
                Cell::Bool(b) => Some(*b as u8 as f64),
                // "1e400" parses as infinity: only an explicit infinity is one.
                Cell::Decimal(s) | Cell::Text(s) => {
                    s.trim().parse::<f64>().ok().filter(|f| f.is_finite() || s.to_ascii_lowercase().contains("inf"))
                }
                _ => None,
            };
            B::F(v.ok_or_else(|| bad(&cell, col))?)
        }
        Kind::Bool => {
            let v = match &cell {
                Cell::Bool(b) => Some(*b),
                Cell::Int(i) => Some(*i != 0),
                Cell::UInt(u) => Some(*u != 0),
                Cell::Text(s) => match s.trim().to_ascii_lowercase().as_str() {
                    "1" | "true" | "t" | "y" | "yes" => Some(true),
                    "0" | "false" | "f" | "n" | "no" => Some(false),
                    _ => None,
                },
                _ => None,
            };
            B::Bool(v.ok_or_else(|| bad(&cell, col))?)
        }
        Kind::Raw => B::R(match cell {
            Cell::Bytes(b) => b,
            Cell::Uuid(s) => hex(&s.replace('-', "")).ok_or_else(|| bad(&Cell::Uuid(s.clone()), col))?,
            Cell::Text(s) => {
                let h = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X"));
                match col.raw_text {
                    RawText::Hex => hex(h.unwrap_or(&s)).ok_or_else(|| bad(&Cell::Text(s.clone()), col))?,
                    RawText::Utf8 => s.into_bytes(),
                    RawText::Unknown => match h.and_then(hex) {
                        Some(b) => b,
                        None => s.into_bytes(),
                    },
                }
            }
            other => return Err(bad(&other, col)),
        }),
        Kind::Timestamp => {
            let t = match &cell {
                Cell::Date(s) | Cell::DateTime(s) | Cell::DateTimeTz(s) | Cell::Text(s) => parse_ts(s),
                Cell::Time(s) => parse_ts(&format!("1970-01-01 {s}")),
                _ => None,
            }
            .ok_or_else(|| bad(&cell, col))?;
            B::T(OracleTimestamp::new_timestamp(t.y, t.mo, t.d, t.h, t.mi, t.s, t.ns))
        }
        Kind::TimestampTz => match cell {
            // The native read's own text, with its region.
            Cell::Text(s) if native => B::S(s),
            Cell::Date(s) | Cell::DateTime(s) | Cell::DateTimeTz(s) | Cell::Text(s) => {
                B::S(parse_ts(&s).ok_or_else(|| bad(&Cell::Text(s.clone()), col))?.tz_text())
            }
            other => return Err(bad(&other, col)),
        },
        Kind::IntervalDs => B::S(match cell {
            Cell::Text(s) => s,
            Cell::Time(s) => format!("+0 {s}"),
            other => return Err(bad(&other, col)),
        }),
        Kind::IntervalYm => B::S(match cell {
            Cell::Text(s) => s,
            other => return Err(bad(&other, col)),
        }),
        Kind::Text | Kind::Json => B::S(match cell {
            Cell::Text(s) | Cell::Json(s) | Cell::Decimal(s) | Cell::Date(s) | Cell::Time(s) | Cell::DateTime(s) | Cell::DateTimeTz(s) | Cell::Uuid(s) => s,
            Cell::Int(i) => i.to_string(),
            Cell::UInt(u) => u.to_string(),
            Cell::Float(f) => f.to_string(),
            Cell::Bool(b) => (if b { "1" } else { "0" }).to_string(),
            Cell::Bytes(b) => b.iter().map(|x| format!("{x:02X}")).collect(),
            Cell::Null => unreachable!(),
        }),
    };
    // Oracle keeps no empty VARCHAR2 / CHAR / RAW (nor an empty interval
    // or JSON): the bind would be stored as NULL, or refused by NOT NULL.
    // Empty CLOBs and BLOBs are fine (see `B::is_big`).
    let empty = matches!(&b, B::S(s) if s.is_empty()) || matches!(&b, B::R(r) if r.is_empty());
    if empty && !col.lob {
        return Err(Error::Unsupported(format!(
            "Columna {}: Oracle guarda el texto vacío ('') y el binario vacío como NULL, así que no se puede copiar ese valor \
             sin cambiarlo. Convertí los vacíos a NULL (u otro valor) en el origen, o usá una columna CLOB / BLOB en el destino.",
            col.name
        )));
    }
    Ok(b)
}

fn hex(s: &str) -> Option<Vec<u8>> {
    if !s.len().is_multiple_of(2) || !s.bytes().all(|b| b.is_ascii_hexdigit()) {
        return None;
    }
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i + 2], 16).ok()).collect()
}

/// A decimal number as plain digits (`1.5e-3` → `0.0015`), `None` when it
/// isn't a number or is outside NUMBER's range (so the text never grows
/// past the input plus 130 digits).
fn plain_decimal(s: &str) -> Option<String> {
    let (neg, body) = match s.strip_prefix('-') {
        Some(r) => (true, r),
        None => (false, s.strip_prefix('+').unwrap_or(s)),
    };
    let (mant, exp) = match body.find(['e', 'E']) {
        Some(i) => (&body[..i], body[i + 1..].parse::<i64>().ok()?),
        None => (body, 0),
    };
    let (int, frac) = mant.split_once('.').unwrap_or((mant, ""));
    if int.is_empty() && frac.is_empty() || !int.bytes().chain(frac.bytes()).all(|b| b.is_ascii_digit()) {
        return None;
    }
    let digits = format!("{int}{frac}");
    let significant = digits.trim_start_matches('0');
    if significant.is_empty() {
        return Some("0".into());
    }
    // Where the point goes, counted from the first digit, then from the
    // first significant one (the value is 0.significant × 10^magnitude).
    let point = (int.len() as i64).checked_add(exp)?;
    let magnitude = point - (digits.len() - significant.len()) as i64;
    if !(NUMBER_MIN_MAGNITUDE..=NUMBER_MAX_MAGNITUDE).contains(&magnitude) {
        return None;
    }
    let digits = significant;
    let point = magnitude;
    let mut out = String::new();
    if point <= 0 {
        out.push_str("0.");
        out.extend(std::iter::repeat_n('0', (-point) as usize));
        out.push_str(digits);
    } else if point as usize >= digits.len() {
        out.push_str(digits);
        out.extend(std::iter::repeat_n('0', point as usize - digits.len()));
    } else {
        out.push_str(&digits[..point as usize]);
        out.push('.');
        out.push_str(&digits[point as usize..]);
    }
    let out = if out.contains('.') { out.trim_end_matches('0').trim_end_matches('.').to_string() } else { out };
    let out = out.trim_start_matches('0');
    let out = if out.is_empty() || out.starts_with('.') { format!("0{out}") } else { out.to_string() };
    Some(if neg && out != "0" { format!("-{out}") } else { out })
}

/// A parsed date-time.
#[derive(Debug, Clone, Copy, PartialEq)]
struct Ts {
    /// Oracle's year: negative is BC (-1 is 1 BC; there is no year 0).
    y: i16,
    mo: u8,
    d: u8,
    h: u8,
    mi: u8,
    s: u8,
    ns: u32,
    /// Offset in minutes.
    tz: Option<i32>,
}

impl Ts {
    /// For `TO_TIMESTAMP_TZ(…, TZ_FORMAT)`; no offset means UTC.
    fn tz_text(&self) -> String {
        let off = self.tz.unwrap_or(0);
        let sign = if off < 0 { '-' } else { '+' };
        format!(
            "{}{:04}-{:02}-{:02} {:02}:{:02}:{:02}.{:09} {sign}{:02}:{:02}",
            if self.y < 0 { "-" } else { "" },
            self.y.unsigned_abs(),
            self.mo,
            self.d,
            self.h,
            self.mi,
            self.s,
            self.ns,
            off.abs() / 60,
            off.abs() % 60
        )
    }
}

/// `YYYY-MM-DD[( |T)HH:MM[:SS[.f]]][ ][Z|±HH[:MM]][ BC]`.
fn parse_ts(s: &str) -> Option<Ts> {
    let mut s = s.trim();
    let bc = s.len() > 3 && s[s.len() - 3..].eq_ignore_ascii_case(" bc");
    if bc {
        s = s[..s.len() - 3].trim_end();
    }
    let num = |t: &str| -> Option<u32> { (!t.is_empty() && t.bytes().all(|b| b.is_ascii_digit())).then(|| t.parse().ok()).flatten() };
    let date = s.get(..10)?;
    let mut parts = date.split('-');
    let (y, mo, d) = (num(parts.next()?)?, num(parts.next()?)?, num(parts.next()?)?);
    // Oracle's years: 4712 BC to 9999 AD, no year 0.
    if !(1..=12).contains(&mo) || !(1..=31).contains(&d) || y > 9999 || y == 0 || bc && y > 4712 {
        return None;
    }
    let y = if bc { -(y as i16) } else { y as i16 };
    let mut t = Ts { y, mo: mo as u8, d: d as u8, h: 0, mi: 0, s: 0, ns: 0, tz: None };
    let mut rest = &s[10..];
    if let Some(r) = rest.strip_prefix([' ', 'T']) {
        let end = r.find(|c: char| !(c.is_ascii_digit() || c == ':' || c == '.')).unwrap_or(r.len());
        let (time, tail) = r.split_at(end);
        let (hms, frac) = time.split_once('.').unwrap_or((time, ""));
        let mut f = hms.split(':');
        t.h = num(f.next()?)? as u8;
        t.mi = num(f.next()?)? as u8;
        t.s = f.next().map(num).unwrap_or(Some(0))? as u8;
        if f.next().is_some() || t.h > 23 || t.mi > 59 || t.s > 60 {
            return None;
        }
        if !frac.is_empty() {
            let digits: String = frac.chars().take(9).collect();
            t.ns = num(&digits)? * 10u32.pow(9 - digits.len() as u32);
        }
        rest = tail;
    }
    let rest = rest.trim_start();
    if rest.is_empty() {
        return Some(t);
    }
    if rest == "Z" || rest == "z" {
        t.tz = Some(0);
        return Some(t);
    }
    let sign = match rest.as_bytes()[0] {
        b'+' => 1,
        b'-' => -1,
        _ => return None,
    };
    let off = rest[1..].replace(':', "");
    let (h, m) = match off.len() {
        2 => (num(&off)?, 0),
        4 => (num(&off[..2])?, num(&off[2..])?),
        _ => return None,
    };
    t.tz = Some(sign * (h as i32 * 60 + m as i32));
    Some(t)
}

// ------------------------------------------------------------ native copy

fn oracle(s: &mut dyn Session) -> Option<&mut OracleSession> {
    s.as_any()?.downcast_mut::<OracleSession>()
}

/// The native read's end: batches (then `None`) to the load.
struct NativeSink {
    tx: tokio::sync::mpsc::Sender<Option<RowBatch>>,
}

impl BatchSink for NativeSink {
    fn begin(&mut self, _columns: &[TransferColumn]) -> std::io::Result<()> {
        Ok(())
    }

    fn batch(&mut self, batch: RowBatch) -> std::io::Result<()> {
        // On the read's blocking thread: waits while the load is behind.
        self.tx.blocking_send(Some(batch)).map_err(|_| std::io::Error::other("se detuvo la escritura en el destino"))
    }
}

/// The load's end. If the read goes away without `None` (it failed) this
/// never returns: the copy ends through the read's error.
struct NativeSource {
    rx: tokio::sync::mpsc::Receiver<Option<RowBatch>>,
}

#[dbine_driver::async_trait]
impl BatchSource for NativeSource {
    async fn next(&mut self) -> Option<RowBatch> {
        match self.rx.recv().await {
            Some(batch) => batch,
            None => std::future::pending().await,
        }
    }
}

/// Oracle to Oracle: the read and the load above, joined by a channel of
/// [`NATIVE_BATCHES`], with time zone regions and extended JSON kept (see
/// the module's docs). The source only runs a `SELECT`.
pub(crate) async fn copy_native(source: &mut dyn Session, target: &mut dyn Session, spec: &CopySpec, progress: Progress<'_>) -> Result<u64> {
    let (Some(src), Some(dst)) = (oracle(source), oracle(target)) else {
        return Err(Error::Unsupported("copia directa no disponible: las sesiones no son de Oracle".into()));
    };
    let (tx, rx) = tokio::sync::mpsc::channel(NATIVE_BATCHES);
    let end = tx.clone();
    let sink: BatchSinkRef = Arc::new(Mutex::new(NativeSink { tx }));
    let reader = async move {
        let n = read_with(src, &spec.source, sink, true).await?;
        end.send(None).await.map_err(|_| Error::State("se detuvo la escritura en el destino".into()))?;
        Ok::<_, Error>(n)
    };
    let mut from = NativeSource { rx };
    let writer = load_with(dst, &spec.target, &[], &mut from, progress, true);
    tokio::pin!(reader);
    tokio::pin!(writer);
    tokio::select! {
        r = &mut reader => {
            // A failed read drops the load: nothing of it stays committed.
            r?;
            writer.await
        }
        w = &mut writer => {
            // The load ends only after the read's `None`, or with an error;
            // on an error the read stops at its next batch (the channel is
            // closed when this returns).
            let n = w?;
            reader.await?;
            Ok(n)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn col(kind: Kind) -> Col {
        Col { name: "c".into(), kind, index: 0, lob: false, raw_text: RawText::Unknown }
    }

    #[test]
    fn decimals_become_plain_digits() {
        assert_eq!(plain_decimal("1.5e-3").as_deref(), Some("0.0015"));
        assert_eq!(plain_decimal("1e20").as_deref(), Some("100000000000000000000"));
        assert_eq!(plain_decimal("-12.3400").as_deref(), Some("-12.34"));
        assert_eq!(plain_decimal("0.000").as_deref(), Some("0"));
        assert_eq!(plain_decimal("-0").as_deref(), Some("0"));
        assert_eq!(plain_decimal("007").as_deref(), Some("7"));
        assert_eq!(plain_decimal(".5").as_deref(), Some("0.5"));
        assert_eq!(plain_decimal("0.0012e3").as_deref(), Some("1.2"));
        assert_eq!(plain_decimal("12345678901234567890.123456789").as_deref(), Some("12345678901234567890.123456789"));
        assert_eq!(plain_decimal("abc"), None);
        assert_eq!(plain_decimal(""), None);
        assert_eq!(plain_decimal(&format!("{:e}", 0.1f64)).as_deref(), Some("0.1"));
    }

    #[test]
    fn huge_exponents_are_refused_without_allocating() {
        // Used to overflow (a panic in the worker) or build a 200 MB string.
        assert_eq!(plain_decimal("1e2147483647"), None);
        assert_eq!(plain_decimal("1e-2147483648"), None);
        assert_eq!(plain_decimal("1e200000000"), None);
        assert_eq!(plain_decimal("1e99999999999999999999"), None);
        assert_eq!(plain_decimal("0e999999999").as_deref(), Some("0"));
        // NUMBER's range: below 1e126, down to 1e-130.
        assert_eq!(plain_decimal("9.99e125").map(|s| s.len()), Some(126));
        assert_eq!(plain_decimal("1e126"), None);
        assert!(plain_decimal("1e-130").is_some());
        assert_eq!(plain_decimal("1e-131"), None);
        assert!(bind(Cell::Text("1e2147483647".into()), &col(Kind::Number), false).is_err());
        assert!(bind(Cell::Float(1e300), &col(Kind::Number), false).is_err());
    }

    #[test]
    fn date_times_parse_with_and_without_zone() {
        let t = parse_ts("2024-01-31 13:45:07.1234").unwrap();
        assert_eq!((t.y, t.mo, t.d, t.h, t.mi, t.s, t.ns, t.tz), (2024, 1, 31, 13, 45, 7, 123_400_000, None));
        assert_eq!(parse_ts("2024-01-31").unwrap().h, 0);
        assert_eq!(parse_ts("2024-01-31T01:02:03Z").unwrap().tz, Some(0));
        assert_eq!(parse_ts("2024-01-31 01:02:03-03:00").unwrap().tz, Some(-180));
        assert_eq!(parse_ts("2024-01-31 01:02:03 +0530").unwrap().tz, Some(330));
        assert_eq!(parse_ts("2024-01-31 01:02").unwrap().mi, 2);
        assert_eq!(parse_ts("2024-13-01"), None);
        assert_eq!(parse_ts("hola"), None);
        assert_eq!(
            parse_ts("2024-01-31 01:02:03.5-03:00").unwrap().tz_text(),
            "2024-01-31 01:02:03.500000000 -03:00"
        );
        assert_eq!(parse_ts("2024-01-31 01:02:03").unwrap().tz_text(), "2024-01-31 01:02:03.000000000 +00:00");
    }

    #[test]
    fn bc_dates_round_trip_as_text() {
        let t = OracleTimestamp::new_timestamp(-44, 3, 15, 12, 0, 0, 500_000_000);
        assert_eq!(ts_cell(&t, true, false), Cell::Text("0044-03-15 12:00:00.5 BC".into()));
        assert_eq!(ts_cell(&t, true, true), Cell::Text("0044-03-15 12:00:00.5+00:00 BC".into()));
        let t = OracleTimestamp::new_timestamp(2024, 1, 31, 0, 0, 0, 0);
        assert_eq!(ts_cell(&t, false, false), Cell::DateTime("2024-01-31 00:00:00".into()));
        assert_eq!(tz_cell("-0044-03-15 12:00:00.000000000+01:00"), Cell::Text("0044-03-15 12:00:00+01:00 BC".into()));
        assert_eq!(tz_cell(" 2024-01-31 13:45:07.500000000-03:00"), Cell::DateTimeTz("2024-01-31 13:45:07.5-03:00".into()));
        let p = parse_ts("0044-03-15 12:00:00 BC").unwrap();
        assert_eq!((p.y, p.mo, p.d, p.h), (-44, 3, 15, 12));
        assert_eq!(parse_ts("0044-03-15 12:00:00+01:00 BC").unwrap().tz_text(), "-0044-03-15 12:00:00.000000000 +01:00");
        assert_eq!(parse_ts("0044-03-15 bc").unwrap().y, -44);
        assert_eq!(parse_ts("0000-01-01"), None);
        assert_eq!(parse_ts("4713-01-01 BC"), None);
        match bind(Cell::Text("0044-03-15 12:00:00 BC".into()), &col(Kind::Timestamp), false).unwrap() {
            B::T(t) => assert_eq!((t.year(), t.month(), t.day(), t.hour()), (-44, 3, 15, 12)),
            _ => panic!(),
        }
    }

    #[test]
    fn target_types_pick_the_bind() {
        assert_eq!(kind_of("NUMBER"), Kind::Number);
        assert_eq!(kind_of("BINARY_FLOAT"), Kind::Double);
        assert_eq!(kind_of("TIMESTAMP(6)"), Kind::Timestamp);
        assert_eq!(kind_of("TIMESTAMP(6) WITH TIME ZONE"), Kind::TimestampTz);
        assert_eq!(kind_of("TIMESTAMP(9) WITH LOCAL TIME ZONE"), Kind::TimestampTz);
        assert_eq!(kind_of("INTERVAL DAY(2) TO SECOND(6)"), Kind::IntervalDs);
        assert_eq!(kind_of("INTERVAL YEAR(2) TO MONTH"), Kind::IntervalYm);
        assert_eq!(kind_of("BLOB"), Kind::Raw);
        assert_eq!(kind_of("NCLOB"), Kind::Text);
        assert_eq!(kind_of("DATE"), Kind::Timestamp);
        assert_eq!(Kind::TimestampTz.expr(":3", false), "TO_TIMESTAMP_TZ(:3, 'SYYYY-MM-DD HH24:MI:SS.FF9 TZR TZD')");
        assert_eq!(Kind::Json.expr(":1", false), ":1");
        assert_eq!(Kind::Json.expr(":1", true), "JSON(:1 EXTENDED)");
    }

    #[test]
    fn cells_bind_by_target_type() {
        let n = |c: Cell| match bind(c, &col(Kind::Number), false).unwrap() {
            B::S(n) => n,
            _ => panic!(),
        };
        assert_eq!(n(Cell::Int(-5)), "-5");
        assert_eq!(n(Cell::UInt(u64::MAX)), u64::MAX.to_string());
        assert_eq!(n(Cell::Decimal("123456789012345678901234567890.25".into())), "123456789012345678901234567890.25");
        assert_eq!(n(Cell::Float(0.1)), "0.1");
        assert_eq!(n(Cell::Bool(true)), "1");
        assert!(bind(Cell::Text("x".into()), &col(Kind::Number), false).is_err());
        assert!(bind(Cell::Text("1e400".into()), &col(Kind::Double), false).is_err());
        assert!(matches!(bind(Cell::Null, &col(Kind::Raw), false).unwrap(), B::Null(t) if t == oracledb::DB_TYPE_RAW));
        assert!(matches!(bind(Cell::Uuid("00112233-4455-6677-8899-aabbccddeeff".into()), &col(Kind::Raw), false).unwrap(), B::R(r) if r.len() == 16));
        assert!(matches!(bind(Cell::Text("0xABCD".into()), &col(Kind::Raw), false).unwrap(), B::R(r) if r == vec![0xAB, 0xCD]));
        assert!(matches!(bind(Cell::Bytes(vec![1, 255]), &col(Kind::Text), false).unwrap(), B::S(s) if s == "01FF"));
        match bind(Cell::DateTime("2024-02-29 23:59:58.000001".into()), &col(Kind::Timestamp), false).unwrap() {
            B::T(t) => assert_eq!(fmt_ts(&t, true), "2024-02-29 23:59:58.000001"),
            _ => panic!(),
        }
        assert!(matches!(bind(Cell::DateTimeTz("2024-02-29 23:59:58+02:00".into()), &col(Kind::TimestampTz), false).unwrap(),
            B::S(s) if s == "2024-02-29 23:59:58.000000000 +02:00"));
        // A native copy's text keeps its region.
        assert!(matches!(bind(Cell::Text("2024-07-01 10:00:00.5 EUROPE/MADRID CEST".into()), &col(Kind::TimestampTz), true).unwrap(),
            B::S(s) if s == "2024-07-01 10:00:00.5 EUROPE/MADRID CEST"));
        assert!(bind(Cell::Text("2024-07-01 10:00:00.5 EUROPE/MADRID CEST".into()), &col(Kind::TimestampTz), false).is_err());
        assert!(matches!(bind(Cell::Time("01:02:03".into()), &col(Kind::IntervalDs), false).unwrap(), B::S(s) if s == "+0 01:02:03"));
        assert!(bind(Cell::Text("x".repeat(LOB_INLINE + 1)), &col(Kind::Text), false).unwrap().is_big(false));
        assert!(!bind(Cell::Text("x".repeat(LOB_INLINE)), &col(Kind::Text), false).unwrap().is_big(false));
    }

    #[test]
    fn text_into_raw_follows_the_source_type() {
        let raw = |t: RawText, s: &str| match bind(Cell::Text(s.into()), &Col { raw_text: t, ..col(Kind::Raw) }, false) {
            Ok(B::R(r)) => Some(r),
            _ => None,
        };
        // Text is its bytes, whatever it looks like.
        assert_eq!(raw(raw_text("VARCHAR2(10)"), "cafe"), Some(b"cafe".to_vec()));
        assert_eq!(raw(raw_text("text"), "0xcafe"), Some(b"0xcafe".to_vec()));
        // Binary sources (an ObjectId too) are hex, or an error.
        assert_eq!(raw(raw_text("objectId"), "65a1b2c3d4e5f60718293a4b").map(|r| r.len()), Some(12));
        assert_eq!(raw(raw_text("varbinary(16)"), "0xCAFE"), Some(vec![0xCA, 0xFE]));
        assert_eq!(raw(raw_text("bytea"), "hola"), None);
        // Unknown: only 0x… is hex.
        assert_eq!(raw(RawText::Unknown, "cafe"), Some(b"cafe".to_vec()));
        assert_eq!(raw(RawText::Unknown, "0xcafe"), Some(vec![0xCA, 0xFE]));
        assert_eq!(raw_text(""), RawText::Unknown);
    }

    #[test]
    fn empty_values_are_refused_except_in_lobs() {
        for (kind, cell) in [(Kind::Text, Cell::Text(String::new())), (Kind::Raw, Cell::Bytes(vec![])), (Kind::Text, Cell::Bytes(vec![]))] {
            let e = bind(cell, &col(kind), false).err().expect("refused");
            assert!(matches!(&e, Error::Unsupported(m) if m.contains("NULL")), "{e}");
        }
        let lob = |kind| Col { lob: true, ..col(kind) };
        assert!(bind(Cell::Text(String::new()), &lob(Kind::Text), false).unwrap().is_big(true));
        assert!(bind(Cell::Bytes(vec![]), &lob(Kind::Raw), false).unwrap().is_big(true));
        assert!(!bind(Cell::Text("a".into()), &lob(Kind::Text), false).unwrap().is_big(true));
    }

    #[test]
    fn fractions_are_trimmed() {
        assert_eq!(trim_fraction("2024-01-31 13:45:07.500000000-03:00"), "2024-01-31 13:45:07.5-03:00");
        assert_eq!(trim_fraction("2024-01-31 13:45:07.000000000+00:00"), "2024-01-31 13:45:07+00:00");
        assert_eq!(trim_fraction("2024-01-31 13:45:07+00:00"), "2024-01-31 13:45:07+00:00");
    }

    #[test]
    fn text_pieces_cut_on_characters() {
        let s = "ñ".repeat(10); // 2 bytes each
        let p = utf8_pieces(&s, 5);
        assert!(p.iter().all(|x| x.len() <= 5));
        assert_eq!(p.concat(), s);
        assert!(utf8_pieces("", 5).is_empty());
    }

    #[test]
    fn a_closed_gate_waits_for_the_commit_in_progress() {
        let gate = Arc::new(Gate::default());
        let held = gate.0.lock().unwrap();
        let g = gate.clone();
        let closer = std::thread::spawn(move || drop(CloseOnDrop(g)));
        std::thread::sleep(std::time::Duration::from_millis(50));
        // The "commit" still holds the lock: the drop hasn't returned.
        assert!(!closer.is_finished());
        drop(held);
        closer.join().unwrap();
        assert!(gate.closed());
    }

    #[test]
    fn insert_uses_the_hint_only_for_direct_path() {
        let mut p = Plan {
            table: "\"S\".\"T\"".into(),
            nls: None,
            cols: vec![
                Col { name: "A".into(), kind: Kind::Number, index: 0, lob: false, raw_text: RawText::Unknown },
                Col { name: "B".into(), kind: Kind::IntervalYm, index: 1, lob: false, raw_text: RawText::Unknown },
            ],
            direct: false,
            native: false,
            commit_rows: 100_000,
            commit_bytes: 1 << 29,
        };
        assert_eq!(p.insert_sql(), "INSERT INTO \"S\".\"T\" (\"A\", \"B\") VALUES (TO_NUMBER(:1), TO_YMINTERVAL(:2))");
        assert_eq!(p.array_rows(), ARRAY_ROWS);
        p.direct = true;
        assert!(p.insert_sql().starts_with("INSERT /*+ APPEND_VALUES */ INTO"));
        p.commit_rows = 500;
        assert_eq!(p.array_rows(), 500);
    }
}
