//! "Clonar tabla" against a live server, any driver: clones a table, then
//! compares the original and the clone (row count and every row, read
//! with `read_batches`) and inserts one row into the clone.
//!
//! Ignored by default. Run it against a test container (`dbine-test-*`):
//!
//! ```sh
//! DBINE_CLONE_DRIVER=postgres \
//! DBINE_CLONE_CONFIG='{"host":"localhost","port":5432,"username":"postgres","password":"x"}' \
//! DBINE_CLONE_DATABASE=postgres \
//! DBINE_CLONE_SETUP='DROP TABLE IF EXISTS public.clon_src CASCADE; CREATE TABLE public.clon_src (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, n text, b bytea); INSERT INTO public.clon_src (n, b) SELECT md5(g::text), NULL FROM generate_series(1, 500) g;' \
//! DBINE_CLONE_TABLE=public.clon_src \
//! cargo test -p dbine-transfer --test clone_table_live -- --ignored --nocapture
//! ```
//!
//! - `DBINE_CLONE_DRIVER`: the driver id (`postgres`, `mysql`, `sqlserver`,
//!   `oracle`, `mongodb`…).
//! - `DBINE_CLONE_CONFIG`: a `ConnectionConfig` as JSON (`driver` may be
//!   left out: it's `DBINE_CLONE_DRIVER`).
//! - `DBINE_CLONE_DATABASE`: the database to connect to (optional).
//! - `DBINE_CLONE_SETUP`: a script, in the driver's language, that creates
//!   the sample table (optional; run first, on a writable connection).
//! - `DBINE_CLONE_TABLE`: `schema.name` or `name`.
//! - `DBINE_CLONE_KIND`: the object kind (default `table`; `collection`…).
//! - `DBINE_CLONE_INSERT`: the insert to try on the clone, `{table}` being
//!   its quoted name (optional; by default the original's first row again,
//!   without its identity and computed columns: on SQL engines with a
//!   primary key, that row is deleted from the clone and copied back with
//!   `INSERT … SELECT` from the original, so values keep their types and
//!   unique columns don't collide; elsewhere through `insert_script`).
//! - `DBINE_CLONE_CHECK`: a query that must return 0 when the clone's
//!   values are the original's as the server sees them, `{source}` and
//!   `{clone}` being their quoted names (optional; the rows read with
//!   `read_batches` are compared anyway, but a reader may normalise what
//!   differs, like Trino's zone names: `SELECT count(*) FROM (SELECT
//!   CAST(ts AS varchar) FROM {source} EXCEPT SELECT CAST(ts AS varchar)
//!   FROM {clone})`).
//! - `DBINE_CLONE_NAME`: the clone's name (default: the one the dialog
//!   proposes). With a setup that gives other objects the names the clone's
//!   constraints and indexes would take, the clone must avoid them (Oracle:
//!   `CREATE TABLE clonv_col (id NUMBER CONSTRAINT pk_clonv_col PRIMARY
//!   KEY, v NUMBER); CREATE INDEX ix_clonv_col_v ON clonv_col (v); CREATE
//!   TABLE clonv_other (a NUMBER CONSTRAINT pk_clonv_col_x PRIMARY KEY, b
//!   NUMBER); CREATE INDEX ix_clonv_col_x_v ON clonv_other (b)` with
//!   `DBINE_CLONE_NAME=CLONV_COL_X`; MySQL / MariaDB, whose foreign key
//!   names, and MySQL's CHECK names, are unique per schema: `CREATE TABLE
//!   c3 (id INT PRIMARY KEY, a INT, p INT, CONSTRAINT ck CHECK (a>0),
//!   CONSTRAINT fk_c3_p FOREIGN KEY (p) REFERENCES c3(id)); CREATE TABLE
//!   occ (id INT PRIMARY KEY, a INT, p INT, CONSTRAINT c3x_ck CHECK (a>0),
//!   CONSTRAINT fk_c3x_p FOREIGN KEY (p) REFERENCES occ(id)); INSERT INTO
//!   c3 VALUES (1,1,NULL),(2,2,1)` with `DBINE_CLONE_NAME=c3x`).
//! - `DBINE_CLONE_AFTER`: like `DBINE_CLONE_CHECK`, run after the insert
//!   into the clone (optional; e.g. the id the clone's IDENTITY gave it,
//!   or that a row a disabled constraint lets in went in).
//! - `DBINE_CLONE_KEEP=1`: leave the clone (it's dropped by default, also
//!   when a check after the clone fails).
//! - `DBINE_CLONE_REFUSED`: the clone must be refused, its error containing
//!   this text, and leave no table behind (the other checks are skipped).
//!   StarRocks / Doris, a rollup still being built on the original (its
//!   `DESC … ALL` doesn't list it yet, so the clone would miss it):
//!   `DBINE_CLONE_SETUP='DROP TABLE IF EXISTS rr FORCE; CREATE TABLE rr (k
//!   INT, j INT, v BIGINT SUM) AGGREGATE KEY(k,j) DISTRIBUTED BY HASH(k)
//!   BUCKETS 1 PROPERTIES("replication_num"="1"); INSERT INTO rr VALUES
//!   (1,2,3),(2,3,4); ALTER TABLE rr ADD ROLLUP r_v (j, v)'`,
//!   `DBINE_CLONE_TABLE=rr`, `DBINE_CLONE_REFUSED='se está construyendo el
//!   rollup o vista materializada «r_v»'` (the same with `CREATE
//!   MATERIALIZED VIEW mv_x AS SELECT k, sum(v) FROM rr GROUP BY k`, or an
//!   `ALTER TABLE rr MODIFY COLUMN …` job: «un cambio de columnas»).
//!   StarRocks, a pending OPTIMIZE (`LIKE` would copy the old
//!   distribution): `CREATE TABLE od (k INT, j INT, v BIGINT) DUPLICATE
//!   KEY(k) DISTRIBUTED BY HASH(k) BUCKETS 1 PROPERTIES
//!   ("replication_num"="1"); INSERT INTO od VALUES (1,1,1),(2,2,2),(3,3,3);
//!   ALTER TABLE od DISTRIBUTED BY HASH(j) BUCKETS 3`, then
//!   `DBINE_CLONE_TABLE=od`, `DBINE_CLONE_REFUSED='un cambio de
//!   distribución, buckets o particiones (OPTIMIZE)'`.
//!   StarRocks, a finished rollup on a table of another database than the
//!   connection's (`DBINE_CLONE_TABLE='otra_db.rr x'`, rollup `r v`): it
//!   clones, rollup included (it isn't taken for a synchronous
//!   materialized view).
//! - ClickHouse, a CHECK added after rows that break it (the engine checks
//!   it on every INSERT, not on the rows already there): `CREATE TABLE
//!   clonev.ckv (id UInt32, v Int32) ENGINE=MergeTree ORDER BY id; INSERT
//!   INTO clonev.ckv VALUES (1,-5),(2,7); ALTER TABLE clonev.ckv ADD
//!   CONSTRAINT ck_pos CHECK v > 0` with `DBINE_CLONE_TABLE=clonev.ckv`
//!   and `DBINE_CLONE_INSERT='INSERT INTO {table} VALUES (3, 1)'`: the
//!   clone has both rows and the constraint, in the original's order.
//! - StarRocks / ClickHouse, a table in another database than the
//!   connection's, or with no database at all (`DBINE_CLONE_DATABASE`
//!   unset or another one): it clones as with its own database, computed
//!   columns left out of the copy. StarRocks: `CREATE DATABASE IF NOT
//!   EXISTS otra_db; CREATE TABLE otra_db.gc (k INT, m INT, d BIGINT AS
//!   (m * 2)) DUPLICATE KEY(k) DISTRIBUTED BY HASH(k) BUCKETS 1
//!   PROPERTIES('replication_num'='1'); INSERT INTO otra_db.gc (k,m)
//!   VALUES (1,2)` with `DBINE_CLONE_TABLE=otra_db.gc` (also with the
//!   connection's database holding tables with indexes or computed
//!   columns, or one called `gc`). ClickHouse: `otra_ch.plain` with
//!   MATERIALIZED, ALIAS and EPHEMERAL columns, a skip index and a CHECK,
//!   with `DBINE_CLONE_DATABASE=clonev` or unset. A table that isn't
//!   there (`DBINE_CLONE_TABLE=otra_db.nohay`):
//!   `DBINE_CLONE_REFUSED='no se encontró la tabla «nohay»'`.
//!
//! SQL Server cases (IDENTITY after deletes, disabled / untrusted / NOT
//! FOR REPLICATION CHECKs and foreign keys, full-text KEY INDEX):
//!
//! ```sh
//! # setup: IDENTITY(50,10), two rows inserted and deleted (next id 70)
//! DBINE_CLONE_TABLE='ventas odd.vacia borr' \
//! DBINE_CLONE_INSERT='INSERT INTO {table} (n) VALUES (1)' \
//! DBINE_CLONE_AFTER='SELECT COUNT(*) FROM {clone} WHERE id <> 70'
//! # a table with a CHECK and a foreign key NOCHECK (and rows that break
//! # them), an untrusted CHECK, NOT FOR REPLICATION ones: the clone's have
//! # the same states, and take what the original's let in
//! DBINE_CLONE_TABLE='ventas odd.hijo' \
//! DBINE_CLONE_CHECK="WITH s AS (SELECT o.parent_object_id p, o.type,c.is_disabled d, c.is_not_trusted t, c.is_not_for_replication r \
//!   FROM sys.check_constraints c JOIN sys.objects o ON o.object_id = c.object_id UNION ALL SELECT o.parent_object_id, o.type,\
//!   f.is_disabled, f.is_not_trusted, f.is_not_for_replication FROM sys.foreign_keys f JOIN sys.objects o ON o.object_id = f.object_id), \
//!   a AS (SELECT type, d, t, r, COUNT(*) n FROM s WHERE p = OBJECT_ID(N'{source}') GROUP BY type, d, t, r), \
//!   b AS (SELECT type, d, t, r, COUNT(*) n FROM s WHERE p = OBJECT_ID(N'{clone}') GROUP BY type, d, t, r) \
//!   SELECT COUNT(*) FROM ((SELECT * FROM a EXCEPT SELECT * FROM b) UNION ALL (SELECT * FROM b EXCEPT SELECT * FROM a)) x" \
//! DBINE_CLONE_INSERT="INSERT INTO {table} (v, w, p, txt) VALUES (-1, 7, 99, N'x')"
//! # the primary key's clustering, key order and storage options: `CREATE
//! # TABLE [ventas odd].pkopt (id int NOT NULL, k int NOT NULL, CONSTRAINT
//! # PK_pkopt PRIMARY KEY NONCLUSTERED (id DESC) WITH (DATA_COMPRESSION =
//! # ROW, FILLFACTOR = 80), CONSTRAINT UQ_pkopt_k UNIQUE CLUSTERED (k))`
//! # (also a heap's NONCLUSTERED key with PAD_INDEX / IGNORE_DUP_KEY /
//! # ALLOW_*_LOCKS = OFF, and one ON a partition scheme with compression
//! # per partition): the clone's key index is the original's, name aside
//! DBINE_CLONE_TABLE='ventas odd.pkopt' \
//! DBINE_CLONE_CHECK="SELECT CASE WHEN ISNULL(K('{source}'), N'-') = ISNULL(K('{clone}'), N'-') THEN 0 ELSE 1 END"
//! #   where K(t) is: (SELECT CAST(i.type_desc + '|' + CAST(i.fill_factor AS varchar(5)) + '|' + CAST(i.is_padded AS varchar(1))
//! #   + CAST(i.ignore_dup_key AS varchar(1)) + CAST(i.allow_row_locks AS varchar(1)) + CAST(i.allow_page_locks AS varchar(1))
//! #   + '|' + ds.name + '|' + (SELECT c.name + CASE WHEN ic.is_descending_key = 1 THEN ' DESC' ELSE '' END + ','
//! #   FROM sys.index_columns ic JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
//! #   WHERE ic.object_id = i.object_id AND ic.index_id = i.index_id AND ic.key_ordinal > 0 ORDER BY ic.key_ordinal FOR XML PATH(''))
//! #   + '|' + (SELECT p.data_compression_desc + ',' FROM sys.partitions p WHERE p.object_id = i.object_id AND p.index_id = i.index_id
//! #   ORDER BY p.partition_number FOR XML PATH('')) AS nvarchar(4000)) COLLATE Latin1_General_BIN FROM sys.indexes i
//! #   JOIN sys.key_constraints k ON k.parent_object_id = i.object_id AND k.unique_index_id = i.index_id AND k.type = 'PK'
//! #   JOIN sys.data_spaces ds ON ds.data_space_id = i.data_space_id WHERE i.object_id = OBJECT_ID(N't'))
//! #   (each text part COLLATE DATABASE_DEFAULT when the catalog's collations differ)
//! # a full-text index whose KEY INDEX is a UNIQUE constraint the server
//! # named (`CREATE TABLE [ventas odd].ft_uq (id int NOT NULL UNIQUE, …)`):
//! # the clone's is named by the server too, and is its KEY INDEX
//! DBINE_CLONE_TABLE='ventas odd.ft_uq' \
//! DBINE_CLONE_CHECK="SELECT CASE WHEN (SELECT CAST(k.is_system_named AS int) FROM sys.fulltext_indexes f \
//!   JOIN sys.key_constraints k ON k.parent_object_id = f.object_id AND k.unique_index_id = f.unique_index_id \
//!   WHERE f.object_id = OBJECT_ID(N'{clone}')) = 1 THEN 0 ELSE 1 END"
//! # graph tables (`CREATE TABLE [ventas odd].[nodo v4] (id int PRIMARY
//! # KEY, nombre nvarchar(20)) AS NODE`, and an `AS EDGE` one with a
//! # CONNECTION to it): refused before the read, in Spanish
//! DBINE_CLONE_TABLE='ventas odd.nodo v4' DBINE_CLONE_REFUSED='tabla de grafo de nodos (AS NODE)'
//! DBINE_CLONE_TABLE='ventas odd.arista v4' DBINE_CLONE_REFUSED='tabla de grafo de aristas (AS EDGE)'
//! # a temporal table whose history is in another schema (`HISTORY_TABLE =
//! # [hist ñ].[tv3 hist]`) with an index added to it (`CREATE INDEX
//! # IX_tv3_hist_extra ON [hist ñ].[tv3 hist] (code) WITH (DATA_COMPRESSION
//! # = ROW)`): the clone's history is `[hist ñ].[tv3 c hist]`, with that
//! # index (the harness drops the clone with its history)
//! DBINE_CLONE_TABLE='ventas odd.tv3' DBINE_CLONE_NAME='tv3 c'
//! ```
//!
//! The same, self-contained: `sql_server_primary_key_options_and_server_named_uniques`
//! in `clone_table_sqlserver.rs`.
//!
//! Oracle case (CHECKs DISABLE / ENABLE NOVALIDATE / DEFERRABLE, a
//! foreign key DISABLE with an orphan row, a unique constraint DEFERRABLE,
//! a primary key USING INDEX of its own name): the clone's constraints have
//! the original's states and the key's index its renamed name, and take
//! what the original's let in:
//!
//! ```sh
//! DBINE_CLONE_SETUP="BEGIN FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN ('CLONV_ST', 'CLONV_ST_C')) LOOP \
//!   EXECUTE IMMEDIATE 'DROP TABLE \"' || t.table_name || '\" CASCADE CONSTRAINTS PURGE'; END LOOP; END;
//! /
//! CREATE TABLE CLONV_ST (id NUMBER, v NUMBER, p NUMBER, u NUMBER, CONSTRAINT CK_POS CHECK (v > 0) DISABLE, \
//!   CONSTRAINT CK_SMALL CHECK (v < 100) DISABLE, CONSTRAINT CK_CLONV_ST_ID CHECK (id IS NOT NULL) DEFERRABLE INITIALLY DEFERRED, \
//!   CONSTRAINT UQ_CLONV_ST_U UNIQUE (u) DEFERRABLE INITIALLY DEFERRED);
//! CREATE UNIQUE INDEX UXI_CLONV_ST ON CLONV_ST (id);
//! ALTER TABLE CLONV_ST ADD CONSTRAINT PK_CLONV_ST PRIMARY KEY (id) USING INDEX UXI_CLONV_ST;
//! ALTER TABLE CLONV_ST ADD CONSTRAINT FK_CLONV_ST_P FOREIGN KEY (p) REFERENCES CLONV_ST (id) DISABLE;
//! INSERT INTO CLONV_ST VALUES (1, -5, NULL, 1);
//! INSERT INTO CLONV_ST VALUES (2, 500, 999, 2);
//! ALTER TABLE CLONV_ST MODIFY CONSTRAINT CK_SMALL ENABLE NOVALIDATE;
//! COMMIT" \
//! DBINE_CLONE_TABLE=DBINE.CLONV_ST DBINE_CLONE_NAME=CLONV_ST_C \
//! DBINE_CLONE_CHECK="SELECT COUNT(*) FROM ((SELECT constraint_type, status, validated, deferrable, deferred, rely, generated, COUNT(*) n \
//!   FROM user_constraints WHERE table_name = 'CLONV_ST' GROUP BY constraint_type, status, validated, deferrable, deferred, rely, generated \
//!   MINUS SELECT constraint_type, status, validated, deferrable, deferred, rely, generated, COUNT(*) FROM user_constraints \
//!   WHERE table_name = 'CLONV_ST_C' GROUP BY constraint_type, status, validated, deferrable, deferred, rely, generated) \
//!   UNION ALL (SELECT … 'CLONV_ST_C' … MINUS SELECT … 'CLONV_ST' …) \
//!   UNION ALL SELECT 'X', NULL, NULL, NULL, NULL, NULL, NULL, 0 FROM dual WHERE NOT EXISTS (SELECT 1 FROM user_constraints \
//!   WHERE table_name = 'CLONV_ST_C' AND constraint_name = 'PK_CLONV_ST_C' AND index_name = 'UXI_CLONV_ST_C'))" \
//! DBINE_CLONE_INSERT='INSERT INTO {table} (id, v, p, u) VALUES (3, -7, 12345, 3)' \
//! DBINE_CLONE_AFTER='SELECT COUNT(*) - 1 FROM {clone} WHERE id = 3'
//! ```
//!
//! Oracle storage and server-named constraints. Each table `T` cloned
//! as `T_C` with `DBINE_CLONE_CHECK` comparing both in the catalog: the
//! constraints (`constraint_type, status, validated, deferrable, deferred,
//! rely, generated` and their index's `generated`), and the table
//! (`iot_type, partitioned, row_movement`, partition count, partitioned
//! indexes), `(A MINUS B) + (B MINUS A)` = 0:
//!
//! ```sh
//! # Unique constraints named by the server (enabled and DISABLE) stay so.
//! CREATE TABLE FX3_A1 (id NUMBER PRIMARY KEY, u NUMBER UNIQUE, v NUMBER CHECK (v > 0), w NUMBER, CONSTRAINT UQ_FX3_A1_W UNIQUE (w));
//! CREATE TABLE FX3_DIS (id NUMBER PRIMARY KEY, u NUMBER, UNIQUE (u) DISABLE);   -- rows (1,5), (2,5)
//! # Index-organized (PCTTHRESHOLD, COMPRESS carried) and partitioned
//! # (RANGE / LIST / HASH, LOCAL indexes, ROW MOVEMENT) come out the same.
//! CREATE TABLE FX3_A2 (id NUMBER, v VARCHAR2(10), CONSTRAINT PK_FX3_A2 PRIMARY KEY (id)) ORGANIZATION INDEX;
//! CREATE TABLE FX3_A2C (id NUMBER, k NUMBER, v VARCHAR2(10), CONSTRAINT PK_FX3_A2C PRIMARY KEY (id, k)) ORGANIZATION INDEX COMPRESS 1 PCTTHRESHOLD 30;
//! CREATE TABLE FX3_A3 (id NUMBER, d DATE, CONSTRAINT PK_FX3_A3 PRIMARY KEY (id)) PARTITION BY RANGE (d)
//!   (PARTITION P1 VALUES LESS THAN (DATE '2024-01-01'), PARTITION P2 VALUES LESS THAN (MAXVALUE)) ENABLE ROW MOVEMENT;
//! CREATE INDEX IX_FX3_A3_D ON FX3_A3 (d) LOCAL;
//! CREATE TABLE FX3_A4 (id NUMBER PRIMARY KEY, r VARCHAR2(5)) PARTITION BY LIST (r) (PARTITION PN VALUES ('N', 'NE'), PARTITION PD VALUES (DEFAULT));
//! CREATE TABLE FX3_A5 (id NUMBER PRIMARY KEY) PARTITION BY HASH (id) PARTITIONS 4;
//! # Refused up front (DBINE_CLONE_REFUSED='no se puede clonar'): INTERVAL,
//! # composite partitioning, an IOT with OVERFLOW.
//! CREATE TABLE FX3_A6 (id NUMBER PRIMARY KEY, d DATE) PARTITION BY RANGE (d) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH')) (PARTITION P0 VALUES LESS THAN (DATE '2024-01-01'));
//! CREATE TABLE FX3_A7 (id NUMBER, v VARCHAR2(10), big VARCHAR2(4000), CONSTRAINT PK_FX3_A7 PRIMARY KEY (id)) ORGANIZATION INDEX INCLUDING v OVERFLOW;
//! CREATE TABLE FX3_A8 (id NUMBER PRIMARY KEY, d DATE) PARTITION BY RANGE (d) SUBPARTITION BY HASH (id) SUBPARTITIONS 2 (PARTITION P1 VALUES LESS THAN (MAXVALUE));
//! ```
//!
//! SQLite, libSQL, DuckDB and Firebird cases (a column qualified with the
//! table's name; Firebird's index and constraint names, unique per
//! database, already taken by another table's):
//!
//! ```sh
//! # SQLite / libSQL (DuckDB alike, without WITHOUT ROWID): the clone's
//! # CHECK and partial index name the clone
//! DBINE_CLONE_SETUP="DROP TABLE IF EXISTS tq; CREATE TABLE tq (k TEXT PRIMARY KEY, v INT, CHECK (tq.v >= 0)) WITHOUT ROWID; \
//!   CREATE INDEX ix_tq_v ON tq (v) WHERE tq.v > 1; INSERT INTO tq VALUES ('a', 1), ('b', 5)" \
//! DBINE_CLONE_TABLE=tq DBINE_CLONE_NAME=tq2 \
//! DBINE_CLONE_CHECK="SELECT (SELECT count(*) FROM sqlite_master WHERE name = 'tq2' AND sql LIKE '%\"tq2\".v >= 0%') \
//!   + (SELECT count(*) FROM sqlite_master WHERE name = 'ix_tq2_v' AND sql LIKE '%WHERE \"tq2\".v > 1%') - 2"
//! # SQLite / libSQL: a name starting with sqlite_ (any case) is the
//! # engine's: refused up front
//! DBINE_CLONE_SETUP="CREATE TABLE IF NOT EXISTS g (id INTEGER PRIMARY KEY AUTOINCREMENT, a INT)" \
//! DBINE_CLONE_TABLE=g DBINE_CLONE_NAME=SQLITE_sequence DBINE_CLONE_REFUSED='empiezan con «sqlite_»'
//! # DuckDB: a nextval default and a `"` in the new name: the clone's
//! # sequence gets none (sq_a_b), the original's doesn't move
//! DBINE_CLONE_SETUP="CREATE SEQUENCE sq_g; CREATE TABLE g (id INT PRIMARY KEY DEFAULT nextval('sq_g'), a INT, \
//!   b INT GENERATED ALWAYS AS (a * 2) VIRTUAL, CONSTRAINT ck_g CHECK (g.a > 0 AND a < 100)); CREATE INDEX ix_g_a ON g (a); \
//!   INSERT INTO g (a) VALUES (1), (2)" \
//! DBINE_CLONE_TABLE=g DBINE_CLONE_NAME='a"b' \
//! DBINE_CLONE_CHECK="SELECT (SELECT count(*) FROM duckdb_sequences() WHERE sequence_name = 'sq_a_b') \
//!   + (SELECT count(*) FROM duckdb_indexes() WHERE index_name = 'ix_a\"b_a') \
//!   + (SELECT count(*) FROM duckdb_constraints() WHERE table_name = 'a\"b' AND constraint_type = 'CHECK') - 3" \
//! DBINE_CLONE_INSERT='INSERT INTO {table} (a) VALUES (5)' \
//! DBINE_CLONE_AFTER="SELECT (SELECT count(*) FROM {clone} WHERE id = 3 AND b = 10) + (SELECT currval('sq_g')) - 3"
//! # Firebird: CHECK, computed column, expression and partial indexes
//! # qualified with the table's name
//! DBINE_CLONE_SETUP="CREATE TABLE ADV4 (ID INTEGER NOT NULL PRIMARY KEY, V INTEGER, D COMPUTED BY (ADV4.V * 2), \
//!   CONSTRAINT CK_ADV4_V CHECK (ADV4.V >= 0)); CREATE INDEX IX_ADV4_E ON ADV4 COMPUTED BY (ADV4.V + 1); \
//!   CREATE INDEX IX_ADV4_P ON ADV4 (ID) WHERE ADV4.V > 5; INSERT INTO ADV4 (ID, V) VALUES (1, 5)" \
//! DBINE_CLONE_TABLE=ADV4 DBINE_CLONE_NAME=ADV4_C DBINE_CLONE_INSERT='INSERT INTO {table} (ID, V) VALUES (3, 9)'
//! # Firebird: CK_ADV3_C_V and IX_ADV3_C_V belong to another table; the
//! # clone's get other names
//! DBINE_CLONE_SETUP="CREATE TABLE ADV3 (ID INTEGER NOT NULL PRIMARY KEY, V INTEGER, CONSTRAINT CK_ADV3_V CHECK (V > 0)); \
//!   CREATE INDEX IX_ADV3_V ON ADV3 (V); CREATE TABLE ADV3_OTHER (A INTEGER, C_V INTEGER, CONSTRAINT CK_ADV3_C_V CHECK (C_V > 0)); \
//!   CREATE INDEX IX_ADV3_C_V ON ADV3_OTHER (C_V); INSERT INTO ADV3 VALUES (1, 5)" \
//! DBINE_CLONE_TABLE=ADV3 DBINE_CLONE_NAME=ADV3_C DBINE_CLONE_INSERT='INSERT INTO {table} (ID, V) VALUES (3, 9)' \
//! DBINE_CLONE_CHECK="SELECT COUNT(*) FROM RDB\$RELATION_CONSTRAINTS WHERE RDB\$RELATION_NAME = 'ADV3_C' \
//!   AND RDB\$CONSTRAINT_TYPE = 'CHECK' AND RDB\$CONSTRAINT_NAME NOT STARTING WITH 'CK_ADV3_C_V_'"
//! ```
//!
//! On engines whose clone is checked by its definition (StarRocks, Doris,
//! ClickHouse, GreptimeDB, Trino), the original's and the clone's must
//! match (partitions, distribution, key model, engine settings…). The
//! columns the engine computes or numbers come from `engine_columns`
//! (StarRocks' AUTO_INCREMENT and generated columns, ClickHouse's
//! MATERIALIZED / ALIAS / EPHEMERAL), so the insert is tried there too.
//! The stored ones (MATERIALIZED) are compared: the clone keeps their
//! values.

use dbine_driver::transfer::{BatchSink, BatchSinkRef, Cell, RowBatch, TransferColumn};
use dbine_driver::{ConnectionConfig, DdlParts, ObjectRef, QueryOutcome, ReadSpec, Session, TableSchema};
use dbine_transfer::clone_table::{
    clone_table, default_clone_name_for, definition_differences, engine_columns, quoted_name, CloneControl, CloneEvent, CloneOptions, CloneRequest, ConfigEndpoints,
};
use dbine_transfer::Endpoints;
use std::sync::{Arc, Mutex};

/// Drops the clone when a check after it panics (a failed run never leaves
/// it behind); the run that ends well drops it itself.
struct DropOnPanic {
    endpoints: Arc<ConfigEndpoints>,
    sql: String,
}

impl Drop for DropOnPanic {
    fn drop(&mut self) {
        if !std::thread::panicking() {
            return;
        }
        let (endpoints, sql) = (self.endpoints.clone(), self.sql.clone());
        tokio::task::block_in_place(|| {
            tokio::runtime::Handle::current().block_on(async move {
                let mut out = QueryOutcome::default();
                match endpoints.open_target().await {
                    Ok(mut s) => match s.execute(&sql, 0, &mut out).await {
                        Ok(()) if out.error.is_none() => eprintln!("clon borrado tras el fallo"),
                        r => eprintln!("no se pudo borrar el clon: {:?} {:?}", r.err(), out.error),
                    },
                    Err(e) => eprintln!("no se pudo borrar el clon: {e}"),
                }
            })
        });
    }
}

fn env(k: &str) -> Option<String> {
    std::env::var(k).ok().filter(|v| !v.trim().is_empty())
}

#[derive(Default)]
struct Collect {
    rows: Vec<Vec<Cell>>,
}

impl BatchSink for Collect {
    fn begin(&mut self, _: &[TransferColumn]) -> std::io::Result<()> {
        Ok(())
    }
    fn batch(&mut self, b: RowBatch) -> std::io::Result<()> {
        self.rows.extend(b.rows);
        Ok(())
    }
}

async fn read_all(s: &mut dyn Session, table: &ObjectRef, columns: &[String]) -> Vec<String> {
    let sink = Arc::new(Mutex::new(Collect::default()));
    let dyn_sink: BatchSinkRef = sink.clone();
    s.read_batches(&ReadSpec { table: table.clone(), columns: Some(columns.to_vec()), filter: None }, dyn_sink).await.unwrap();
    let mut rows: Vec<String> = sink.lock().unwrap().rows.iter().map(|r| format!("{r:?}")).collect();
    rows.sort();
    rows
}

async fn run(s: &mut dyn Session, sql: &str) {
    let mut out = QueryOutcome::default();
    s.execute(sql, 0, &mut out).await.unwrap_or_else(|e| panic!("{sql}: {e}"));
    if let Some(e) = out.error {
        panic!("{sql}: {e}");
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "needs a live server: see the top of the file"]
async fn clone_on_a_live_server() {
    let id = env("DBINE_CLONE_DRIVER").expect("DBINE_CLONE_DRIVER");
    let driver = dbine_drivers::find(&id).unwrap_or_else(|| panic!("no driver '{id}'")).clone();
    let mut json: serde_json::Value = serde_json::from_str(&env("DBINE_CLONE_CONFIG").unwrap_or_else(|| "{}".into())).expect("DBINE_CLONE_CONFIG");
    json.as_object_mut().expect("config object").entry("driver").or_insert(serde_json::json!(id));
    let config: ConnectionConfig = serde_json::from_value(json).expect("ConnectionConfig");
    let (schema, name) = match env("DBINE_CLONE_TABLE").expect("DBINE_CLONE_TABLE").split_once('.') {
        Some((s, n)) => (Some(s.to_string()), n.to_string()),
        None => (None, env("DBINE_CLONE_TABLE").unwrap()),
    };
    let kind = env("DBINE_CLONE_KIND").unwrap_or_else(|| "table".into());
    let source = ObjectRef { kind: kind.clone(), schema: schema.clone(), name: name.clone() };
    let endpoints = Arc::new(ConfigEndpoints { driver: driver.clone(), config, database: env("DBINE_CLONE_DATABASE") });

    let mut w = endpoints.open_target().await.unwrap();
    if let Some(setup) = env("DBINE_CLONE_SETUP") {
        run(&mut *w, &setup).await;
    }

    let new_name = env("DBINE_CLONE_NAME").unwrap_or_else(|| default_clone_name_for(&*driver, &name, chrono::Local::now().naive_local()));
    let req = CloneRequest { source: source.clone(), new_name: new_name.clone(), options: CloneOptions::default() };
    let report = clone_table(endpoints.clone(), req, &CloneControl::default(), |e| match e {
        CloneEvent::Phase { phase } => println!("fase: {phase:?}"),
        CloneEvent::Progress { rows_done, rows_total, .. } => println!("filas: {rows_done} de {rows_total:?}"),
        CloneEvent::Log { level, text } => println!("{level:?}: {text}"),
    })
    .await;
    // A clone that must be refused up front (in Spanish), leaving nothing.
    if let Some(expected) = env("DBINE_CLONE_REFUSED") {
        let e = match report {
            Ok(_) => panic!("the clone «{new_name}» was made; it had to be refused with «{expected}»"),
            Err(e) => e.to_string(),
        };
        assert!(e.contains(&expected), "refused with «{e}», not «{expected}»");
        let left = w.database_schema().await.unwrap().into_iter().any(|t| t.name == new_name && t.schema == schema);
        assert!(!left, "the refused clone «{new_name}» was left behind");
        println!("rechazada: {e}");
        return;
    }
    let report = report.unwrap_or_else(|e| panic!("clone failed: {e}"));
    println!("clonada «{new_name}»: {} filas en {} ms; notas: {:?}; nombres: {:?}", report.rows, report.elapsed_ms, report.notes, report.renames);
    let clone = report.table.clone();
    // InfluxDB 1's driver has no DDL for a measurement: its drop is
    // `DROP MEASUREMENT`, as the clone's own cleanup writes it.
    let drop_sql = match driver.table_ddl(
        &TableSchema { kind: kind.clone(), schema: schema.clone(), name: new_name.clone(), ..Default::default() },
        DdlParts { drop: true, if_exists: true, ..Default::default() },
    ) {
        // The MySQL family's DROP names the table alone: qualified here
        // for a table in another database than the connection's.
        Ok(_) if driver.info().dialect == "mysql" && schema.is_some() => {
            let q = |n: &str| format!("`{}`", n.replace('`', "``"));
            format!("DROP TABLE IF EXISTS {}.{}", q(schema.as_deref().unwrap()), q(&new_name))
        }
        Ok(sql) => sql,
        Err(_) if driver.info().dialect == "influxql" => format!("DROP MEASUREMENT \"{}\"", new_name.replace('\\', "\\\\").replace('"', "\\\"")),
        Err(e) => panic!("no drop for the clone: {e}"),
    };
    // SQL Server: a temporal clone goes with its history table (a
    // versioned table can't be dropped as it is).
    let drop_sql = if driver.info().dialect == "mssql" {
        let q = |n: &str| format!("[{}]", n.replace(']', "]]"));
        let lit = format!("{}.{}", q(schema.as_deref().unwrap_or("dbo")), q(&new_name)).replace('\'', "''");
        format!(
            "IF OBJECTPROPERTY(OBJECT_ID(N'{lit}'), 'TableTemporalType') = 2\nBEGIN\n    \
             DECLARE @h nvarchar(600) = (SELECT QUOTENAME(OBJECT_SCHEMA_NAME(history_table_id)) + N'.' + QUOTENAME(OBJECT_NAME(history_table_id)) FROM sys.tables WHERE object_id = OBJECT_ID(N'{lit}'));\n    \
             EXEC(N'ALTER TABLE {lit} SET (SYSTEM_VERSIONING = OFF)');\n    EXEC(N'DROP TABLE ' + @h);\nEND;\n{drop_sql}"
        )
    } else {
        drop_sql
    };
    let _drop_on_panic = env("DBINE_CLONE_KEEP").is_none().then(|| DropOnPanic { endpoints: endpoints.clone(), sql: drop_sql.clone() });

    // The same table, as the engine describes it.
    if let Some(d) = definition_differences(&*driver, &mut *w, &source, &clone).await.unwrap() {
        panic!("the clone's definition differs: {d}");
    }

    // Same rows, value for value (computed columns left out: recalculated).
    let cols = w.columns(&source).await.unwrap();
    // Some engines (Oracle) report their own schema's tables with none:
    // a name given with that schema is still the same table.
    let tables = w.database_schema().await.unwrap();
    let schema_t = tables
        .iter()
        .find(|t| t.name == name && t.schema == schema)
        .or_else(|| tables.iter().find(|t| t.name == name && t.schema.is_none()))
        .cloned();
    let roles = match &schema_t {
        Some(t) => engine_columns(&*driver, &mut *w, t).await.unwrap(),
        None => Default::default(),
    };
    // Stored computed columns (ClickHouse's MATERIALIZED) must keep the
    // original's values: compared too.
    let skip: Vec<String> = roles.generated.iter().filter(|c| !roles.stored.contains(c)).cloned().collect();
    let names: Vec<String> = cols.iter().map(|c| c.name.clone()).filter(|c| !skip.contains(c)).collect();
    let a = read_all(&mut *w, &source, &names).await;
    let b = read_all(&mut *w, &clone, &names).await;
    assert_eq!(a.len() as u64, report.rows, "rows copied");
    assert_eq!(a.len(), b.len(), "row count");
    assert!(a == b, "the clone's rows differ from the original's");
    println!("{} filas iguales", a.len());
    if let Some(check) = env("DBINE_CLONE_CHECK") {
        let sql = check.replace("{source}", &quoted_name(&*driver, &source)).replace("{clone}", &quoted_name(&*driver, &clone));
        let mut out = QueryOutcome::default();
        w.execute(&sql, 1, &mut out).await.unwrap_or_else(|e| panic!("{sql}: {e}"));
        let n = out.results.iter().rev().find_map(|r| r.rows.first()).and_then(|r| r.first()).cloned().unwrap_or_default();
        assert!(n == serde_json::json!(0) || n == serde_json::json!("0"), "DBINE_CLONE_CHECK: {n} (expected 0)");
        println!("comprobación en el servidor: bien");
    }

    // One more row in the clone.
    // Rows the clone gains with it.
    let mut gained = 1;
    let insert = match env("DBINE_CLONE_INSERT") {
        Some(sql) => Some(sql.replace("{table}", &quoted_name(&*driver, &clone))),
        None => {
            let auto: Vec<String> = roles.auto_increment.clone();
            let keep: Vec<usize> = (0..names.len()).filter(|i| !auto.contains(&names[*i]) && !roles.stored.contains(&names[*i])).collect();
            if auto.is_empty() {
                println!("sin columna autoincremental ni DBINE_CLONE_INSERT: no se prueba la inserción");
                None
            } else {
                let sink = Arc::new(Mutex::new(Collect::default()));
                let dyn_sink: BatchSinkRef = sink.clone();
                w.read_batches(&ReadSpec { table: source.clone(), columns: Some(names.clone()), filter: None }, dyn_sink).await.unwrap();
                let first = sink.lock().unwrap().rows.first().cloned();
                let pk: Vec<usize> = (0..names.len()).filter(|i| cols.iter().any(|c| c.primary_key && c.name == names[*i])).collect();
                first.map(|r| {
                    let columns: Vec<String> = keep.iter().map(|i| names[*i].clone()).collect();
                    let values: Vec<serde_json::Value> = keep.iter().map(|i| r[*i].to_json()).collect();
                    let insert = driver.insert_script(&clone, &columns, &[values]).unwrap();
                    if driver.info().language != dbine_driver::Language::Sql || pk.is_empty() {
                        return insert;
                    }
                    // `DELETE FROM <clone> WHERE <key>`, then the same row from
                    // the original with `INSERT INTO <clone> (<cols>) SELECT <cols>
                    // FROM <original> WHERE <key>` (names quoted by the driver).
                    let key: Vec<(String, serde_json::Value)> = pk.iter().map(|i| (names[*i].clone(), r[*i].to_json())).collect();
                    let delete = driver.delete_script(&clone, &[key.clone()]).unwrap();
                    let from_original = driver.delete_script(&source, &[key]).unwrap();
                    let (src_name, filter) = from_original.trim().trim_end_matches(';').trim_start_matches("DELETE FROM ").split_once(" WHERE ").unwrap();
                    let head = &insert[..insert.find(" VALUES").unwrap()];
                    let list = &head[head.find('(').unwrap()..];
                    gained = 0;
                    format!("{};\n{head} SELECT {} FROM {src_name} WHERE {filter};", delete.trim().trim_end_matches(';'), &list[1..list.len() - 1])
                })
            }
        }
    };
    if let Some(sql) = insert {
        run(&mut *w, &sql).await;
        let after = read_all(&mut *w, &clone, &names).await;
        assert_eq!(after.len(), b.len() + gained, "the insert into the clone");
        println!("inserción en el clon: bien");
    }
    if let Some(check) = env("DBINE_CLONE_AFTER") {
        let sql = check.replace("{source}", &quoted_name(&*driver, &source)).replace("{clone}", &quoted_name(&*driver, &clone));
        let mut out = QueryOutcome::default();
        w.execute(&sql, 1, &mut out).await.unwrap_or_else(|e| panic!("{sql}: {e}"));
        assert!(out.error.is_none(), "DBINE_CLONE_AFTER: {:?}", out.error);
        let n = out.results.iter().rev().find_map(|r| r.rows.first()).and_then(|r| r.first()).cloned().unwrap_or_default();
        assert!(n == serde_json::json!(0) || n == serde_json::json!("0"), "DBINE_CLONE_AFTER: {n} (expected 0)");
        println!("comprobación después de la inserción: bien");
    }

    if env("DBINE_CLONE_KEEP").is_none() {
        run(&mut *w, &drop_sql).await;
    }
}
