//! "Clonar tabla" on Firebird, against a live server: the identity's kind
//! (`ALWAYS` / `BY DEFAULT`), `START WITH`, `INCREMENT BY` and counter
//! come along, with rows and with every row deleted.
//!
//! Ignored by default:
//!
//! ```sh
//! docker start dbine-test-firebird   # -p 25602:3050, user dbine/dbine, test.fdb
//! cargo test -p dbine-transfer --test clone_table_firebird -- --ignored --nocapture --test-threads=1
//! ```
//!
//! `DBINE_TEST_FIREBIRD_URL` overrides the server (default
//! `firebird://dbine:dbine@localhost:25602//var/lib/firebird/data/test.fdb`).

use dbine_driver::{ConnectionConfig, ObjectRef, QueryOutcome, Session};
use dbine_transfer::clone_table::{clone_table, CloneControl, CloneOptions, CloneRequest, ConfigEndpoints};
use dbine_transfer::Endpoints;
use serde_json::Value;
use std::sync::Arc;

fn endpoints() -> Arc<ConfigEndpoints> {
    let url = std::env::var("DBINE_TEST_FIREBIRD_URL")
        .unwrap_or_else(|_| "firebird://dbine:dbine@localhost:25602//var/lib/firebird/data/test.fdb".into());
    let rest = url.strip_prefix("firebird://").expect("firebird://user:pass@host:port/path");
    let (cred, addr) = rest.split_once('@').unwrap();
    let (user, pass) = cred.split_once(':').unwrap();
    let (hostport, path) = addr.split_once('/').unwrap();
    let (host, port) = hostport.split_once(':').unwrap();
    let config = ConnectionConfig {
        driver: "firebird".into(),
        host: host.into(),
        port: port.parse().unwrap(),
        database: path.into(),
        username: Some(user.into()),
        password: Some(pass.into()),
        ..Default::default()
    };
    let driver = dbine_drivers::find("firebird").expect("firebird driver").clone();
    Arc::new(ConfigEndpoints { driver, config, database: None })
}

async fn query(s: &mut dyn Session, sql: &str) -> Result<Vec<Vec<Value>>, String> {
    let mut out = QueryOutcome::default();
    s.execute(sql, 1000, &mut out).await.map_err(|e| e.to_string())?;
    if let Some(e) = out.error {
        return Err(e);
    }
    Ok(out.results.into_iter().rev().find(|r| !r.columns.is_empty()).map(|r| r.rows).unwrap_or_default())
}

async fn run(s: &mut dyn Session, sql: &str) {
    query(s, sql).await.unwrap_or_else(|e| panic!("{sql}: {e}"));
}

async fn int(s: &mut dyn Session, sql: &str) -> i64 {
    let rows = query(s, sql).await.unwrap_or_else(|e| panic!("{sql}: {e}"));
    match rows.first().and_then(|r| r.first()) {
        Some(Value::Number(n)) => n.as_i64().unwrap(),
        Some(Value::String(v)) => v.trim().parse().unwrap(),
        v => panic!("{sql}: {v:?}"),
    }
}

async fn drop_table(s: &mut dyn Session, name: &str) {
    let _ = query(s, &format!("DROP TABLE \"{name}\"")).await;
}

/// (identity type, START WITH, INCREMENT BY) of the table's `ID`.
async fn identity(s: &mut dyn Session, table: &str) -> (i64, i64, i64) {
    let w = format!(
        "FROM RDB$RELATION_FIELDS rf JOIN RDB$GENERATORS g ON g.RDB$GENERATOR_NAME = rf.RDB$GENERATOR_NAME WHERE rf.RDB$RELATION_NAME = '{table}' AND rf.RDB$FIELD_NAME = 'ID'"
    );
    (
        int(s, &format!("SELECT rf.RDB$IDENTITY_TYPE {w}")).await,
        int(s, &format!("SELECT g.RDB$INITIAL_VALUE {w}")).await,
        int(s, &format!("SELECT g.RDB$GENERATOR_INCREMENT {w}")).await,
    )
}

/// The id the next insert gets (every identity here goes up).
async fn next_id(s: &mut dyn Session, table: &str) -> i64 {
    run(s, &format!("INSERT INTO \"{table}\" (V) VALUES (0)")).await;
    int(s, &format!("SELECT MAX(ID) FROM \"{table}\"")).await
}

async fn clone(src: &str, new_name: &str) -> Result<u64, String> {
    let req = CloneRequest {
        source: ObjectRef { kind: "table".into(), schema: None, name: src.into() },
        new_name: new_name.into(),
        options: CloneOptions { with_data: true, with_indexes: true },
    };
    clone_table(endpoints(), req, &CloneControl::default(), |e| println!("{e:?}")).await.map(|r| r.rows).map_err(|e| e.to_string())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "needs a live Firebird: see the top of the file"]
async fn identity_kind_options_and_counter() {
    let mut s = endpoints().open_target().await.expect("connect");
    let s = &mut *s;
    let tables = ["CLONFB_ALW", "CLONFB_ALW_C", "CLONFB_DEF", "CLONFB_DEF_C", "CLONFB_EMP", "CLONFB_EMP_C"];
    for t in tables {
        drop_table(s, t).await;
    }
    // ALWAYS, START WITH 100, INCREMENT BY 3, with rows: 100, 103, 106.
    run(s, "CREATE TABLE CLONFB_ALW (ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 100 INCREMENT BY 3) NOT NULL PRIMARY KEY, V INTEGER)").await;
    // BY DEFAULT, START WITH 100, INCREMENT BY 3, rows deleted: nothing
    // copied, the counter past 106 anyway.
    run(s, "CREATE TABLE CLONFB_DEF (ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 3) NOT NULL, V INTEGER)").await;
    // Never used: the clone's first id is the original's.
    run(s, "CREATE TABLE CLONFB_EMP (ID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 50) NOT NULL, V INTEGER)").await;
    for _ in 0..3 {
        run(s, "INSERT INTO CLONFB_ALW (V) VALUES (1)").await;
        run(s, "INSERT INTO CLONFB_DEF (V) VALUES (1)").await;
    }
    run(s, "DELETE FROM CLONFB_DEF").await;

    let result = async {
        assert_eq!(clone("CLONFB_ALW", "CLONFB_ALW_C").await.unwrap(), 3);
        assert_eq!(identity(s, "CLONFB_ALW_C").await, identity(s, "CLONFB_ALW").await);
        assert_eq!(identity(s, "CLONFB_ALW_C").await, (0, 100, 3));
        // ALWAYS: an explicit id is refused on both.
        assert!(query(s, "INSERT INTO CLONFB_ALW_C (ID, V) VALUES (999, 1)").await.is_err());
        assert_eq!(next_id(s, "CLONFB_ALW_C").await, next_id(s, "CLONFB_ALW").await);

        assert_eq!(clone("CLONFB_DEF", "CLONFB_DEF_C").await.unwrap(), 0);
        assert_eq!(identity(s, "CLONFB_DEF_C").await, identity(s, "CLONFB_DEF").await);
        assert_eq!(identity(s, "CLONFB_DEF_C").await, (1, 100, 3));
        let (a, b) = (next_id(s, "CLONFB_DEF").await, next_id(s, "CLONFB_DEF_C").await);
        assert_eq!((a, b), (109, 109));

        assert_eq!(clone("CLONFB_EMP", "CLONFB_EMP_C").await.unwrap(), 0);
        assert_eq!(identity(s, "CLONFB_EMP_C").await, identity(s, "CLONFB_EMP").await);
        assert_eq!(next_id(s, "CLONFB_EMP_C").await, next_id(s, "CLONFB_EMP").await);
    };
    let outcome = futures::FutureExt::catch_unwind(std::panic::AssertUnwindSafe(result)).await;
    for t in tables {
        drop_table(s, t).await;
    }
    if let Err(p) = outcome {
        std::panic::resume_unwind(p);
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "needs a live Firebird: see the top of the file"]
async fn identity_counters_past_2_53_and_at_bigint_limit() {
    let mut s = endpoints().open_target().await.expect("connect");
    let s = &mut *s;
    let tables = ["CLONFB_BIG", "CLONFB_BIG_C", "CLONFB_LIM", "CLONFB_LIM_C", "CLONFB_END", "CLONFB_END_C"];
    for t in tables {
        drop_table(s, t).await;
    }
    // Past 2^53: the driver gives these as text; never rounded through f64.
    run(s, "CREATE TABLE CLONFB_BIG (ID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 9007199254740993) NOT NULL PRIMARY KEY, V INTEGER)").await;
    // Near BIGINT's end, the next id still fits.
    run(s, "CREATE TABLE CLONFB_LIM (ID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 9223372036854775700 INCREMENT BY 100) NOT NULL, V INTEGER)").await;
    // The next id would be past BIGINT: refused up front, in Spanish.
    run(s, "CREATE TABLE CLONFB_END (ID BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 9223372036854775800 INCREMENT BY 100) NOT NULL, V INTEGER)").await;
    for t in ["CLONFB_BIG", "CLONFB_LIM", "CLONFB_END"] {
        run(s, &format!("INSERT INTO {t} (V) VALUES (1)")).await;
    }

    let result = async {
        assert_eq!(clone("CLONFB_BIG", "CLONFB_BIG_C").await.unwrap(), 1);
        let (a, b) = (next_id(s, "CLONFB_BIG").await, next_id(s, "CLONFB_BIG_C").await);
        assert_eq!((a, b), (9007199254740994, 9007199254740994));

        assert_eq!(clone("CLONFB_LIM", "CLONFB_LIM_C").await.unwrap(), 1);
        let (a, b) = (next_id(s, "CLONFB_LIM").await, next_id(s, "CLONFB_LIM_C").await);
        assert_eq!((a, b), (9223372036854775800, 9223372036854775800));

        let e = clone("CLONFB_END", "CLONFB_END_C").await.unwrap_err();
        assert!(e.contains("límite de BIGINT"), "{e}");
        assert!(query(s, "SELECT 1 FROM CLONFB_END_C").await.is_err(), "nothing left behind");
    };
    let outcome = futures::FutureExt::catch_unwind(std::panic::AssertUnwindSafe(result)).await;
    for t in tables {
        drop_table(s, t).await;
    }
    if let Err(p) = outcome {
        std::panic::resume_unwind(p);
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "needs a live Firebird: see the top of the file"]
async fn checks_and_index_kinds_come_along_renamed() {
    let mut s = endpoints().open_target().await.expect("connect");
    let s = &mut *s;
    let tables = ["CLONFB_STR", "CLONFB_STR_C"];
    for t in tables {
        drop_table(s, t).await;
    }
    run(s, "CREATE TABLE CLONFB_STR (ID INTEGER NOT NULL PRIMARY KEY, V INTEGER, N VARCHAR(20), CONSTRAINT CK_CLONFB_STR_V CHECK (V >= 0), CHECK (N <> ''))").await;
    run(s, "CREATE DESCENDING INDEX IX_CLONFB_STR_V ON CLONFB_STR (V)").await;
    run(s, "CREATE INDEX IX_CLONFB_STR_UP ON CLONFB_STR COMPUTED BY (UPPER(N))").await;
    run(s, "CREATE UNIQUE INDEX UX_CLONFB_STR_N ON CLONFB_STR (N)").await;
    run(s, "CREATE INDEX IX_CLONFB_STR_OFF ON CLONFB_STR (N, V)").await;
    run(s, "ALTER INDEX IX_CLONFB_STR_OFF INACTIVE").await;
    // Partial indexes: Firebird 5 on.
    let partial = query(s, "CREATE INDEX IX_CLONFB_STR_P ON CLONFB_STR (V) WHERE V > 10").await.is_ok();
    run(s, "INSERT INTO CLONFB_STR VALUES (1, 5, 'a')").await;

    let result = async {
        assert_eq!(clone("CLONFB_STR", "CLONFB_STR_C").await.unwrap(), 1);
        let all = s.database_schema().await.unwrap();
        let get = |n: &str| all.iter().find(|t| t.name == n).cloned().unwrap();
        let (o, c) = (get("CLONFB_STR"), get("CLONFB_STR_C"));
        // CHECKs: same conditions; the named one renamed (names are the
        // database's in Firebird).
        let expr = |t: &dbine_driver::TableSchema| {
            let mut v: Vec<String> = t.checks.iter().map(|c| c.expression.clone()).collect();
            v.sort();
            v
        };
        assert_eq!(expr(&c), expr(&o));
        assert!(c.checks.iter().any(|k| k.name.as_deref() == Some("CK_CLONFB_STR_C_V")), "{:?}", c.checks);
        // Indexes: same kind (DESC, COMPUTED), uniqueness, filter and
        // options (INACTIVE), each under its renamed name.
        let key = |t: &dbine_driver::TableSchema| {
            let mut v: Vec<_> = t.indexes.iter().map(|i| (i.columns.clone(), i.unique, i.kind.clone(), i.filter.clone(), i.options.clone())).collect();
            v.sort_by(|a, b| format!("{a:?}").cmp(&format!("{b:?}")));
            v
        };
        assert_eq!(key(&c), key(&o));
        let names: Vec<&str> = c.indexes.iter().map(|i| i.name.as_str()).collect();
        for n in ["IX_CLONFB_STR_C_V", "IX_CLONFB_STR_C_UP", "UX_CLONFB_STR_C_N", "IX_CLONFB_STR_C_OFF"] {
            assert!(names.contains(&n), "{names:?}");
        }
        if partial {
            assert!(names.contains(&"IX_CLONFB_STR_C_P"), "{names:?}");
        }
        assert!(query(s, "INSERT INTO CLONFB_STR_C VALUES (2, -1, 'b')").await.is_err(), "the check came along");
    };
    let outcome = futures::FutureExt::catch_unwind(std::panic::AssertUnwindSafe(result)).await;
    for t in tables.iter().rev() {
        drop_table(s, t).await;
    }
    if let Err(p) = outcome {
        std::panic::resume_unwind(p);
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
#[ignore = "needs a live Firebird: see the top of the file"]
async fn checks_and_computed_columns_reading_the_table_read_the_clone() {
    let mut s = endpoints().open_target().await.expect("connect");
    let s = &mut *s;
    let tables = ["CLONFB_SU", "CLONFB_SU_C", "CLONFB_SC", "CLONFB_SC_C"];
    for t in tables {
        drop_table(s, t).await;
    }
    run(s, "CREATE TABLE CLONFB_SU (ID INTEGER NOT NULL PRIMARY KEY, A INTEGER, CONSTRAINT CK_CLONFB_SU_U CHECK (NOT EXISTS (SELECT 1 FROM CLONFB_SU X WHERE X.A = CLONFB_SU.A AND X.ID <> CLONFB_SU.ID)))").await;
    run(s, "INSERT INTO CLONFB_SU VALUES (1, 10)").await;
    run(s, "CREATE TABLE CLONFB_SC (ID INTEGER NOT NULL PRIMARY KEY, P INTEGER, T COMPUTED BY ((SELECT COUNT(*) FROM CLONFB_SC Z WHERE Z.P = CLONFB_SC.ID)), CONSTRAINT FK_CLONFB_SC_P FOREIGN KEY (P) REFERENCES CLONFB_SC (ID))").await;
    run(s, "INSERT INTO CLONFB_SC (ID, P) VALUES (1, NULL)").await;
    run(s, "INSERT INTO CLONFB_SC (ID, P) VALUES (2, 1)").await;

    let result = async {
        let req = |src: &str, to: &str| CloneRequest {
            source: ObjectRef { kind: "table".into(), schema: None, name: src.into() },
            new_name: to.into(),
            options: CloneOptions { with_data: true, with_indexes: true },
        };
        // CHECK with a subquery on the table: in the clone, on the clone.
        let r = clone_table(endpoints(), req("CLONFB_SU", "CLONFB_SU_C"), &CloneControl::default(), |_| {}).await.unwrap();
        assert!(r.notes.iter().any(|n| n.contains("misma tabla")), "{:?}", r.notes);
        run(s, "INSERT INTO CLONFB_SU_C VALUES (4, 99)").await;
        assert!(query(s, "INSERT INTO CLONFB_SU_C VALUES (5, 99)").await.is_err(), "the clone's check reads the clone");
        // Nothing of the clone's in the original's check: 99 is free there.
        run(s, "INSERT INTO CLONFB_SU VALUES (5, 99)").await;
        // A computed column counting the table's rows counts the clone's.
        let r = clone_table(endpoints(), req("CLONFB_SC", "CLONFB_SC_C"), &CloneControl::default(), |_| {}).await.unwrap();
        assert!(r.notes.iter().any(|n| n.contains("columna calculada T")), "{:?}", r.notes);
        run(s, "INSERT INTO CLONFB_SC_C (ID, P) VALUES (3, 2)").await;
        assert_eq!(int(s, "SELECT T FROM CLONFB_SC_C WHERE ID = 2").await, 1);
        assert_eq!(int(s, "SELECT T FROM CLONFB_SC WHERE ID = 2").await, 0);
        // The clone no longer depends on the original.
        run(s, "DROP TABLE CLONFB_SC").await;
        assert_eq!(int(s, "SELECT T FROM CLONFB_SC_C WHERE ID = 1").await, 1);
    };
    let outcome = futures::FutureExt::catch_unwind(std::panic::AssertUnwindSafe(result)).await;
    for t in tables.iter().rev() {
        drop_table(s, t).await;
    }
    if let Err(p) = outcome {
        std::panic::resume_unwind(p);
    }
}
