//! SQL DDL and INSERT scripts from a [`TableSchema`], shaped by a
//! [`SqlFlavor`]. Relational drivers describe their dialect once and get
//! CREATE TABLE / indexes / foreign keys / DROP / INSERT batches; engines
//! with their own syntax (Cassandra, Mongo, Elasticsearch…) write their own.

use crate::schema::{DdlParts, TableSchema};
use crate::sql::{qualified_name, quote_ident, Quote};
use serde_json::Value;

/// How the dialect writes auto-increment columns.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AutoIncrement {
    /// Not supported: the flag is ignored.
    None,
    /// `IDENTITY(1,1)` (SQL Server, Sybase).
    Identity,
    /// `GENERATED BY DEFAULT AS IDENTITY` (PostgreSQL 10+, Oracle 12c+, Db2…).
    GeneratedIdentity,
    /// `AUTO_INCREMENT` (MySQL family).
    AutoIncrementKeyword,
    /// `INTEGER PRIMARY KEY AUTOINCREMENT` (SQLite).
    SqliteAutoincrement,
}

#[derive(Debug, Clone, Copy)]
pub struct SqlFlavor {
    pub quote: Quote,
    pub auto_increment: AutoIncrement,
    /// `COMMENT ON TABLE/COLUMN … IS '…'` statements (PostgreSQL, Oracle…).
    pub comment_on: bool,
    /// Inline `COMMENT '…'` after the column / table (MySQL family).
    pub inline_comments: bool,
    /// `DROP TABLE IF EXISTS` / `CREATE TABLE IF NOT EXISTS` / `CREATE INDEX IF NOT EXISTS`.
    pub if_exists: bool,
    /// Foreign keys go inside CREATE TABLE (engines without `ALTER TABLE ADD
    /// CONSTRAINT`, like SQLite) instead of separate ALTERs.
    pub fk_inline: bool,
    /// `INSERT … VALUES (…), (…)` with several rows (else one per row).
    pub multi_row_insert: bool,
    /// Literals for booleans.
    pub true_literal: &'static str,
    pub false_literal: &'static str,
}

impl SqlFlavor {
    pub const fn ansi() -> Self {
        Self {
            quote: Quote::Double,
            auto_increment: AutoIncrement::GeneratedIdentity,
            comment_on: true,
            inline_comments: false,
            if_exists: true,
            fk_inline: false,
            multi_row_insert: true,
            true_literal: "TRUE",
            false_literal: "FALSE",
        }
    }
}

fn q(f: &SqlFlavor, name: &str) -> String {
    quote_ident(f.quote, name)
}

fn table_name(f: &SqlFlavor, t: &TableSchema) -> String {
    qualified_name(f.quote, t.schema.as_deref().filter(|s| !s.is_empty()), &t.name)
}

fn lit(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

fn fk_clause(f: &SqlFlavor, t: &TableSchema, fk: &crate::schema::ForeignKeyDef) -> String {
    let cols: Vec<String> = fk.columns.iter().map(|c| q(f, c)).collect();
    let refs: Vec<String> = fk.ref_columns.iter().map(|c| q(f, c)).collect();
    let target = qualified_name(f.quote, fk.ref_schema.as_deref().or(t.schema.as_deref()).filter(|s| !s.is_empty()), &fk.ref_table);
    let mut s = String::new();
    if let Some(n) = fk.name.as_deref().filter(|n| !n.is_empty()) {
        s.push_str(&format!("CONSTRAINT {} ", q(f, n)));
    }
    s.push_str(&format!("FOREIGN KEY ({}) REFERENCES {target} ({})", cols.join(", "), refs.join(", ")));
    if let Some(a) = fk.on_delete.as_deref().filter(|a| !a.is_empty()) {
        s.push_str(&format!(" ON DELETE {a}"));
    }
    if let Some(a) = fk.on_update.as_deref().filter(|a| !a.is_empty()) {
        s.push_str(&format!(" ON UPDATE {a}"));
    }
    s
}

/// A column as CREATE TABLE writes it: name, type, identity, default,
/// nullability and (inline) comment.
pub fn column_def(f: &SqlFlavor, t: &TableSchema, c: &crate::schema::ColumnDef) -> String {
    let in_pk = t.primary_key.as_ref().is_some_and(|k| k.columns.iter().any(|p| p == &c.name));
    column_def_inner(f, c, in_pk, false)
}

fn column_def_inner(f: &SqlFlavor, c: &crate::schema::ColumnDef, in_pk: bool, inline_pk: bool) -> String {
    let mut l = format!("{} {}", q(f, &c.name), c.data_type);
    if inline_pk {
        l.push_str(" PRIMARY KEY AUTOINCREMENT");
    } else if c.auto_increment {
        match f.auto_increment {
            AutoIncrement::Identity => l.push_str(" IDENTITY(1,1)"),
            AutoIncrement::GeneratedIdentity => l.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
            AutoIncrement::AutoIncrementKeyword => l.push_str(" AUTO_INCREMENT"),
            AutoIncrement::SqliteAutoincrement | AutoIncrement::None => {}
        }
    }
    if let Some(d) = c.default_value.as_deref().filter(|d| !d.is_empty()) {
        l.push_str(&format!(" DEFAULT {d}"));
    }
    if inline_pk {
        // INTEGER PRIMARY KEY is already NOT NULL.
    } else if !c.nullable || in_pk {
        l.push_str(" NOT NULL");
    } else {
        l.push_str(" NULL");
    }
    if f.inline_comments {
        if let Some(cm) = c.comment.as_deref().filter(|s| !s.is_empty()) {
            l.push_str(&format!(" COMMENT {}", lit(cm)));
        }
    }
    l
}

/// DDL for the requested parts, statements ending in `;`.
pub fn table_ddl(f: &SqlFlavor, t: &TableSchema, parts: DdlParts) -> String {
    let name = table_name(f, t);
    let mut out: Vec<String> = Vec::new();

    if parts.drop {
        out.push(format!("DROP TABLE {}{name};", if parts.if_exists && f.if_exists { "IF EXISTS " } else { "" }));
    }

    if parts.create {
        let pk_cols: Vec<&str> = t.primary_key.as_ref().map(|k| k.columns.iter().map(String::as_str).collect()).unwrap_or_default();
        // SQLite's AUTOINCREMENT only exists as an inline single-column key.
        let sqlite_inline_pk = f.auto_increment == AutoIncrement::SqliteAutoincrement
            && pk_cols.len() == 1
            && t.columns.iter().any(|c| c.name == pk_cols[0] && c.auto_increment);
        let mut lines: Vec<String> = t
            .columns
            .iter()
            .map(|c| format!("    {}", column_def_inner(f, c, pk_cols.contains(&c.name.as_str()), sqlite_inline_pk && c.name == pk_cols[0])))
            .collect();
        if !pk_cols.is_empty() && !sqlite_inline_pk {
            let cols: Vec<String> = pk_cols.iter().map(|c| q(f, c)).collect();
            let named = t.primary_key.as_ref().and_then(|k| k.name.as_deref()).filter(|n| !n.is_empty());
            lines.push(match named {
                Some(n) => format!("    CONSTRAINT {} PRIMARY KEY ({})", q(f, n), cols.join(", ")),
                None => format!("    PRIMARY KEY ({})", cols.join(", ")),
            });
        }
        if f.fk_inline {
            for fk in &t.foreign_keys {
                lines.push(format!("    {}", fk_clause(f, t, fk)));
            }
        }
        for c in &t.checks {
            lines.push(format!("    {}", check_clause(f, c)));
        }
        let mut create = format!(
            "CREATE TABLE {}{name} (\n{}\n)",
            if parts.if_exists && f.if_exists && !parts.drop { "IF NOT EXISTS " } else { "" },
            lines.join(",\n")
        );
        if f.inline_comments {
            if let Some(cm) = t.comment.as_deref().filter(|s| !s.is_empty()) {
                create.push_str(&format!(" COMMENT={}", lit(cm)));
            }
        }
        create.push(';');
        out.push(create);
        if f.comment_on {
            if let Some(cm) = t.comment.as_deref().filter(|s| !s.is_empty()) {
                out.push(format!("COMMENT ON TABLE {name} IS {};", lit(cm)));
            }
            for c in &t.columns {
                if let Some(cm) = c.comment.as_deref().filter(|s| !s.is_empty()) {
                    out.push(format!("COMMENT ON COLUMN {name}.{} IS {};", q(f, &c.name), lit(cm)));
                }
            }
        }
    }

    if parts.indexes {
        for ix in &t.indexes {
            let cols: Vec<String> = ix.columns.iter().map(|c| q(f, c)).collect();
            let mut s = format!(
                "CREATE {}INDEX {}{} ON {name} ({})",
                if ix.unique { "UNIQUE " } else { "" },
                if parts.if_exists && f.if_exists { "IF NOT EXISTS " } else { "" },
                q(f, &ix.name),
                cols.join(", ")
            );
            // Only engines that have INCLUDE report included columns.
            if !ix.include.is_empty() {
                let inc: Vec<String> = ix.include.iter().map(|c| q(f, c)).collect();
                s.push_str(&format!(" INCLUDE ({})", inc.join(", ")));
            }
            if let Some(w) = ix.filter.as_deref().filter(|w| !w.is_empty()) {
                s.push_str(&format!(" WHERE {w}"));
            }
            s.push(';');
            out.push(s);
        }
    }

    if parts.foreign_keys && !f.fk_inline {
        for fk in &t.foreign_keys {
            out.push(format!("ALTER TABLE {name} ADD {};", fk_clause(f, t, fk)));
        }
    }

    out.join("\n")
}

/// `[CONSTRAINT name] CHECK (expr)`, as CREATE TABLE and ALTER TABLE ADD write it.
pub fn check_clause(f: &SqlFlavor, c: &crate::schema::CheckDef) -> String {
    let expr = c.expression.trim();
    // Engines report it with or without the outer parentheses.
    let expr = if expr.starts_with('(') && balanced_outer(expr) { expr.to_string() } else { format!("({expr})") };
    match c.name.as_deref().filter(|n| !n.is_empty()) {
        Some(n) => format!("CONSTRAINT {} CHECK {expr}", q(f, n)),
        None => format!("CHECK {expr}"),
    }
}

/// `(…)` wraps the whole text (not `(a) AND (b)`).
pub(crate) fn balanced_outer(s: &str) -> bool {
    let mut depth = 0i32;
    for (i, ch) in s.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 && i != s.len() - 1 {
                    return false;
                }
            }
            _ => {}
        }
    }
    s.ends_with(')') && depth == 0
}

/// A value as a SQL literal.
pub fn sql_literal(f: &SqlFlavor, v: &Value) -> String {
    match v {
        Value::Null => "NULL".into(),
        Value::Bool(b) => if *b { f.true_literal.into() } else { f.false_literal.into() },
        Value::Number(n) => n.to_string(),
        Value::String(s) => lit(s),
        other => lit(&other.to_string()),
    }
}

/// `INSERT` statements for rows, `batch` rows per statement when the
/// dialect takes several.
pub fn insert_script(f: &SqlFlavor, schema: Option<&str>, table: &str, columns: &[String], rows: &[Vec<Value>], batch: usize) -> String {
    insert_script_with(f, schema, table, columns, rows, batch, &|v| sql_literal(f, v))
}

/// [`insert_script`] with the engine's own literals (`lit`).
pub fn insert_script_with(
    f: &SqlFlavor,
    schema: Option<&str>,
    table: &str,
    columns: &[String],
    rows: &[Vec<Value>],
    batch: usize,
    lit: &dyn Fn(&Value) -> String,
) -> String {
    let name = qualified_name(f.quote, schema.filter(|s| !s.is_empty()), table);
    let cols: Vec<String> = columns.iter().map(|c| q(f, c)).collect();
    let head = format!("INSERT INTO {name} ({}) VALUES", cols.join(", "));
    let tuple = |r: &Vec<Value>| format!("({})", r.iter().map(lit).collect::<Vec<_>>().join(", "));
    let per = if f.multi_row_insert { batch.max(1) } else { 1 };
    rows.chunks(per)
        .map(|chunk| {
            if per == 1 {
                format!("{head} {};", tuple(&chunk[0]))
            } else {
                format!("{head}\n  {};", chunk.iter().map(tuple).collect::<Vec<_>>().join(",\n  "))
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// `UPDATE … SET … WHERE …;` per changed row. `lit` writes a value as a
/// literal of the engine (drivers pass their own); a null key value
/// becomes `IS NULL`.
pub fn update_script_with(
    quote: Quote,
    schema: Option<&str>,
    table: &str,
    changes: &[crate::RowChange],
    lit: &dyn Fn(&Value) -> String,
) -> String {
    let name = qualified_name(quote, schema.filter(|s| !s.is_empty()), table);
    changes
        .iter()
        .filter(|c| !c.set.is_empty())
        .map(|c| {
            let set: Vec<String> = c.set.iter().map(|(k, v)| format!("{} = {}", quote_ident(quote, k), lit(v))).collect();
            let wh: Vec<String> = c
                .key
                .iter()
                .map(|(k, v)| if v.is_null() { format!("{} IS NULL", quote_ident(quote, k)) } else { format!("{} = {}", quote_ident(quote, k), lit(v)) })
                .collect();
            if wh.is_empty() {
                format!("UPDATE {name} SET {};", set.join(", "))
            } else {
                format!("UPDATE {name} SET {} WHERE {};", set.join(", "), wh.join(" AND "))
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// [`update_script_with`] with the flavor's literals.
pub fn update_script(f: &SqlFlavor, schema: Option<&str>, table: &str, changes: &[crate::RowChange]) -> String {
    update_script_with(f.quote, schema, table, changes, &|v| sql_literal(f, v))
}

/// `DELETE … WHERE <key>` for each row key (NULL key parts as IS NULL).
/// A key with no columns is skipped: it would delete the whole table.
pub fn delete_script_with(
    quote: Quote,
    schema: Option<&str>,
    table: &str,
    keys: &[Vec<(String, Value)>],
    lit: &dyn Fn(&Value) -> String,
) -> String {
    let name = qualified_name(quote, schema.filter(|s| !s.is_empty()), table);
    keys.iter()
        .filter(|k| !k.is_empty())
        .map(|k| {
            let wh: Vec<String> = k
                .iter()
                .map(|(c, v)| if v.is_null() { format!("{} IS NULL", quote_ident(quote, c)) } else { format!("{} = {}", quote_ident(quote, c), lit(v)) })
                .collect();
            format!("DELETE FROM {name} WHERE {};", wh.join(" AND "))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// [`delete_script_with`] with the flavor's literals.
pub fn delete_script(f: &SqlFlavor, schema: Option<&str>, table: &str, keys: &[Vec<(String, Value)>]) -> String {
    delete_script_with(f.quote, schema, table, keys, &|v| sql_literal(f, v))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn deletes_by_key_and_never_the_whole_table() {
        let keys = vec![vec![("id".into(), Value::from(7)), ("region".into(), Value::Null)], vec![], vec![("id".into(), Value::from("O'B"))]];
        assert_eq!(
            delete_script(&SqlFlavor::ansi(), Some("dbo"), "clientes", &keys),
            "DELETE FROM \"dbo\".\"clientes\" WHERE \"id\" = 7 AND \"region\" IS NULL;\nDELETE FROM \"dbo\".\"clientes\" WHERE \"id\" = 'O''B';"
        );
    }

    #[test]
    fn updates_by_key_with_null_keys() {
        let c = crate::RowChange {
            key: vec![("id".into(), Value::from(7)), ("region".into(), Value::Null)],
            set: vec![("nombre".into(), Value::from("O'Brien")), ("activo".into(), Value::Bool(false)), ("baja".into(), Value::Null)], ..Default::default()
        };
        let s = update_script(&SqlFlavor::ansi(), Some("dbo"), "clientes", &[c, crate::RowChange::default()]);
        assert_eq!(
            s,
            "UPDATE \"dbo\".\"clientes\" SET \"nombre\" = 'O''Brien', \"activo\" = FALSE, \"baja\" = NULL WHERE \"id\" = 7 AND \"region\" IS NULL;"
        );
    }
    use crate::schema::{ColumnDef, ForeignKeyDef, IndexDef, KeyDef};
    use serde_json::json;

    fn t() -> TableSchema {
        TableSchema {
            kind: "table".into(),
            schema: Some("dbo".into()),
            name: "pedidos".into(),
            columns: vec![
                ColumnDef { name: "id".into(), data_type: "int".into(), nullable: false, auto_increment: true, ..Default::default() },
                ColumnDef { name: "cliente_id".into(), data_type: "int".into(), nullable: true, comment: Some("dueño".into()), ..Default::default() },
                ColumnDef { name: "estado".into(), data_type: "varchar(20)".into(), nullable: false, default_value: Some("'nuevo'".into()), ..Default::default() },
            ],
            primary_key: Some(KeyDef { name: Some("pk_pedidos".into()), columns: vec!["id".into()] }),
            foreign_keys: vec![ForeignKeyDef {
                name: Some("fk_cliente".into()),
                columns: vec!["cliente_id".into()],
                ref_table: "clientes".into(),
                ref_columns: vec!["id".into()],
                on_delete: Some("CASCADE".into()),
                ..Default::default()
            }],
            indexes: vec![IndexDef { name: "ix_estado".into(), columns: vec!["estado".into()], ..Default::default() }],
            comment: Some("Pedidos".into()),
            ..Default::default()
        }
    }
    const ALL: DdlParts = DdlParts { drop: false, if_exists: false, create: true, indexes: true, foreign_keys: true };

    #[test]
    fn sql_server_flavor() {
        let f = SqlFlavor { quote: Quote::Bracket, auto_increment: AutoIncrement::Identity, comment_on: false, if_exists: true, ..SqlFlavor::ansi() };
        let s = table_ddl(&f, &t(), ALL);
        assert!(s.contains("CREATE TABLE [dbo].[pedidos] (\n    [id] int IDENTITY(1,1) NOT NULL,"), "{s}");
        assert!(s.contains("[estado] varchar(20) DEFAULT 'nuevo' NOT NULL"));
        assert!(s.contains("CONSTRAINT [pk_pedidos] PRIMARY KEY ([id])"));
        assert!(s.contains("CREATE INDEX [ix_estado] ON [dbo].[pedidos] ([estado]);"));
        assert!(s.contains("ALTER TABLE [dbo].[pedidos] ADD CONSTRAINT [fk_cliente] FOREIGN KEY ([cliente_id]) REFERENCES [dbo].[clientes] ([id]) ON DELETE CASCADE;"));
    }

    #[test]
    fn postgres_comments_and_drop() {
        let s = table_ddl(&SqlFlavor::ansi(), &t(), DdlParts { drop: true, if_exists: true, ..ALL });
        assert!(s.starts_with("DROP TABLE IF EXISTS \"dbo\".\"pedidos\";"));
        assert!(s.contains("\"id\" int GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assert!(s.contains("COMMENT ON TABLE \"dbo\".\"pedidos\" IS 'Pedidos';"));
        assert!(s.contains("COMMENT ON COLUMN \"dbo\".\"pedidos\".\"cliente_id\" IS 'dueño';"));
    }

    #[test]
    fn sqlite_inline_key_and_foreign_keys() {
        let f = SqlFlavor { auto_increment: AutoIncrement::SqliteAutoincrement, comment_on: false, fk_inline: true, ..SqlFlavor::ansi() };
        let mut tt = t();
        tt.schema = None;
        tt.columns[0].data_type = "INTEGER".into();
        let s = table_ddl(&f, &tt, ALL);
        assert!(s.contains("\"id\" INTEGER PRIMARY KEY AUTOINCREMENT,"), "{s}");
        assert!(!s.contains("CONSTRAINT \"pk_pedidos\""));
        assert!(s.contains("    CONSTRAINT \"fk_cliente\" FOREIGN KEY (\"cliente_id\") REFERENCES \"clientes\" (\"id\") ON DELETE CASCADE\n);"));
        assert!(!s.contains("ALTER TABLE"));
    }

    #[test]
    fn mysql_inline_comments() {
        let f = SqlFlavor { quote: Quote::Backtick, auto_increment: AutoIncrement::AutoIncrementKeyword, comment_on: false, inline_comments: true, ..SqlFlavor::ansi() };
        let s = table_ddl(&f, &t(), DdlParts { create: true, ..Default::default() });
        assert!(s.contains("`id` int AUTO_INCREMENT NOT NULL"));
        assert!(s.contains("`cliente_id` int NULL COMMENT 'dueño'"));
        assert!(s.ends_with(") COMMENT='Pedidos';"));
    }

    #[test]
    fn inserts_batch_and_escape() {
        let f = SqlFlavor::ansi();
        let rows = vec![vec![json!(1), json!("O'Brien"), Value::Null], vec![json!(2), json!(true), json!(1.5)]];
        let s = insert_script(&f, None, "t", &["a".into(), "b".into(), "c".into()], &rows, 100);
        assert_eq!(s, "INSERT INTO \"t\" (\"a\", \"b\", \"c\") VALUES\n  (1, 'O''Brien', NULL),\n  (2, TRUE, 1.5);");
        let one = insert_script(&SqlFlavor { multi_row_insert: false, ..f }, None, "t", &["a".into()], &[vec![json!(1)], vec![json!(2)]], 100);
        assert_eq!(one.lines().count(), 2);
    }
}
