//! Databricks (Delta / Unity Catalog) DDL: tables with identity columns,
//! defaults, comments, informational PK / FK, partitioning or liquid
//! clustering; INSERT scripts with Spark literals; the designer and the
//! templates. Also turns `information_schema` rows into [`TableSchema`]s.

use dbine_driver::sql::{quote_ident, Quote};
use dbine_driver::{
    kinds, CheckDef, ColumnDef, CreateTemplate, DdlParts, DesignerSpec, Field, FieldKind, ForeignKeyDef, KeyDef, RowChange,
    TableSchema,
};
use dbine_driver::{Error, Result};
use serde_json::Value as Json;
use std::collections::HashMap;

/// A catalog row by lowercase column name; NULLs are absent.
pub type Row = HashMap<String, String>;

pub const PARTITIONED_BY: &str = "partitioned_by";
pub const CLUSTER_BY: &str = "cluster_by";
/// Column option: `ALWAYS` or `BY DEFAULT` for identity columns.
pub const IDENTITY: &str = "identity";

pub(crate) fn q(name: &str) -> String {
    quote_ident(Quote::Backtick, name)
}

pub(crate) fn table_name(schema: Option<&str>, name: &str) -> String {
    match schema.filter(|s| !s.is_empty()) {
        Some(s) => format!("{}.{}", q(s), q(name)),
        None => q(name),
    }
}

/// A Spark SQL string literal: `''` would concatenate two literals there,
/// so quotes and backslashes are escaped with a backslash.
pub fn lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('\'');
    out
}

fn has(s: &Option<String>) -> Option<&str> {
    s.as_deref().filter(|v| !v.trim().is_empty())
}

fn cols(names: &[String]) -> String {
    names.iter().map(|c| q(c)).collect::<Vec<_>>().join(", ")
}

/// `a, b` or `` `a`, `b` `` → quoted list.
fn name_list(v: &str) -> String {
    v.split(',').map(|c| c.trim().trim_matches('`')).filter(|c| !c.is_empty()).map(q).collect::<Vec<_>>().join(", ")
}

fn constraint(name: &Option<String>) -> String {
    has(name).map(|n| format!("CONSTRAINT {} ", q(n))).unwrap_or_default()
}

pub fn table_ddl(t: &TableSchema, parts: DdlParts) -> String {
    let name = table_name(t.schema.as_deref(), &t.name);
    let mut out = Vec::new();
    if parts.drop {
        out.push(format!("DROP TABLE {}{name};", if parts.if_exists { "IF EXISTS " } else { "" }));
    }
    if parts.create {
        let pk: &[String] = t.primary_key.as_ref().map_or(&[], |k| &k.columns);
        let mut lines: Vec<String> = t
            .columns
            .iter()
            .map(|c| {
                let mut l = format!("  {} {}", q(&c.name), c.data_type);
                // Primary key columns must be NOT NULL.
                if !c.nullable || pk.contains(&c.name) {
                    l.push_str(" NOT NULL");
                }
                if c.auto_increment {
                    let always = c.options.get(IDENTITY).is_some_and(|v| v.eq_ignore_ascii_case("ALWAYS"));
                    l.push_str(if always { " GENERATED ALWAYS AS IDENTITY" } else { " GENERATED BY DEFAULT AS IDENTITY" });
                } else if let Some(d) = has(&c.default_value) {
                    l.push_str(&format!(" DEFAULT {d}"));
                }
                if let Some(cm) = has(&c.comment) {
                    l.push_str(&format!(" COMMENT {}", lit(cm)));
                }
                l
            })
            .collect();
        if let Some(k) = t.primary_key.as_ref().filter(|k| !k.columns.is_empty()) {
            lines.push(format!("  {}PRIMARY KEY ({})", constraint(&k.name), cols(&k.columns)));
        }
        let mut s = format!(
            "CREATE TABLE {}{name} (\n{}\n) USING DELTA",
            if parts.if_exists && !parts.drop { "IF NOT EXISTS " } else { "" },
            lines.join(",\n")
        );
        if let Some(p) = t.options.get(PARTITIONED_BY).map(|v| name_list(v)).filter(|v| !v.is_empty()) {
            s.push_str(&format!("\nPARTITIONED BY ({p})"));
        }
        if let Some(c) = t.options.get(CLUSTER_BY).map(|v| name_list(v)).filter(|v| !v.is_empty()) {
            s.push_str(&format!("\nCLUSTER BY ({c})"));
        }
        if let Some(cm) = has(&t.comment) {
            s.push_str(&format!("\nCOMMENT {}", lit(cm)));
        }
        // Column defaults are a Delta table feature that has to be enabled.
        if t.columns.iter().any(|c| !c.auto_increment && has(&c.default_value).is_some()) {
            s.push_str("\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported')");
        }
        s.push(';');
        out.push(s);
    }
    // Delta CHECK constraints are added once the table exists.
    if parts.create {
        for c in &t.checks {
            out.push(format!("ALTER TABLE {name} ADD {};", check_clause(c)));
        }
    }
    // Databricks has no indexes (bloom filter indexes aside, which are
    // column metadata and deprecated).
    if parts.foreign_keys {
        for fk in &t.foreign_keys {
            let target = table_name(fk.ref_schema.as_deref().or(t.schema.as_deref()), &fk.ref_table);
            out.push(format!(
                "ALTER TABLE {name} ADD {}FOREIGN KEY ({}) REFERENCES {target} ({});",
                constraint(&fk.name),
                cols(&fk.columns),
                cols(&fk.ref_columns)
            ));
        }
    }
    out.join("\n")
}

/// `CONSTRAINT n CHECK (…)`; Delta names every CHECK.
fn check_clause(c: &CheckDef) -> String {
    let e = c.expression.trim();
    match has(&c.name) {
        Some(n) => format!("CONSTRAINT {} CHECK ({e})", q(n)),
        None => format!("CHECK ({e})"),
    }
}

/// A Delta table's CHECK constraints from its properties
/// (`delta.constraints.<name>` = condition), as `SHOW TBLPROPERTIES` lists them.
pub fn checks_from_properties(props: &[(String, String)]) -> Vec<CheckDef> {
    let mut out: Vec<CheckDef> = props
        .iter()
        .filter_map(|(k, v)| {
            let name = k.strip_prefix("delta.constraints.")?;
            Some(CheckDef { name: Some(name.to_string()), expression: v.trim().to_string() })
        })
        .collect();
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

pub fn value(v: &Json) -> String {
    match v {
        Json::Null => "NULL".into(),
        Json::Bool(b) => if *b { "TRUE" } else { "FALSE" }.into(),
        Json::Number(n) => n.to_string(),
        Json::String(s) => lit(s),
        other => lit(&other.to_string()),
    }
}

pub fn insert_script(schema: Option<&str>, table: &str, columns: &[String], rows: &[Vec<Json>]) -> String {
    let head = format!("INSERT INTO {} ({}) VALUES", table_name(schema, table), cols(columns));
    rows.chunks(100)
        .map(|chunk| {
            let tuples: Vec<String> =
                chunk.iter().map(|r| format!("({})", r.iter().map(value).collect::<Vec<_>>().join(", "))).collect();
            format!("{head}\n  {};", tuples.join(",\n  "))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// `UPDATE … SET … WHERE …;` per edited row (Delta tables), with the
/// INSERT literals.
/// The browse query restricted by the grid's column filters, with Spark
/// literals (backslash escapes): LIKE patterns rely on the default `\`
/// escape instead of an ESCAPE clause.
pub fn filtered_browse(browse: &str, filters: &[dbine_driver::ColumnFilter]) -> Result<String> {
    use dbine_driver::filter::{insert_where, sql_condition, FilterOp, SqlFilterStyle};
    if filters.is_empty() {
        return Ok(browse.to_string());
    }
    let style = SqlFilterStyle { quote: Quote::Backtick, literal: &value, like: "LIKE", true_literal: "TRUE", false_literal: "FALSE" };
    let mut parts = Vec::new();
    for f in filters {
        let c = sql_condition(std::slice::from_ref(f), &style)?;
        let like = matches!(f.op, FilterOp::Contains | FilterOp::NotContains | FilterOp::StartsWith | FilterOp::EndsWith);
        parts.push(match c.strip_suffix(" ESCAPE '\\'") {
            Some(s) if like => s.to_string(),
            _ => c,
        });
    }
    insert_where(browse, &parts.join("\n  AND "))
        .ok_or_else(|| Error::Unsupported("no se pudo agregar el filtro a la consulta de este objeto".into()))
}

pub fn update_script(schema: Option<&str>, table: &str, changes: &[RowChange]) -> String {
    dbine_driver::ddl::update_script_with(Quote::Backtick, schema, table, changes, &value)
}

/// `DELETE … WHERE <key>` per row key, with the same literals as
/// [`update_script`] (Delta tables take DELETE).
pub fn delete_script(schema: Option<&str>, table: &str, keys: &[Vec<(String, Json)>]) -> String {
    dbine_driver::ddl::delete_script_with(Quote::Backtick, schema, table, keys, &value)
}

pub fn designer() -> DesignerSpec {
    let mut d = DesignerSpec::sql_table(vec![
        "BIGINT", "INT", "SMALLINT", "TINYINT", "DECIMAL(10,2)", "DOUBLE", "FLOAT", "BOOLEAN", "STRING", "VARCHAR(100)",
        "DATE", "TIMESTAMP", "TIMESTAMP_NTZ", "BINARY", "VARIANT", "ARRAY<STRING>", "MAP<STRING, STRING>",
        "STRUCT<a: INT, b: STRING>",
    ]);
    d.schemas = true;
    d.comments = true;
    d.indexes = false;
    d.column_options = vec![Field::new(
        IDENTITY,
        "Identidad",
        FieldKind::Select(vec![("BY DEFAULT", "GENERATED BY DEFAULT"), ("ALWAYS", "GENERATED ALWAYS")]),
    )
    .default_value("BY DEFAULT")
    .help("Para columnas autoincrementales (solo BIGINT).")];
    d.table_options = vec![
        Field::new(PARTITIONED_BY, "Particionar por", FieldKind::Text)
            .placeholder("columna1, columna2")
            .help("Columnas de PARTITIONED BY (no se combina con CLUSTER BY)."),
        Field::new(CLUSTER_BY, "Liquid clustering (CLUSTER BY)", FieldKind::Text)
            .placeholder("columna1, columna2")
            .help("Hasta cuatro columnas, separadas por coma."),
    ];
    d
}

pub fn templates() -> Vec<CreateTemplate> {
    let t = |kind, label, template: &str| CreateTemplate { kind, label, template: template.to_string() };
    vec![
        t(kinds::VIEW, "Nueva vista", "CREATE OR REPLACE VIEW `{schema}`.`{name}`\nCOMMENT ''\nAS\nSELECT *\nFROM `{schema}`.`tabla`;\n"),
        t(
            kinds::MATERIALIZED_VIEW,
            "Nueva vista materializada",
            "CREATE OR REPLACE MATERIALIZED VIEW `{schema}`.`{name}`\n  SCHEDULE EVERY 1 HOUR\nAS\nSELECT columna, COUNT(*) AS total\nFROM `{schema}`.`tabla`\nGROUP BY columna;\n",
        ),
        t(
            kinds::FUNCTION,
            "Nueva función SQL",
            "CREATE OR REPLACE FUNCTION `{schema}`.`{name}`(x INT)\nRETURNS INT\nCOMMENT ''\nRETURN x * 2;\n",
        ),
        t(
            kinds::FUNCTION,
            "Nueva función Python",
            "CREATE OR REPLACE FUNCTION `{schema}`.`{name}`(x DOUBLE)\nRETURNS DOUBLE\nLANGUAGE PYTHON\nAS $$\n  return x * 2\n$$;\n",
        ),
    ]
}

/// Rows → tables: `tables` / `columns` from information_schema, `pks`
/// (schema, table, constraint, column, ordinal) and `fks` (the same plus
/// the referenced schema, table and column, and the rules).
pub fn assemble(tables: &[Row], columns: &[Row], pks: &[Row], fks: &[Row]) -> Vec<TableSchema> {
    let g = |r: &Row, k: &str| r.get(k).cloned().unwrap_or_default();
    let num = |r: &Row, k: &str| r.get(k).and_then(|v| v.parse::<i64>().ok()).unwrap_or(0);
    let mut out: Vec<TableSchema> = tables
        .iter()
        .map(|r| TableSchema {
            kind: kinds::TABLE.into(),
            schema: Some(g(r, "table_schema")),
            name: g(r, "table_name"),
            comment: r.get("comment").filter(|c| !c.is_empty()).cloned(),
            ..Default::default()
        })
        .collect();
    out.sort_by(|a, b| (&a.schema, &a.name).cmp(&(&b.schema, &b.name)));
    let find =
        |out: &[TableSchema], r: &Row| out.iter().position(|t| t.schema.as_deref() == r.get("table_schema").map(String::as_str) && Some(&t.name) == r.get("table_name"));

    let mut cs: Vec<&Row> = columns.iter().collect();
    cs.sort_by_key(|r| num(r, "ordinal_position"));
    let mut partitions: HashMap<usize, Vec<(i64, String)>> = HashMap::new();
    for r in cs {
        let Some(i) = find(&out, r) else { continue };
        let auto = g(r, "is_identity") == "YES";
        let mut c = ColumnDef {
            name: g(r, "column_name"),
            data_type: g(r, "full_data_type"),
            nullable: g(r, "is_nullable") != "NO",
            default_value: r.get("column_default").filter(|_| !auto).cloned(),
            auto_increment: auto,
            comment: r.get("comment").filter(|c| !c.is_empty()).cloned(),
            ..Default::default()
        };
        if auto && g(r, "identity_generation").eq_ignore_ascii_case("ALWAYS") {
            c.options.insert(IDENTITY.into(), "ALWAYS".into());
        }
        if let Some(p) = r.get("partition_index").and_then(|p| p.parse::<i64>().ok()) {
            partitions.entry(i).or_default().push((p, c.name.clone()));
        }
        out[i].columns.push(c);
    }
    for (i, mut p) in partitions {
        p.sort();
        out[i].options.insert(PARTITIONED_BY.into(), p.into_iter().map(|(_, n)| n).collect::<Vec<_>>().join(", "));
    }

    let mut pks: Vec<&Row> = pks.iter().collect();
    pks.sort_by_key(|r| num(r, "ordinal_position"));
    for r in pks {
        let Some(i) = find(&out, r) else { continue };
        out[i].primary_key.get_or_insert_with(|| KeyDef { name: r.get("constraint_name").cloned(), columns: Vec::new() }).columns.push(g(r, "column_name"));
    }
    let rule = |r: &Row, k: &str| r.get(k).filter(|v| !matches!(v.as_str(), "" | "NO ACTION" | "RESTRICT")).cloned();
    let mut fks: Vec<&Row> = fks.iter().collect();
    fks.sort_by_key(|r| num(r, "ordinal_position"));
    let mut seen: HashMap<(usize, String), usize> = HashMap::new();
    for r in fks {
        let Some(i) = find(&out, r) else { continue };
        let at = *seen.entry((i, g(r, "constraint_name"))).or_insert_with(|| {
            out[i].foreign_keys.push(ForeignKeyDef {
                name: r.get("constraint_name").cloned(),
                ref_schema: r.get("ref_schema").cloned(),
                ref_table: g(r, "ref_table"),
                on_delete: rule(r, "delete_rule"),
                on_update: rule(r, "update_rule"),
                ..Default::default()
            });
            out[i].foreign_keys.len() - 1
        });
        let fk = &mut out[i].foreign_keys[at];
        fk.columns.push(g(r, "column_name"));
        fk.ref_columns.push(g(r, "ref_column"));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn filtered_browse_uses_spark_literals() {
        use dbine_driver::{ColumnFilter, FilterOp};
        let f = |column: &str, op: FilterOp, values: Vec<Json>| ColumnFilter { column: column.into(), op, values, sql: None };
        let browse = "SELECT *\nFROM `main`.`s`.`t`\nLIMIT 200";
        assert_eq!(
            filtered_browse(
                browse,
                &[
                    f("nombre", FilterOp::Ne, vec![json!("O'Brien")]),
                    f("nota", FilterOp::EndsWith, vec![json!("100%")]),
                    f("n", FilterOp::Ge, vec![json!(1.5)]),
                    f("baja", FilterOp::IsNull, vec![]),
                    f("pais", FilterOp::In, vec![json!("AR"), json!("UY")]),
                ]
            )
            .unwrap(),
            "SELECT *\nFROM `main`.`s`.`t`\nWHERE `nombre` <> 'O\\'Brien'\n  AND `nota` LIKE '%100\\\\%'\n  AND `n` >= 1.5\n  AND `baja` IS NULL\n  AND `pais` IN ('AR', 'UY')\nLIMIT 200"
        );
    }

    fn row(pairs: &[(&str, &str)]) -> Row {
        pairs.iter().map(|(k, v)| (k.to_string(), v.to_string())).collect()
    }

    fn sample() -> Vec<TableSchema> {
        let tables = vec![
            row(&[("table_schema", "ventas"), ("table_name", "pedidos"), ("comment", "Pedidos")]),
            row(&[("table_schema", "ventas"), ("table_name", "clientes")]),
        ];
        let c = |t: &str, n: &str, pos: &str, ty: &str, extra: &[(&str, &str)]| {
            let mut r = row(&[("table_schema", "ventas"), ("table_name", t), ("column_name", n), ("ordinal_position", pos), ("full_data_type", ty), ("is_nullable", "YES"), ("is_identity", "NO")]);
            r.extend(extra.iter().map(|(k, v)| (k.to_string(), v.to_string())));
            r
        };
        let columns = vec![
            c("pedidos", "estado", "2", "string", &[("column_default", "'nuevo'"), ("partition_index", "0")]),
            c("pedidos", "id", "0", "bigint", &[("is_identity", "YES"), ("identity_generation", "ALWAYS"), ("is_nullable", "NO")]),
            c("pedidos", "cliente_id", "1", "bigint", &[("comment", "dueño")]),
            c("clientes", "id", "0", "bigint", &[("is_nullable", "NO")]),
            c("clientes", "tags", "1", "array<string>", &[]),
        ];
        let pks = vec![
            row(&[("table_schema", "ventas"), ("table_name", "pedidos"), ("constraint_name", "pk_pedidos"), ("column_name", "id"), ("ordinal_position", "1")]),
            row(&[("table_schema", "ventas"), ("table_name", "clientes"), ("constraint_name", "pk_clientes"), ("column_name", "id"), ("ordinal_position", "1")]),
        ];
        let fks = vec![row(&[
            ("table_schema", "ventas"), ("table_name", "pedidos"), ("constraint_name", "fk_cliente"), ("column_name", "cliente_id"),
            ("ordinal_position", "1"), ("ref_schema", "ventas"), ("ref_table", "clientes"), ("ref_column", "id"),
            ("update_rule", "NO ACTION"), ("delete_rule", "NO ACTION"),
        ])];
        assemble(&tables, &columns, &pks, &fks)
    }

    #[test]
    fn update_script_per_row() {
        let c = RowChange {
            key: vec![("id".into(), json!(7)), ("region".into(), Json::Null)],
            set: vec![("nombre".into(), json!("O'Brien")), ("baja".into(), Json::Null)], ..Default::default()
        };
        assert_eq!(
            update_script(Some("ventas"), "clientes", &[c, RowChange::default()]),
            "UPDATE `ventas`.`clientes` SET `nombre` = 'O\\'Brien', `baja` = NULL WHERE `id` = 7 AND `region` IS NULL;"
        );
    }

    #[test]
    fn delete_script_per_row() {
        let keys = vec![vec![("nombre".into(), json!("O'Brien")), ("region".into(), Json::Null)], vec![]];
        assert_eq!(
            delete_script(Some("ventas"), "clientes", &keys),
            "DELETE FROM `ventas`.`clientes` WHERE `nombre` = 'O\\'Brien' AND `region` IS NULL;"
        );
    }

    #[test]
    fn catalog_rows_become_tables() {
        let s = sample();
        assert_eq!(s.iter().map(|t| t.name.as_str()).collect::<Vec<_>>(), vec!["clientes", "pedidos"]);
        let p = &s[1];
        assert_eq!(p.columns.iter().map(|c| (c.name.as_str(), c.data_type.as_str())).collect::<Vec<_>>(), vec![("id", "bigint"), ("cliente_id", "bigint"), ("estado", "string")]);
        assert!(p.columns[0].auto_increment && p.columns[0].options.get(IDENTITY).map(String::as_str) == Some("ALWAYS"));
        assert_eq!(p.columns[1].comment.as_deref(), Some("dueño"));
        assert_eq!(p.columns[2].default_value.as_deref(), Some("'nuevo'"));
        assert_eq!(p.options.get(PARTITIONED_BY).map(String::as_str), Some("estado"));
        assert_eq!(p.comment.as_deref(), Some("Pedidos"));
        assert_eq!(p.primary_key, Some(KeyDef { name: Some("pk_pedidos".into()), columns: vec!["id".into()] }));
        assert_eq!(
            p.foreign_keys,
            vec![ForeignKeyDef {
                name: Some("fk_cliente".into()),
                columns: vec!["cliente_id".into()],
                ref_schema: Some("ventas".into()),
                ref_table: "clientes".into(),
                ref_columns: vec!["id".into()],
                on_delete: None,
                on_update: None
            }]
        );
    }

    #[test]
    fn ddl_for_all_parts() {
        let s = sample();
        let all = DdlParts { drop: true, if_exists: true, create: true, indexes: true, foreign_keys: true };
        let p = table_ddl(&s[1], all);
        assert!(p.starts_with("DROP TABLE IF EXISTS `ventas`.`pedidos`;\nCREATE TABLE `ventas`.`pedidos` (\n"), "{p}");
        assert!(p.contains("  `id` bigint NOT NULL GENERATED ALWAYS AS IDENTITY,\n"));
        assert!(p.contains("  `cliente_id` bigint COMMENT 'dueño',\n"));
        assert!(p.contains("  `estado` string DEFAULT 'nuevo',\n  CONSTRAINT `pk_pedidos` PRIMARY KEY (`id`)\n) USING DELTA\nPARTITIONED BY (`estado`)\nCOMMENT 'Pedidos'\nTBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');"));
        assert!(p.ends_with("ALTER TABLE `ventas`.`pedidos` ADD CONSTRAINT `fk_cliente` FOREIGN KEY (`cliente_id`) REFERENCES `ventas`.`clientes` (`id`);"));
        let mut c = s[0].clone();
        c.options.insert(CLUSTER_BY.into(), "id".into());
        c.columns[0].nullable = true;
        let d = table_ddl(&c, DdlParts { create: true, if_exists: true, ..Default::default() });
        assert!(d.starts_with("CREATE TABLE IF NOT EXISTS `ventas`.`clientes` (\n  `id` bigint NOT NULL,\n  `tags` array<string>,"), "{d}");
        assert!(d.ends_with(") USING DELTA\nCLUSTER BY (`id`);"));
    }

    #[test]
    fn inserts_escape_with_backslashes() {
        let rows = vec![vec![json!(1), json!("O'Brien \\"), Json::Null], vec![json!(2), json!(true), json!(1.5)]];
        let s = insert_script(Some("ventas"), "t", &["a".into(), "b".into(), "c".into()], &rows);
        assert_eq!(s, "INSERT INTO `ventas`.`t` (`a`, `b`, `c`) VALUES\n  (1, 'O\\'Brien \\\\', NULL),\n  (2, TRUE, 1.5);");
    }

    #[test]
    fn templates_cover_the_kinds() {
        let t = templates();
        for k in [kinds::VIEW, kinds::MATERIALIZED_VIEW, kinds::FUNCTION] {
            assert!(t.iter().any(|x| x.kind == k && x.template.contains("`{schema}`.`{name}`")), "{k}");
        }
    }

    #[test]
    fn check_constraints_from_properties_and_back() {
        let props = vec![
            ("delta.minReaderVersion".to_string(), "1".to_string()),
            ("delta.constraints.precio_positivo".to_string(), "precio > 0".to_string()),
            ("delta.constraints.a_fecha".to_string(), "fecha >= '2020-01-01'".to_string()),
        ];
        let checks = checks_from_properties(&props);
        assert_eq!(checks.len(), 2);
        assert_eq!(checks[0].name.as_deref(), Some("a_fecha"));
        assert_eq!(checks[1].expression, "precio > 0");
        let t = TableSchema {
            schema: Some("s".into()),
            name: "t".into(),
            columns: vec![ColumnDef { name: "precio".into(), data_type: "INT".into(), nullable: true, ..Default::default() }],
            checks,
            ..Default::default()
        };
        let ddl = table_ddl(&t, DdlParts { drop: false, if_exists: false, create: true, indexes: true, foreign_keys: true });
        assert!(ddl.ends_with(
            "ALTER TABLE `s`.`t` ADD CONSTRAINT `a_fecha` CHECK (fecha >= '2020-01-01');\nALTER TABLE `s`.`t` ADD CONSTRAINT `precio_positivo` CHECK (precio > 0);"
        ), "{ddl}");
    }
}
