//! "Comparar esquemas" against real servers: two databases that differ in
//! every kind of thing the compare reads (CHECK, INCLUDE / STORING, index
//! methods, sort orders and operator classes, expression and full-text
//! indexes, storage parameters, NULLS NOT DISTINCT, UNIQUE and EXCLUDE
//! constraints, sequences, enums, domains, composite and range types). The
//! sync script is run on one side and both must then read the same.
//!
//! ```sh
//! DBINE_TEST_POSTGRES_URL=postgres://postgres:pw@localhost:25010/postgres \
//! DBINE_TEST_COCKROACH_URL=postgres://root@localhost:26014/defaultdb \
//!   cargo test -p dbine-driver-postgres --test compare -- --ignored --nocapture
//! ```
//!
//! `DBINE_TEST_TIMESCALE_URL` and `DBINE_TEST_YUGABYTE_URL` run the same
//! checks on TimescaleDB and YugabyteDB.

use dbine_driver::{ConnectionConfig, Driver, ObjectRef, QueryOutcome, Session, TableChange, TableSchema};
use std::collections::BTreeMap;
use std::sync::Arc;

fn parse_url(driver: &str, url: &str) -> ConnectionConfig {
    let rest = url.split_once("://").map_or(url, |(_, r)| r);
    let (auth, hostpart) = rest.rsplit_once('@').unwrap_or(("", rest));
    let (user, pass) = auth.split_once(':').map_or((auth, None), |(u, p)| (u, Some(p)));
    let (hostport, db) = hostpart.split_once('/').unwrap_or((hostpart, ""));
    let (host, port) = hostport.rsplit_once(':').map_or((hostport, 0), |(h, p)| (h, p.parse().unwrap()));
    ConnectionConfig {
        driver: driver.into(),
        host: host.into(),
        port,
        database: db.into(),
        username: (!user.is_empty()).then(|| user.into()),
        password: pass.map(Into::into),
        ..Default::default()
    }
}

fn driver(id: &str) -> Arc<dyn Driver> {
    dbine_driver_postgres::drivers().into_iter().find(|d| d.info().id == id).unwrap()
}

async fn run(s: &mut Box<dyn Session>, sql: &str) -> Result<(), String> {
    let mut out = QueryOutcome::default();
    s.execute(sql, 100, &mut out).await.map_err(|e| e.to_string())?;
    match out.error.take() {
        Some(e) => Err(e),
        None => Ok(()),
    }
}

/// One statement at a time (CockroachDB won't use a type in the
/// transaction that made it).
async fn run_all(s: &mut Box<dyn Session>, script: &str) {
    for stmt in script.split(";\n").map(str::trim).filter(|s| !s.is_empty()) {
        run(s, stmt).await.unwrap_or_else(|e| panic!("{e}\n---\n{stmt}"));
    }
}

const PG_SOURCE: &str = "
CREATE SCHEMA app;
CREATE TYPE app.mood AS ENUM ('bien', 'mal', 'así así');
CREATE DOMAIN app.positivo AS integer DEFAULT 1 NOT NULL CONSTRAINT positivo_ck CHECK (VALUE > 0);
CREATE TYPE app.punto AS (x double precision, y double precision);
CREATE TYPE app.rango_fl AS RANGE (SUBTYPE = double precision);
CREATE SEQUENCE app.folio AS integer START WITH 100 INCREMENT BY 5 CACHE 10;
CREATE TABLE app.docs (
    id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT docs_pk PRIMARY KEY,
    codigo varchar(20) NOT NULL,
    titulo text NOT NULL,
    cuerpo text,
    vigencia int4range,
    sala integer,
    animo app.mood,
    cant app.positivo,
    CONSTRAINT docs_codigo_uq UNIQUE NULLS NOT DISTINCT (codigo) INCLUDE (titulo) WITH (fillfactor = 70),
    CONSTRAINT docs_vigencia_ex EXCLUDE USING gist (vigencia WITH &&) WHERE (sala IS NOT NULL),
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 2)
);
CREATE INDEX docs_titulo_ix ON app.docs (titulo DESC NULLS LAST, lower(cuerpo) text_pattern_ops) INCLUDE (codigo) WITH (fillfactor = 80);
CREATE INDEX docs_fts_ix ON app.docs USING gin (to_tsvector('spanish', titulo || ' ' || coalesce(cuerpo, '')));
CREATE INDEX docs_id_brin ON app.docs USING brin (id) WITH (pages_per_range = 16);
CREATE UNIQUE INDEX docs_sala_ux ON app.docs (sala) NULLS NOT DISTINCT WHERE sala > 0;
CREATE INDEX docs_cuerpo_hash ON app.docs USING hash (cuerpo);
CREATE SEQUENCE app.suelta OWNED BY app.docs.sala;
COMMENT ON TABLE app.docs IS 'Documentos';
COMMENT ON COLUMN app.docs.titulo IS 'Título nuevo';
COMMENT ON COLUMN app.docs.animo IS 'ánimo (columna nueva)';
";

const PG_TARGET: &str = "
CREATE SCHEMA app;
CREATE TYPE app.mood AS ENUM ('bien', 'mal');
CREATE DOMAIN app.positivo AS integer CONSTRAINT positivo_ck CHECK (VALUE >= 0);
CREATE SEQUENCE app.folio AS integer;
CREATE SEQUENCE app.extra;
CREATE TABLE app.docs (
    id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT docs_pk PRIMARY KEY,
    codigo varchar(20) NOT NULL,
    titulo text NOT NULL,
    cuerpo text,
    vigencia int4range,
    sala integer,
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 0)
);
CREATE UNIQUE INDEX docs_codigo_uq ON app.docs (codigo);
CREATE INDEX docs_titulo_ix ON app.docs (titulo);
CREATE INDEX docs_fts_ix ON app.docs USING gin (to_tsvector('english', titulo));
CREATE INDEX docs_id_brin ON app.docs USING brin (id);
COMMENT ON COLUMN app.docs.titulo IS 'Título viejo';
COMMENT ON COLUMN app.docs.cuerpo IS 'se va';
";

const CRDB_SOURCE: &str = "
CREATE SCHEMA app;
CREATE TYPE app.mood AS ENUM ('bien', 'mal', 'así así');
CREATE TYPE app.punto AS (x FLOAT8, y FLOAT8);
CREATE SEQUENCE app.folio START WITH 100 INCREMENT BY 5;
CREATE TABLE app.docs (
    id INT8 PRIMARY KEY,
    codigo STRING NOT NULL,
    titulo STRING NOT NULL,
    j JSONB,
    animo app.mood,
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 2)
);
CREATE UNIQUE INDEX docs_codigo_uq ON app.docs (codigo) STORING (titulo);
CREATE INDEX docs_titulo_ix ON app.docs (titulo DESC, codigo) STORING (j);
CREATE INVERTED INDEX docs_j_gin ON app.docs (j);
CREATE INDEX docs_lower_ix ON app.docs (lower(titulo)) WHERE codigo > 'a';
";

const CRDB_TARGET: &str = "
CREATE SCHEMA app;
CREATE TYPE app.mood AS ENUM ('bien', 'mal');
CREATE SEQUENCE app.folio;
CREATE SEQUENCE app.extra;
CREATE TABLE app.docs (
    id INT8 PRIMARY KEY,
    codigo STRING NOT NULL,
    titulo STRING NOT NULL,
    j JSONB,
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 0)
);
CREATE UNIQUE INDEX docs_codigo_uq ON app.docs (codigo);
CREATE INDEX docs_titulo_ix ON app.docs (titulo);
";

/// The object kinds the compare reads by their source (src-tauri's list).
const CODE_KINDS: &[&str] = &["view", "materialized_view", "procedure", "function", "trigger", "sequence", "synonym", "type", "domain"];
/// Made before the tables, dropped after them.
const PREREQS: &[&str] = &["type", "sequence", "domain"];

#[derive(Debug, Clone, Copy, PartialEq)]
enum Op {
    Create,
    Drop,
    Replace,
}

type Objects = BTreeMap<(String, Option<String>, String), String>;

fn normalized(mut t: TableSchema) -> TableSchema {
    t.indexes.sort_by(|a, b| a.name.cmp(&b.name));
    t.checks.sort_by(|a, b| a.name.cmp(&b.name));
    t
}

fn squash(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ").trim_end_matches(';').to_string()
}

async fn read(s: &mut Box<dyn Session>) -> (BTreeMap<String, TableSchema>, Objects) {
    let tables = s
        .database_schema()
        .await
        .expect("database_schema")
        .into_iter()
        .filter(|t| t.schema.as_deref() == Some("app"))
        .map(|t| (t.name.clone(), normalized(t)))
        .collect();
    let mut objects = Objects::new();
    for o in s.list_objects().await.expect("list_objects") {
        if !CODE_KINDS.contains(&o.kind.as_str()) || o.schema.as_deref() != Some("app") {
            continue;
        }
        let r = ObjectRef { kind: o.kind.clone(), schema: o.schema.clone(), name: o.name.clone() };
        let def = s.definition(&r).await.expect("definition").unwrap_or_else(|| panic!("no definition for {r:?}"));
        objects.insert((o.kind, o.schema, o.name), def);
    }
    (tables, objects)
}

fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('"', "\"\""))
}

/// What src-tauri's `drop_other` writes.
fn drop_other(kind: &str, schema: Option<&str>, name: &str) -> String {
    let full = match schema {
        Some(s) => format!("{}.{}", quote(s), quote(name)),
        None => quote(name),
    };
    format!("DROP {} IF EXISTS {full};", kind.replace('_', " ").to_uppercase())
}

/// What src-tauri's compare `drop_statements` writes on PostgreSQL: a
/// trigger is dropped `ON` each of its tables, and an object only being
/// dropped with several overloads goes one signature at a time. `def` is
/// what `definition` read (`pg_get_triggerdef` / `pg_get_functiondef`,
/// joined); the parsing is simple: the test's definitions have no defaults
/// nor tricky names.
fn drop_statements(kind: &str, schema: Option<&str>, name: &str, def: &str, whole: bool) -> Vec<String> {
    let plain = drop_other(kind, schema, name);
    match kind {
        "trigger" => {
            let tables: Vec<String> = def
                .split("CREATE ")
                .filter_map(|d| d.split_once(" ON ").map(|(_, rest)| rest.split_whitespace().next().unwrap_or("").to_string()))
                .filter(|t| !t.is_empty())
                .map(|t| match schema {
                    Some(s) if !t.contains('.') => format!("{}.{t}", quote(s)),
                    _ => t,
                })
                .collect();
            if tables.is_empty() {
                return vec![plain];
            }
            tables.into_iter().map(|t| format!("DROP TRIGGER IF EXISTS {} ON {t};", quote(name))).collect()
        }
        "function" | "procedure" if whole => {
            let keyword = kind.to_uppercase();
            let head = format!("{keyword} ");
            // `CREATE OR REPLACE …` (PostgreSQL) or `CREATE …` (CockroachDB).
            let sigs: Vec<String> = def
                .split("CREATE ")
                .filter_map(|d| d.strip_prefix("OR REPLACE ").unwrap_or(d).strip_prefix(&head))
                .filter_map(|d| d.find(')').map(|end| d[..=end].to_string()))
                .collect();
            if sigs.len() < 2 {
                return vec![plain];
            }
            sigs.into_iter().map(|sig| format!("DROP {keyword} IF EXISTS {sig};")).collect()
        }
        _ => vec![plain],
    }
}

/// Drops ordered as src-tauri's compare does: one whose definition names
/// another goes first (a trigger before its function, a view before the
/// view it reads). Same-named statements (a trigger on two tables) once.
fn drops_in_order(items: Vec<(String, String, Vec<String>)>) -> Vec<String> {
    let mut left = items;
    let mut out: Vec<String> = Vec::new();
    while !left.is_empty() {
        // The first one no other remaining definition names.
        let i = (0..left.len())
            .find(|&i| !left.iter().enumerate().any(|(j, (n, d, _))| j != i && *n != left[i].0 && named_in(&left[i].0, d)))
            .unwrap_or(0);
        for s in left.remove(i).2 {
            if !out.contains(&s) {
                out.push(s);
            }
        }
    }
    out
}

/// Whether `text` names `name` as a whole word.
fn named_in(name: &str, text: &str) -> bool {
    let word = |c: char| c.is_alphanumeric() || c == '_' || c == '$';
    text.to_lowercase().split(|c: char| !word(c)).any(|w| w == name.to_lowercase())
}

/// `plan` in src-tauri's compare: object drops, prerequisites, tables,
/// other objects, then dropped prerequisites.
fn plan(d: &dyn Driver, tables: &[TableChange], objects: &[(Op, String, Option<String>, String, String)]) -> Vec<String> {
    let (mut before, mut early, mut after, mut late) = (Vec::new(), Vec::new(), Vec::new(), Vec::new());
    for (op, kind, schema, name, def) in objects {
        let prereq = PREREQS.contains(&kind.as_str());
        let drops = || (name.clone(), def.clone(), drop_statements(kind, schema.as_deref(), name, def, *op == Op::Drop));
        match op {
            Op::Drop if prereq => late.push(drops()),
            Op::Drop | Op::Replace => before.push(drops()),
            _ => {}
        }
        if *op != Op::Drop {
            if prereq {
                early.push(def.clone())
            } else {
                after.push(def.clone())
            }
        }
    }
    let script = d.sync_script(tables).expect("sync_script");
    for w in &script.warnings {
        eprintln!("aviso: {w}");
    }
    drops_in_order(before).into_iter().chain(early).chain(script.statements).chain(after).chain(drops_in_order(late)).collect()
}

fn ix<'a>(t: &'a TableSchema, n: &str) -> &'a dbine_driver::IndexDef {
    t.indexes.iter().find(|i| i.name == n).unwrap_or_else(|| panic!("{n} in {:#?}", t.indexes))
}

/// Sets up both databases, checks what was read with `inspect`, syncs B to
/// A and compares again. Returns the object operations.
async fn compare_and_sync(
    id: &str,
    url: &str,
    source: &str,
    target: &str,
    inspect: impl Fn(&BTreeMap<String, TableSchema>, &Objects),
) -> Vec<(Op, String)> {
    let cfg = parse_url(id, url);
    let d = driver(id);
    let kinds: Vec<&str> = d.info().object_kinds.iter().map(|k| k.id).collect();
    let want: &[&str] = match id {
        "h2" => &["sequence", "domain"],
        "materialize" => &["type"],
        "risingwave" => &[],
        _ => &["sequence", "type"],
    };
    for k in want {
        assert!(kinds.contains(k), "{k} in {kinds:?}");
    }
    let mut admin = d.connect(&cfg, None).await.expect("connect");
    let (a_db, b_db) = ("dbine_cmp_a", "dbine_cmp_b");
    // H2 makes a database on first connection; the schema is cleared instead.
    let own_databases = d.capabilities().create_database;
    if own_databases {
        for db in [a_db, b_db] {
            let _ = admin.drop_database(db).await;
            admin.create_database(db).await.expect("create_database");
        }
    }
    let mut a = d.connect(&cfg, Some(a_db)).await.unwrap();
    let mut b = d.connect(&cfg, Some(b_db)).await.unwrap();
    if !own_databases {
        for s in [&mut a, &mut b] {
            run(s, "DROP SCHEMA IF EXISTS app CASCADE").await.unwrap();
        }
    }
    run_all(&mut a, source).await;
    run_all(&mut b, target).await;

    let (ta, oa) = read(&mut a).await;
    let (tb, ob) = read(&mut b).await;
    for ((k, s, n), def) in &oa {
        eprintln!("-- {k} {s:?}.{n}\n{def}");
    }
    for t in ta.values() {
        eprintln!("{t:#?}");
    }
    inspect(&ta, &oa);

    let mut tables = Vec::new();
    for (name, t) in &ta {
        match tb.get(name) {
            None => tables.push(TableChange::Create { table: t.clone() }),
            Some(o) if o != t => tables.push(TableChange::Alter { old: o.clone(), new: t.clone() }),
            Some(_) => {}
        }
    }
    for (name, t) in &tb {
        if !ta.contains_key(name) {
            tables.push(TableChange::Drop { table: t.clone() });
        }
    }
    let mut objects = Vec::new();
    for ((k, s, n), def) in &oa {
        match ob.get(&(k.clone(), s.clone(), n.clone())) {
            None => objects.push((Op::Create, k.clone(), s.clone(), n.clone(), def.clone())),
            Some(o) if squash(o) != squash(def) => objects.push((Op::Replace, k.clone(), s.clone(), n.clone(), def.clone())),
            Some(_) => {}
        }
    }
    for ((k, s, n), def) in &ob {
        if !oa.contains_key(&(k.clone(), s.clone(), n.clone())) {
            objects.push((Op::Drop, k.clone(), s.clone(), n.clone(), def.clone()));
        }
    }

    let statements = plan(d.as_ref(), &tables, &objects);
    eprintln!("---- sync script\n{}", statements.join("\n"));
    for (i, s) in statements.iter().enumerate() {
        if let Err(e) = run(&mut b, s).await {
            panic!("statement {i} failed: {e}\n---\n{s}\n---\nwhole script:\n{}", statements.join("\n"));
        }
    }
    let (tb2, ob2) = read(&mut b).await;
    for (name, t) in &ta {
        assert_eq!(tb2.get(name), Some(t), "table {name} after the sync");
    }
    assert_eq!(tb2.len(), ta.len());
    let squashed = |o: &Objects| o.iter().map(|(k, v)| (k.clone(), squash(v))).collect::<Vec<_>>();
    assert_eq!(squashed(&ob2), squashed(&oa));

    if own_databases {
        drop(a);
        drop(b);
        for db in [a_db, b_db] {
            admin.drop_database(db).await.expect("drop_database");
        }
    } else {
        for s in [&mut a, &mut b] {
            run(s, "DROP SCHEMA IF EXISTS app CASCADE").await.unwrap();
        }
    }
    objects.into_iter().map(|(op, _, _, n, _)| (op, n)).collect()
}

fn pg_inspect(ta: &BTreeMap<String, TableSchema>, oa: &Objects) {
    let docs = &ta["docs"];
    let o = |i: &dbine_driver::IndexDef, k: &str| i.options.get(k).cloned();
    let uq = ix(docs, "docs_codigo_uq");
    assert_eq!(uq.include, ["titulo"]);
    assert_eq!(o(uq, "constraint").as_deref(), Some("UNIQUE NULLS NOT DISTINCT (codigo) INCLUDE (titulo) WITH (fillfactor=70)"));
    let ex = ix(docs, "docs_vigencia_ex");
    assert_eq!(ex.kind.as_deref(), Some("EXCLUDE"));
    assert!(o(ex, "constraint").unwrap().starts_with("EXCLUDE USING gist (vigencia WITH &&) WHERE"));
    let t = ix(docs, "docs_titulo_ix");
    assert_eq!(t.include, ["codigo"]);
    assert_eq!(o(t, "fillfactor").as_deref(), Some("80"));
    assert_eq!(o(t, "keys").as_deref(), Some("titulo DESC NULLS LAST, lower(cuerpo) text_pattern_ops"));
    let fts = ix(docs, "docs_fts_ix");
    assert_eq!(fts.kind.as_deref(), Some("gin"));
    assert!(fts.columns[0].starts_with("(to_tsvector('spanish'::regconfig"), "{:?}", fts.columns);
    assert_eq!(o(ix(docs, "docs_id_brin"), "pages_per_range").as_deref(), Some("16"));
    let sala = ix(docs, "docs_sala_ux");
    assert!(sala.options.contains_key("nulls_not_distinct") && sala.filter.is_some());
    assert_eq!(ix(docs, "docs_cuerpo_hash").kind.as_deref(), Some("hash"));
    assert_eq!(docs.checks.len(), 1);
    assert_eq!(docs.checks[0].name.as_deref(), Some("docs_codigo_ck"));
    let get = |k: &str, n: &str| oa.get(&(k.to_string(), Some("app".to_string()), n.to_string())).cloned().unwrap_or_else(|| panic!("{k} {n}"));
    assert!(get("sequence", "folio").contains("AS integer INCREMENT BY 5 MINVALUE 1 MAXVALUE 2147483647 START WITH 100 CACHE 10 NO CYCLE"));
    assert!(get("sequence", "suelta").contains("OWNED BY \"app\".\"docs\".\"sala\""));
    assert_eq!(get("type", "mood"), "CREATE TYPE \"app\".\"mood\" AS ENUM ('bien', 'mal', 'así así');");
    assert!(get("type", "positivo").contains("DEFAULT 1 NOT NULL\n    CONSTRAINT positivo_ck CHECK ((VALUE > 0))"));
    assert_eq!(get("type", "punto"), "CREATE TYPE \"app\".\"punto\" AS (\n    x double precision,\n    y double precision\n);");
    assert!(get("type", "rango_fl").contains("SUBTYPE = double precision"));
    // Identity sequences and range constructors belong to their owner.
    assert!(!oa.keys().any(|(k, _, n)| k == "function" || n.contains("docs_id_seq")), "{:?}", oa.keys());
}

const PG_OPS: [(Op, &str); 7] = [
    (Op::Replace, "folio"),
    (Op::Create, "suelta"),
    (Op::Replace, "mood"),
    (Op::Replace, "positivo"),
    (Op::Create, "punto"),
    (Op::Create, "rango_fl"),
    (Op::Drop, "extra"),
];

fn ops(v: &[(Op, &str)]) -> Vec<(Op, String)> {
    v.iter().map(|(o, n)| (*o, n.to_string())).collect()
}

#[tokio::test]
#[ignore]
async fn postgres() {
    let Ok(url) = std::env::var("DBINE_TEST_POSTGRES_URL") else {
        eprintln!("DBINE_TEST_POSTGRES_URL not set; skipping");
        return;
    };
    assert_eq!(compare_and_sync("postgres", &url, PG_SOURCE, PG_TARGET, pg_inspect).await, ops(&PG_OPS));
}

#[tokio::test]
#[ignore]
async fn timescale() {
    let Ok(url) = std::env::var("DBINE_TEST_TIMESCALE_URL") else {
        eprintln!("DBINE_TEST_TIMESCALE_URL not set; skipping");
        return;
    };
    assert_eq!(compare_and_sync("timescaledb", &url, PG_SOURCE, PG_TARGET, pg_inspect).await, ops(&PG_OPS));
}

#[tokio::test]
#[ignore]
async fn cockroach() {
    let Ok(url) = std::env::var("DBINE_TEST_COCKROACH_URL") else {
        eprintln!("DBINE_TEST_COCKROACH_URL not set; skipping");
        return;
    };
    let got = compare_and_sync("cockroachdb", &url, CRDB_SOURCE, CRDB_TARGET, |ta, oa| {
        let docs = &ta["docs"];
        assert_eq!(ix(docs, "docs_codigo_uq").include, ["titulo"]);
        let t = ix(docs, "docs_titulo_ix");
        assert_eq!((t.include.as_slice(), t.options.get("keys").map(String::as_str)), (&["j".to_string()][..], Some("titulo DESC, codigo ASC")));
        assert_eq!(ix(docs, "docs_j_gin").kind.as_deref(), Some("gin"));
        assert_eq!(t.kind.as_deref(), Some("btree"));
        assert_eq!(ix(docs, "docs_lower_ix").columns, ["(lower(titulo))"]);
        assert_eq!(docs.checks.len(), 1);
        let get = |k: &str, n: &str| oa.get(&(k.to_string(), Some("app".to_string()), n.to_string())).cloned().unwrap_or_else(|| panic!("{k} {n}"));
        assert!(get("sequence", "folio").contains("INCREMENT BY 5") && get("sequence", "folio").contains("START WITH 100"));
        assert_eq!(get("type", "mood"), "CREATE TYPE \"app\".\"mood\" AS ENUM ('bien', 'mal', 'así así');");
        assert!(get("type", "punto").contains("x FLOAT8") || get("type", "punto").contains("x double precision"), "{}", get("type", "punto"));
    })
    .await;
    assert_eq!(got, ops(&[(Op::Replace, "folio"), (Op::Replace, "mood"), (Op::Create, "punto"), (Op::Drop, "extra")]));
}

const OG_SOURCE: &str = "
CREATE SCHEMA app;
CREATE TYPE app.mood AS ENUM ('bien', 'mal', 'así así');
CREATE TYPE app.punto AS (x double precision, y double precision);
CREATE SEQUENCE app.folio START WITH 100 INCREMENT BY 5 CACHE 10;
CREATE TABLE app.docs (
    id serial CONSTRAINT docs_pk PRIMARY KEY,
    codigo varchar(20) NOT NULL,
    titulo text NOT NULL,
    cuerpo text,
    animo app.mood,
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 2)
) WITH (storage_type = ustore);
ALTER TABLE app.docs ADD CONSTRAINT docs_codigo_uq UNIQUE (codigo) INCLUDE (titulo);
CREATE INDEX docs_titulo_ix ON app.docs USING ubtree (titulo DESC, lower(cuerpo)) INCLUDE (codigo) WITH (fillfactor = 80);
CREATE TABLE app.notas (id int PRIMARY KEY, texto text);
CREATE INDEX notas_fts_ix ON app.notas USING gin (to_tsvector('english', texto));
CREATE SYNONYM app.sin_docs FOR app.docs;
";

const OG_TARGET: &str = "
CREATE SCHEMA app;
CREATE TYPE app.mood AS ENUM ('bien', 'mal');
CREATE SEQUENCE app.folio;
CREATE SEQUENCE app.extra;
CREATE TABLE app.docs (
    id serial CONSTRAINT docs_pk PRIMARY KEY,
    codigo varchar(20) NOT NULL,
    titulo text NOT NULL,
    cuerpo text,
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 0)
) WITH (storage_type = ustore);
CREATE UNIQUE INDEX docs_codigo_uq ON app.docs (codigo);
CREATE INDEX docs_titulo_ix ON app.docs (titulo);
CREATE TABLE app.notas (id int PRIMARY KEY, texto text);
CREATE SYNONYM app.sin_viejo FOR app.notas;
";

/// openGauss: INCLUDE on ubtree (Ustore) indexes, synonyms.
///
/// ```sh
/// DBINE_TEST_OPENGAUSS_URL='postgres://gaussdb:Dbine@1234@localhost:25020/postgres' \
///   cargo test -p dbine-driver-postgres --test compare opengauss -- --ignored --nocapture
/// ```
#[tokio::test]
#[ignore]
async fn opengauss() {
    let Ok(url) = std::env::var("DBINE_TEST_OPENGAUSS_URL") else {
        eprintln!("DBINE_TEST_OPENGAUSS_URL not set; skipping");
        return;
    };
    let got = compare_and_sync("opengauss", &url, OG_SOURCE, OG_TARGET, |ta, oa| {
        let docs = &ta["docs"];
        let uq = ix(docs, "docs_codigo_uq");
        assert_eq!((uq.include.as_slice(), uq.options.get("constraint").map(String::as_str)), (&["titulo".to_string()][..], Some("UNIQUE (codigo) INCLUDE (titulo) WITH (storage_type=ustore, index_type=rcr)")));
        let t = ix(docs, "docs_titulo_ix");
        assert_eq!(t.include, ["codigo"]);
        assert_eq!(t.options.get("fillfactor").map(String::as_str), Some("80"));
        assert!(t.options.get("keys").is_some_and(|k| k.starts_with("titulo DESC")), "{t:?}");
        assert_eq!(docs.checks.len(), 1);
        assert!(ix(&ta["notas"], "notas_fts_ix").columns[0].starts_with("(to_tsvector("));
        let get = |k: &str, n: &str| oa.get(&(k.to_string(), Some("app".to_string()), n.to_string())).cloned().unwrap_or_else(|| panic!("{k} {n}"));
        assert_eq!(get("synonym", "sin_docs"), "CREATE SYNONYM \"app\".\"sin_docs\" FOR app.docs;");
        assert!(get("sequence", "folio").contains("START WITH 100"));
    })
    .await;
    assert_eq!(
        got,
        ops(&[(Op::Replace, "folio"), (Op::Create, "sin_docs"), (Op::Replace, "mood"), (Op::Create, "punto"), (Op::Drop, "extra"), (Op::Drop, "sin_viejo")])
    );
}

const H2_SOURCE: &str = "
CREATE SCHEMA app;
CREATE DOMAIN app.positivo AS integer DEFAULT 1 CHECK (VALUE > 0);
CREATE SEQUENCE app.folio START WITH 100 INCREMENT BY 5 CACHE 10;
CREATE TABLE app.docs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(20) NOT NULL,
    titulo varchar(200) NOT NULL,
    cant integer,
    g geometry,
    CONSTRAINT docs_pk PRIMARY KEY (id),
    CONSTRAINT docs_codigo_uq UNIQUE (codigo),
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 2)
);
CREATE INDEX docs_titulo_ix ON app.docs (titulo DESC, codigo);
CREATE HASH INDEX docs_cant_hash ON app.docs (cant);
CREATE SPATIAL INDEX docs_g_sp ON app.docs (g);
";

const H2_TARGET: &str = "
CREATE SCHEMA app;
CREATE DOMAIN app.positivo AS integer CHECK (VALUE >= 0);
CREATE SEQUENCE app.folio;
CREATE SEQUENCE app.extra;
CREATE TABLE app.docs (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    codigo varchar(20) NOT NULL,
    titulo varchar(200) NOT NULL,
    cant integer,
    g geometry,
    CONSTRAINT docs_pk PRIMARY KEY (id),
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 0)
);
CREATE UNIQUE INDEX docs_codigo_uq ON app.docs (codigo);
CREATE INDEX docs_titulo_ix ON app.docs (titulo);
";

/// H2 (PostgreSQL server mode): CHECK, indexes and UNIQUE constraints,
/// sequences and domains from its `information_schema`.
///
/// ```sh
/// DBINE_TEST_H2_URL=postgres://sa:sa@localhost:25025/test \
///   cargo test -p dbine-driver-postgres --test compare h2 -- --ignored --nocapture
/// ```
#[tokio::test]
#[ignore]
async fn h2() {
    let Ok(url) = std::env::var("DBINE_TEST_H2_URL") else {
        eprintln!("DBINE_TEST_H2_URL not set; skipping");
        return;
    };
    let got = compare_and_sync("h2", &url, H2_SOURCE, H2_TARGET, |ta, oa| {
        let docs = &ta["docs"];
        assert_eq!(ix(docs, "docs_codigo_uq").options.get("constraint").map(String::as_str), Some("UNIQUE (\"codigo\")"));
        assert_eq!(ix(docs, "docs_titulo_ix").options.get("keys").map(String::as_str), Some("\"titulo\" DESC, \"codigo\""));
        assert_eq!(ix(docs, "docs_cant_hash").kind.as_deref(), Some("HASH"));
        assert_eq!(ix(docs, "docs_g_sp").kind.as_deref(), Some("SPATIAL"));
        assert_eq!(docs.checks.len(), 1);
        let get = |k: &str, n: &str| oa.get(&(k.to_string(), Some("app".to_string()), n.to_string())).cloned().unwrap_or_else(|| panic!("{k} {n}"));
        assert!(get("sequence", "folio").contains("START WITH 100") && get("sequence", "folio").contains("CACHE 10"));
        assert!(get("domain", "positivo").contains("DEFAULT 1") && get("domain", "positivo").contains("CHECK (VALUE > 0)"), "{}", get("domain", "positivo"));
    })
    .await;
    assert_eq!(got, ops(&[(Op::Replace, "positivo"), (Op::Replace, "folio"), (Op::Drop, "extra")]));
}

const MZ_SOURCE: &str = "
CREATE SCHEMA app;
CREATE TYPE app.enteros AS LIST (ELEMENT TYPE = int4);
CREATE TYPE app.par AS (x int4, y text);
CREATE TABLE app.docs (id int NOT NULL, codigo text NOT NULL, titulo text);
CREATE INDEX docs_titulo_ix ON app.docs (titulo, lower(codigo));
CREATE INDEX docs_id_ix ON app.docs (id);
";

const MZ_TARGET: &str = "
CREATE SCHEMA app;
CREATE TYPE app.enteros AS LIST (ELEMENT TYPE = int8);
CREATE TABLE app.docs (id int NOT NULL, codigo text NOT NULL, titulo text);
CREATE INDEX docs_titulo_ix ON app.docs (titulo);
";

/// Materialize: indexes (arrangements) and list / map / record types.
///
/// ```sh
/// DBINE_TEST_MATERIALIZE_URL=postgres://materialize@localhost:25024/materialize \
///   cargo test -p dbine-driver-postgres --test compare materialize -- --ignored --nocapture
/// ```
#[tokio::test]
#[ignore]
async fn materialize() {
    let Ok(url) = std::env::var("DBINE_TEST_MATERIALIZE_URL") else {
        eprintln!("DBINE_TEST_MATERIALIZE_URL not set; skipping");
        return;
    };
    let got = compare_and_sync("materialize", &url, MZ_SOURCE, MZ_TARGET, |ta, oa| {
        assert_eq!(ix(&ta["docs"], "docs_titulo_ix").columns.len(), 2);
        let get = |n: &str| oa.get(&("type".to_string(), Some("app".to_string()), n.to_string())).cloned().unwrap_or_else(|| panic!("{n}"));
        assert!(get("enteros").starts_with("CREATE TYPE app.enteros AS LIST"), "{}", get("enteros"));
    })
    .await;
    assert_eq!(got, ops(&[(Op::Replace, "enteros"), (Op::Create, "par")]));
}

/// CrateDB: one namespace of schemas, so the two sides are `cmp_a` and
/// `cmp_b`. A new table comes out with its full-text indexes, `INDEX OFF`
/// columns and CHECKs; an existing one can't take them, and the sync says
/// the table must be made again.
///
/// ```sh
/// DBINE_TEST_CRATEDB_URL=postgres://crate@localhost:25041/doc \
///   cargo test -p dbine-driver-postgres --test compare cratedb -- --ignored --nocapture
/// ```
#[tokio::test]
#[ignore]
async fn cratedb() {
    let Ok(url) = std::env::var("DBINE_TEST_CRATEDB_URL") else {
        eprintln!("DBINE_TEST_CRATEDB_URL not set; skipping");
        return;
    };
    let d = driver("cratedb");
    let mut s = d.connect(&parse_url("cratedb", &url), None).await.expect("connect");
    let clean = "DROP TABLE IF EXISTS cmp_a.docs;\nDROP TABLE IF EXISTS cmp_a.nuevos;\nDROP TABLE IF EXISTS cmp_b.docs;\nDROP TABLE IF EXISTS cmp_b.nuevos";
    run_all(&mut s, clean).await;
    run_all(
        &mut s,
        "CREATE TABLE cmp_a.docs (id int PRIMARY KEY, titulo text, cuerpo text, nota text INDEX OFF,
             CONSTRAINT docs_ck CHECK (id > 0), INDEX ft USING FULLTEXT (titulo, cuerpo) WITH (analyzer = 'english'));
         CREATE TABLE cmp_a.nuevos (id int PRIMARY KEY, b text INDEX USING FULLTEXT WITH (analyzer = 'spanish'), c text,
             d text INDEX OFF, INDEX ft USING FULLTEXT (c), CONSTRAINT nuevos_ck CHECK (id < 100), CHECK (length(c) > 1));
         CREATE TABLE cmp_b.docs (id int PRIMARY KEY, titulo text, cuerpo text, nota text INDEX OFF, CONSTRAINT viejo_ck CHECK (id > -1))",
    )
    .await;
    let ta = crate_read(&mut s, "cmp_a").await;
    let tb = crate_read(&mut s, "cmp_b").await;
    eprintln!("{ta:#?}");
    let nuevos = &ta["nuevos"];
    assert_eq!(ix(nuevos, "b").options.get("analyzer").map(String::as_str), Some("spanish"));
    assert_eq!(ix(nuevos, "d").kind.as_deref(), Some("OFF"));
    assert_eq!(ix(nuevos, "ft").columns, ["c"]);
    assert_eq!(nuevos.checks.len(), 2);
    assert_eq!(ix(&ta["docs"], "ft").options.get("analyzer").map(String::as_str), Some("english"));

    let changes = vec![
        TableChange::Alter { old: tb["docs"].clone(), new: ta["docs"].clone() },
        TableChange::Create { table: ta["nuevos"].clone() },
    ];
    let script = d.sync_script(&changes).unwrap();
    eprintln!("{}\n{:?}", script.statements.join("\n"), script.warnings);
    assert!(script.warnings.iter().any(|w| w.contains("cmp_b.docs") && w.contains("recrear la tabla")), "{:?}", script.warnings);
    for st in &script.statements {
        run(&mut s, st).await.unwrap_or_else(|e| panic!("{e}\n{st}"));
    }
    let tb2 = crate_read(&mut s, "cmp_b").await;
    assert_eq!(tb2["nuevos"], ta["nuevos"]);
    // docs keeps what it had: no full-text index, and its old CHECK dropped only if not replaced.
    assert!(tb2["docs"].indexes.iter().all(|i| i.name != "ft"));
    run_all(&mut s, clean).await;
}

/// One CrateDB schema's tables, named as if they were in `cmp_b`.
async fn crate_read(s: &mut Box<dyn Session>, schema: &str) -> BTreeMap<String, TableSchema> {
    s.database_schema()
        .await
        .unwrap()
        .into_iter()
        .filter(|t| t.schema.as_deref() == Some(schema))
        .map(|mut t| {
            t.schema = Some("cmp_b".into());
            (t.name.clone(), normalized(t))
        })
        .collect()
}

/// RisingWave: indexes with INCLUDE, DESC keys and DISTRIBUTED BY.
///
/// ```sh
/// DBINE_TEST_RISINGWAVE_URL=postgres://root@localhost:25042/dev \
///   cargo test -p dbine-driver-postgres --test compare risingwave -- --ignored --nocapture
/// ```
#[tokio::test]
#[ignore]
async fn risingwave() {
    let Ok(url) = std::env::var("DBINE_TEST_RISINGWAVE_URL") else {
        eprintln!("DBINE_TEST_RISINGWAVE_URL not set; skipping");
        return;
    };
    let table = "CREATE SCHEMA app;\nCREATE TABLE app.docs (id int PRIMARY KEY, a int, b varchar, c varchar);\n";
    let source = format!(
        "{table}CREATE INDEX docs_ix ON app.docs (a DESC, b) INCLUDE (c);\nCREATE INDEX docs_ix2 ON app.docs (lower(b)) DISTRIBUTED BY (lower(b));\nCREATE INDEX docs_todo ON app.docs (c);\n"
    );
    let target = format!("{table}CREATE INDEX docs_ix ON app.docs (a);\n");
    let got = compare_and_sync("risingwave", &url, &source, &target, |ta, _| {
        let docs = &ta["docs"];
        let i = ix(docs, "docs_ix");
        assert_eq!((i.include.as_slice(), i.options.get("keys").map(String::as_str)), (&["c".to_string()][..], Some("a DESC, b")));
        assert_eq!(ix(docs, "docs_ix2").options.get("distributed_by").map(String::as_str), Some("lower(b)"));
        assert!(ix(docs, "docs_todo").include.is_empty());
    })
    .await;
    assert!(got.is_empty());
}

const YB_SOURCE: &str = "
CREATE SCHEMA app;
CREATE TYPE app.mood AS ENUM ('bien', 'mal', 'así así');
CREATE DOMAIN app.positivo AS integer DEFAULT 1 NOT NULL CONSTRAINT positivo_ck CHECK (VALUE > 0);
CREATE TYPE app.punto AS (x double precision, y double precision);
CREATE TYPE app.rango_fl AS RANGE (SUBTYPE = double precision);
CREATE SEQUENCE app.folio AS integer START WITH 100 INCREMENT BY 5 CACHE 10;
CREATE TABLE app.docs (
    id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT docs_pk PRIMARY KEY,
    codigo varchar(20) NOT NULL,
    titulo text NOT NULL,
    cuerpo text,
    sala integer,
    animo app.mood,
    CONSTRAINT docs_codigo_uq UNIQUE NULLS NOT DISTINCT (codigo) INCLUDE (titulo),
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 2)
);
CREATE INDEX docs_titulo_ix ON app.docs (titulo DESC, lower(cuerpo)) INCLUDE (codigo);
CREATE INDEX docs_sala_hash ON app.docs (sala HASH);
CREATE INDEX docs_fts_ix ON app.docs USING ybgin (to_tsvector('spanish', titulo));
CREATE UNIQUE INDEX docs_sala_ux ON app.docs (sala) WHERE sala > 0;
";

const YB_TARGET: &str = "
CREATE SCHEMA app;
CREATE TYPE app.mood AS ENUM ('bien', 'mal');
CREATE SEQUENCE app.folio AS integer;
CREATE SEQUENCE app.extra;
CREATE TABLE app.docs (
    id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT docs_pk PRIMARY KEY,
    codigo varchar(20) NOT NULL,
    titulo text NOT NULL,
    cuerpo text,
    sala integer,
    CONSTRAINT docs_codigo_ck CHECK (length(codigo) > 0)
);
CREATE UNIQUE INDEX docs_codigo_uq ON app.docs (codigo);
CREATE INDEX docs_titulo_ix ON app.docs (titulo);
";

/// YugabyteDB: lsm indexes with HASH / ASC / DESC keys, INCLUDE, ybgin
/// full-text, NULLS NOT DISTINCT, sequences and types.
///
/// ```sh
/// DBINE_TEST_YUGABYTE_URL=postgres://yugabyte@localhost:25043/yugabyte \
///   cargo test -p dbine-driver-postgres --test compare yugabyte -- --ignored --nocapture
/// ```
#[tokio::test]
#[ignore]
async fn yugabyte() {
    let Ok(url) = std::env::var("DBINE_TEST_YUGABYTE_URL") else {
        eprintln!("DBINE_TEST_YUGABYTE_URL not set; skipping");
        return;
    };
    let got = compare_and_sync("yugabytedb", &url, YB_SOURCE, YB_TARGET, |ta, oa| {
        let docs = &ta["docs"];
        let uq = ix(docs, "docs_codigo_uq");
        assert_eq!(uq.include, ["titulo"]);
        assert!(uq.options.get("constraint").is_some_and(|c| c.contains("NULLS NOT DISTINCT")), "{uq:?}");
        let t = ix(docs, "docs_titulo_ix");
        assert_eq!(t.include, ["codigo"]);
        assert!(t.options.get("keys").is_some_and(|k| k.starts_with("titulo DESC")), "{t:?}");
        assert!(ix(docs, "docs_sala_hash").options.get("keys").is_some_and(|k| k.contains("HASH")));
        assert_eq!(ix(docs, "docs_fts_ix").kind.as_deref(), Some("ybgin"));
        assert_eq!(docs.checks.len(), 1);
        assert!(oa.contains_key(&("type".to_string(), Some("app".to_string()), "rango_fl".to_string())));
    })
    .await;
    assert_eq!(
        got,
        ops(&[(Op::Replace, "folio"), (Op::Replace, "mood"), (Op::Create, "positivo"), (Op::Create, "punto"), (Op::Create, "rango_fl"), (Op::Drop, "extra")])
    );
}

/// Both sides start the same; "Eliminar" then drops on one side or both.
const DROP_SCHEMA: &str = "
CREATE SCHEMA app;
CREATE TABLE app.padre (id int PRIMARY KEY, nombre text NOT NULL, CONSTRAINT padre_nombre_ck CHECK (length(nombre) > 0));
CREATE INDEX padre_nombre_ix ON app.padre (nombre);
CREATE TABLE app.hijo (id int CONSTRAINT hijo_pk PRIMARY KEY, padre_id int, nota text, extra text,
    CONSTRAINT hijo_padre_fk FOREIGN KEY (padre_id) REFERENCES app.padre (id),
    CONSTRAINT hijo_nota_ck CHECK (nota <> ''));
CREATE INDEX hijo_nota_ix ON app.hijo (nota);
CREATE INDEX hijo_padre_ix ON app.hijo (padre_id);
CREATE TABLE app.nieto (id int PRIMARY KEY, hijo_id int, CONSTRAINT nieto_hijo_fk FOREIGN KEY (hijo_id) REFERENCES app.hijo (id));
CREATE VIEW app.v1 AS SELECT id, nombre FROM app.padre;
CREATE VIEW app.v2 AS SELECT id FROM app.v1;
CREATE FUNCTION app.audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
CREATE TRIGGER marca BEFORE INSERT ON app.hijo FOR EACH ROW EXECUTE FUNCTION app.audit();
CREATE TRIGGER marca BEFORE UPDATE ON app.nieto FOR EACH ROW EXECUTE FUNCTION app.audit();
CREATE FUNCTION app.f(a integer) RETURNS integer LANGUAGE sql AS $$ SELECT a $$;
CREATE FUNCTION app.f(a text) RETURNS integer LANGUAGE sql AS $$ SELECT length(a) $$;
CREATE PROCEDURE app.p() LANGUAGE sql AS $$ SELECT 1 $$;
";

/// `t` without the item `pred` picks in one of its lists, as CompareView's
/// `removeItem` leaves the side's work copy.
fn without(t: &TableSchema, f: impl FnOnce(&mut TableSchema)) -> TableSchema {
    let mut n = t.clone();
    f(&mut n);
    n
}

/// Runs the script CompareView's sync would make for one side: `tables` as
/// `changesOf` gives them, `objects` (kind, name) dropped.
async fn sync_side(d: &dyn Driver, s: &mut Box<dyn Session>, tables: &[TableChange], objects: &[(&str, &str)], read_objects: &Objects) {
    let mut objs = Vec::new();
    for ((k, sc, n), def) in read_objects {
        if objects.contains(&(k.as_str(), n.as_str())) {
            objs.push((Op::Drop, k.clone(), sc.clone(), n.clone(), def.clone()));
        }
    }
    assert_eq!(objs.len(), objects.len(), "{objects:?} in {:?}", read_objects.keys());
    let statements = plan(d, tables, &objs);
    eprintln!("---- drop script\n{}", statements.join("\n"));
    for st in &statements {
        run(s, st).await.unwrap_or_else(|e| panic!("{e}\n---\n{st}\n---\nwhole script:\n{}", statements.join("\n")));
    }
}

/// "Eliminar" in the compare, against a live server: an index on one side
/// and then the other (the difference goes), and on both sides at once an
/// index, a column, a foreign key, a CHECK, the primary key (kept with a
/// warning where the engine needs one: `pk_drops` false), a table other tables reference (their keys go
/// first), two views over each other, a same-named trigger on two tables
/// and its function, overloaded functions and a procedure.
async fn compare_drops(id: &str, url: &str, pk_drops: bool) {
    let cfg = parse_url(id, url);
    let d = driver(id);
    let mut admin = d.connect(&cfg, None).await.expect("connect");
    let (a_db, b_db) = ("dbine_drop_a", "dbine_drop_b");
    for db in [a_db, b_db] {
        let _ = admin.drop_database(db).await;
        admin.create_database(db).await.expect("create_database");
    }
    let mut a = d.connect(&cfg, Some(a_db)).await.unwrap();
    let mut b = d.connect(&cfg, Some(b_db)).await.unwrap();
    run_all(&mut a, DROP_SCHEMA).await;
    run_all(&mut b, DROP_SCHEMA).await;
    let (ta, oa) = read(&mut a).await;
    let (tb, ob) = read(&mut b).await;
    assert_eq!(ta, tb);
    assert_eq!(oa.keys().collect::<Vec<_>>(), ob.keys().collect::<Vec<_>>());
    for k in [("view", "v1"), ("view", "v2"), ("function", "audit"), ("trigger", "marca"), ("function", "f"), ("procedure", "p")] {
        assert!(oa.keys().any(|(kind, _, n)| (kind.as_str(), n.as_str()) == k), "{k:?} in {:?}", oa.keys());
    }
    eprintln!("-- marca\n{}\n-- f\n{}", oa.iter().find(|(k, _)| k.2 == "marca").unwrap().1, oa.iter().find(|(k, _)| k.2 == "f").unwrap().1);

    // An unused index, dropped on the left only: the difference is just that.
    let no_ix = |t: &TableSchema| without(t, |n| n.indexes.retain(|i| i.name != "padre_nombre_ix"));
    sync_side(d.as_ref(), &mut a, &[TableChange::Alter { old: ta["padre"].clone(), new: no_ix(&ta["padre"]) }], &[], &oa).await;
    let (ta1, _) = read(&mut a).await;
    assert!(ta1["padre"].indexes.iter().all(|i| i.name != "padre_nombre_ix"));
    assert_eq!(ta1["padre"], no_ix(&tb["padre"]));
    assert_ne!(ta1, tb);
    // Then on the right: both read the same again.
    sync_side(d.as_ref(), &mut b, &[TableChange::Alter { old: tb["padre"].clone(), new: no_ix(&tb["padre"]) }], &[], &ob).await;
    let (tb1, _) = read(&mut b).await;
    assert_eq!(ta1, tb1);

    // The rest on both sides at once, as the two tabs of the sync dialog.
    let objects = [("view", "v1"), ("view", "v2"), ("trigger", "marca"), ("function", "audit"), ("function", "f"), ("procedure", "p")];
    for (s, t, o) in [(&mut a, &ta1, &oa), (&mut b, &tb1, &ob)] {
        let hijo = without(&t["hijo"], |n| {
            n.indexes.retain(|i| i.name != "hijo_nota_ix");
            n.columns.retain(|c| c.name != "extra");
            n.checks.retain(|c| c.name.as_deref() != Some("hijo_nota_ck"));
            // Padre goes: the key that references it too (CompareView's cascade).
            n.foreign_keys.retain(|f| f.name.as_deref() != Some("hijo_padre_fk"));
            n.primary_key = None;
        });
        let nieto = without(&t["nieto"], |n| n.foreign_keys.retain(|f| f.name.as_deref() != Some("nieto_hijo_fk")));
        let tables = [
            TableChange::Alter { old: t["hijo"].clone(), new: hijo },
            TableChange::Alter { old: t["nieto"].clone(), new: nieto },
            TableChange::Drop { table: t["padre"].clone() },
        ];
        let warnings = d.sync_script(&tables).expect("sync_script").warnings;
        assert_eq!(warnings.iter().any(|w| w.contains("sin clave primaria: app.hijo")), !pk_drops, "{warnings:?}");
        sync_side(d.as_ref(), s, &tables, &objects, o).await;
    }
    let (ta2, oa2) = read(&mut a).await;
    let (tb2, ob2) = read(&mut b).await;
    eprintln!("{ta2:#?}");
    assert_eq!(ta2.keys().collect::<Vec<_>>(), ["hijo", "nieto"]);
    let hijo = &ta2["hijo"];
    assert!(hijo.indexes.iter().all(|i| i.name != "hijo_nota_ix"), "{:?}", hijo.indexes);
    assert!(hijo.indexes.iter().any(|i| i.name == "hijo_padre_ix"), "{:?}", hijo.indexes);
    assert_eq!(hijo.columns.iter().map(|c| c.name.as_str()).collect::<Vec<_>>(), ["id", "padre_id", "nota"]);
    assert!(hijo.checks.is_empty(), "{:?}", hijo.checks);
    assert!(hijo.foreign_keys.is_empty(), "{:?}", hijo.foreign_keys);
    assert_eq!(hijo.primary_key.is_none(), pk_drops, "{:?}", hijo.primary_key);
    assert!(ta2["nieto"].foreign_keys.is_empty());
    assert!(oa2.is_empty(), "{:?}", oa2.keys());
    // Recompared: nothing left between the sides.
    assert_eq!(ta2, tb2);
    assert_eq!(oa2, ob2);

    drop(a);
    drop(b);
    for db in [a_db, b_db] {
        admin.drop_database(db).await.expect("drop_database");
    }
}

#[tokio::test]
#[ignore]
async fn postgres_drops() {
    let Ok(url) = std::env::var("DBINE_TEST_POSTGRES_URL") else {
        eprintln!("DBINE_TEST_POSTGRES_URL not set; skipping");
        return;
    };
    compare_drops("postgres", &url, true).await;
}

/// CockroachDB won't drop a primary key without adding another in the
/// same transaction: the sync keeps it and says so.
#[tokio::test]
#[ignore]
async fn cockroach_drops() {
    let Ok(url) = std::env::var("DBINE_TEST_COCKROACH_URL") else {
        eprintln!("DBINE_TEST_COCKROACH_URL not set; skipping");
        return;
    };
    compare_drops("cockroachdb", &url, false).await;
}

/// A primary key that changes (an arrow, not a drop) goes in one statement
/// on CockroachDB: dropped and added in the same transaction.
#[tokio::test]
#[ignore]
async fn cockroach_changes_a_primary_key() {
    let Ok(url) = std::env::var("DBINE_TEST_COCKROACH_URL") else {
        eprintln!("DBINE_TEST_COCKROACH_URL not set; skipping");
        return;
    };
    let cfg = parse_url("cockroachdb", &url);
    let d = driver("cockroachdb");
    let mut admin = d.connect(&cfg, None).await.expect("connect");
    let db = "dbine_pk_change";
    let _ = admin.drop_database(db).await;
    admin.create_database(db).await.expect("create_database");
    let mut s = d.connect(&cfg, Some(db)).await.unwrap();
    run_all(&mut s, "CREATE SCHEMA app;\nCREATE TABLE app.t (id INT8 NOT NULL, a INT8 NOT NULL, CONSTRAINT t_pk PRIMARY KEY (id));\nINSERT INTO app.t VALUES (1, 10), (2, 20)").await;
    let (t, _) = read(&mut s).await;
    let old = t["t"].clone();
    let mut new = old.clone();
    new.primary_key = Some(dbine_driver::KeyDef { name: Some("t_pk2".into()), columns: vec!["a".into()] });
    let script = d.sync_script(&[TableChange::Alter { old, new: new.clone() }]).expect("sync_script");
    eprintln!("{:#?}", script.statements);
    assert!(script.statements.iter().all(|x| x != "ALTER TABLE \"app\".\"t\" DROP CONSTRAINT \"t_pk\";"), "{:?}", script.statements);
    for st in &script.statements {
        run(&mut s, st).await.unwrap_or_else(|e| panic!("{e}\n---\n{st}"));
    }
    let (t2, _) = read(&mut s).await;
    let got = &t2["t"];
    assert_eq!(got.primary_key.as_ref().map(|k| k.columns.clone()), Some(vec!["a".to_string()]), "{got:#?}");
    assert_eq!(got.primary_key.as_ref().and_then(|k| k.name.clone()).as_deref(), Some("t_pk2"));
    // No unique index left behind for the old key.
    assert!(got.indexes.is_empty(), "{:?}", got.indexes);
    drop(s);
    admin.drop_database(db).await.expect("drop_database");
}
