//! Structure, DDL round trip and database create/drop against real
//! servers. Each test reads `DBINE_TEST_<ENGINE>_URL` like `integration.rs`:
//!
//! ```sh
//! DBINE_TEST_POSTGRES_URL=postgres://postgres:pw@localhost:26011/postgres \
//! DBINE_TEST_COCKROACH_URL=postgres://root@localhost:26014/defaultdb \
//!   cargo test -p dbine-driver-postgres --test schema -- --ignored
//! ```

use dbine_driver::{ConnectionConfig, DdlParts, Driver, ObjectRef, QueryOutcome, Session};
use serde_json::json;
use std::sync::Arc;

fn parse_url(driver: &str, url: &str) -> ConnectionConfig {
    let rest = url.split_once("://").map_or(url, |(_, r)| r);
    let (auth, hostpart) = rest.rsplit_once('@').unwrap_or(("", rest));
    let (user, pass) = auth.split_once(':').map_or((auth, None), |(u, p)| (u, Some(p)));
    let (hostport, db) = hostpart.split_once('/').unwrap_or((hostpart, ""));
    let (host, port) = hostport.rsplit_once(':').map_or((hostport, 0), |(h, p)| (h, p.parse().unwrap()));
    ConnectionConfig {
        driver: driver.into(),
        host: host.into(),
        port,
        database: db.into(),
        username: (!user.is_empty()).then(|| user.into()),
        password: pass.map(Into::into),
        ..Default::default()
    }
}

fn driver(id: &str) -> Arc<dyn Driver> {
    dbine_driver_postgres::drivers().into_iter().find(|d| d.info().id == id).unwrap()
}

async fn run(s: &mut Box<dyn Session>, sql: &str) {
    let mut out = QueryOutcome::default();
    s.execute(sql, 100, &mut out).await.unwrap_or_else(|e| panic!("{e}\n---\n{sql}"));
}

const SOURCE: &str = r#"
CREATE SCHEMA app;
CREATE TABLE app.clientes (
    id integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT clientes_pk PRIMARY KEY,
    email varchar(120) NOT NULL,
    nombre text NOT NULL DEFAULT 'sin nombre',
    alta timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE app.pedidos (
    id bigserial CONSTRAINT pedidos_pk PRIMARY KEY,
    cliente_id integer NOT NULL CONSTRAINT pedidos_cliente_fk REFERENCES app.clientes (id) ON DELETE CASCADE,
    estado varchar(20),
    total numeric(18,2) NOT NULL DEFAULT 0
);
CREATE TABLE app.items (
    pedido_id bigint NOT NULL,
    linea integer NOT NULL,
    cliente_id integer,
    producto text,
    CONSTRAINT items_pk PRIMARY KEY (pedido_id, linea),
    CONSTRAINT items_pedido_fk FOREIGN KEY (pedido_id) REFERENCES app.pedidos (id) ON DELETE CASCADE,
    CONSTRAINT items_cliente_fk FOREIGN KEY (cliente_id) REFERENCES app.clientes (id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX clientes_email_ux ON app.clientes (lower(email));
CREATE INDEX pedidos_estado_ix ON app.pedidos (estado, total) WHERE estado IS NOT NULL;
COMMENT ON TABLE app.clientes IS 'Clientes de la tienda';
COMMENT ON COLUMN app.clientes.email IS 'Correo único';
"#;

async fn round_trip(id: &str, env: &str) {
    let Ok(url) = std::env::var(env) else {
        eprintln!("{env} not set; skipping");
        return;
    };
    let cfg = parse_url(id, &url);
    let d = driver(id);
    let mut admin = d.connect(&cfg, None).await.expect("connect");
    for db in ["dbine_ddl_src", "dbine_ddl_dst"] {
        let _ = admin.drop_database(db).await;
        admin.create_database(db).await.expect("create_database");
    }
    assert!(admin.list_databases().await.unwrap().contains(&"dbine_ddl_src".to_string()));

    let mut src = d.connect(&cfg, Some("dbine_ddl_src")).await.unwrap();
    // openGauss has no identity columns: serial instead.
    let source = if id == "opengauss" { SOURCE.replace("integer GENERATED BY DEFAULT AS IDENTITY", "serial") } else { SOURCE.to_string() };
    run(&mut src, &source).await;
    let schema = src.database_schema().await.unwrap();
    for t in &schema {
        eprintln!("{t:?}");
    }
    let names: Vec<&str> = schema.iter().map(|t| t.name.as_str()).collect();
    assert_eq!(names, ["clientes", "items", "pedidos"]);
    let clientes = &schema[0];
    assert_eq!(clientes.comment.as_deref(), Some("Clientes de la tienda"));
    assert_eq!(clientes.columns[1].comment.as_deref(), Some("Correo único"));
    assert!(clientes.columns[0].auto_increment);
    assert_eq!(clientes.primary_key.as_ref().unwrap().name.as_deref(), Some("clientes_pk"));
    let ux = clientes.indexes.iter().find(|i| i.name == "clientes_email_ux").unwrap();
    assert!(ux.unique);
    assert!(ux.columns[0].starts_with("(lower("), "{:?}", ux.columns);
    let items = &schema[1];
    assert_eq!(items.primary_key.as_ref().unwrap().columns, ["pedido_id", "linea"]);
    assert_eq!(items.foreign_keys.len(), 2);
    let fk = items.foreign_keys.iter().find(|f| f.name.as_deref() == Some("items_cliente_fk")).unwrap();
    assert_eq!((fk.ref_table.as_str(), fk.on_delete.as_deref()), ("clientes", Some("SET NULL")));
    let pedidos = &schema[2];
    if id == "cockroachdb" {
        // CockroachDB's serial is a unique_rowid() default, kept as such.
        assert_eq!(pedidos.columns[0].default_value.as_deref(), Some("unique_rowid()"));
    } else {
        assert!(pedidos.columns[0].auto_increment && pedidos.columns[0].default_value.is_none(), "bigserial");
    }
    let ix = pedidos.indexes.iter().find(|i| i.name == "pedidos_estado_ix").unwrap();
    assert_eq!(ix.columns, ["estado", "total"]);
    assert!(ix.filter.as_deref().unwrap().contains("estado IS NOT NULL"));

    let mut script = vec!["CREATE SCHEMA app;".to_string()];
    for t in &schema {
        script.push(d.table_ddl(t, DdlParts { create: true, if_exists: true, ..Default::default() }).unwrap());
    }
    for t in &schema {
        script.push(d.table_ddl(t, DdlParts { indexes: true, foreign_keys: true, if_exists: true, ..Default::default() }).unwrap());
    }
    let script = script.join("\n");
    eprintln!("{script}");
    let mut dst = d.connect(&cfg, Some("dbine_ddl_dst")).await.unwrap();
    run(&mut dst, &script).await;
    let copy = dst.database_schema().await.unwrap();
    assert_eq!(copy, schema);
    // Guards: the same script again changes nothing.
    run(&mut dst, &script.replacen("CREATE SCHEMA app;", "", 1)).await;

    let target = |n: &str| ObjectRef { kind: "table".into(), schema: Some("app".into()), name: n.into() };
    let ins = d
        .insert_script(&target("clientes"), &["email".into(), "nombre".into()], &[vec![json!("a@x.com"), json!("Año O'Brien")], vec![json!("b@x.com"), json!("Beto")]])
        .unwrap();
    run(&mut dst, &ins).await;
    let ins = d.insert_script(&target("pedidos"), &["cliente_id".into(), "estado".into(), "total".into()], &[vec![json!(1), json!("nuevo"), json!(10.5)]]).unwrap();
    run(&mut dst, &ins).await;

    assert!(dst.drop_database("dbine_ddl_dst").await.is_err(), "own database");
    drop(src);
    // `dst` stays connected: the drop ends that session.
    for db in ["dbine_ddl_src", "dbine_ddl_dst"] {
        admin.drop_database(db).await.expect("drop_database");
    }
    assert!(!admin.list_databases().await.unwrap().contains(&"dbine_ddl_dst".to_string()));
}

#[tokio::test]
#[ignore]
async fn postgres_schema_round_trip() {
    round_trip("postgres", "DBINE_TEST_POSTGRES_URL").await;
}

/// Identity columns keep ALWAYS and their sequence options through
/// `database_schema` + `table_ddl`.
#[tokio::test]
#[ignore]
async fn postgres_identity_options_round_trip() {
    let Ok(url) = std::env::var("DBINE_TEST_POSTGRES_URL") else {
        eprintln!("DBINE_TEST_POSTGRES_URL not set; skipping");
        return;
    };
    let cfg = parse_url("postgres", &url);
    let d = driver("postgres");
    let mut admin = d.connect(&cfg, None).await.expect("connect");
    for db in ["dbine_ident_src", "dbine_ident_dst"] {
        let _ = admin.drop_database(db).await;
        admin.create_database(db).await.expect("create_database");
    }
    let mut src = d.connect(&cfg, Some("dbine_ident_src")).await.unwrap();
    run(
        &mut src,
        "CREATE TABLE contadores (
            id int GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5) PRIMARY KEY,
            ronda smallint GENERATED ALWAYS AS IDENTITY (MINVALUE 10 MAXVALUE 50 CACHE 3 CYCLE),
            plano bigint GENERATED BY DEFAULT AS IDENTITY,
            baja integer GENERATED ALWAYS AS IDENTITY (INCREMENT BY -1),
            viejo serial
        );
        ALTER SEQUENCE contadores_viejo_seq RESTART WITH 1 START WITH 7;",
    )
    .await;
    let schema = src.database_schema().await.unwrap();
    let t = schema.iter().find(|t| t.name == "contadores").unwrap();
    let opt = |i: usize| t.columns[i].options.get("identity").cloned();
    assert_eq!(opt(0).as_deref(), Some("BY DEFAULT (START WITH 100 INCREMENT BY 5)"));
    assert_eq!(opt(1).as_deref(), Some("ALWAYS (MINVALUE 10 MAXVALUE 50 CACHE 3 CYCLE)"));
    assert_eq!(opt(2), None);
    assert_eq!(opt(3).as_deref(), Some("ALWAYS (INCREMENT BY -1)"));
    assert_eq!(opt(4).as_deref(), Some("BY DEFAULT (START WITH 7)"));

    let ddl = d.table_ddl(t, DdlParts { create: true, indexes: true, foreign_keys: true, ..Default::default() }).unwrap();
    eprintln!("{ddl}");
    assert!(ddl.contains("\"id\" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5) NOT NULL"), "{ddl}");
    assert!(ddl.contains("\"ronda\" smallint GENERATED ALWAYS AS IDENTITY (MINVALUE 10 MAXVALUE 50 CACHE 3 CYCLE) NOT NULL"), "{ddl}");
    assert!(ddl.contains("\"plano\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"), "{ddl}");

    let mut dst = d.connect(&cfg, Some("dbine_ident_dst")).await.unwrap();
    run(&mut dst, &ddl).await;
    let copy = dst.database_schema().await.unwrap();
    assert_eq!(copy, schema);
    run(&mut dst, "INSERT INTO contadores DEFAULT VALUES; INSERT INTO contadores DEFAULT VALUES;").await;
    let mut out = QueryOutcome::default();
    dst.execute("SELECT max(id), max(ronda), min(baja), max(viejo) FROM contadores", 10, &mut out).await.unwrap();
    assert_eq!(out.results[0].rows[0], vec![json!("105"), json!("11"), json!("-2"), json!("8")]);

    drop((src, dst));
    for db in ["dbine_ident_src", "dbine_ident_dst"] {
        admin.drop_database(db).await.expect("drop_database");
    }
}

#[tokio::test]
#[ignore]
async fn cockroach_schema_round_trip() {
    round_trip("cockroachdb", "DBINE_TEST_COCKROACH_URL").await;
}

#[tokio::test]
#[ignore]
async fn opengauss_schema_round_trip() {
    round_trip("opengauss", "DBINE_TEST_OPENGAUSS_URL").await;
}
