//! Against a real server:
//!
//! ```sh
//! docker run -d --name dbine-test-firebird -p 25602:3050 -e FIREBIRD_ROOT_PASSWORD=masterkey \
//!   -e FIREBIRD_DATABASE=test.fdb -e FIREBIRD_USER=dbine -e FIREBIRD_PASSWORD=dbine firebirdsql/firebird:5
//! DBINE_TEST_FIREBIRD_URL=firebird://dbine:dbine@localhost:25602//var/lib/firebird/data/test.fdb \
//!   cargo test -p dbine-driver-firebird -- --ignored
//! ```

use dbine_driver::{ConnectionConfig, ObjectRef, QueryOutcome, Session};
use serde_json::json;

fn config() -> ConnectionConfig {
    let url = std::env::var("DBINE_TEST_FIREBIRD_URL").expect("DBINE_TEST_FIREBIRD_URL");
    let rest = url.strip_prefix("firebird://").expect("firebird://user:pass@host:port/path");
    let (cred, addr) = rest.split_once('@').unwrap();
    let (user, pass) = cred.split_once(':').unwrap();
    let (hostport, path) = addr.split_once('/').unwrap();
    let (host, port) = hostport.split_once(':').unwrap();
    ConnectionConfig {
        driver: "firebird".into(),
        host: host.into(),
        port: port.parse().unwrap(),
        database: path.into(),
        username: Some(user.into()),
        password: Some(pass.into()),
        ..Default::default()
    }
}

async fn session() -> Box<dyn Session> {
    let driver = dbine_driver_firebird::drivers().remove(0);
    driver.connect(&config(), None).await.expect("connect")
}

async fn run(s: &mut Box<dyn Session>, sql: &str) -> QueryOutcome {
    let mut out = QueryOutcome::default();
    if let Err(e) = s.execute(sql, 1000, &mut out).await {
        panic!("{sql}: {e}");
    }
    out
}

fn obj(kind: &str, name: &str) -> ObjectRef {
    ObjectRef { kind: kind.into(), schema: None, name: name.into() }
}

const DROPS: &[&str] = &[
    "DROP TRIGGER dbine_trg",
    "DROP VIEW dbine_v",
    "DROP PROCEDURE dbine_proc",
    "DROP FUNCTION dbine_fn",
    "DROP PACKAGE BODY dbine_pkg",
    "DROP PACKAGE dbine_pkg",
    "DROP TABLE dbine_t",
    "DROP SEQUENCE dbine_seq",
];

async fn clean(s: &mut Box<dyn Session>) {
    for d in DROPS {
        let _ = s.execute(d, 10, &mut QueryOutcome::default()).await;
    }
}

#[tokio::test]
#[ignore]
async fn catalog_values_and_scripts() {
    let mut s = session().await;
    let v = s.server_version().await.unwrap();
    assert!(v.starts_with("Firebird "), "{v}");
    clean(&mut s).await;

    let script = r#"
CREATE TABLE dbine_t (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(50) DEFAULT 'x' NOT NULL,
  amount NUMERIC(12,2),
  big INT128,
  ts TIMESTAMP,
  d DATE,
  t TIME,
  doc BLOB SUB_TYPE TEXT,
  bin CHAR(4) CHARACTER SET OCTETS,
  flag BOOLEAN,
  ident INTEGER GENERATED BY DEFAULT AS IDENTITY
);
CREATE VIEW dbine_v AS SELECT id, name FROM dbine_t;
CREATE SEQUENCE dbine_seq;
SET TERM ^ ;
CREATE OR ALTER PROCEDURE dbine_proc (a INTEGER) RETURNS (b INTEGER) AS
BEGIN
  b = a * 2;
  SUSPEND;
END^
SET TERM ; ^
create or alter function dbine_fn (x integer) returns integer as
begin
  return case when x > 0 then x else 0 end;
end;
create package dbine_pkg as begin procedure hello returns (s varchar(20)); end;
create package body dbine_pkg as begin
  procedure hello returns (s varchar(20)) as begin s = 'hola'; suspend; end
end;
CREATE TRIGGER dbine_trg FOR dbine_t BEFORE INSERT OR UPDATE AS
BEGIN
  NEW.name = UPPER(NEW.name);
END;
INSERT INTO dbine_t (id, name, amount, big, ts, d, t, doc, bin, flag)
  VALUES (1, 'uno;dos', 1234.5, 170141183460469231731687303715884105727,
          TIMESTAMP '2024-01-31 13:45:00.123', DATE '2024-02-01', TIME '08:30:00', 'texto largo',
          x'DEADBEEF', TRUE);
INSERT INTO dbine_t (id, name) VALUES (2, 'b');
UPDATE dbine_t SET amount = 1 WHERE id = 2;
"#;
    let out = run(&mut s, script).await;
    let affected: Vec<_> = out.results.iter().filter_map(|r| r.rows_affected).collect();
    assert_eq!(affected, vec![1, 1, 1]);

    // Autocommit is on by default: a second session sees the rows.
    let mut other = session().await;
    let o = run(&mut other, "SELECT COUNT(*) FROM dbine_t").await;
    assert_eq!(o.results[0].rows[0][0], json!(2));

    let objs = s.list_objects().await.unwrap();
    let has = |k: &str, n: &str| objs.iter().any(|o| o.kind == k && o.name == n);
    assert!(has("table", "DBINE_T"));
    assert!(has("view", "DBINE_V"));
    assert!(has("sequence", "DBINE_SEQ"));
    assert!(has("procedure", "DBINE_PROC"));
    assert!(has("function", "DBINE_FN"));
    assert!(has("package", "DBINE_PKG"));
    let trg = objs.iter().find(|o| o.kind == "trigger" && o.name == "DBINE_TRG").unwrap();
    assert_eq!(trg.parent.as_deref(), Some("DBINE_T"));
    assert!(!objs.iter().any(|o| o.name.starts_with("RDB$")), "system objects are hidden");

    let cols = s.columns(&obj("table", "DBINE_T")).await.unwrap();
    let names: Vec<_> = cols.iter().map(|c| c.name.as_str()).collect();
    assert_eq!(names, ["ID", "NAME", "AMOUNT", "BIG", "TS", "D", "T", "DOC", "BIN", "FLAG", "IDENT"]);
    assert!(cols[0].primary_key && !cols[0].nullable);
    assert_eq!(cols[1].data_type, "VARCHAR(50)");
    assert_eq!(cols[1].default_value.as_deref(), Some("'x'"));
    assert_eq!(cols[2].data_type, "NUMERIC(12,2)");
    assert_eq!(cols[3].data_type, "INT128");
    assert!(cols[10].auto_increment);

    let ddl = s.definition(&obj("procedure", "DBINE_PROC")).await.unwrap().unwrap();
    assert!(ddl.starts_with("CREATE OR ALTER PROCEDURE \"DBINE_PROC\" (\n    \"A\" INTEGER\n)\nRETURNS"), "{ddl}");
    let ddl = s.definition(&obj("trigger", "DBINE_TRG")).await.unwrap().unwrap();
    assert!(ddl.contains("FOR \"DBINE_T\"\nACTIVE BEFORE INSERT OR UPDATE POSITION 0"), "{ddl}");
    let ddl = s.definition(&obj("function", "DBINE_FN")).await.unwrap().unwrap();
    assert!(ddl.contains("RETURNS INTEGER"), "{ddl}");
    assert!(s.definition(&obj("view", "DBINE_V")).await.unwrap().unwrap().contains("SELECT"));
    assert!(s.definition(&obj("package", "DBINE_PKG")).await.unwrap().unwrap().contains("PACKAGE BODY"));
    assert!(s.definition(&obj("sequence", "DBINE_SEQ")).await.unwrap().unwrap().starts_with("CREATE SEQUENCE"));

    // Definitions run again as they are (no SET TERM needed).
    let ddl = s.definition(&obj("procedure", "DBINE_PROC")).await.unwrap().unwrap();
    run(&mut s, &ddl).await;

    let q = s.browse_query(&obj("table", "DBINE_T"), 10);
    assert_eq!(q, "SELECT FIRST 10 *\nFROM \"DBINE_T\"");
    let out = run(&mut s, &format!("{q}\nORDER BY id")).await;
    let r = &out.results[0];
    assert_eq!(r.total_rows, 2);
    let row = &r.rows[0];
    assert_eq!(row[0], json!(1));
    assert_eq!(row[1], json!("UNO;DOS"), "trigger upper-cased it");
    assert_eq!(row[2], json!("1234.50"));
    assert_eq!(row[3], json!("170141183460469231731687303715884105727"));
    assert!(row[4].as_str().unwrap().starts_with("2024-01-31 13:45:00.123"), "{}", row[4]);
    assert_eq!(row[5], json!("2024-02-01"));
    assert!(row[6].as_str().unwrap().starts_with("08:30:00"), "{}", row[6]);
    assert_eq!(row[7], json!("texto largo"));
    assert_eq!(row[8], json!("0xDEADBEEF"));
    assert_eq!(row[9], json!(true));

    let out = run(&mut s, "SELECT * FROM dbine_proc(21); EXECUTE PROCEDURE dbine_proc(4); SELECT dbine_fn(-3) FROM rdb$database; SELECT * FROM dbine_pkg.hello").await;
    assert_eq!(out.results[0].rows[0][0], json!(42));
    assert_eq!(out.results[1].rows[0][0], json!(8));
    assert_eq!(out.results[2].rows[0][0], json!(0));
    assert_eq!(out.results[3].rows[0][0], json!("hola"));

    // RETURNING and an empty result.
    let out = run(&mut s, "INSERT INTO dbine_t (id, name) VALUES (3, 'c') RETURNING id, name; SELECT * FROM dbine_t WHERE id < 0").await;
    // The client can't read a single-row RETURNING: it runs and says so.
    assert_eq!(out.results[0].rows_affected, Some(1));
    assert!(out.messages.iter().any(|m| m.contains("RETURNING")));
    assert_eq!(out.results[1].total_rows, 0);

    // Manual transactions.
    let driver = dbine_driver_firebird::drivers().remove(0);
    let mut cfg = config();
    cfg.options.insert("autocommit".into(), "false".into());
    let mut manual = driver.connect(&cfg, None).await.unwrap();
    run(&mut manual, "DELETE FROM dbine_t WHERE id = 3").await;
    let o = run(&mut other, "SELECT COUNT(*) FROM dbine_t WHERE id = 3").await;
    assert_eq!(o.results[0].rows[0][0], json!(1), "not committed yet");
    run(&mut manual, "COMMIT").await;
    let o = run(&mut other, "SELECT COUNT(*) FROM dbine_t WHERE id = 3").await;
    assert_eq!(o.results[0].rows[0][0], json!(0));

    // Errors stop the script and keep what ran.
    let mut out = QueryOutcome::default();
    let e = s
        .execute("SELECT 1 FROM rdb$database; SELECT * FROM no_such_table; SELECT 2 FROM rdb$database", 10, &mut out)
        .await;
    assert!(e.unwrap_err().to_string().contains("NO_SUCH_TABLE"));
    assert_eq!(out.results.len(), 1);

    drop(manual);
    drop(other);
    clean(&mut s).await;
}

#[tokio::test]
#[ignore]
async fn interrupter_cancels_a_running_statement() {
    let mut s = session().await;
    let stop = s.interrupter().expect("an interrupter");
    let started = std::time::Instant::now();
    tokio::spawn(async move {
        tokio::time::sleep(std::time::Duration::from_secs(2)).await;
        stop();
    });
    // A long cross join.
    let mut out = QueryOutcome::default();
    let e = s
        .execute(
            "SELECT COUNT(*) FROM rdb$fields a CROSS JOIN rdb$fields b CROSS JOIN rdb$fields c CROSS JOIN rdb$fields d",
            10,
            &mut out,
        )
        .await
        .unwrap_err();
    assert!(matches!(e, dbine_driver::Error::Cancelled), "{e}");
    assert!(started.elapsed().as_secs() < 20);
    let out = run(&mut s, "SELECT 1 FROM rdb$database").await;
    assert_eq!(out.results[0].rows[0][0], json!(1));
}

#[tokio::test]
#[ignore]
async fn bad_password_is_auth_failed() {
    let mut cfg = config();
    cfg.password = Some("wrong".into());
    let driver = dbine_driver_firebird::drivers().remove(0);
    match driver.connect(&cfg, None).await {
        Err(dbine_driver::Error::AuthFailed(_)) => {}
        Err(e) => panic!("expected AuthFailed, got {e:?}"),
        Ok(_) => panic!("connected with a wrong password"),
    }
}

#[tokio::test]
#[ignore]
async fn plans() {
    let mut s = session().await;
    let mut out = QueryOutcome::default();
    let _ = s.execute("DROP TABLE DBINE_PLAN", 10, &mut out).await;
    run(&mut s, "CREATE TABLE DBINE_PLAN (ID INT PRIMARY KEY, X INT)").await;
    run(&mut s, "INSERT INTO DBINE_PLAN VALUES (1, 1); INSERT INTO DBINE_PLAN VALUES (2, 2)").await;

    let mut out = QueryOutcome::default();
    s.explain(
        "SELECT a.X FROM DBINE_PLAN a JOIN DBINE_PLAN b ON b.ID = a.X ORDER BY 1; DELETE FROM DBINE_PLAN",
        false,
        10,
        &mut out,
    )
    .await
    .unwrap();
    assert!(out.results.is_empty(), "nothing ran");
    assert_eq!(out.plans.len(), 2, "{:?}", out.messages);
    println!("{}\n{:#?}", out.plans[0].raw, out.plans[0].root);
    assert_eq!(out.plans[0].root.op, "Select Expression");
    assert!(out.plans[0].raw.contains("DBINE_PLAN"));
    let o = run(&mut s, "SELECT COUNT(*) FROM DBINE_PLAN").await;
    assert_eq!(o.results[0].rows[0][0], json!(2), "the DELETE didn't run");

    let mut out = QueryOutcome::default();
    s.explain("SELECT * FROM DBINE_PLAN WHERE ID = 1", true, 10, &mut out).await.unwrap();
    assert_eq!(out.results[0].rows.len(), 1);
    assert!(out.plans[0].root.props.iter().any(|(k, v)| k == "Filas devueltas" && v == "1"), "{:#?}", out.plans[0].root);

    run(&mut s, "DROP TABLE DBINE_PLAN").await;
}

const DDL_TABLES: [&str; 3] = ["DBINE_CUSTOMERS", "DBINE_ORDERS", "DBINE_LINES"];

/// Our tables of a database schema, with indexes in name order (unique
/// constraints and unique indexes come from different catalog queries).
fn ours(mut schema: Vec<dbine_driver::TableSchema>) -> Vec<dbine_driver::TableSchema> {
    schema.retain(|t| DDL_TABLES.contains(&t.name.as_str()));
    for t in &mut schema {
        t.indexes.sort_by(|a, b| a.name.cmp(&b.name));
    }
    schema
}

#[tokio::test]
#[ignore]
async fn schema_ddl_round_trip() {
    let driver = dbine_driver_firebird::drivers().remove(0);
    assert!(driver.capabilities().create_database && driver.capabilities().foreign_keys);
    let mut s = session().await;
    for t in DDL_TABLES.iter().rev() {
        let _ = s.execute(&format!("DROP TABLE {t}"), 10, &mut QueryOutcome::default()).await;
    }
    run(
        &mut s,
        r#"
CREATE TABLE dbine_customers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT pk_customers PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  name VARCHAR(50) DEFAULT 'anon' NOT NULL,
  active BOOLEAN DEFAULT TRUE,
  CONSTRAINT uq_customers_email UNIQUE (email)
);
CREATE TABLE dbine_orders (
  id INTEGER NOT NULL PRIMARY KEY,
  customer_id INTEGER,
  total NUMERIC(12,2) DEFAULT 0,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  note BLOB SUB_TYPE TEXT,
  twice COMPUTED BY (total * 2),
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES dbine_customers (id) ON DELETE SET NULL
);
CREATE TABLE dbine_lines (
  order_id INTEGER NOT NULL,
  line_no SMALLINT NOT NULL,
  qty DECIMAL(9,3),
  code CHAR(5),
  big BIGINT,
  PRIMARY KEY (order_id, line_no),
  FOREIGN KEY (order_id) REFERENCES dbine_orders (id) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX ix_orders_created ON dbine_orders (created);
CREATE DESC INDEX ix_lines_qty ON dbine_lines (qty);
CREATE UNIQUE INDEX ux_lines_code ON dbine_lines (code, big);
CREATE INDEX ix_customers_up ON dbine_customers COMPUTED BY (UPPER(name));
CREATE INDEX ix_orders_big ON dbine_orders (total) WHERE total > 100;
COMMENT ON TABLE dbine_customers IS 'Clientes';
COMMENT ON COLUMN dbine_customers.email IS 'Correo';
"#,
    )
    .await;

    let schema = ours(s.database_schema().await.unwrap());
    assert_eq!(schema.iter().map(|t| t.name.as_str()).collect::<Vec<_>>(), ["DBINE_CUSTOMERS", "DBINE_LINES", "DBINE_ORDERS"]);
    let (cust, lines, orders) = (&schema[0], &schema[1], &schema[2]);
    assert_eq!(cust.comment.as_deref(), Some("Clientes"));
    assert_eq!(cust.columns[1].comment.as_deref(), Some("Correo"));
    assert!(cust.columns[0].auto_increment && !cust.columns[0].nullable);
    assert_eq!(cust.columns[2].default_value.as_deref(), Some("'anon'"));
    assert_eq!(cust.primary_key.as_ref().unwrap().name.as_deref(), Some("PK_CUSTOMERS"));
    let ix = |t: &dbine_driver::TableSchema, n: &str| t.indexes.iter().find(|i| i.name == n).cloned().unwrap_or_else(|| panic!("{n}: {:?}", t.indexes));
    assert!(ix(cust, "UQ_CUSTOMERS_EMAIL").unique);
    assert_eq!(ix(cust, "IX_CUSTOMERS_UP").kind.as_deref(), Some("COMPUTED"));
    assert_eq!(ix(lines, "IX_LINES_QTY").kind.as_deref(), Some("DESC"));
    assert_eq!(ix(lines, "UX_LINES_CODE").columns, ["CODE", "BIG"]);
    assert_eq!(ix(orders, "IX_ORDERS_BIG").filter.as_deref(), Some("total > 100"));
    assert!(!ix(orders, "IX_ORDERS_CREATED").unique);
    assert_eq!(orders.columns[5].data_type, "COMPUTED BY (total * 2)");
    assert_eq!(lines.primary_key.as_ref().unwrap().columns, ["ORDER_ID", "LINE_NO"]);
    assert_eq!(lines.primary_key.as_ref().unwrap().name, None);
    let fk = &lines.foreign_keys[0];
    assert_eq!((fk.name.as_deref(), fk.ref_table.as_str(), fk.on_delete.as_deref(), fk.on_update.as_deref()), (None, "DBINE_ORDERS", Some("CASCADE"), Some("CASCADE")));
    let fk = &orders.foreign_keys[0];
    assert_eq!((fk.name.as_deref(), fk.columns[0].as_str(), fk.ref_columns[0].as_str(), fk.on_delete.as_deref(), fk.on_update.as_deref()),
        (Some("FK_ORDERS_CUSTOMER"), "CUSTOMER_ID", "ID", Some("SET NULL"), None));

    // Round trip into a new database file.
    let rt = format!("{}/dbine_rt.fdb", config().database.rsplit_once('/').unwrap().0);
    let _ = s.drop_database(&rt).await;
    s.create_database(&rt).await.expect("create database");
    let mut r = driver.connect(&config(), Some(&rt)).await.expect("connect to the new database");
    let mut script = String::new();
    for t in &schema {
        script += &driver.table_ddl(t, dbine_driver::DdlParts { create: true, ..Default::default() }).unwrap();
        script.push('\n');
    }
    for t in &schema {
        script += &driver.table_ddl(t, dbine_driver::DdlParts { indexes: true, foreign_keys: true, ..Default::default() }).unwrap();
        script.push('\n');
    }
    run(&mut r, &script).await;
    assert_eq!(ours(r.database_schema().await.unwrap()), schema, "{script}");

    // Guarded drop / create run again over what exists.
    let guarded = driver.table_ddl(&schema[1], dbine_driver::DdlParts { drop: true, if_exists: true, create: true, indexes: true, foreign_keys: true }).unwrap();
    run(&mut r, &guarded).await;
    let again = driver.table_ddl(&schema[1], dbine_driver::DdlParts { if_exists: true, create: true, indexes: true, ..Default::default() }).unwrap();
    run(&mut r, &again).await;
    assert_eq!(ours(r.database_schema().await.unwrap()), schema);

    // INSERT script: one statement per row.
    let cols: Vec<String> = ["ID", "EMAIL", "NAME", "ACTIVE"].map(String::from).to_vec();
    let rows = vec![vec![json!(1), json!("ana@x"), json!("Ana"), json!(true)], vec![json!(2), json!("o'brien@x"), json!("O'Brien"), json!(null)]];
    let ins = driver.insert_script(&obj("table", "DBINE_CUSTOMERS"), &cols, &rows).unwrap();
    let out = run(&mut r, &ins).await;
    assert_eq!(out.results.iter().filter_map(|x| x.rows_affected).sum::<u64>(), 2);
    let out = run(&mut r, "SELECT name FROM dbine_customers WHERE id = 2").await;
    assert_eq!(out.results[0].rows[0][0], json!("O'Brien"));

    // Templates that don't depend on a table named `tabla` run as they are.
    for t in driver.create_templates().iter().filter(|t| ["function", "package", "sequence"].contains(&t.kind)) {
        run(&mut r, &t.template.replace("{name}", &format!("dbine_tpl_{}", t.kind))).await;
    }
    let out = run(&mut r, "SELECT dbine_tpl_function(21), dbine_tpl_package.doble(2) FROM rdb$database").await;
    assert_eq!(out.results[0].rows[0], vec![json!(42), json!(4)]);

    drop(r);
    let e = s.drop_database(&config().database).await.unwrap_err();
    assert!(e.to_string().contains("conexión actual"), "{e}");
    s.drop_database(&rt).await.expect("drop database");
    assert!(driver.connect(&config(), Some(&rt)).await.is_err(), "the file is gone");

    for t in DDL_TABLES.iter().rev() {
        run(&mut s, &format!("DROP TABLE {t}")).await;
    }
}

/// The monitor, with a second connection running a statement and holding
/// a transaction open.
#[tokio::test]
#[ignore]
async fn monitor() {
    let driver = dbine_driver_firebird::drivers().remove(0);
    assert!(driver.capabilities().monitor);
    let mut s = session().await;
    let mut cfg = config();
    cfg.options.insert("autocommit".into(), "false".into());
    let mut other = driver.connect(&cfg, None).await.unwrap();
    run(&mut other, "SELECT COUNT(*) FROM RDB$RELATIONS").await;
    let snap = s.monitor().await.expect("monitor");
    for m in &snap.metrics {
        eprintln!("{:<20} {:<44} {:?} max={:?}{}", m.key, m.label, m.value, m.max, if m.counter { " (counter)" } else { "" });
    }
    for t in &snap.tables {
        eprintln!("[{}] {} rows; first: {:?}", t.key, t.rows.len(), t.rows.first());
    }
    eprintln!("info: {:?}\nnotes: {:?}", snap.info, snap.notes);
    let has = |k: &str| snap.metrics.iter().any(|m| m.key == k && m.value.is_some());
    for k in ["mem_used", "mem_cache", "connections", "transactions", "rows_read", "disk_read", "cache_hit", "storage_used", "tx_gap"] {
        assert!(has(k), "{k}");
    }
    let sessions = snap.tables.iter().find(|t| t.key == "sessions").unwrap();
    assert!(!sessions.rows.is_empty(), "the other connection");
    assert!(snap.tables.iter().any(|t| t.key == "transactions" && !t.rows.is_empty()), "its open transaction");
    // A fresh snapshot each time (not the one of the session's transaction).
    run(&mut s, "SELECT COUNT(*) FROM RDB$FIELDS").await;
    let again = s.monitor().await.unwrap();
    let rows = |x: &dbine_driver::MonitorSnapshot| x.metrics.iter().find(|m| m.key == "rows_read").and_then(|m| m.value).unwrap();
    assert!(rows(&again) > rows(&snap));
}

/// The profiler samples MON$STATEMENTS: one session profiles while another
/// (same user, so no admin rights are needed) runs a slow statement.
#[tokio::test]
#[ignore]
async fn profiler() {
    let driver = dbine_driver_firebird::drivers().remove(0);
    assert!(driver.supports_profiler());
    let cfg = config();
    let mut p = driver.connect(&cfg, None).await.expect("connect");
    let mut w = driver.connect(&cfg, None).await.expect("connect");
    let opts = dbine_driver::ProfilerOptions { database: cfg.database.clone(), change_server: true };
    let started = p.profiler_start(&opts).await.expect("profiler_start");
    eprintln!("{started:?}");
    let marker = format!("dbine_prof_{}", std::process::id());
    // Busy for 600 ms ('NOW' is read each time; CURRENT_TIMESTAMP isn't).
    let slow = format!(
        "EXECUTE BLOCK RETURNS ({marker}_slow INTEGER) AS DECLARE t TIMESTAMP; BEGIN t = CAST('NOW' AS TIMESTAMP); \
         WHILE (DATEDIFF(MILLISECOND FROM t TO CAST('NOW' AS TIMESTAMP)) < 600) DO {marker}_slow = 1; SUSPEND; END"
    );
    let work = async {
        tokio::time::sleep(std::time::Duration::from_millis(300)).await;
        run(&mut w, &slow).await;
        tokio::time::sleep(std::time::Duration::from_millis(600)).await;
    };
    let watch = async {
        let mut got = Vec::new();
        let until = std::time::Instant::now() + std::time::Duration::from_secs(4);
        while std::time::Instant::now() < until {
            got.extend(p.profiler_poll().await.expect("profiler_poll"));
            if got.iter().any(|s| s.text.contains(&marker)) {
                break;
            }
        }
        got
    };
    let ((), got) = tokio::join!(work, watch);
    p.profiler_stop().await.expect("profiler_stop");
    let mine: Vec<_> = got.iter().filter(|s| s.text.contains(&marker)).collect();
    eprintln!("{mine:#?}");
    assert_eq!(mine.len(), 1, "the slow statement once");
    let ms = mine[0].duration_ms.unwrap_or(0.0);
    assert!((300.0..3000.0).contains(&ms), "duration {ms}");
    // Page fetches and marks from MON$IO_STATS.
    assert_eq!(started.reads_unit.as_deref(), Some("páginas"));
    assert!(mine[0].reads.is_some() && mine[0].writes.is_some(), "figures");
    assert!(got.iter().all(|s| !s.text.contains("MON$STATEMENTS")), "its own statements are left out");
}

/// Schema sync against the server: the generated script turns a table into
/// its new version (keys with generated names included), and a second
/// comparison finds nothing left to change.
#[tokio::test]
#[ignore]
async fn schema_sync_applies() {
    use dbine_driver::{IndexDef, TableChange};
    let driver = dbine_driver_firebird::drivers().remove(0);
    assert!(driver.supports_schema_sync());
    let mut s = session().await;
    for d in ["DROP TABLE dbine_sync_hijo", "DROP TABLE dbine_sync_padre"] {
        let mut out = QueryOutcome::default();
        let _ = s.execute(d, 10, &mut out).await;
    }
    run(
        &mut s,
        r#"
CREATE TABLE dbine_sync_padre (id INTEGER NOT NULL PRIMARY KEY, codigo INTEGER NOT NULL);
CREATE TABLE dbine_sync_hijo (
  id INTEGER NOT NULL PRIMARY KEY,
  padre_id INTEGER REFERENCES dbine_sync_padre (id),
  nombre VARCHAR(20) NOT NULL,
  codigo INTEGER,
  baja DATE,
  CONSTRAINT uq_sync_hijo_codigo UNIQUE (codigo)
);
CREATE INDEX ix_sync_hijo_nombre ON dbine_sync_hijo (nombre);
INSERT INTO dbine_sync_padre VALUES (1, 10);
INSERT INTO dbine_sync_hijo VALUES (1, 1, 'uno', 5, NULL);
"#,
    )
    .await;
    let find = |schema: &[dbine_driver::TableSchema], n: &str| schema.iter().find(|t| t.name == n).unwrap().clone();
    let old = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_HIJO");
    assert!(old.primary_key.as_ref().unwrap().name.is_none() && old.foreign_keys[0].name.is_none(), "{old:?}");
    let mut new = old.clone();
    let nombre = new.columns.iter_mut().find(|c| c.name == "NOMBRE").unwrap();
    nombre.data_type = "VARCHAR(40)".into();
    nombre.nullable = true;
    nombre.default_value = Some("'x'".into());
    new.columns.retain(|c| c.name != "BAJA");
    new.columns.push(dbine_driver::ColumnDef { name: "EMAIL".into(), data_type: "VARCHAR(100)".into(), nullable: true, ..Default::default() });
    new.indexes = vec![IndexDef { name: "IX_SYNC_HIJO_EMAIL".into(), columns: vec!["EMAIL".into()], unique: false, kind: None, filter: None, ..Default::default() }];
    new.primary_key = Some(dbine_driver::KeyDef { name: Some("PK_SYNC_HIJO".into()), columns: vec!["ID".into()] });
    new.foreign_keys[0].name = Some("FK_SYNC_HIJO_PADRE".into());
    new.foreign_keys[0].on_delete = Some("CASCADE".into());
    let script = driver.sync_script(&[TableChange::Alter { old, new: new.clone() }]).unwrap();
    eprintln!("{}\n{:?}", script.statements.join("\n"), script.warnings);
    for st in &script.statements {
        run(&mut s, st).await;
    }
    let after = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_HIJO");
    let left = driver.sync_script(&[TableChange::Alter { old: after, new: new.clone() }]).unwrap();
    assert!(left.statements.is_empty(), "{:?}", left.statements);

    let mut last = new.clone();
    last.columns.iter_mut().find(|c| c.name == "NOMBRE").unwrap().nullable = false;
    last.columns.iter_mut().find(|c| c.name == "NOMBRE").unwrap().default_value = None;
    last.indexes.clear();
    last.foreign_keys.clear();
    // The key gets a column: the one with a generated name is looked up and dropped.
    last.primary_key = Some(dbine_driver::KeyDef { name: None, columns: vec!["ID".into(), "NOMBRE".into()] });
    let current = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_HIJO");
    let script = driver.sync_script(&[TableChange::Alter { old: current, new: last.clone() }]).unwrap();
    eprintln!("{}", script.statements.join("\n"));
    for st in &script.statements {
        run(&mut s, st).await;
    }
    let after = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_HIJO");
    let left = driver.sync_script(&[TableChange::Alter { old: after, new: last.clone() }]).unwrap();
    assert!(left.statements.is_empty(), "{:?}", left.statements);
    let padre = find(&s.database_schema().await.unwrap(), "DBINE_SYNC_PADRE");
    let script = driver.sync_script(&[TableChange::Drop { table: last }, TableChange::Drop { table: padre }]).unwrap();
    for st in &script.statements {
        run(&mut s, st).await;
    }
}

/// The editor's script contract: errors with SQLCODE and position in the
/// script, skipped isql commands said, manual transactions.
#[tokio::test]
#[ignore]
async fn script_errors_messages_and_transactions() {
    let driver = dbine_driver_firebird::drivers().remove(0);
    assert_eq!(driver.script_dialect(), dbine_driver::sql::ScriptDialect::firebird());
    assert!(driver.supports_manual_transactions());
    let mut s = session().await;
    let _ = s.execute("DROP TABLE dbine_tx", 10, &mut QueryOutcome::default()).await;
    run(&mut s, "CREATE TABLE dbine_tx (id INTEGER NOT NULL PRIMARY KEY)").await;

    let script = "SELECT 1 FROM rdb$database;\nSHOW TABLES;\nSELECT 2 FROM\n  rdb$database WHERE nope = 1;";
    let mut out = QueryOutcome::default();
    let e = s.execute(script, 10, &mut out).await.unwrap_err().to_script_error();
    eprintln!("{e:?}");
    assert_eq!(e.code.as_deref(), Some("-206"), "{e:?}");
    assert_eq!(e.offset, Some(script.find("nope").unwrap()), "{e:?}");
    assert_eq!(e.line, Some(4));
    assert_eq!(out.results.len(), 1);
    assert!(out.log.iter().any(|m| m.text.contains("SHOW TABLES")), "{:?}", out.log);

    let mut out = QueryOutcome::default();
    let e = s.execute("SELEC 1", 10, &mut out).await.unwrap_err().to_script_error();
    assert_eq!((e.code.as_deref(), e.line, e.offset), (Some("-104"), Some(1), Some(0)), "{e:?}");

    // Errors whose status vector has no SQLCODE get isql's code and SQLSTATE.
    run(&mut s, "INSERT INTO dbine_tx VALUES (7)").await;
    let e = s.execute("INSERT INTO dbine_tx VALUES (7)", 10, &mut out).await.unwrap_err().to_script_error();
    eprintln!("{e:?}");
    assert_eq!((e.code.as_deref(), e.sqlstate.as_deref()), (Some("-803"), Some("23000")), "{e:?}");
    let e = s.execute("DROP TRIGGER dbine_no_such_trigger", 10, &mut out).await.unwrap_err().to_script_error();
    eprintln!("{e:?}");
    assert!(e.code.is_some(), "{e:?}");

    // Editor run (isql's default): goes on after each error, every
    // statement reported live with its place in the script.
    let seen = std::sync::Arc::new(std::sync::Mutex::new(Vec::new()));
    let seen2 = seen.clone();
    let mut out = QueryOutcome {
        continue_on_error: Some(true),
        progress_sink: Some(dbine_driver::ProgressSinkRef(std::sync::Arc::new(move |e: &dbine_driver::StatementEnd| {
            seen2.lock().unwrap().push((e.statement, e.line, e.errors.len(), e.results.len()))
        }))),
        ..Default::default()
    };
    let script = "INSERT INTO dbine_tx VALUES (7);\nSELECT 2 FROM nosuch;\nSELECT 3 FROM rdb$database";
    s.execute(script, 10, &mut out).await.unwrap();
    assert_eq!(*seen.lock().unwrap(), vec![(0, 1, 1, 0), (1, 2, 1, 0), (2, 3, 0, 1)]);
    let codes: Vec<_> = out.errors.iter().map(|e| (e.code.clone(), e.line, e.statement)).collect();
    assert_eq!(codes, vec![(Some("-803".to_string()), Some(1), Some(0)), (Some("-204".to_string()), Some(2), Some(1))], "{:?}", out.errors);
    assert_eq!(out.errors[1].offset.map(|o| &script[o..o + 6]), Some("nosuch"), "{:?}", out.errors);
    assert_eq!((out.results.len(), out.results[0].statement, out.results[0].line), (1, Some(2), Some(3)));
    assert_eq!(out.results[0].rows[0][0], json!(3));
    // Any other caller stops at the first error.
    let mut out = QueryOutcome::default();
    assert!(s.execute(script, 10, &mut out).await.is_err());
    assert!(out.results.is_empty() && out.errors.is_empty());
    run(&mut s, "DELETE FROM dbine_tx").await;

    assert_eq!(s.transaction_state().await.unwrap(), Some(dbine_driver::TxState::Idle));
    s.set_autocommit(false).await.unwrap();
    run(&mut s, "SELECT 1 FROM rdb$database").await;
    assert_eq!(s.transaction_state().await.unwrap(), Some(dbine_driver::TxState::Idle));
    run(&mut s, "INSERT INTO dbine_tx VALUES (1)").await;
    assert_eq!(s.transaction_state().await.unwrap(), Some(dbine_driver::TxState::Open));
    s.rollback().await.unwrap();
    assert_eq!(s.transaction_state().await.unwrap(), Some(dbine_driver::TxState::Idle));
    run(&mut s, "INSERT INTO dbine_tx VALUES (2)").await;
    // Another session doesn't see it until the commit.
    let mut other = session().await;
    let out = run(&mut other, "SELECT COUNT(*) FROM dbine_tx").await;
    assert_eq!(out.results[0].rows[0][0], json!(0));
    s.commit().await.unwrap();
    s.set_autocommit(true).await.unwrap();
    let out = run(&mut other, "SELECT LIST(id) FROM dbine_tx").await;
    eprintln!("{:?}", out.results[0].rows);
    drop(other);
    run(&mut s, "DROP TABLE dbine_tx").await;
}
