//! Against a real SAP HANA (there's no practical Docker image; HANA express
//! is large and licensed):
//!
//! ```sh
//! DBINE_TEST_HANA_URL=hana://USER:PASSWORD@host:39041 cargo test -p dbine-driver-hana -- --ignored
//! ```
//! Add `?tls` to the URL for an encrypted connection (HANA Cloud: port 443).

use dbine_driver::{ConnectionConfig, ObjectRef, QueryOutcome};
use serde_json::json;

fn config() -> ConnectionConfig {
    let url = std::env::var("DBINE_TEST_HANA_URL").expect("DBINE_TEST_HANA_URL");
    let rest = url.strip_prefix("hana://").expect("hana://user:pass@host:port");
    let (rest, tls) = match rest.split_once('?') {
        Some((r, q)) => (r, q.contains("tls")),
        None => (rest, false),
    };
    let (cred, addr) = rest.split_once('@').unwrap();
    let (user, pass) = cred.split_once(':').unwrap();
    let (host, port) = addr.split_once(':').unwrap();
    ConnectionConfig {
        driver: "hana".into(),
        host: host.into(),
        port: port.trim_end_matches('/').parse().unwrap(),
        username: Some(user.into()),
        password: Some(pass.into()),
        encrypt: tls,
        ..Default::default()
    }
}

#[tokio::test]
#[ignore]
async fn round_trip() {
    let driver = dbine_driver_hana::drivers().remove(0);
    let mut s = driver.connect(&config(), None).await.expect("connect");
    assert!(s.server_version().await.unwrap().starts_with("SAP HANA"));
    assert!(!s.list_databases().await.unwrap().is_empty());

    let _ = s.execute("DROP TABLE DBINE_T", 10, &mut QueryOutcome::default()).await;
    let _ = s.execute("DROP PROCEDURE DBINE_P", 10, &mut QueryOutcome::default()).await;
    let mut out = QueryOutcome::default();
    s.execute(
        "CREATE COLUMN TABLE DBINE_T (ID INTEGER PRIMARY KEY, NAME NVARCHAR(20), AMOUNT DECIMAL(10,2), TS TIMESTAMP);
         INSERT INTO DBINE_T VALUES (1, 'uno;dos', 12.5, '2024-01-31 13:45:00.123');
         CREATE PROCEDURE DBINE_P (OUT n INTEGER) AS BEGIN SELECT COUNT(*) INTO n FROM DBINE_T; END;
         CALL DBINE_P(?)",
        100,
        &mut out,
    )
    .await
    .expect("script");

    let objs = s.list_objects().await.unwrap();
    assert!(objs.iter().any(|o| o.kind == "table" && o.name == "DBINE_T"));
    assert!(objs.iter().any(|o| o.kind == "procedure" && o.name == "DBINE_P"));
    let t = ObjectRef { kind: "table".into(), schema: None, name: "DBINE_T".into() };
    let cols = s.columns(&t).await.unwrap();
    assert!(cols[0].primary_key);
    assert_eq!(cols[2].data_type, "DECIMAL(10,2)");

    let mut out = QueryOutcome::default();
    s.execute(&s.browse_query(&t, 10), 10, &mut out).await.unwrap();
    let row = &out.results[0].rows[0];
    assert_eq!(row[1], json!("uno;dos"));
    assert_eq!(row[2], json!("12.50"));
    assert_eq!(row[3], json!("2024-01-31 13:45:00.123"));

    let p = ObjectRef { kind: "procedure".into(), schema: None, name: "DBINE_P".into() };
    assert!(s.definition(&p).await.unwrap().unwrap().contains("CREATE PROCEDURE"));

    let _ = s.execute("DROP PROCEDURE DBINE_P; DROP TABLE DBINE_T", 10, &mut QueryOutcome::default()).await;
}

const DDL_TABLES: [&str; 3] = ["DBINE_CUSTOMERS", "DBINE_ORDERS", "DBINE_LINES"];

fn ours(mut schema: Vec<dbine_driver::TableSchema>) -> Vec<dbine_driver::TableSchema> {
    schema.retain(|t| DDL_TABLES.contains(&t.name.as_str()));
    for t in &mut schema {
        t.indexes.sort_by(|a, b| a.name.cmp(&b.name));
    }
    schema
}

async fn run(s: &mut Box<dyn dbine_driver::Session>, sql: &str) -> QueryOutcome {
    let mut out = QueryOutcome::default();
    if let Err(e) = s.execute(sql, 1000, &mut out).await {
        panic!("{sql}: {e}");
    }
    out
}

#[tokio::test]
#[ignore]
async fn schema_ddl_round_trip() {
    let driver = dbine_driver_hana::drivers().remove(0);
    let mut s = driver.connect(&config(), None).await.expect("connect");
    for t in DDL_TABLES.iter().rev() {
        let _ = s.execute(&format!("DROP TABLE {t}"), 10, &mut QueryOutcome::default()).await;
    }
    run(
        &mut s,
        "CREATE COLUMN TABLE dbine_customers (
           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
           email NVARCHAR(100) NOT NULL,
           name NVARCHAR(50) DEFAULT 'anon' NOT NULL,
           CONSTRAINT uq_customers_email UNIQUE (email));
         CREATE COLUMN TABLE dbine_orders (
           id INTEGER NOT NULL PRIMARY KEY,
           customer_id BIGINT,
           total DECIMAL(12,2) DEFAULT 0,
           created TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
         CREATE ROW TABLE dbine_lines (
           order_id INTEGER NOT NULL,
           line_no SMALLINT NOT NULL,
           qty DOUBLE,
           PRIMARY KEY (order_id, line_no));
         ALTER TABLE dbine_orders ADD CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES dbine_customers (id) ON DELETE SET NULL;
         ALTER TABLE dbine_lines ADD CONSTRAINT fk_lines_order FOREIGN KEY (order_id) REFERENCES dbine_orders (id) ON DELETE CASCADE;
         CREATE INDEX ix_orders_created ON dbine_orders (created);
         CREATE UNIQUE INDEX ux_lines_qty ON dbine_lines (qty, line_no);
         COMMENT ON TABLE dbine_customers IS 'Clientes';
         COMMENT ON COLUMN dbine_customers.email IS 'Correo'",
    )
    .await;

    let schema = ours(s.database_schema().await.unwrap());
    assert_eq!(schema.iter().map(|t| t.name.as_str()).collect::<Vec<_>>(), ["DBINE_CUSTOMERS", "DBINE_LINES", "DBINE_ORDERS"]);
    let (cust, lines, orders) = (&schema[0], &schema[1], &schema[2]);
    assert_eq!(cust.comment.as_deref(), Some("Clientes"));
    assert_eq!(cust.columns[1].comment.as_deref(), Some("Correo"));
    assert!(cust.columns[0].auto_increment);
    assert_eq!(cust.columns[2].default_value.as_deref(), Some("'anon'"));
    assert!(cust.indexes.iter().any(|i| i.name == "UQ_CUSTOMERS_EMAIL" && i.unique), "{:?}", cust.indexes);
    assert_eq!(lines.options.get("store").map(String::as_str), Some("ROW"));
    assert_eq!(lines.primary_key.as_ref().unwrap().columns, ["ORDER_ID", "LINE_NO"]);
    assert!(lines.indexes.iter().any(|i| i.name == "UX_LINES_QTY" && i.unique && i.columns == ["QTY", "LINE_NO"]));
    assert!(orders.indexes.iter().any(|i| i.name == "IX_ORDERS_CREATED" && !i.unique));
    assert_eq!(lines.foreign_keys[0].on_delete.as_deref(), Some("CASCADE"));
    assert_eq!(orders.foreign_keys[0].on_delete.as_deref(), Some("SET NULL"));
    assert_eq!(orders.foreign_keys[0].ref_table, "DBINE_CUSTOMERS");

    // Round trip into a new schema.
    let _ = s.drop_database("DBINE_RT").await;
    s.create_database("DBINE_RT").await.expect("create schema");
    let mut r = driver.connect(&config(), Some("DBINE_RT")).await.expect("connect to the new schema");
    let mut script = String::new();
    for t in &schema {
        script += &driver.table_ddl(t, dbine_driver::DdlParts { create: true, ..Default::default() }).unwrap();
        script.push('\n');
    }
    for t in &schema {
        script += &driver.table_ddl(t, dbine_driver::DdlParts { indexes: true, foreign_keys: true, ..Default::default() }).unwrap();
        script.push('\n');
    }
    run(&mut r, &script).await;
    assert_eq!(ours(r.database_schema().await.unwrap()), schema, "{script}");
    let guarded = driver.table_ddl(&schema[1], dbine_driver::DdlParts { drop: true, if_exists: true, create: true, indexes: true, foreign_keys: true }).unwrap();
    run(&mut r, &guarded).await;

    let cols: Vec<String> = ["ID", "EMAIL", "NAME"].map(String::from).to_vec();
    let rows = vec![vec![json!(1), json!("ana@x"), json!("Ana")], vec![json!(2), json!("o'brien@x"), json!("O'Brien")]];
    let ins = driver.insert_script(&ObjectRef { kind: "table".into(), schema: None, name: "DBINE_CUSTOMERS".into() }, &cols, &rows).unwrap();
    let out = run(&mut r, &ins).await;
    assert_eq!(out.results.iter().filter_map(|x| x.rows_affected).sum::<u64>(), 2);

    let e = r.drop_database("DBINE_RT").await.unwrap_err();
    assert!(e.to_string().contains("conexión actual"), "{e}");
    drop(r);
    s.drop_database("DBINE_RT").await.expect("drop schema");
    for t in DDL_TABLES.iter().rev() {
        run(&mut s, &format!("DROP TABLE {t}")).await;
    }
}

#[tokio::test]
#[ignore]
async fn monitor() {
    let driver = dbine_driver_hana::drivers().remove(0);
    assert!(driver.capabilities().monitor);
    let mut s = driver.connect(&config(), None).await.expect("connect");
    let snap = s.monitor().await.expect("monitor");
    for m in &snap.metrics {
        println!("{:<18} {:?} max {:?}", m.key, m.value, m.max);
    }
    for t in &snap.tables {
        println!("tabla {} ({} filas)", t.key, t.rows.len());
    }
    println!("info: {:?}\nnotas: {:?}", snap.info, snap.notes);
    let value = |k: &str| snap.metrics.iter().find(|m| m.key == k).and_then(|m| m.value);
    assert!(value("uptime").is_some_and(|v| v > 0.0));
    assert!(value("connections").is_some_and(|v| v >= 1.0));
    assert!(value("mem_used").is_some_and(|v| v > 0.0));
    assert!(snap.tables.iter().any(|t| t.key == "sessions" && !t.rows.is_empty()));
}

/// The profiler: one session profiles its schema while another runs a slow
/// statement and a fast one. Complete (the expensive statements trace) with
/// INIFILE ADMIN, else sampled (only the slow one is sure to be seen).
#[tokio::test]
#[ignore]
async fn profiler() {
    let driver = dbine_driver_hana::drivers().remove(0);
    assert!(driver.supports_profiler());
    let mut p = driver.connect(&config(), None).await.expect("connect");
    let mut w = driver.connect(&config(), None).await.expect("connect");
    let mut out = QueryOutcome::default();
    w.execute("SELECT CURRENT_SCHEMA FROM DUMMY", 10, &mut out).await.unwrap();
    let schema = out.results[0].rows[0][0].as_str().unwrap().to_string();
    let opts = dbine_driver::ProfilerOptions { database: schema, change_server: true };
    let started = p.profiler_start(&opts).await.expect("profiler_start");
    eprintln!("{started:?}");
    let complete = started.mode == dbine_driver::ProfilerMode::Complete;
    let marker = format!("dbine_prof_{}", std::process::id());
    let slow = format!("DO BEGIN USING SQLSCRIPT_SYNC AS SYNCLIB; DECLARE {marker}_slow INT; CALL SYNCLIB:SLEEP_SECONDS(0.6); END");
    let fast = format!("SELECT 1 AS {marker}_fast FROM DUMMY");
    let work = async {
        tokio::time::sleep(std::time::Duration::from_millis(300)).await;
        w.execute(&slow, 10, &mut QueryOutcome::default()).await.expect("slow");
        tokio::time::sleep(std::time::Duration::from_millis(400)).await;
        w.execute(&fast, 10, &mut QueryOutcome::default()).await.expect("fast");
        tokio::time::sleep(std::time::Duration::from_millis(600)).await;
    };
    let watch = async {
        let mut got = Vec::new();
        let until = std::time::Instant::now() + std::time::Duration::from_secs(if complete { 10 } else { 4 });
        while std::time::Instant::now() < until {
            got.extend(p.profiler_poll().await.expect("profiler_poll"));
            if got.iter().filter(|s| s.text.contains(&marker)).count() >= if complete { 2 } else { 1 } {
                break;
            }
            if complete {
                tokio::time::sleep(std::time::Duration::from_millis(500)).await;
            }
        }
        got
    };
    let ((), got) = tokio::join!(work, watch);
    p.profiler_stop().await.expect("profiler_stop");
    let mine: Vec<_> = got.iter().filter(|s| s.text.contains(&marker)).collect();
    eprintln!("{mine:#?}");
    let slow_seen: Vec<_> = mine.iter().filter(|s| s.text.contains("_slow")).collect();
    assert_eq!(slow_seen.len(), 1, "the slow statement once");
    assert!(slow_seen[0].duration_ms.unwrap_or(0.0) >= 300.0, "duration {:?}", slow_seen[0].duration_ms);
    if complete {
        assert_eq!(mine.iter().filter(|s| s.text.contains("_fast")).count(), 1, "the fast statement once");
    }
    assert!(got.iter().all(|s| !s.text.contains("M_EXPENSIVE_STATEMENTS") && !s.text.contains("M_ACTIVE_STATEMENTS")));
}
