//! One entry per engine served through ODBC. They share the session code
//! and differ in the connection-string template, the SQL dialect details
//! (quoting, row limit, batching) and a few catalog queries.

use dbine_driver::sql::Quote;
use dbine_driver::Family;

/// A value in the connection-string template.
#[derive(Debug, Clone, Copy)]
pub enum V {
    /// `{driver name}`.
    Driver,
    Host,
    Port,
    /// `host:port`.
    HostPort,
    Database,
    User,
    Password,
    /// A preset-specific option (`cfg.option(key)`).
    Opt(&'static str),
    Lit(&'static str),
    /// `5.0` when the driver is FreeTDS (Sybase ASE speaks TDS 5.0).
    FreeTdsVersion,
    /// Simba/Cloudera AuthMech: 3 user+password, 2 user only, 0 none.
    SimbaAuthMech,
    /// A value built from `{host}`, `{port}`, `{database}`, `{user}` and
    /// `{opt:key}`, written as is (Ingres vnodes, NuoDB `db@host:port`…).
    Fmt(&'static str),
    /// A preset option, or this default when it's empty.
    OptOr(&'static str, &'static str),
}

/// How a script is sent to the server.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Batch {
    /// One `SQLExecDirect` per statement, split on `;`.
    Statements,
    /// Blocks separated by `GO` lines (T-SQL style), each sent whole.
    Go,
    /// The whole text in one call.
    Script,
}

impl Batch {
    pub fn from_option(v: &str) -> Option<Batch> {
        match v {
            "statements" => Some(Batch::Statements),
            "go" => Some(Batch::Go),
            "script" => Some(Batch::Script),
            _ => None,
        }
    }
}

/// How the first rows of a table are asked for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LimitStyle {
    /// `… LIMIT n`
    Limit,
    /// `SELECT TOP n …` (Sybase, SQL Anywhere, Teradata).
    Top,
    /// `… FETCH FIRST n ROWS ONLY` (DB2, Oracle-like).
    FetchFirst,
    /// `SELECT FIRST n …` (Informix, GBase 8s).
    First,
}

/// A parameter of a definition query.
#[derive(Debug, Clone, Copy)]
pub enum P {
    Schema,
    Name,
    /// The session's database (catalog).
    Catalog,
    /// `schema.name` (or just the name), unquoted.
    Qualified,
}

/// Where an object's source comes from.
#[derive(Debug, Clone, Copy)]
pub enum Def {
    None,
    /// A query with `?` parameters; its rows' first column, joined.
    Sql(&'static str, &'static [P], &'static str),
    /// `<prefix> schema.name` with quoted identifiers (Hive, Teradata);
    /// rows joined with newlines.
    Show(&'static str),
}

#[derive(Debug, Clone, Copy)]
pub struct Defs {
    pub table: Def,
    pub view: Def,
    pub procedure: Def,
    pub function: Def,
}

const NO_DEFS: Defs = Defs { table: Def::None, view: Def::None, procedure: Def::None, function: Def::None };

#[derive(Debug)]
pub struct Preset {
    pub id: &'static str,
    pub name: &'static str,
    pub family: Family,
    pub dialect: &'static str,
    pub default_port: u16,
    /// `None`: ask the driver (SQL_IDENTIFIER_QUOTE_CHAR).
    pub quote: Option<Quote>,
    /// `None`: guess from the DBMS name.
    pub limit: Option<LimitStyle>,
    pub driver_hint: &'static str,
    pub driver_help: &'static str,
    /// Connection-string attributes; empty ones are left out.
    pub template: &'static [(&'static str, V)],
    /// Label of the database form field (when the template uses it).
    pub database_label: &'static str,
    pub database_required: bool,
    /// Extra text options: (key, label, placeholder, required, help).
    pub extra_options: &'static [(&'static str, &'static str, &'static str, bool, &'static str)],
    /// Several databases per server: the explorer lists them.
    pub databases_label: &'static str,
    /// The query that lists them (else SQLTables for catalogs).
    pub databases_sql: Option<&'static str>,
    pub has_schemas: bool,
    pub procedures: bool,
    pub functions: bool,
    /// Schemas hidden from the explorer; `X*` is a prefix, case-insensitive.
    pub system_schemas: &'static [&'static str],
    pub batch: Batch,
    pub defs: Defs,
}

impl Preset {
    pub fn is_generic(&self) -> bool {
        self.id == "odbc"
    }

    /// The "database" is a local file or folder (Access, dBase).
    pub fn database_file(&self) -> bool {
        matches!(self.id, "access" | "dbase")
    }

    /// The template uses a `{placeholder}` of [`V::Fmt`] or one of these values.
    pub fn uses_part(&self, v: fn(&V) -> bool, placeholder: &str) -> bool {
        self.template.iter().any(|(_, x)| v(x) || matches!(x, V::Fmt(f) if f.contains(placeholder)))
    }

    pub fn uses(&self, v: fn(&V) -> bool) -> bool {
        self.template.iter().any(|(_, x)| v(x))
    }

    pub fn is_system_schema(&self, schema: &str) -> bool {
        self.system_schemas.iter().any(|p| match p.strip_suffix('*') {
            Some(prefix) => schema.len() >= prefix.len() && schema[..prefix.len()].eq_ignore_ascii_case(prefix),
            None => schema.eq_ignore_ascii_case(p),
        })
    }
}

const DB2_HELP: &str = "Nombre del driver ODBC tal como figura en odbcinst.ini (en Windows, en el Administrador de orígenes de datos ODBC). Se instala con IBM Data Server Driver for ODBC and CLI (clidriver), que se descarga de IBM Fix Central o del sitio de IBM Db2.";

const DB2_SYS: &[&str] = &["SYS*", "NULLID", "SQLJ"];

const DB2_DEFS: Defs = Defs {
    table: Def::None,
    view: Def::Sql("SELECT TEXT FROM SYSCAT.VIEWS WHERE VIEWSCHEMA = ? AND VIEWNAME = ?", &[P::Schema, P::Name], ""),
    procedure: Def::Sql(
        "SELECT TEXT FROM SYSCAT.ROUTINES WHERE ROUTINESCHEMA = ? AND ROUTINENAME = ? AND ROUTINETYPE = 'P'",
        &[P::Schema, P::Name],
        "\n\n",
    ),
    function: Def::Sql(
        "SELECT TEXT FROM SYSCAT.ROUTINES WHERE ROUTINESCHEMA = ? AND ROUTINENAME = ? AND ROUTINETYPE = 'F'",
        &[P::Schema, P::Name],
        "\n\n",
    ),
};

const INFORMIX_DEFS: Defs = Defs {
    table: Def::None,
    view: Def::Sql(
        "SELECT v.viewtext FROM sysviews v JOIN systables t ON t.tabid = v.tabid WHERE t.owner = ? AND t.tabname = ? ORDER BY v.seqno",
        &[P::Schema, P::Name],
        "",
    ),
    procedure: Def::Sql(
        "SELECT b.data FROM sysprocbody b JOIN sysprocedures p ON p.procid = b.procid WHERE p.owner = ? AND p.procname = ? AND b.datakey = 'T' ORDER BY b.seqno",
        &[P::Schema, P::Name],
        "",
    ),
    function: Def::Sql(
        "SELECT b.data FROM sysprocbody b JOIN sysprocedures p ON p.procid = b.procid WHERE p.owner = ? AND p.procname = ? AND b.datakey = 'T' ORDER BY b.seqno",
        &[P::Schema, P::Name],
        "",
    ),
};

const INFORMIX_TEMPLATE: &[(&str, V)] = &[
    ("DRIVER", V::Driver),
    ("HOST", V::Host),
    ("SERVICE", V::Port),
    ("SERVER", V::Opt("informix_server")),
    ("PROTOCOL", V::Lit("onsoctcp")),
    ("DATABASE", V::Database),
    ("UID", V::User),
    ("PWD", V::Password),
    // Double-quoted identifiers instead of string literals.
    ("DELIMIDENT", V::Lit("y")),
];

const INFORMIX_SERVER: &[(&str, &str, &str, bool, &str)] = &[(
    "informix_server",
    "Nombre del servidor (INFORMIXSERVER)",
    "ol_informix1210",
    true,
    "El nombre de la instancia, como en la variable INFORMIXSERVER o en sqlhosts.",
)];

const SIMBA_SYS: &[&str] = &["sys", "information_schema", "_impala_builtins"];

pub static PRESETS: &[Preset] = &[
    Preset {
        id: "odbc",
        name: "ODBC (genérico)",
        family: Family::Relational,
        dialect: "standard",
        default_port: 0,
        quote: None,
        limit: None,
        driver_hint: "",
        driver_help: "",
        template: &[],
        database_label: "Catálogo",
        database_required: false,
        extra_options: &[],
        databases_label: "Catálogos",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &[
            "INFORMATION_SCHEMA",
            "sys",
            "pg_catalog",
            "SYSIBM",
            "SYSCAT",
            "SYSSTAT",
            "SYSFUN",
            "SYSPROC",
            "SYSIBMADM",
            "SYSTOOLS",
        ],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT VIEW_DEFINITION FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT ROUTINE_DEFINITION FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_NAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::Sql(
                "SELECT ROUTINE_DEFINITION FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_NAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
        },
    },
    Preset {
        id: "db2",
        name: "IBM Db2 (LUW)",
        family: Family::Relational,
        dialect: "db2",
        default_port: 50000,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::FetchFirst),
        driver_hint: "IBM DB2 ODBC DRIVER",
        driver_help: DB2_HELP,
        template: &[
            ("DRIVER", V::Driver),
            ("DATABASE", V::Database),
            ("HOSTNAME", V::Host),
            ("PORT", V::Port),
            ("PROTOCOL", V::Lit("TCPIP")),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: DB2_SYS,
        batch: Batch::Statements,
        defs: DB2_DEFS,
    },
    Preset {
        id: "db2i",
        name: "IBM Db2 for i (AS/400)",
        family: Family::Relational,
        dialect: "db2",
        default_port: 8471,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::FetchFirst),
        driver_hint: "IBM i Access ODBC Driver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Viene con IBM i Access Client Solutions (paquete «Application Package» para Windows, Linux o macOS), que se descarga del sitio de IBM.",
        template: &[
            ("DRIVER", V::Driver),
            ("SYSTEM", V::Host),
            ("DBQ", V::Database),
            ("NAM", V::Lit("0")),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Biblioteca predeterminada",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["Q*", "SYS*", "SQLJ"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT VIEW_DEFINITION FROM QSYS2.SYSVIEWS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT ROUTINE_DEFINITION FROM QSYS2.SYSROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_NAME = ?",
                &[P::Schema, P::Name],
                "\n\n",
            ),
            function: Def::Sql(
                "SELECT ROUTINE_DEFINITION FROM QSYS2.SYSROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_NAME = ?",
                &[P::Schema, P::Name],
                "\n\n",
            ),
        },
    },
    Preset {
        id: "db2zos",
        name: "IBM Db2 for z/OS",
        family: Family::Relational,
        dialect: "db2",
        default_port: 446,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::FetchFirst),
        driver_hint: "IBM DB2 ODBC DRIVER",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Es el mismo IBM Data Server Driver for ODBC and CLI de Db2 LUW; para z/OS hace falta además la licencia de Db2 Connect.",
        template: &[
            ("DRIVER", V::Driver),
            ("DATABASE", V::Database),
            ("HOSTNAME", V::Host),
            ("PORT", V::Port),
            ("PROTOCOL", V::Lit("TCPIP")),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Ubicación (location)",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["SYS*", "DSN*", "NULLID", "SQLJ"],
        batch: Batch::Statements,
        defs: Defs {
            view: Def::Sql(
                "SELECT STATEMENT FROM SYSIBM.SYSVIEWS WHERE CREATOR = ? AND NAME = ? ORDER BY SEQNO",
                &[P::Schema, P::Name],
                "",
            ),
            ..NO_DEFS
        },
    },
    Preset {
        id: "sybase",
        name: "SAP ASE (Sybase)",
        family: Family::Relational,
        dialect: "sybase",
        default_port: 5000,
        quote: Some(Quote::Bracket),
        limit: Some(LimitStyle::Top),
        driver_hint: "FreeTDS",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Opciones: FreeTDS (libre; en macOS `brew install freetds` y registrar libtdsodbc en odbcinst.ini; se usa TDS 5.0) o el driver «Adaptive Server Enterprise» del SAP ASE SDK / SDK for SAP ASE.",
        template: &[
            ("DRIVER", V::Driver),
            ("SERVER", V::Host),
            ("PORT", V::Port),
            ("DATABASE", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
            ("TDS_Version", V::FreeTdsVersion),
        ],
        database_label: "Base de datos",
        database_required: false,
        extra_options: &[],
        databases_label: "Bases de datos",
        databases_sql: Some("SELECT name FROM master..sysdatabases ORDER BY name"),
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &[],
        batch: Batch::Go,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT c.text FROM syscomments c JOIN sysobjects o ON o.id = c.id WHERE user_name(o.uid) = ? AND o.name = ? ORDER BY c.number, c.colid2, c.colid",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT c.text FROM syscomments c JOIN sysobjects o ON o.id = c.id WHERE user_name(o.uid) = ? AND o.name = ? ORDER BY c.number, c.colid2, c.colid",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::Sql(
                "SELECT c.text FROM syscomments c JOIN sysobjects o ON o.id = c.id WHERE user_name(o.uid) = ? AND o.name = ? ORDER BY c.number, c.colid2, c.colid",
                &[P::Schema, P::Name],
                "",
            ),
        },
    },
    Preset {
        id: "sqlanywhere",
        name: "SAP SQL Anywhere",
        family: Family::Relational,
        dialect: "sybase",
        default_port: 2638,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "SQL Anywhere 17",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini (por ejemplo «SQL Anywhere 17»). Viene con SAP SQL Anywhere o con su Client, que se descarga del sitio de SAP.",
        template: &[
            ("DRIVER", V::Driver),
            ("HOST", V::HostPort),
            ("DBN", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["SYS", "dbo", "rs_systabgroup", "SA_DEBUG", "diagnostics"],
        batch: Batch::Go,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT v.view_def FROM SYS.SYSVIEW v JOIN SYS.SYSTAB t ON t.object_id = v.view_object_id JOIN SYS.SYSUSER u ON u.user_id = t.creator WHERE u.user_name = ? AND t.table_name = ?",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT p.proc_defn FROM SYS.SYSPROCEDURE p JOIN SYS.SYSUSER u ON u.user_id = p.creator WHERE u.user_name = ? AND p.proc_name = ?",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::Sql(
                "SELECT p.proc_defn FROM SYS.SYSPROCEDURE p JOIN SYS.SYSUSER u ON u.user_id = p.creator WHERE u.user_name = ? AND p.proc_name = ?",
                &[P::Schema, P::Name],
                "",
            ),
        },
    },
    Preset {
        id: "hive",
        name: "Apache Hive",
        family: Family::Analytical,
        dialect: "hive",
        default_port: 10000,
        quote: Some(Quote::Backtick),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Cloudera ODBC Driver for Apache Hive",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Se usa el driver de Cloudera (Simba) para Apache Hive, que se descarga gratis del sitio de Cloudera.",
        template: &[
            ("DRIVER", V::Driver),
            ("Host", V::Host),
            ("Port", V::Port),
            ("Schema", V::Database),
            ("AuthMech", V::SimbaAuthMech),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos predeterminada",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: SIMBA_SYS,
        batch: Batch::Statements,
        defs: Defs { table: Def::Show("SHOW CREATE TABLE"), view: Def::Show("SHOW CREATE TABLE"), ..NO_DEFS },
    },
    Preset {
        id: "impala",
        name: "Apache Impala",
        family: Family::Analytical,
        dialect: "hive",
        default_port: 21050,
        quote: Some(Quote::Backtick),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Cloudera ODBC Driver for Impala",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Se usa el driver de Cloudera (Simba) para Impala, que se descarga gratis del sitio de Cloudera.",
        template: &[
            ("DRIVER", V::Driver),
            ("Host", V::Host),
            ("Port", V::Port),
            ("Schema", V::Database),
            ("AuthMech", V::SimbaAuthMech),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos predeterminada",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: SIMBA_SYS,
        batch: Batch::Statements,
        defs: Defs { table: Def::Show("SHOW CREATE TABLE"), view: Def::Show("SHOW CREATE VIEW"), ..NO_DEFS },
    },
    Preset {
        id: "informix",
        name: "IBM Informix",
        family: Family::Relational,
        dialect: "informix",
        default_port: 9088,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::First),
        driver_hint: "IBM INFORMIX ODBC DRIVER",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Viene con IBM Informix Client SDK (CSDK), que se descarga del sitio de IBM.",
        template: INFORMIX_TEMPLATE,
        database_label: "Base de datos",
        database_required: true,
        extra_options: INFORMIX_SERVER,
        databases_label: "Bases de datos",
        databases_sql: Some("SELECT name FROM sysmaster:sysdatabases ORDER BY name"),
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &[],
        batch: Batch::Statements,
        defs: INFORMIX_DEFS,
    },
    Preset {
        id: "teradata",
        name: "Teradata",
        family: Family::Analytical,
        dialect: "teradata",
        default_port: 1025,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "Teradata Database ODBC Driver 17.20",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini (incluye la versión, por ejemplo «Teradata Database ODBC Driver 17.20»). Se descarga gratis de Teradata Downloads (Teradata Tools and Utilities o el paquete ODBC suelto).",
        template: &[
            ("DRIVER", V::Driver),
            ("DBCName", V::Host),
            ("TDMSTPortNumber", V::Port),
            ("Database", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos predeterminada",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &[
            "DBC",
            "Sys*",
            "TD_*",
            "TDStats",
            "TDQCD",
            "TDMaps",
            "TDPUSER",
            "SystemFe",
            "dbcmngr",
            "SQLJ",
            "LockLogShredder",
            "All",
            "Crashdumps",
            "PUBLIC",
            "EXTUSER",
            "Default",
        ],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::Show("SHOW TABLE"),
            view: Def::Show("SHOW VIEW"),
            procedure: Def::Show("SHOW PROCEDURE"),
            function: Def::Show("SHOW FUNCTION"),
        },
    },
    Preset {
        id: "vertica",
        name: "Vertica",
        family: Family::Analytical,
        dialect: "vertica",
        default_port: 5433,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Vertica",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Viene con los Vertica Client Drivers, que se descargan del sitio de OpenText Vertica.",
        template: &[
            ("DRIVER", V::Driver),
            ("ServerName", V::Host),
            ("Port", V::Port),
            ("Database", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["v_*"],
        batch: Batch::Statements,
        defs: Defs {
            view: Def::Sql(
                "SELECT view_definition FROM v_catalog.views WHERE table_schema = ? AND table_name = ?",
                &[P::Schema, P::Name],
                "",
            ),
            ..NO_DEFS
        },
    },
    Preset {
        id: "exasol",
        name: "Exasol",
        family: Family::Analytical,
        dialect: "exasol",
        default_port: 8563,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "EXASolution Driver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. El driver ODBC de Exasol se descarga gratis del portal de descargas de Exasol.",
        template: &[
            ("DRIVER", V::Driver),
            ("EXAHOST", V::HostPort),
            ("EXASCHEMA", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Esquema predeterminado",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["SYS", "EXA_STATISTICS"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT VIEW_TEXT FROM EXA_ALL_VIEWS WHERE VIEW_SCHEMA = ? AND VIEW_NAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT SCRIPT_TEXT FROM EXA_ALL_SCRIPTS WHERE SCRIPT_SCHEMA = ? AND SCRIPT_NAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::Sql(
                "SELECT FUNCTION_TEXT FROM EXA_ALL_FUNCTIONS WHERE FUNCTION_SCHEMA = ? AND FUNCTION_NAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
        },
    },
    Preset {
        id: "netezza",
        name: "IBM Netezza",
        family: Family::Analytical,
        dialect: "netezza",
        default_port: 5480,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "NetezzaSQL",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Viene con el paquete de clientes de IBM Netezza (nz-odbc), que se descarga de IBM Fix Central.",
        template: &[
            ("DRIVER", V::Driver),
            ("SERVERNAME", V::Host),
            ("PORT", V::Port),
            ("DATABASE", V::Database),
            ("USERNAME", V::User),
            ("PASSWORD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: false,
        extra_options: &[],
        databases_label: "Bases de datos",
        databases_sql: Some("SELECT DATABASE FROM _V_DATABASE ORDER BY DATABASE"),
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["DEFINITION_SCHEMA", "INFORMATION_SCHEMA"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT DEFINITION FROM _V_VIEW WHERE SCHEMA = ? AND VIEWNAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT PROCEDURESOURCE FROM _V_PROCEDURE WHERE SCHEMA = ? AND PROCEDURE = ?",
                &[P::Schema, P::Name],
                "\n\n",
            ),
            function: Def::None,
        },
    },
    Preset {
        id: "altibase",
        name: "Altibase",
        family: Family::Relational,
        dialect: "altibase",
        default_port: 20300,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "ALTIBASE_HDB_ODBC_64bit",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Viene con el cliente de Altibase (Altibase Client), que se descarga del sitio o del GitHub de Altibase.",
        template: &[
            ("DRIVER", V::Driver),
            ("SERVER", V::Host),
            ("PORT", V::Port),
            ("USER", V::User),
            ("PASSWORD", V::Password),
            ("NLS_USE", V::Lit("UTF8")),
        ],
        database_label: "",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["SYSTEM_", "X$*"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT P.PARSE FROM SYSTEM_.SYS_VIEW_PARSE_ P JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = P.USER_ID JOIN SYSTEM_.SYS_TABLES_ T ON T.TABLE_ID = P.VIEW_ID WHERE U.USER_NAME = ? AND T.TABLE_NAME = ? ORDER BY P.SEQ_NO",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT P.PARSE FROM SYSTEM_.SYS_PROC_PARSE_ P JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = P.USER_ID JOIN SYSTEM_.SYS_PROCEDURES_ R ON R.PROC_OID = P.PROC_OID WHERE U.USER_NAME = ? AND R.PROC_NAME = ? ORDER BY P.SEQ_NO",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::Sql(
                "SELECT P.PARSE FROM SYSTEM_.SYS_PROC_PARSE_ P JOIN SYSTEM_.SYS_USERS_ U ON U.USER_ID = P.USER_ID JOIN SYSTEM_.SYS_PROCEDURES_ R ON R.PROC_OID = P.PROC_OID WHERE U.USER_NAME = ? AND R.PROC_NAME = ? ORDER BY P.SEQ_NO",
                &[P::Schema, P::Name],
                "",
            ),
        },
    },
    Preset {
        id: "cubrid",
        name: "CUBRID",
        family: Family::Relational,
        dialect: "cubrid",
        default_port: 33000,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "CUBRID Driver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. El driver ODBC de CUBRID (solo Windows) se descarga del sitio de CUBRID.",
        template: &[
            ("DRIVER", V::Driver),
            ("SERVER", V::Host),
            ("PORT", V::Port),
            ("DB_NAME", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
            ("CHARSET", V::Lit("utf-8")),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: false,
        procedures: true,
        functions: true,
        system_schemas: &[],
        batch: Batch::Statements,
        defs: Defs {
            view: Def::Sql("SELECT vclass_def FROM db_vclass WHERE vclass_name = ?", &[P::Name], ""),
            ..NO_DEFS
        },
    },
    Preset {
        id: "dameng",
        name: "Dameng (DM)",
        family: Family::Relational,
        dialect: "oracle",
        default_port: 5236,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "DM8 ODBC DRIVER",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Viene con la instalación de DM (drivers/odbc) o con su cliente, que se descarga del sitio de Dameng.",
        template: &[
            ("DRIVER", V::Driver),
            ("SERVER", V::Host),
            ("TCP_PORT", V::Port),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["SYS", "SYSAUDITOR", "SYSSSO", "CTISYS", "SYSJOB"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::Sql("SELECT DBMS_METADATA.GET_DDL('TABLE', ?, ?) FROM DUAL", &[P::Name, P::Schema], ""),
            view: Def::Sql("SELECT TEXT FROM ALL_VIEWS WHERE OWNER = ? AND VIEW_NAME = ?", &[P::Schema, P::Name], ""),
            procedure: Def::Sql(
                "SELECT TEXT FROM ALL_SOURCE WHERE OWNER = ? AND NAME = ? ORDER BY LINE",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::Sql(
                "SELECT TEXT FROM ALL_SOURCE WHERE OWNER = ? AND NAME = ? ORDER BY LINE",
                &[P::Schema, P::Name],
                "",
            ),
        },
    },
    Preset {
        id: "gbase8s",
        name: "GBase 8s",
        family: Family::Relational,
        dialect: "informix",
        default_port: 9088,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::First),
        driver_hint: "GBase ODBC DRIVER",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Viene con GBase 8s Client SDK (CSDK), que se descarga del sitio de GBase.",
        template: INFORMIX_TEMPLATE,
        database_label: "Base de datos",
        database_required: true,
        extra_options: INFORMIX_SERVER,
        databases_label: "Bases de datos",
        databases_sql: Some("SELECT name FROM sysmaster:sysdatabases ORDER BY name"),
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &[],
        batch: Batch::Statements,
        defs: INFORMIX_DEFS,
    },
    Preset {
        id: "ocient",
        name: "Ocient",
        family: Family::Analytical,
        dialect: "standard",
        default_port: 4050,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Ocient ODBC Driver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. El driver ODBC de Ocient se pide al soporte de Ocient o se descarga de su portal de clientes.",
        template: &[
            ("DRIVER", V::Driver),
            ("Host", V::Host),
            ("Port", V::Port),
            ("Database", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: &["sys", "information_schema"],
        batch: Batch::Statements,
        defs: NO_DEFS,
    },
    Preset {
        id: "spark",
        name: "Spark Thrift Server",
        family: Family::Analytical,
        dialect: "sparksql",
        default_port: 10000,
        quote: Some(Quote::Backtick),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Simba Spark ODBC Driver",
        driver_help: SPARK_HELP,
        template: SPARK_TEMPLATE,
        database_label: "Base de datos predeterminada",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: SIMBA_SYS,
        batch: Batch::Statements,
        defs: Defs { table: Def::Show("SHOW CREATE TABLE"), view: Def::Show("SHOW CREATE TABLE"), ..NO_DEFS },
    },
    Preset {
        id: "kyuubi",
        name: "Apache Kyuubi",
        family: Family::Analytical,
        dialect: "sparksql",
        default_port: 10009,
        quote: Some(Quote::Backtick),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Simba Spark ODBC Driver",
        driver_help: SPARK_HELP,
        template: SPARK_TEMPLATE,
        database_label: "Base de datos predeterminada",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: SIMBA_SYS,
        batch: Batch::Statements,
        defs: Defs { table: Def::Show("SHOW CREATE TABLE"), view: Def::Show("SHOW CREATE TABLE"), ..NO_DEFS },
    },
    Preset {
        id: "cloudera",
        name: "Cloudera CDP (Hive por HTTP)",
        family: Family::Analytical,
        dialect: "hive",
        default_port: 443,
        quote: Some(Quote::Backtick),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Cloudera ODBC Driver for Apache Hive",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini. Se usa el driver de Cloudera (Simba) para Apache Hive, que se descarga gratis del sitio de Cloudera. Para Cloudera Data Warehouse o Data Hub: transporte HTTP con TLS (puerto 443) y el usuario de workload de CDP.",
        template: &[
            ("DRIVER", V::Driver),
            ("Host", V::Host),
            ("Port", V::Port),
            ("Schema", V::Database),
            ("AuthMech", V::SimbaAuthMech),
            ("ThriftTransport", V::Lit("2")),
            ("HTTPPath", V::OptOr("http_path", "cliservice")),
            ("SSL", V::Lit("1")),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos predeterminada",
        database_required: false,
        extra_options: &[(
            "http_path",
            "Ruta HTTP (HTTPPath)",
            "cliservice",
            false,
            "La ruta del endpoint HiveServer2 por HTTP; en Cloudera Data Warehouse suele ser «cliservice».",
        )],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: SIMBA_SYS,
        batch: Batch::Statements,
        defs: Defs { table: Def::Show("SHOW CREATE TABLE"), view: Def::Show("SHOW CREATE TABLE"), ..NO_DEFS },
    },
    Preset {
        id: "monetdb",
        name: "MonetDB",
        family: Family::Analytical,
        dialect: "standard",
        default_port: 50000,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "MonetDB ODBC Driver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («MonetDB ODBC Driver» en Windows, «MonetDB» con unixODBC). Viene con el servidor en Linux y macOS (libMonetODBC) y con un instalador aparte en Windows, desde monetdb.org.",
        template: &[
            ("DRIVER", V::Driver),
            ("HOST", V::Host),
            ("PORT", V::Port),
            ("DATABASE", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["sys", "tmp", "json", "profiler", "logging", "information_schema", "wlc", "wlr"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT t.query FROM sys.tables t JOIN sys.schemas s ON s.id = t.schema_id WHERE s.name = ? AND t.name = ?",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT f.func FROM sys.functions f JOIN sys.schemas s ON s.id = f.schema_id WHERE s.name = ? AND f.name = ?",
                &[P::Schema, P::Name],
                "\n\n",
            ),
            function: Def::Sql(
                "SELECT f.func FROM sys.functions f JOIN sys.schemas s ON s.id = f.schema_id WHERE s.name = ? AND f.name = ?",
                &[P::Schema, P::Name],
                "\n\n",
            ),
        },
    },
    Preset {
        id: "virtuoso",
        name: "OpenLink Virtuoso",
        family: Family::Relational,
        dialect: "standard",
        default_port: 1111,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "OpenLink Virtuoso",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («OpenLink Virtuoso» u «OpenLink Virtuoso Driver» en Windows; en Linux y macOS, la biblioteca virtodbcu_r.so). Viene con Virtuoso (Open Source o Enterprise) y su cliente, desde openlinksw.com.",
        template: &[
            ("DRIVER", V::Driver),
            ("HOST", V::HostPort),
            ("DATABASE", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
            ("CHARSET", V::Lit("UTF-8")),
        ],
        database_label: "Calificador (catálogo)",
        database_required: false,
        extra_options: &[],
        databases_label: "Catálogos",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: false,
        system_schemas: &["SYS"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT coalesce(V_TEXT, blob_to_string(V_EXT)) FROM DB.DBA.SYS_VIEWS WHERE V_NAME = concat(?, '.', ?, '.', ?)",
                &[P::Catalog, P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT coalesce(P_TEXT, blob_to_string(P_MORE)) FROM DB.DBA.SYS_PROCEDURES WHERE P_NAME = concat(?, '.', ?, '.', ?)",
                &[P::Catalog, P::Schema, P::Name],
                "",
            ),
            function: Def::None,
        },
    },
    Preset {
        id: "ingres",
        name: "Actian Ingres",
        family: Family::Relational,
        dialect: "standard",
        default_port: 21064,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::First),
        driver_hint: "Ingres",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («Ingres», o «Ingres XX» con otro ID de instalación). Viene con Actian Ingres, Actian Vector o su Client Runtime; en Linux se registra con iiodbcinst. Se conecta con un vnode dinámico (@servidor,tcp_ip,puerto): el puerto es el del Ingres/Net listener (21064 para la instalación II).",
        template: &[
            ("DRIVER", V::Driver),
            ("SERVER", V::Fmt("@{host},tcp_ip,{port}")),
            ("SERVERTYPE", V::Lit("INGRES")),
            ("DATABASE", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: false,
        system_schemas: &["$ingres", "$aux"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT text_segment FROM iiviews WHERE table_owner = ? AND table_name = ? ORDER BY text_sequence",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT text_segment FROM iiprocedures WHERE procedure_owner = ? AND procedure_name = ? ORDER BY text_sequence",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::None,
        },
    },
    Preset {
        id: "mimer",
        name: "Mimer SQL",
        family: Family::Relational,
        dialect: "standard",
        default_port: 1360,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::FetchFirst),
        driver_hint: "MIMER",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («MIMER» en Windows; en Linux suele ser «mimersql», con libmimodbc.so). Viene con Mimer SQL o su cliente para Windows, Linux y macOS, desde mimer.com.",
        template: &[
            ("DRIVER", V::Driver),
            ("PROTOCOL", V::Lit("tcp")),
            ("NODE", V::Host),
            ("SERVICE", V::Port),
            ("DATABASE", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["SYSTEM", "INFORMATION_SCHEMA", "MIMER", "BUILTIN"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(MIMER_SOURCE_VIEW, &[P::Schema, P::Name], ""),
            procedure: Def::Sql(MIMER_SOURCE_PROCEDURE, &[P::Schema, P::Name], ""),
            function: Def::Sql(MIMER_SOURCE_FUNCTION, &[P::Schema, P::Name], ""),
        },
    },
    Preset {
        id: "iris",
        name: "InterSystems IRIS",
        family: Family::Relational,
        dialect: "standard",
        default_port: 1972,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "InterSystems ODBC35",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («InterSystems ODBC35» o «InterSystems ODBC»; en Linux, libirisodbc.so). Viene con IRIS o se descarga suelto del sitio de InterSystems (WRC) o de su repositorio de drivers.",
        template: IRIS_TEMPLATE,
        database_label: "Espacio de nombres (namespace)",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: IRIS_SYS,
        batch: Batch::Statements,
        defs: INFO_SCHEMA_DEFS,
    },
    Preset {
        id: "cache",
        name: "InterSystems Caché",
        family: Family::Relational,
        dialect: "standard",
        default_port: 1972,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "InterSystems ODBC",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («InterSystems ODBC» o «InterSystems ODBC35»; en Linux, libcacheodbc.so). Viene con Caché o su cliente, desde el sitio de InterSystems (WRC).",
        template: IRIS_TEMPLATE,
        database_label: "Espacio de nombres (namespace)",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: IRIS_SYS,
        batch: Batch::Statements,
        defs: INFO_SCHEMA_DEFS,
    },
    Preset {
        id: "openedge",
        name: "Progress OpenEdge",
        family: Family::Relational,
        dialect: "standard",
        default_port: 0,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "Progress OpenEdge 12.8 Driver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini (incluye la versión, por ejemplo «Progress OpenEdge 12.8 Driver»). Es el driver DataDirect que viene con el cliente de OpenEdge (SQL Client Access o el instalador de OpenEdge). El puerto es el del broker SQL de la base (-S).",
        template: &[
            ("DRIVER", V::Driver),
            ("HOST", V::Host),
            ("PORT", V::Port),
            ("DB", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: false,
        system_schemas: &["SYSPROGRESS"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT VIEWTEXT FROM SYSPROGRESS.SYSVIEWS WHERE OWNER = ? AND VIEWNAME = ? ORDER BY SEQ",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT t.PROC_TEXT FROM SYSPROGRESS.SYSPROCTEXT t JOIN SYSPROGRESS.SYSPROCEDURES p ON p.PROC_ID = t.ID WHERE p.OWNER = ? AND p.PROC_NAME = ? ORDER BY t.SEQ",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::None,
        },
    },
    Preset {
        id: "zen",
        name: "Actian Zen (Pervasive PSQL)",
        family: Family::Relational,
        dialect: "standard",
        default_port: 1583,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "Pervasive ODBC Interface",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («Pervasive ODBC Interface» de 64 bits, «Pervasive ODBC Client Interface» de 32). Viene con Actian Zen o su Client, para Windows, Linux y macOS, desde el sitio de Actian.",
        template: &[
            ("DRIVER", V::Driver),
            ("ServerName", V::Fmt("{host}.{port}")),
            ("DBQ", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos (nombre interno)",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: false,
        procedures: true,
        functions: false,
        system_schemas: &[],
        batch: Batch::Statements,
        defs: NO_DEFS,
    },
    Preset {
        id: "sqream",
        name: "SQream DB",
        family: Family::Analytical,
        dialect: "standard",
        default_port: 5000,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "SqreamODBCDriver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («SqreamODBCDriver» en Linux, con sqream_odbc64.so). Se descarga del sitio de SQream, para Linux y Windows.",
        template: &[
            ("DRIVER", V::Driver),
            ("Server", V::Host),
            ("Port", V::Port),
            ("Database", V::Database),
            ("User", V::User),
            ("Password", V::Password),
            ("Service", V::OptOr("service", "sqream")),
            ("Cluster", V::OptOr("cluster", "false")),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[
            (
                "cluster",
                "Balanceador (Cluster)",
                "false",
                false,
                "«true» si te conectás al balanceador de carga (puerto 3108); «false» para un worker directo (puerto 5000).",
            ),
            ("service", "Servicio", "sqream", false, "El servicio (cola de trabajo) de SQream."),
        ],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: true,
        system_schemas: &["sqream_catalog"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::Sql("SELECT GET_DDL(?)", &[P::Qualified], ""),
            view: Def::Sql("SELECT GET_VIEW_DDL(?)", &[P::Qualified], ""),
            procedure: Def::None,
            function: Def::Sql("SELECT GET_FUNCTION_DDL(?)", &[P::Name], ""),
        },
    },
    Preset {
        id: "maxdb",
        name: "SAP MaxDB",
        family: Family::Relational,
        dialect: "standard",
        default_port: 7210,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "MaxDB",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («MaxDB», «SAP DB (Unicode)» o similar; bibliotecas sdbodbc / libsdbodbc). Viene con el cliente de SAP MaxDB. El servidor atiende en el X Server (puerto 7210).",
        template: &[
            ("DRIVER", V::Driver),
            ("SERVERNODE", V::Host),
            ("SERVERDB", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos (SERVERDB)",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: false,
        system_schemas: &["SYS", "DOMAIN", "SYSINFO"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT DEFINITION FROM DOMAIN.VIEWDEFS WHERE SCHEMANAME = ? AND VIEWNAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT DEFINITION FROM DOMAIN.DBPROCEDURES WHERE SCHEMANAME = ? AND DBPROCNAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::None,
        },
    },
    Preset {
        id: "access",
        name: "Microsoft Access",
        family: Family::Relational,
        dialect: "access",
        default_port: 0,
        quote: Some(Quote::Bracket),
        limit: Some(LimitStyle::Top),
        driver_hint: "Microsoft Access Driver (*.mdb, *.accdb)",
        driver_help: "Nombre del driver ODBC tal como figura en el Administrador de orígenes de datos ODBC. Viene con Microsoft Access o con el Microsoft Access Database Engine (redistribuible), solo en Windows; la versión de 64 o 32 bits tiene que coincidir con la de DBine.",
        template: &[("DRIVER", V::Driver), ("DBQ", V::Database), ("PWD", V::Password)],
        database_label: "Archivo (.accdb / .mdb)",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: false,
        procedures: false,
        functions: false,
        system_schemas: &[],
        batch: Batch::Statements,
        defs: NO_DEFS,
    },
    Preset {
        id: "dbase",
        name: "Archivos dBase (DBF)",
        family: Family::Relational,
        dialect: "access",
        default_port: 0,
        quote: Some(Quote::Bracket),
        limit: Some(LimitStyle::Top),
        driver_hint: "Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)",
        driver_help: "Nombre del driver ODBC tal como figura en el Administrador de orígenes de datos ODBC: «Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)» (Access Database Engine) o «Microsoft dBase Driver (*.dbf)» (el de 32 bits de Windows). Solo en Windows.",
        template: &[("DRIVER", V::Driver), ("DBQ", V::Database), ("DriverID", V::Lit("277"))],
        database_label: "Carpeta con los .dbf (o uno de sus archivos)",
        database_required: true,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: false,
        procedures: false,
        functions: false,
        system_schemas: &[],
        batch: Batch::Statements,
        defs: NO_DEFS,
    },
    Preset {
        id: "nuodb",
        name: "NuoDB",
        family: Family::Relational,
        dialect: "standard",
        default_port: 48004,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "NuoDB ODBC Driver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («NuoDB ODBC Driver» en Windows; en Linux, libNuoODBC.so con el nombre que le des). Es el driver de código abierto de NuoDB (github.com/nuodb/nuodb-odbc), para Windows y Linux. El puerto es el del admin (AP) de NuoDB.",
        template: &[
            ("DRIVER", V::Driver),
            ("DATABASE", V::Fmt("{database}@{host}:{port}")),
            ("UID", V::User),
            ("PWD", V::Password),
            ("SCHEMA", V::Opt("schema")),
        ],
        database_label: "Base de datos",
        database_required: true,
        extra_options: &[("schema", "Esquema predeterminado", "USER", false, "El esquema de la sesión (SCHEMA).")],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: true,
        functions: true,
        system_schemas: &["SYSTEM"],
        batch: Batch::Statements,
        defs: Defs {
            table: Def::None,
            view: Def::Sql(
                "SELECT VIEWDEFINITION FROM SYSTEM.TABLES WHERE SCHEMA = ? AND TABLENAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            procedure: Def::Sql(
                "SELECT PROCEDURETEXT FROM SYSTEM.PROCEDURES WHERE SCHEMA = ? AND PROCEDURENAME = ?",
                &[P::Schema, P::Name],
                "",
            ),
            function: Def::None,
        },
    },
    Preset {
        id: "heavydb",
        name: "HeavyDB (OmniSciDB)",
        family: Family::Analytical,
        dialect: "standard",
        default_port: 6274,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "HeavyaiDriver",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («HeavyaiDriver», con libheavyaiODBC.so). Se descarga de HEAVY.AI (builds.mapd.com, con cuenta), para Windows y Linux.",
        template: &[
            ("DRIVER", V::Driver),
            ("HOST", V::Host),
            ("PORT", V::Port),
            ("DATABASE", V::Database),
            ("UID", V::User),
            ("PWD", V::Password),
        ],
        database_label: "Base de datos",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: false,
        procedures: false,
        functions: false,
        system_schemas: &["information_schema"],
        batch: Batch::Statements,
        defs: Defs { table: Def::Show("SHOW CREATE TABLE"), view: Def::Show("SHOW CREATE TABLE"), ..NO_DEFS },
    },
    Preset {
        id: "machbase",
        name: "Machbase",
        family: Family::TimeSeries,
        dialect: "standard",
        default_port: 5656,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "MACHBASE",
        driver_help: "Nombre con el que registraste el driver ODBC de Machbase en odbcinst.ini (biblioteca libmachbasecli_dll.so; en Windows, su DLL). Viene con el paquete de Machbase (carpeta lib).",
        template: &[
            ("DRIVER", V::Driver),
            ("SERVER", V::Host),
            ("PORT_NO", V::Port),
            ("UID", V::User),
            ("PWD", V::Password),
            ("CONNTYPE", V::Lit("1")),
        ],
        database_label: "",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: &[],
        batch: Batch::Statements,
        defs: Defs {
            view: Def::Sql("SELECT VIEW_SQL FROM M$SYS_VIEWS WHERE VIEW_NAME = ?", &[P::Name], ""),
            ..NO_DEFS
        },
    },
    Preset {
        id: "ignite",
        name: "Apache Ignite 2",
        family: Family::Relational,
        dialect: "standard",
        default_port: 10800,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Apache Ignite",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («Apache Ignite»). En Windows viene como instalador .msi con Ignite; en Linux se compila y se registra libignite-odbc.so con odbcinst.",
        template: &[
            ("DRIVER", V::Driver),
            ("ADDRESS", V::HostPort),
            ("SCHEMA", V::Database),
            ("USER", V::User),
            ("PASSWORD", V::Password),
        ],
        database_label: "Esquema",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: &["SYS", "INFORMATION_SCHEMA"],
        batch: Batch::Statements,
        defs: Defs {
            view: Def::Sql("SELECT SQL FROM SYS.VIEWS WHERE SCHEMA = ? AND NAME = ?", &[P::Schema, P::Name], ""),
            ..NO_DEFS
        },
    },
    Preset {
        id: "ignite3",
        name: "Apache Ignite 3",
        family: Family::Relational,
        dialect: "standard",
        default_port: 10800,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Limit),
        driver_hint: "Apache Ignite 3",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («Apache Ignite 3»). Se instala con los paquetes de Ignite 3 para Windows y Linux.",
        template: &[
            ("DRIVER", V::Driver),
            ("ADDRESS", V::HostPort),
            ("SCHEMA", V::Database),
            ("IDENTITY", V::User),
            ("SECRET", V::Password),
        ],
        database_label: "Esquema",
        database_required: false,
        extra_options: &[],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: &["SYSTEM", "INFORMATION_SCHEMA", "DEFINITION_SCHEMA"],
        batch: Batch::Statements,
        defs: NO_DEFS,
    },
    Preset {
        id: "netsuite",
        name: "Oracle NetSuite (SuiteAnalytics Connect)",
        family: Family::Relational,
        dialect: "standard",
        default_port: 1708,
        quote: Some(Quote::Double),
        limit: Some(LimitStyle::Top),
        driver_hint: "NetSuite Drivers 64bit",
        driver_help: "Nombre del driver ODBC tal como figura en odbcinst.ini («NetSuite Drivers 64bit» en Windows, «NetSuite ODBC Drivers 7.2» en Linux). Se descarga desde NetSuite (portlet Settings › Set Up SuiteAnalytics Connect), donde también figuran el servidor, el ID de cuenta y el ID de rol. Es de solo lectura.",
        template: &[
            ("DRIVER", V::Driver),
            ("Host", V::Host),
            ("Port", V::Port),
            ("Encrypted", V::Lit("1")),
            ("AllowSinglePacketLogout", V::Lit("1")),
            ("Truststore", V::OptOr("truststore", "system")),
            ("ServerDataSource", V::Lit("NetSuite2.com")),
            ("UID", V::User),
            ("PWD", V::Password),
            // Last: its value carries `;` and the driver reads it to the end.
            ("CustomProperties", V::Fmt("AccountID={opt:account_id};RoleID={opt:role_id}")),
        ],
        database_label: "",
        database_required: false,
        extra_options: &[
            ("account_id", "ID de cuenta", "1234567", true, "El Account ID que muestra la página de descarga del driver."),
            ("role_id", "ID de rol", "3", true, "El rol con permiso de SuiteAnalytics Connect (Role ID)."),
            (
                "truststore",
                "Truststore",
                "system",
                false,
                "«system» usa los certificados del sistema; en Linux, la ruta del archivo .cer de NetSuite.",
            ),
        ],
        databases_label: "",
        databases_sql: None,
        has_schemas: true,
        procedures: false,
        functions: false,
        system_schemas: &[],
        batch: Batch::Statements,
        defs: NO_DEFS,
    },
];

const SPARK_HELP: &str = "Nombre del driver ODBC tal como figura en odbcinst.ini. Se usa el driver Simba de Spark (el «Databricks ODBC Driver» / «Simba Spark ODBC Driver»), que se descarga gratis; también sirve el driver de Cloudera para Hive, porque el servidor habla el protocolo de HiveServer2.";

const SPARK_TEMPLATE: &[(&str, V)] = &[
    ("DRIVER", V::Driver),
    ("Host", V::Host),
    ("Port", V::Port),
    ("Schema", V::Database),
    ("AuthMech", V::SimbaAuthMech),
    // 3: Spark Thrift Server (HiveServer2 protocol).
    ("SparkServerType", V::Lit("3")),
    ("UID", V::User),
    ("PWD", V::Password),
];

const IRIS_TEMPLATE: &[(&str, V)] = &[
    ("DRIVER", V::Driver),
    ("SERVER", V::Host),
    ("PORT", V::Port),
    ("DATABASE", V::Database),
    ("UID", V::User),
    ("PWD", V::Password),
];

const IRIS_SYS: &[&str] = &["%*", "INFORMATION_SCHEMA", "Ens*", "HS*"];

const INFO_SCHEMA_DEFS: Defs = Defs {
    table: Def::None,
    view: Def::Sql(
        "SELECT VIEW_DEFINITION FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?",
        &[P::Schema, P::Name],
        "",
    ),
    procedure: Def::Sql(
        "SELECT ROUTINE_DEFINITION FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_NAME = ?",
        &[P::Schema, P::Name],
        "",
    ),
    function: Def::Sql(
        "SELECT ROUTINE_DEFINITION FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = ? AND ROUTINE_NAME = ?",
        &[P::Schema, P::Name],
        "",
    ),
};

/// Mimer keeps the full source in 400-character lines
/// (`VIEWS.VIEW_DEFINITION` is NULL when it's long).
const MIMER_SOURCE_VIEW: &str = "SELECT SOURCE_DEFINITION FROM INFORMATION_SCHEMA.EXT_SOURCE_DEFINITION WHERE OBJECT_SCHEMA = ? AND OBJECT_NAME = ? AND OBJECT_TYPE = 'VIEW' ORDER BY LINE_NUMBER";
const MIMER_SOURCE_PROCEDURE: &str = "SELECT SOURCE_DEFINITION FROM INFORMATION_SCHEMA.EXT_SOURCE_DEFINITION WHERE OBJECT_SCHEMA = ? AND OBJECT_NAME = ? AND OBJECT_TYPE = 'PROCEDURE' ORDER BY LINE_NUMBER";
const MIMER_SOURCE_FUNCTION: &str = "SELECT SOURCE_DEFINITION FROM INFORMATION_SCHEMA.EXT_SOURCE_DEFINITION WHERE OBJECT_SCHEMA = ? AND OBJECT_NAME = ? AND OBJECT_TYPE = 'FUNCTION' ORDER BY LINE_NUMBER";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_are_unique_and_lowercase() {
        let mut ids: Vec<_> = PRESETS.iter().map(|p| p.id).collect();
        assert!(ids.iter().all(|i| i.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')));
        let n = ids.len();
        ids.sort();
        ids.dedup();
        assert_eq!(ids.len(), n);
    }

    #[test]
    fn system_schemas_match_prefixes() {
        let db2 = PRESETS.iter().find(|p| p.id == "db2").unwrap();
        assert!(db2.is_system_schema("SYSIBM"));
        assert!(db2.is_system_schema("syscat"));
        assert!(!db2.is_system_schema("APP"));
        let generic = PRESETS.iter().find(|p| p.id == "odbc").unwrap();
        assert!(generic.is_system_schema("sys"));
        assert!(!generic.is_system_schema("dbo"));
    }
}
